### ISSUE TITLE
Rename test suites to avoid dots in names

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#1020]
There are dots (`.` characters) in the name of some test suites (e.g. `test_suite_aes.cbc`). This makes it annoying to write scripts sometimes because we can't assume that base names have no extension (e.g. 071db41627758963a1cedbed923c5e2a51543985). This may also cause trouble with static analysis tools that assume that a module name consists only of alphanumerics and `_`. We should rename the test suites to use only alphanumerics and `_`, e.g. `test_suite_aes_cbc`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1573

**Comment by tom-daubney-arm** [comment]
Closing this issue since we will not find time to put aside to work on this. If someone does want to work on this then please feel free to raise a PR.
