### ISSUE TITLE
Missing cipher

### ISSUE THREAD

**Issue by alexb001** [Mbed-TLS/mbedtls#1047]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Feature Request 
- Priority: ASAP

Please add following cipher to a current suite.
TLS_DH_ANON_WITH_AES_256_GCM_SHA384

Application for this cipher is new NMEA  (http://www.nmea.org ) standard OneNet ( http://www.nmea.org/content/nmea_standards/nmea_onenet.asp). 
This standard is in process of being developed and verified.
There is only 2 ciphers are being used:
TLS_DH_ANON_WITH_AES_256_GCM_SHA384  <<< not available
TLS_PSK_WITH_AES_256_GCM_SHA384              <<< is available
My company (BE Marine Technologies) is part of a Beta Test Team involved in testing and implementation of this standard, and as such I am looking for TSL suites usable in the embedded environment.

**Comment by RonEld** [comment]
Hi @alexb001 Thank ou for posting this request.
We will look and assess this request, to see whether it's something we want to adopt.
Thanks again for your cooperation!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1617

**Comment by aditya-deshpande-arm** [comment]
After an internal discussion we have decided that we are not adopting this and are unlikely to do so in the future.
