### ISSUE TITLE
Support for alternative modular exponentiation 

### ISSUE THREAD

**Issue by TrinityTonic** [Mbed-TLS/mbedtls#1090]
### Add support for alternative modular exponentiation
- Type: Enhancement\Feature Request 
- Priority: Minor

----------------------------------------------------------------
## Enhancement\Feature Request

Nowadays some available crypto cores can accelerate modular exponentiation. Right now the mbedTLS library does not support replacement of its native modular exponentiatiation method in bignum.c. Supporting replacement of mbed_tls_mod_exp would make some things easier when integrating a hardware exponentiation core.

**Comment by RonEld** [comment]
Hi @TrinityTonic Thank you for raising this issue.
We will take into consideration your request.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1750

**Comment by RonEld** [comment]
Hi @TrinityTonic We have released version 2.7.0, which has support for alternative ECDSA functionality ( sign, verify and generate key pair), alternative ECDH functionality( for generating public and computing shared secret), and alternative functionalities for RSA. Note it also support alternative ECP.
Would this suffice your needs?

**Comment by TrinityTonic** [comment]
Thanks for the notification @RonEld. I'll try to evaluate the new features in mbedtls-2.7.0 as soon as possible and will let you know.

**Comment by TrinityTonic** [comment]
Hi Ron,
for RSA I was rather looking for something like replacing the modular exponentiation function in bignum.c as this is the core operation of all DH(E) and RSA operations. For Elliptic Curve I'm missing replacement of the core EC function, namely elliptic curve point multiplication which is currently handled inside mbedtls_ecp_mul.
