### ISSUE TITLE
Consider refactoring mbedtls_gcm_self_test()

### ISSUE THREAD

**Issue by andresag01** [Mbed-TLS/mbedtls#1103]
### Description
- Type: Enhancement
- Priority: Minor

----------------------------------------------------------------
## Enhancement
The self test code in `mbedtls_gcm_self_test()` is confusing, hard to maintain and prone to memory issues when modified. We should consider refactoring the code to improve readability and make maintenance much easier in the future.

**Comment by tom-daubney-arm** [comment]
We will not have the bandwidth to make these sorts of improvements in the near future and so this will be closed as a won't fix.
