### ISSUE TITLE
Improve "bad message length" debug messages

### ISSUE THREAD

**Issue by marcelstoer** [Mbed-TLS/mbedtls#1169]
### Description
- Type: Enhancement
- Priority: Minor

## Enhancement Request

**Justification - why does the library need this feature?**
Help with debugging, primarily for non-library developers.

**Suggested enhancement**
Starting at https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_tls.c#L3522 you check for six conditions which could lead to "bad message length" debug messages. With just a little effort you could greatly improve those messages - be more specific. For example, when the message size is beyond the limit configured in `MBEDTLS_SSL_MAX_CONTENT_LEN` "bad message length" is misleading. The message length is not really _bad_ but simply beyond a configured limit. "bad" in my non-English-mother-tongue ears sounds like "violating some spec/RfC". If the messages were more specific we wouldn't see the same message for essentially six different violations.

What I would expect in the example above is something like this: "Message length n beyond MBEDTLS_SSL_MAX_CONTENT_LEN of N.":
- message specific for exactly this condition
- values used in evaluation part of message (i.e. expected and actual)
- hint for user how to fix by including name of config param

I'm with the NodeMCU firmware team (ESP8266) and we've unearthed this issue at https://github.com/nodemcu/nodemcu-firmware/issues/1707#issuecomment-344532787

**Comment by RonEld** [comment]
Hi @marcelstoer thank you for your suggestion and interest in Mbed TLS!
We will consider your enhancement suggestion!

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1934

**Comment by tom-daubney-arm** [comment]
This is not something we plan to change in the near future.
