### ISSUE TITLE
Linker error on Windows UWP

### ISSUE THREAD

**Issue by GregSlazinski** [Mbed-TLS/mbedtls#1227]
Trying to link on Windows UWP x86 I get following errors:
2>DebugUniversal64DX11.lib(x509_crt.obj) : error LNK2019: unresolved external symbol __imp_lstrlenW referenced in function mbedtls_x509_crt_parse_path
2>DebugUniversal64DX11.lib(entropy_poll.obj) : error LNK2019: unresolved external symbol __imp_CryptGenRandom referenced in function mbedtls_platform_entropy_poll

It appears that these functions aren't available on UWP

replacing lstrlenW with wcslen solves the first problem.
https://github.com/ARMmbed/mbedtls/blob/master/library/x509_crt.c#L1145

I think `BCryptGenRandom` should be used instead.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa375458(v=vs.85).aspx

**Comment by RonEld** [comment]
Hi @GregSlazinski Thank you for reporting this issue!
I believe that https://github.com/ARMmbed/mbedtls/pull/730 should fix this issue. Please confirm

**Comment by RonEld** [comment]
Reopening for tracking. Will be closed once the fix is merged

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1960

**Comment by nahdir** [comment]
This can be fixed by replacing `lstrlenW( file_data.cFileName )` with `-1`. Its what I did locally. lstrlenW expects a null terminated string, and passing -1 just means the string passed to WideCharToMultiByte is null terminated so there should be no difference in behaviour.

**Comment by gilles-peskine-arm** [comment]
Note that the current version of the proposed fix is https://github.com/ARMmbed/mbedtls/pull/1453, but at this time nobody is actively working on it. See also https://github.com/ARMmbed/mbedtls/issues/2994#issuecomment-672072556

**Comment by daverodgman** [comment]
@tom-cosgrove-arm do you have time to look at this, or should the 3.5 subteam pick it up?

**Comment by tom-cosgrove-arm** [comment]
And yes, I think @minosgalanakis is probably best placed to look at this, after his vacation!
