### ISSUE TITLE
[RFC] Sharing buffer with other async io library

### ISSUE THREAD

**Issue by deleisha** [Mbed-TLS/mbedtls#1253]
While trying to abstract out OpenSSL and mbedtls for a common callback based async API with a final objective of integrating with other async IO library like libuv. We came across that mbedtls expect to provide 
``` C
int mbedtls_ssl_send_t(void *ctx, const unsigned char *buf, size_t len);
int mbedtls_ssl_recv_t(void *ctx, unsigned char *buf, size_t len)
```
So, we are required to copy memory from libuv buffer to mbdtls and vice versa. This is also posted by another user [here](https://tls.mbed.org/discussions/generic/async-i-o-with-mbed-tls-epoll-kqueue).

Won't it be useful to have some API to hook so that it can use a share memory location to remove the redundant copy.

**Comment by RonEld** [comment]
Hi @deleisha Thank you for your suggestion!
We will take it into consideration..

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1996

**Comment by hanno-arm** [comment]
Hi @deleisha, that's an option worthwhile pursuing, and as @RonEld mentioned we are considering it. However, note that for TLS, the underlying transport's transmission units are likely to not always contain entire TLS records, and in this case, Mbed TLS needs to accumulate data in a temporary buffer until a full record is available. I'd therefore suspect that there's not much to can gain here. For DTLS, in contrast, records must not be fragmented across datagrams, and I fully agree that the internal record buffer could be shared with the buffer of the underlying datagram transport, saving both space and time.

**Comment by deleisha** [comment]
Thanks @RonEld and @hanno-arm for the consideration and explanation. 
Not comparing with OpenSSL as such but OpenSSL allows us to write data received from network to 
it through BIO pair. This enables us to separate out handling network activity and TLS activity using OpenSSL as independent state machine. 
Perhaps whatever we feed to OpenSSL BIO pair, it internally buffers it ,as you explained, till complete TLS record is read. We might still be copying it but in disguise. 
Sharing the memory buffer will remove the redundant copy. Worthwhile exploring

**Comment by deleisha** [comment]
Also, it is observed that `f_recv` read `5 bytes` followed by another read to read all remaining bytes. 

May be combining the two read calls into a single read and buffering it will improve performance.

**Comment by pfalcon** [comment]
@deleisha:

> May be combining the two read calls into a single read

Sorry, it's impossible, those 5 initial bytes contain the size of the following chunk to read ;-).

>  and buffering it will improve performance.

That, you can easily do in your own implementation of mbedtls_ssl_recv_t (if you don't trust your OS to do that, see https://en.wikipedia.org/wiki/Bufferbloat).

**Comment by deleisha** [comment]
I am not sure how openssl does the buffering in BIO pair,perhaps it reads 5 byte first from the network received data that we feed.  We just write whatever we received from network in the readcallback . 
Easy life. Reducing to a single will improve performance. From the read data, check initial 5  byte and decide how much idea will be necessary. Will that not be possible

Well, The original idea of this issue is to remove a redundant copy from read callback, when using event based library like libuv, to mbedtls.

**Comment by hanno-arm** [comment]
@deleisha As mentioned earlier, if the underlying transport is a stream, there's only a potential gain in memory efficiency if that stream transport's transmission unit is big enough to hold entire records, or at least significant parts of it. For example, if a record is fragmented across two transmission units, Mbed TLS would need to make a copy of the first before requesting the second, but could at least inspect the second one in place - however, even then it's not totally trivial to make this work, because it would require checking and removing record payload protection when the record ciphertext is not available as a single contiguous chunk. 
Also as mentioned above, for DTLS this problem doesn't occur, and I concur with you that it should be possible to work in place on the datagram provided by the underlying transport. This is being planned and implemented at the moment.

**Comment by deleisha** [comment]
@hanno-arm, Yes I read your earlier comment. I was answering pfalcon. 

Again reiterating, I am not sure how openssl does it, but they do it nice and fast.

**Comment by daverodgman** [comment]
Closing - this is a fairly minor optimisation with some complexity, as Hanno notes, with minor benefits and significant cost to introduce a new API for this.
