### ISSUE TITLE
Support for Base64UrlSafe

### ISSUE THREAD

**Issue by snowdream** [Mbed-TLS/mbedtls#1285]
How to encode and decode string with Base64UrlSafe?

**Comment by RonEld** [comment]
@snowdream Mbed TLS does not support Base64 URL safe.
As mentoined in [RFC4648](https://tools.ietf.org/html/rfc4648#section-5):
>This encoding is technically identical to the previous one, except
   for the 62:nd and 63:rd alphabet character, as indicated in Table 2.

On regular base64 n the 62nd character is `+` and the 63rd character is `/`. On Base64 URLSafe, the 62nd character is `-` and the 63rd character is `_`.
The current mapping of Base64 in Mbed TLS is done in [`base64_enc_map`](https://github.com/ARMmbed/mbedtls/blob/development/library/base64.c#L44) which specifies the encoding for every charater and in [`base64_dec_map`](https://github.com/ARMmbed/mbedtls/blob/development/library/base64.c#L55), where every index in the buffer is the ASCII value of the base64 character, and the value is the index in the encoding map.

**Comment by snowdream** [comment]
It is a useful feature,i wish it can be supported in the future.Thank you.

**Comment by x1ddos** [comment]
Base64 URL safe is useful to generate JWT.

**Comment by awakecoding** [comment]
+1 for base64url support, we are currently implementing JWT and we'll have to get base64url support from another library for now (mbedtls would have been perfect).

**Comment by moe123** [comment]
Hello, a quick  patch / duplicate for encoding (@note: you must drop padding too):

`

static const unsigned char base64url_enc_map[64] =
{
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd',
    'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
    'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
    'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7',
    '8', '9', '-', '_'
};

/*
 * Encode a buffer into base64url format
 */
int mbedtls_base64url_encode( unsigned char *dst, size_t dlen, size_t *olen,
                   const unsigned char *src, size_t slen )
{
    size_t i, n;
    int C1, C2, C3;
    unsigned char *p;

    if( slen == 0 )
    {
        *olen = 0;
        return( 0 );
    }

    n = slen / 3 + ( slen % 3 != 0 );

    if( n > ( BASE64_SIZE_T_MAX - 1 ) / 4 )
    {
        *olen = BASE64_SIZE_T_MAX;
        return( MBEDTLS_ERR_BASE64_BUFFER_TOO_SMALL );
    }

    n *= 4;

    if( ( dlen < n + 1 ) || ( NULL == dst ) )
    {
        *olen = n + 1;
        return( MBEDTLS_ERR_BASE64_BUFFER_TOO_SMALL );
    }

    n = ( slen / 3 ) * 3;

    for( i = 0, p = dst; i < n; i += 3 )
    {
        C1 = *src++;
        C2 = *src++;
        C3 = *src++;

        *p++ = base64url_enc_map[(C1 >> 2) & 0x3F];
        *p++ = base64url_enc_map[(((C1 &  3) << 4) + (C2 >> 4)) & 0x3F];
        *p++ = base64url_enc_map[(((C2 & 15) << 2) + (C3 >> 6)) & 0x3F];
        *p++ = base64url_enc_map[C3 & 0x3F];
    }

    if( i < slen )
    {
        C1 = *src++;
        C2 = ( ( i + 1 ) < slen ) ? *src++ : 0;

        *p++ = base64url_enc_map[(C1 >> 2) & 0x3F];
        *p++ = base64url_enc_map[(((C1 & 3) << 4) + (C2 >> 4)) & 0x3F];

        if( ( i + 1 ) < slen )
             *p++ = base64url_enc_map[((C2 & 15) << 2) & 0x3F];
    }

    *olen = p - dst;
    *p = 0;

    return( 0 );
}

`

**Comment by dimakuv** [comment]
+1. This would be a really helpful feature.

**Comment by davidhorstmann-arm** [comment]
Closing as the base64 module is likely to be removed from the public API.
