### ISSUE TITLE
Parameter validation checks required in public facing functions

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#1344]
### Description
- Type: Enhancement\Feature Request 
- Priority: Major 

---------------------------------------------------------------
## Enhancement\Feature Request

Some users have requested (such as in PR #1247) input validation checks in all functions that are part of the public interface.

This presents two challenges:
* the checks are not required by everyone, and are more useful on platforms where the system is open and unvalidated 3rd party code may make use of the interface. e.g. on a Linux system with Mbed TLS used as a dynamic library. On closed systems, such as embedded systems, where the caller is always known and statically linked to the library, the checks may be unnecessary overhead, as the user of the library may be able to be sure the parameters passed to the library will always be valid.
* these checks increase the overall code size, which may not be desirable on smaller, more constrained systems systems. 

**Justification - why does the library need this feature?**  

Such input validation is a common design feature to ensure software never enters into an unknown state, and is a standard technique to ensure CFI.

**Suggested enhancement**  

A validation macro be introduced to verify the parameters within certain constraints (e.g. `!= NULL`, `>= x`, `<= y`) which can be optionally compiled out using conditional compilation, or compiled in, and provide a valid error code if the parameters fail validation.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2078

**Comment by tom-cosgrove-arm** [comment]
@gilles-peskine-arm I'm inclined to close this, as lately we've been removing (NULL pointer) checks from the `mbedtls_` interface, and anyway we are going to be deprecating that in favour of the PSA interface, which I think has better parameter checking.

In other words, we aren't going to do this, now. Do you agree?

**Comment by gilles-peskine-arm** [comment]
We actually did this in 2.x, and then removed it in 3.0.
