### ISSUE TITLE
Add support for certificatePolicies extension

### ISSUE THREAD

**Issue by SteveAtSentosa** [Mbed-TLS/mbedtls#1415]
### Add support for certificatePolicies extension
- Type: Enhancement
- Priority: Major-ish
---------------------------------------------------------------

**Suggested enhancement**  

* Add `certificate_policies` (or similar) field to mbedtls_x509_crt struct, and populate it on cert parse.
* Provide supporting utilities such as `mbedtls_x509write_crt_set_certificate_policies()` (or similar)

**Comment by davidhorstmann-arm** [comment]
This support was added in #2530, closing.
