### ISSUE TITLE
NULL CIPHER WITH SHA2/SHA3

### ISSUE THREAD

**Issue by commandline-be** [Mbed-TLS/mbedtls#1418]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Enhancement\Feature Request
- Priority: Major

---------------------------------------------------------------
## Bug

**OS**  
Mbed OS|linux|windows|

**mbed TLS build:**  
Version: "not appicable"
OS version: "not appicable"  
Configuration: "not appicable"
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  "not appicable"
Additional environment information:  "not appicable"

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:   "not appicable"

**Expected behavior**   
"not appicable"
**Actual behavior**  
"not appicable"
**Steps to reproduce**  
"not appicable"
----------------------------------------------------------------
## Enhancement\Feature Request

For my own reasons i seek protocols which do not encrypt but only sign (encapsulate) for TLS >=1.0 upto TLS 1.3 ECDHE GCM AES SHA2 and/or SHA3 signing.

**Justification - why does the library need this feature?**  

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://tls.mbed.org/discussions)**

**Comment by sbutcher-arm** [comment]
It it the case that you don't want to encrypt traffic between the client and server, and you just want to authenticate the far end? Is that what you're asking for?

**Comment by commandline-be** [comment]
Yes. To provide integrity when encryption is not required. Especially on high volume sites it will also put less load on processing.

**Comment by daverodgman** [comment]
We do support several ciphersuites with a NULL cipher in TLS 1.2. We have no immediate plans to add more, but if there is an important use-case for a specific ciphersuite, we would consider adding it.
