### ISSUE TITLE
Mbed TLS dynamic library builds also produce static library

### ISSUE THREAD

**Issue by andresag01** [Mbed-TLS/mbedtls#1473]
### Description
- Type: Enhancement
- Priority: Minor

----------------------------------------------------------------
## Enhancement

**Justification - why does the library need this feature?**  
The Makefile in library/Makefile is building Mbed TLS both static and dynamic library when SHARED=1, but I would only have expected it to build the static version. Furthermore, different flags are used for the static library when built with(out) SHARED=1.

Furthermore, there several symbolic links to .so are generated as part of the build process, which seem unecessary.

**Suggested enhancement**  
It would be good to remove the redundant symbolic lincs to .so and make sure that the static libraries are not built when SHARED=1 (or at least ensure that the static builds are the same with/without SHARED=1).

**Comment by daverodgman** [comment]
Ideally we wouldn't build the static libraries when we don't need them, but this is harmless.
