### ISSUE TITLE
Check the AES-256-GCM implementation

### ISSUE THREAD

**Issue by shalec** [Mbed-TLS/mbedtls#1564]
Hey, I would like to check the implementation of AES-256 in GCM-Mode. Since this code is really branched, it would be great, if you could make a small "how to extract single-operation for validation purposes". 
Adding a test which requires the user to insert "key, IV, aad, cyphertext, GHash" would be enough for the most testing purposes.

**Comment by RonEld** [comment]
@shalec I apologize for delayed reply.
Don't the gcm test suites fit your needs? It uses standard test vectors for confirmation

**Comment by daverodgman** [comment]
The test suites should cover this.
