### ISSUE TITLE
mbedtls_zeroize should use platform-specific secure zeroize functions

### ISSUE THREAD

**Issue by andresag01** [Mbed-TLS/mbedtls#1584]
### Description
- Type: Enhancement
- Priority: Major

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
Mbed TLS provides an implementation for the function mbedtls_zeroize() that is portable across multiple platforms and compilers.

**Suggested enhancement**  
Whenever possible Mbed TLS should switch to using the platform-specific implementation of secure zeroize functions. For example, if compiling with C11 then use `memset_s()`

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2226

**Comment by daverodgman** [comment]
It looks like `memset_s` is not, and will not be, widely supported - it seems that it's being replaced with `memset_explicit` in C23. We'll look at adding support for this when a C23 compiler is available to test with.

**Comment by gilles-peskine-arm** [comment]
`memset_s` has been snubbed, but `explicit_bzero` is widespread enough that we should support it. See also some discussion in https://github.com/Mbed-TLS/mbedtls/issues/6229, and some old work in https://github.com/Mbed-TLS/mbedtls/pull/1760.

**Comment by daverodgman** [comment]
Fair enough, I've made a PR to cover some of the more common options.
