### ISSUE TITLE
ecdsa derive_mpi unused depending on compiler switches

### ISSUE THREAD

**Issue by HenrikRosenquistAndersson** [Mbed-TLS/mbedtls#1590]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.7.2, 2.8.0
Configuration: please attach config.h file where possible  
#define MBEDTLS_ECDSA_SIGN_ALT
//#ifdef MBEDTLS_ECDSA_DETERMINISTIC
#define MBEDTLS_ECDSA_VERIFY_ALT

Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

I have implemented ECDSA sign and verify by setting MBEDTLS_ECDSA_SIGN_ALT and MBEDTLS_ECDSA_VERIFY_ALT defines. I have also switched off MBEDTLS_ECDSA_DETERMINISTIC.

When building I get an error in my environment since function derive_mpi isn't used anymore.

I would like a switch around that function
#if !defined(MBEDTLS_ECDSA_SIGN_ALT) || defined(MBEDTLS_ECDSA_DETERMINISTIC) || !defined(MBEDTLS_ECDSA_VERIFY_ALT)

**Peer device TLS stack and version**  
Other  
Version:  

**Expected behavior**   
No build error
**Actual behavior**  
Build error
**Steps to reproduce**  
Se description

**Comment by RonEld** [comment]
@HenrikRosenquistAndersson 
Thank you for raising this issue! We will look at the proper way to fix it.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2240

**Comment by daverodgman** [comment]
Already fixed by #4008
