### ISSUE TITLE
Make GCC armv8 (aarch64) compilation use 64bit bignum 

### ISSUE THREAD

**Issue by dbedev** [Mbed-TLS/mbedtls#1636]
### Description
- Type:  Enhancement\Feature Request 
- Priority:Minor
----------------------------------------------------------------
## Enhancement\Feature Request

When compiling for armv8 (aarch64) using gcc(4.9) the bignum.h always takes the 32bit path.
It should be possible to take the 64bit path as is done for the other 64bit cpu targets. 

**Justification - why does the library need this feature?**  
This result in a performance improvement for RSA/ECC operations (Measured ~10% on my Cortex A53  board (aarch64)).

**Suggested enhancement**  

Add  defined(__aarch64__)  as additional GCC architecture in bignum,h basetype integer determination

For even better performance on armv8 overall one had probably best add specific asm for aarch64 as part of bn_mul.h, but I have no idea how to do this or what it's gain would be.

**Comment by tom-cosgrove-arm** [comment]
Closing as completed by https://github.com/ARMmbed/mbed-crypto/pull/240
