### ISSUE TITLE
abi_check.py should work with branches that have / in their name

### ISSUE THREAD

**Issue by Patater** [Mbed-TLS/mbedtls#1637]
### Description
- Type: Enhancement
- Priority: Minor

----------------------------------------------------------------
## Enhancement

When checking for ABI or API changes, it's good to be able to use branches that have `/` in their name.

Replace `/` with underscore before creating folders on disk for the ABI checks.

**Comment by daverodgman** [comment]
Closing - we do not have any active branches with a slash in the name

**Comment by gilles-peskine-arm** [comment]
The name of the head branch can have slashes. And we may well want to use the script with e.g. a feature branch called `feature/stuff`. But I'm not seeing the problem in the current version of the script (maybe we fixed that but had forgotten it used to be a documented problem).
