### ISSUE TITLE
Support of XCBC MAC-96 rfc3566

### ISSUE THREAD

**Issue by meghaamity** [Mbed-TLS/mbedtls#1652]
Description
- Type: Feature Request
- Priority: Blocker

**Justification - why does the library need this feature?**  
This is needed to verify support of XCBC-MAC as per RFC3566 in Automative Security FW
for our project.
When do you plan to implement it?

**Comment by hanno-arm** [comment]
Hi @meghaamity,

thanks for your request! Could you confirm that you need this as a standalone cryptographic feature, or do you intend to use it with TLS?

Kind regards,
Hanno, Mbed TLS team member

**Comment by meghaamity** [comment]
Hello,
I will use it first for standalone cryptographic feature to validate XCBC functionality/ But later user case is of TLS.
standalone cryptographic feature is more critical as if now

Regards,
Megha

**Comment by hanno-arm** [comment]
Hi @meghaamity,

could you point to the standard defining the use of XCBC-MAC with TLS? I am not aware of such.

For now, I am marking this as a cryptographic feature request.

Kind regards,
Hanno

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2322

**Comment by tom-daubney-arm** [comment]
This is not on our roadmap for the forseeable future.
