### ISSUE TITLE
Create a gfmul module that can be ALT implemented

### ISSUE THREAD

**Issue by Patater** [Mbed-TLS/mbedtls#1660]
Note, this has been filed due to feedback on PR #1602. This issue is not relevant until #1602 is merged.

### Description
- Type: Enhancement
- Priority: Minor

## Enhancement\Feature Request

**Justification - why does the library need this feature?**
Currently, gf128mul is used only by the AES XTS implementation. If we extend that function or make others like it, and use them in other places to efficiently multiple within GFs, then we should consider making gfmul into a module.

A gfmul module would provide an optimized multiplication within a GF (e.g. GF(128)). It'd be useful to be able to swap out the implementation provided by the library with a custom, perhaps OS- or hardware-specifc implementation, using an Mbed TLS ALT interface.

**Suggested enhancement**
A gfmul module should be created that allows ALT implementations and should it should also define an error code MBEDTLS_ERR_GF128MUL_HW_ACCEL_FAILED.

**Comment by daverodgman** [comment]
The ALT interface is now deprecated.
