### ISSUE TITLE
MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT needs further tests

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#1661]
### Description
- Type: Enhancement\Feature Request
- Priority: Major

---------------------------------------------------------------
## Bug

As discussed in #1390, `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` needs to be explicitly tested in `all.sh`. 

Also as identified by @gilles-peskine-arm in #1390:

> * No compile-time error `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` and `MBEDTLS_DEPRECATED_REMOVED` are both set.
> * `config.pl full` enabling `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` which is a behavior change and not a feature. (That's not the only one, there's also `RSA_NO_CRT`, for example.)
> * It is legitimate for config.pl full to enable a deprecated feature. This is a design issue in my PR. @andresag01 @mpg Now that Hanno mentions it, I think the DEPRECATED checks should only be done in the default configuration. And we also need a test with the full config; @mpg added one independently in #1243. I propose to switch to the default configuration for DEPRECATED checks here and let #1243 handle the full config test improvements, what do you think?

Therefore, we probably need to consider the following changes:
 * some testing of `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` needs to be tested in `all.sh`
 * `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` probably also needs removing from `config.pl full` as suggested by @mpg, because it's not part of the default 'full config' and should be omitted from tests involving all features to be enabled
 * a test that combines `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT` and MBEDTLS_DEPRECATED_REMOVED is probably needed, as `MBEDTLS_SSL_TRUNCATED_HMAC_COMPAT`should throw a warning about being deprecated.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2371

**Comment by daverodgman** [comment]
This was removed in 3.0.
