### ISSUE TITLE
Speed up XORing of large numbers

### ISSUE THREAD

**Issue by Patater** [Mbed-TLS/mbedtls#1666]
### Description
- Type: Enhancement
- Priority: Minor
----------------------------------------------------------------

## Enhancement

**Justification - why does the library need this feature?** 
The crypto is slow and can easily be much faster on most hardware.
 
**Suggested enhancement**  
Replace loops that XOR large numbers byte-by-byte with a function that XORs large numbers efficiently. The function should take advantage of the hardware available to XOR as much at a time as possible, instead of XORing byte-by-byte. An easy first step would be to XOR 32 bits at a time using a 32-bit register.

See an example of a slow XOR loop in `mbedtls_aes_crypt_cbc()`. A suggested replacement is below.
```diff
-            for( i = 0; i < 16; i++ )
-                output[i] = (unsigned char)( output[i] ^ iv[i] );
+            mbedtls_veryfast_xor(output, iv);
```

**Comment by daverodgman** [comment]
Quick test confirmed a 17x improvement on Cortex m0 by doing a very simple 4-bytes-at-a-time implementation. 8 bytes at a time performed identical to 4.
