### ISSUE TITLE
Deprecate mbedtls_gcm_crypt_and_tag, introduce mbedtls_gcm_encrypt_and_tag

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#1674]
The function `mbedtls_gcm_crypt_and_tag` can be used both to encrypt and decrypt, but in decrypt mode, it doesn't authenticate! This is confusing. #1668 and backports point this out in the documentation. We should go further and do the same as CCM: have a function `mbedtls_gcm_encrypt_and_tag` which only does encryption, alongside the existing function `mbedtls_gcm_auth_decrypt`. Then we can officially deprecate `mbedtls_gcm_crypt_and_tag`.

**Comment by daverodgman** [comment]
Given that the legacy interface will be deprecated, it's not worth re-arranging the GCM legacy API at this point in time (especially since the docs have now been clarified).
