### ISSUE TITLE
parsing failure of PKCS12 file, with supported algorithm

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#1700]
### Description
- Type: Bug 
- Priority:  Minor

Actually, I am not currently sure if this is a bug or an unsupported feature.
According to an online ASN.1 parser(https://lapo.it/asn1js) the format within is PKCS7 which is unsupported, but the encryption algorithm itself (`pbeWithSHAAnd128BitRC4`) is supported

Raised by Heiko Demlang by Email

---------------------------------------------------------------
## Bug

**OS**  
linux|

**mbed TLS build:**  
Version: developemnt
Version:  

**Expected behavior**   
parsing success
**Actual behavior**  
parsing failure with error 0x3d00
**Steps to reproduce**  
~~~
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365
openssl pkcs12 -export -out ssl_pkcs12.pfx -inkey key.pem -in cert.pem -certpbe PBE-SHA1-RC4-128 -keypbe PBE-SHA1-RC4-128
./key_app mode=private filename=ssl_pkcs12.pfx password=<file_password>
~~~

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2355
