### ISSUE TITLE
Testing gap for MBEDTLS_PK_RSA_ALT_SUPPORT feature

### ISSUE THREAD

**Issue by andresag01** [Mbed-TLS/mbedtls#1754]
### Description
- Type: Enhancement
- Priority: Minor

Mbed TLS has a configuration option `MBEDTLS_PK_RSA_ALT_SUPPORT` that allows users to configure an alternative implementation of  RSA operations in the PK module that does not use the default code in `library/pk_wrap.c`. There are some simple unit tests for this feature in `tests/suites`, but integration tests with the SSL module are missing. At the minimum, there should be sanity tests to ensure this feature (which is already present in the library) works well when establishing basic SSL connections, but ideally tests would include more cases such as all ciphersuites with RSA.

Note that this testing gap should be resolved before further additions for alternative primitive support in the PK module can be merged into Mbed TLS. Specifically, this blocks the addition of alternative ECDSA for the PK module for which there is [this](https://github.com/ARMmbed/mbedtls/pull/846) pending PR, which is also missing integration tests.

**Comment by tom-cosgrove-arm** [comment]
Closing this as the `ALT` interface is not going to get any enhancements - this kind of thing is handled by PSA drivers now. At some point in the future the `ALT` interfaces will be deprecated then eventually removed.
