### ISSUE TITLE
CMake build files don't permit cross-compilation

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#1761]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor

----------------------------------------------------------------
## Enhancement\Feature Request

The CMake files don't allow specification of a compiler for a different target from the host. For instance, you can't do something like:

`CC=arm-none-eabi-gcc cmake .`
or
`cmake -DCMAKE_C_COMPILER="arm-none-eabi-gcc" .`

That's because CMake tests the compiler that's provided, by compiling a simple file to ensure it works. A compiler for a different target will fail this, and the [CMake documentation](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling) suggests the compiler needs to be forced using `CMAKE_FORCE_C_COMPILER`.

This isn't wholly true as the IAR Compiler does provide cross-compilation on Windows - but that's one compiler on one platform.

**Justification - why does the library need this feature?**  

Mbed TLS is used as an embedded library as much as a workstation or server library, so the build system should reasonable support this.

**Suggested enhancement**  

I suggest creating a new build type of 'Cross-compile' for `CMAKE_BUILD_TYPE`, that forces the compiler. That probably needs study.

**Comment by mazimkhan** [comment]
One solution is to create a toolchain file per compiler/+target. For cross compilation toolchain file can be supplied on command line as:
```
-D CMAKE_TOOLCHAIN_FILE:String="<path to toolchain.cmake>"
```

Following is a sample toolchain.cmake for arm gcc that I use in my hobby project :
```
include(CMakeForceCompiler)

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_SYSTEM_PROCESSOR "armv7-m")
find_program(GCC arm-none-eabi-gcc)
find_program(GXX arm-none-eabi-g++)
set(CMAKE_C_COMPILER "${GCC}")
set(CMAKE_CXX_COMPILER "${GXX}")

CMAKE_FORCE_C_COMPILER(arm-none-eabi-gcc GNU)
CMAKE_FORCE_CXX_COMPILER(arm-none-eabi-g++ GNU)

# keep every function in a separate section, this allows linker to discard unused ones
set(TOOLCHAIN_C_FLAGS "-mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
set(TOOLCHAIN_C_FLAGS "${TOOLCHAIN_C_FLAGS} -ffunction-sections -fdata-sections -fno-strict-aliasing")
set(TOOLCHAIN_C_FLAGS "${TOOLCHAIN_C_FLAGS} -fno-builtin -fshort-enums")
set(TOOLCHAIN_C_FLAGS "${TOOLCHAIN_C_FLAGS} -DENABLE_RETARGET")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${TOOLCHAIN_C_FLAGS}")

link_directories(
    <path to linker file>
)

set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--gc-sections")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --specs=nano.specs --specs=nosys.specs")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -T<linker file name>")
```

**Comment by daverodgman** [comment]
I've tried this and it now works - closing
