### ISSUE TITLE
add key wrapping with Camellia

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#1789]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor

Enhance the `nist_kw` module to support Camellia cipher as well, as defined in RFC 3657

## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
ENhance the key wrapping feature, with minimal changes

**Suggested enhancement**  
Add `MBEDTLS_CIPHER_ID_CAMELLIA` as a supported cipher, add test vectors, and add the OID for it, if exists.

**Comment by daverodgman** [comment]
Closing - we are unlikely to implement this unless there is a clear external request for this.

**Comment by gilles-peskine-arm** [comment]
@daverodgman Counterpoint: having different levels of support for different block ciphers complicates our test code, so we might decide to do it as a technical debt reduction, even if nobody wants it in production.
