### ISSUE TITLE
README explaining test suites framework design and usage

### ISSUE THREAD

**Issue by mazimkhan** [Mbed-TLS/mbedtls#1843]
Should be fixed after #930, since that modifies the framework.

Following, information should be added to the README
* Explain workflow of generating test suite source and building.
* Steps for testing on target testing. Add mbed-os example.
* Different ways of executing tests on host and target.

**Comment by aditya-deshpande-arm** [comment]
We do not have target tests at the moment, so can't have documentation for something not supported.

**Comment by gilles-peskine-arm** [comment]
This issue was about the unit test framework in general, not just on-target tests. But the part not about on-target tests is fulfilled by the [knowledge base entry](https://mbed-tls.readthedocs.io/en/latest/kb/development/test_suites/).
