### ISSUE TITLE
interoperability with gnutls-cli tests fail on CI because using IPV6, in ssl-opt.sh

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#1851]
### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: development
OS version: Linux
Additional environment information:  IPv6 enabled for `lo` interface

**Peer device TLS stack and version**  
GnuTls
Version:  
3.4.10

**Expected behavior**   
gnutls-cli succeeds to have a DTLS negotiation with ssl_server2
**Actual behavior**  
gnutls-cli fails to send messages over UDP

**Steps to reproduce**  
~~~
ssl_server2 server_addr=127.0.0.1 server_port=<portnum> dtls=1
gnutls-clli -u -p <portnum> localhost
~~~
gnutls-cli translates `localhost` to IPv6 address ( ::1) and fails sending message, because the server is forced to bind to IPV4 address (127.0.0.1)

**Comment by RonEld** [comment]
ARM Internal Ref: IOTSSL-2392

**Comment by RonEld** [comment]
A work around is to disable IPv6 on the CI, or force the server to bind to IPv6 address, but this is not the purpose of thetest

**Comment by mpg** [comment]
I think it's worth noting that the failure is not in any of the existing test so far, only in a test you want to add.

**Comment by RonEld** [comment]
Correct, but that's just because there aren't any interop tests with gnutls-cli over UDP in ssl-opt.sh

**Comment by RonEld** [comment]
Reduced priority, as there is a workaround, and this issue doesn't rerpoduce on existing tests

**Comment by RonEld** [comment]
Changed to a task to change all the certificates to use IPv4 addresses, instead of `localhost` ,except the tests checking IPv6.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because we haven't had IPv6-related failures for a while. The way we test, or don't test IPv6, might not be ideal, but at the moment there is no concrete problem to fix.
