### ISSUE TITLE
Refactor mbedtls_x509_string_to_names() to support RFC 1779

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#1865]
### Description
- Type: Bug | Enhancement
- Priority: Major

[RFC 1779](https://tools.ietf.org/html/rfc1779#section-2.3) defines characters that need to be in quoted strings. 
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
This implies that if those characters are not quoted, then the distinguished name is not valid.
Current behavior is that those characters (except comma, as introduced in #784) are accepted as valid names in the distinguished name.

**Suggested enhancement**  
Accept the following only in quotations, otherwise, return error:

    o  Strings containing ",", "+", "=" or """ , <CR>, "<",
       ">", "#", or ";".

    o  Strings with leading or trailing spaces

    o  Strings containing consecutive spaces

Add tests for such cases and corner cases

**Comment by daverodgman** [comment]
Output was covered in #5861, but looks like parsing was not addressed

**Comment by daverodgman** [comment]
Closing this as a duplicate.
