### ISSUE TITLE
Test that dependencies on cipher algorithms work correctly

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#1892]
On the same model as `depends-hashes.pl` and `depends-pkalgs.pl`, we should have a `depends-ciphers.pl` that checks that the library code and test cases have all correct dependencies on symmetric cipher algorithms, block cipher modes and padding modes.

Internal ref: IOTSSL-1657

**Comment by AndrzejKurek** [comment]
https://github.com/Mbed-TLS/mbedtls/pull/6385 is now ready for review.
