### ISSUE TITLE
MPI inline assembly doesn't compile for PIC on i386 with older gcc

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#1910]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: mbedtls-2.12.0  

With older versions of gcc, Mbed TLS is unable to compile in very specific circumstances:-

 * if optimisation is enabled (e.g. `-O1` or `-O2`)
 * for an i386 target
 * with a version of gcc at least earlier than v6
 * when position independent code is enable for a shared library (e.g. `-fPIC` and `-shared`)

The problem is that the inline assembly for i386 specifies a lot of registers to clobber, and older versions of gcc can't compile with so few registers.

To reproduce the fault:-

 * use an older version of Debian i386. I used Jessue 8.5 (which at time of writing is old but still supported). It supplies gcc version 4.9.2.
 * download the Mbed TLS source code and execute the command:
```
gcc -O2 -fPIC -Iinclude -shared library/bignum.c
```
This will result in the following error:
```
In file included from library/bignum.c:47:0:
library/bignum.c: In function ‘mpi_mul_hlp’:
include/mbedtls/bn_mul.h:46:13: error: PIC register clobbered by ‘ebx’ in ‘asm’
 #define asm __asm
             ^
include/mbedtls/bn_mul.h:62:5: note: in expansion of macro ‘asm’
     asm(                                    \
     ^
library/bignum.c:1142:9: note: in expansion of macro ‘MULADDC_INIT’
         MULADDC_INIT
         ^
include/mbedtls/bn_mul.h:46:13: error: PIC register clobbered by ‘ebx’ in ‘asm’
 #define asm __asm
             ^
```
Workarounds
-------------

There’s a couple of ways around this:

- the easiest option is probably going to be to update the compiler. The code will work with gcc 7 and gcc 6 with no issue. There's also no issue with clang, so swapping to clang may fix this.

- you can specify to turn off inline assembly. This can be done by commenting out the line `’#define MBEDTLS_HAVE_ASM` in the Mbed TLS configuration file, found in `include/mbedlts/config.h`. That slows down some of the asymmetric crypto operations slower, but at least it builds.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2461

**Comment by wyattoday** [comment]
We encountered this bug and worked around this problem by modifying `include/mbedtls/bn_mul.h` to not use the i386 assembly with -fPIC is used during the compilation. So, modifying this...

```
#if defined(__i386__) && defined(__OPTIMIZE__)

#define MULADDC_INIT                        \
    asm(                                    \
....
```


To this:


```
#if defined(__i386__) && defined(__OPTIMIZE__) && !defined(__PIC__)

#define MULADDC_INIT                        \
    asm(                                    \
....
```



Note that `__PIC__` is defined if -fPIC is used during compilation.

**Comment by mckaygerhard** [comment]
we need #1986 merged please

**Comment by gilles-peskine-arm** [comment]
@mckaygerhard Can you please make a rebased version of it for the three supported branches (`development`, `development_2.x`, `mbedtls-2.16`)?

**Comment by mckaygerhard** [comment]
i can help with that.. for the weekend if you guys wait for me! thanks to accept the proposal

**Comment by mckaygerhard** [comment]
I forgot about this, I was too busy, this patch must be apply ..  yet many devices still use gcc 4.X for example embedded... this patch should still be supported because linux kernels like 4.X are still in use... for devices that can't use 5.X as an example, i cannot rebase, cos i used older devices (have a lot of those with large life and i will not change  cos represent a cost)

**Comment by tom-cosgrove-arm** [comment]
Note that the supported branches are now `development` and `mbedtls-2.28`
