### ISSUE TITLE
Documentation of mbedtls_x509_crt_profile imprecise

### ISSUE THREAD

**Issue by hanno-arm** [Mbed-TLS/mbedtls#1992]
The documentation states:

```c
/**
 * Security profile for certificate verification.
 *
 * All lists are bitfields, built by ORing flags from MBEDTLS_X509_ID_FLAG().
 */
typedef struct mbedtls_x509_crt_profile
{
    uint32_t allowed_mds;       /**< MDs for signatures         */
    uint32_t allowed_pks;       /**< PK algs for signatures     */
    uint32_t allowed_curves;    /**< Elliptic curves for ECDSA  */
    uint32_t rsa_min_bitlen;    /**< Minimum size for RSA keys  */
}
mbedtls_x509_crt_profile;
```

This reads as if `allowed_pks` only guards the signatures of certificates in a certificate chain - which would exclude the PK type of the initial CRT itself. However, the [CRT verification](https://github.com/ARMmbed/mbedtls/blob/development/library/x509_crt.c#L2354) checks the PK type of the initial CRT against `allowed_pks`, too:

```c
int mbedtls_x509_crt_verify_with_profile( mbedtls_x509_crt *crt,
                     mbedtls_x509_crt *trust_ca,
                     mbedtls_x509_crl *ca_crl,
                     const mbedtls_x509_crt_profile *profile,
                     const char *cn, uint32_t *flags,
                     int (*f_vrfy)(void *, mbedtls_x509_crt *, int, uint32_t *),
                     void *p_vrfy )
{
    mbedtls_pk_type_t pk_type;

    ...

    /* Check the type and size of the key */
    pk_type = mbedtls_pk_get_type( &crt->pk );

    if( x509_profile_check_pk_alg( profile, pk_type ) != 0 )
        *ee_flags |= MBEDTLS_X509_BADCERT_BAD_PK;
```

The documentation should either state that `allowed_pks` applies to the PK types of all public keys in the CRT chain, or the implementation should be changed to not check the PK type of the initial CRT.

cc @mpg

**Comment by mpg** [comment]
I agree, I remember noticing that during the refactoring. I think it would be more logical to do as the documentation says and just check the signatures inside the chain, as this is what `verify_with_profile()` is about, and checking the type and size/curve on the key in the end-entity (EE) cert belongs more in the part that uses it (eg the SSL/TLS module would check that as the key of the EE cert is used in the handshake).

However, I'm a bit concerned about changing observable behaviour here as some applications might have been written to rely on this undocumented behaviour, and removing that check could in principle reduce security if the application relied on it. (Here I'm thinking non-TLS users obviously, as for TLS we control the part that uses the cert and would be able to add missing checks if any.)

So I'm inclined towards one of the following courses of action:
1. Change the behaviour now in the development branch and clearly state that in the ChangeLog, but in the LTS branches change the documentation instead.
2. Change the documentation now in all branches, and change behaviour only in Mbed TLS 3.0.0.

Actually I think I'd prefer option 1, as waiting for 3.0.0 might not be optimal as the change announcement would likely be buried along with many other changes in the ChangeLog - OTOH, perhaps that's the point where users are most likely to read the Changes section carefully?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2490

**Comment by hanno-arm** [comment]
@mpg Since, as you say, changing the code is a semantic API break which can result in a weakening of security guarantees for some users without them necessarily noticing, I am in favour of option 2., clarifying the documentation but postponing behavioural change to 3.0.0. Are you ok with me going forward and making the corresponding change in the documentation?

**Comment by mpg** [comment]
Yes, absolutely!
