### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by embedthis** [Mbed-TLS/mbedtls#201]
So MbedTLS can be downloaded and installed by package managers (npm, bower, Pak), we should add a package.json.

I've got one prepared and can submit a pull request. The build process then would need to update the version field in the package.json file.

The benefit of having a package.json is MbedTLS can be installed and consumed easily:

```
pak install mbedtls
```

I've got a separate issue open that addresses creating amalgamated releases (single file distributions) and with that, this kind of installation and upgrading works very easily.

**Comment by embedthis** [comment]
A package.json would look something like this:
```
{
    "name": "mbedtls",
    "version": "1.3.11",
    "description": "MbedTLS Source Code",
    "license": "GPLv2",
    "keywords": [
        "mbedtls",
        "ssl",
        "tls"
    ],
    "repository": {
        "type": "git",
        "url": "git://github.com/ARMmbed/mbedtls.git",
    },
    "files": [
        "dist/"
    ]
}
```

**Comment by pjbakker** [comment]
Thanks. We will look into this.

**Comment by embedthis** [comment]
Great. The "files" section points to a "dist" directory that would hold the amalgamated release. Package managers will by default install files under dist (only) into the local application directory. 

Our work flow is then

pak install mbedtls

You then get
```
lib/mbedtlsLib.c
lib/mbedtls.h
```
You can then do

pak upgrade mbedtls

and it will upgrade. You can of course specify the SemVer version in package.json, so if you must stay on 1.3 for example, you can do the following in your application package.json
```
"dependencies": {
    "mbedtls": "^1.3"
}
```

**Comment by embedthis** [comment]
Working on this now. Will have a pull request next week.

**Comment by tom-daubney-arm** [comment]
Closing due to lack of demand.
