### ISSUE TITLE
HMAC trauncated SHA2-512-225,SHA512-224 support missing

### ISSUE THREAD

**Issue by meghaamity** [Mbed-TLS/mbedtls#2022]
- Type: Enhancement\Feature Request
- Priority: Blocker
----------------------------------------------------------------
## Enhancement\Feature Request

**Justification:This is requirement for automotive security firmware.
MAC service implementing HMAC_SHA512/224 algorithm as defined in FIPS 198-1 and SP 800-107
MAC service implementing HMAC_SHA512/256 algorithm as defined in FIPS 198-1 and SP 800-107

See also: #1653

**Suggested enhancement**  

-----------------------------------------------------------------

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**

**Comment by sbutcher-arm** [comment]
Thanks for the feedback! We'll look into it.

**Comment by daverodgman** [comment]
This feature request is covered by #1653 - closing
