### ISSUE TITLE
MBEDTLS_SSL_HW_RECORD_ACCEL untested

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#2026]
__Issue:__ The compilation option `MBEDTLS_SSL_HW_RECORD_ACCEL` is untested and insufficiently documented in `config.h`.

**Comment by gilles-peskine-arm** [comment]
It doesn't even compile when DTLS is enabled. The internal function `ssl_swap_epochs`, which is DTLS-only, has been broken since before the Great Renaming. It does compile with DTLS disabled.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2544

**Comment by andresag01** [comment]
The PR https://github.com/ARMmbed/mbedtls/pull/2263 deprecates this feature.

**Comment by daverodgman** [comment]
Removed in 3.0
