### ISSUE TITLE
Missing dependencies on MBEDTLS_MD_C

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#2202]
Minor — the library doesn't build in a configuration that nobody has complained about to my knowledge, but is sensible nevertheless.

Some functions or modules are missing a dependency on `MBEDTLS_MD_C`. For example: `MBEDTLS_PKCS5_C` and `MBEDTLS_PKCS1_V21` intrinsically depend on `mbedtls_md_xxx` functions. Some parts of `rsa.c` and `pk.c` depend on `mbedtls_md_xxx` functions, but other parts of these modules can be used without md.

Builds without `md.c` aren't common, but this could be useful for tiny builds. You can still have symmetric encryption (including authenticated encryption), CMAC, RSA PKCS#1v1.5 encryption, ECDH, DHM, and even ECDSA randomized signature without any hash function (or manually combined with one individual hash module).

**Comment by daverodgman** [comment]
I've just made a quick test and successfully built using `config-symmetric-only.h`, with `MBEDTLS_HKDF_C`, `MBEDTLS_HMAC_DRBG_C` and `MBEDTLS_MD_C` disabled, but `MBEDTLS_PKCS5_C` and `MBEDTLS_PKCS1_V21` enabled.

Are you aware of any remaining issues or should this be closed?
