### ISSUE TITLE
Add MBEDTLS_ECDSA_DETERMINISTIC to depends-pkalgs.pl

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#2203]
`depends-pkalgs.pl` tests without `MBEDTLS_ECDSA_C`, among others. It should also test a build with `MBEDTLS_ECDSA_C` but without `MBEDTLS_ECDSA_DETERMINSTIC`.

**Comment by mpg** [comment]
Closing in favour of #6438
