### ISSUE TITLE
Enumeration detection in check-names.sh doesn't work properly with multiline comments

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#2210]
__Context:__ The script `tests/scripts/check-names.sh` calls `tests/scripts/list-enum-consts.pl` to extract all defined enumeration constants from the code and subsequently checks that they conform to the `MBEDTLS_XXX` naming scheme.

__Issue:__ `list-enum-consts.pl` doesn't work properly when facing multiline comments in enumerations, such as in 
```c
typedef enum X 
{
    MBEDTLS_X_0 = 0, /* This is a very important identifier
                      * which deserves explanation and documentation
                      * over multiple lines. */
};
```
In this case, `list-enum-consts.pl` treat all but the first comment lines as identifiers and consequently `check-names.sh` fails.

**Comment by daverodgman** [comment]
Closing - there is a simple work-around and the failure case doesn't impact users.

**Comment by gilles-peskine-arm** [comment]
I think this is actually fixed. The python reimplementation of `check_names` parses comments correctly, so I don't think it has this particular bug.
