### ISSUE TITLE
mbedtls_mpi_write_string() could be reduced to use less RAM.

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#2216]
### Description
- Type: Enhancement\Feature Request
- Priority:  Major
As mentioned in https://github.com/ARMmbed/mbedtls/pull/2214#pullrequestreview-176770100, `mbedtls_mpi_write_string()` could be reduced to use less RAM.

## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
It always best to reduce RAM usage, and `mbedtls_mpi_write_string()` is not time-critical 

**Suggested enhancement**  
From https://github.com/ARMmbed/mbedtls/pull/2214#pullrequestreview-176769133:
>Let's safe some bytes and RAM here instead, by not using `T`. Suggestion: Document that `mpi_write_hlp()` ignores the sign and just pass `X` instead of the local copy `T`.

From https://github.com/ARMmbed/mbedtls/pull/2214#pullrequestreview-176770100:
> I think we should call `mpi_write_hlp()` even for radix 16 and get rid of the `radix == 16` branch - it might not be as fast as the hand-coded version, but `mbedtls_mpi_write_string()` is not time-critical anyway.

**Comment by daverodgman** [comment]
Closing - this is only likely to be used in debug builds, so impact is very limited.
