### ISSUE TITLE
PSA: libmbedcrypto.a no longer depends on config.h

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#2238]
### Description
- Type: Bug 
- Priority: Blocker

## Bug

**OS**  
linux - but probably any

**mbed TLS build:**  
Version: branch development-psa  
Additional environment information:  using cmake without `USE_CRYPTO_SUBMODULE`

**Steps to reproduce**  

```
git checkout development-psa
cmake .
make lib
touch include/mbedtls/config.h
make lib
```

**Expected behavior**   

At the last step above, all files contributing to `libmbedcrypto.a` should be rebuilt.

**Actual behavior**  

None of them are - only files contributing to `libmbedx509.a` or `libmbedtls.a` are.

**Comment by mpg** [comment]
cc @Patater 

Sorry, I didn't have any time to investigate yet.

**Comment by tom-cosgrove-arm** [comment]
Closing as this is no longer an issue (tested by @mpg)
