### ISSUE TITLE
Please provide a pkgconfig .pc file

### ISSUE THREAD

**Issue by rubenk** [Mbed-TLS/mbedtls#228]
This would make downstream's life a bit easier.

**Comment by mpg** [comment]
Please excuse my ignorance about pkgconfig and .pc file, but could you please give me a few pointers? Is that specific to one package manager, or can it be used by many of them? If it's specific to one, I'm not sure we want to include that in our distribution, otherwise we'll consider it.

**Comment by rubenk** [comment]
Hi @mpg,

Any project that uses pkg-config (http://www.freedesktop.org/wiki/Software/pkg-config/) can use this file. The autotools have macros to use and create this file, I'm not sure about Cmake.

To give you one example, sqlite drops this file in /usr/lib64/pkgconfig/sqlite3.pc:
```
$ cat /usr/lib64/pkgconfig/sqlite3.pc 
# Package Information for pkg-config

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: SQLite
Description: SQL database engine
Version: 3.8.11
Libs: -L${libdir} -lsqlite3
Libs.private: -ldl -lpthread 
Cflags: -I${includedir}
```
And in powerdns we use the following macro to check if sqlite is installed, and pick up the CFLAGS and LDFLAGS we need:

```
PKG_CHECK_MODULES([SQLITE3], [sqlite3],
      [AC_DEFINE([HAVE_SQLITE3], [1], [Define to 1 if you have sqlite3])],
      [AC_MSG_ERROR([Could not find libsqlite3])]
    )
```

Non-autotools-based projects can also call pkg-config manually, for example:
```
$ pkg-config --libs sqlite3
-lsqlite3 
```

**Comment by mpg** [comment]
Thanks for the info! We'll look into it.

**Comment by lulcat** [comment]
Love this world... here people are writing to-end crypto but haven't heard of pkgconfig. What's next elephants will start dressing in pink panties, throwing tantrums and being general dramaqueens on the savannah? :)

**Comment by janekolszak** [comment]
+1

**Comment by imzxs** [comment]
There is an article about [how to generate a pkg-config file with cmake](http://dailycommit.blogspot.com/2016/10/how-to-generate-pkg-config-file-with.html), that look like very easy.

**Comment by tom-daubney-arm** [comment]
Closing this issue as it will not be worked on in the near future. If someone would like to provide a .pc file via PR then they are more than welcome to do so.

**Comment by Tachi107** [comment]
Hi @tom-daubney-arm, could you please mark the issue as "not planned" instead of "completed"?

In any case, I think I'll look into this issue somewhat soon. Thanks for the ping :)

**Comment by billatarm** [comment]
I have a PR incoming for this
