### ISSUE TITLE
request MISRA C-compliant

### ISSUE THREAD

**Issue by bingzhux** [Mbed-TLS/mbedtls#2303]
## Description
- Type:  Enhancement\Feature Request 
- Priority:  Minor
Can mbedtls be MISRA-C-compliant?
https://en.wikipedia.org/wiki/MISRA_C

----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  

As we want to use mbedtls lib in automotive system, which requires Functional Safety certificates:
https://en.wikipedia.org/wiki/Functional_safety 
https://en.wikipedia.org/wiki/ISO_26262 

one of requirements is to be MISRA C-compliant.

**Comment by RonEld** [comment]
Hi @bzhu5 
Thank you for your query.
Yes, the automotive industry requires functional safety certifications including MISRA-C compliancy.
Mbed TLS is not MISRA-C compliant, and there is no immediate plan in making it MISRA-C compliant at the moment.
I apologize as this is not what you wanted to hear.

**Comment by bzhu5** [comment]
Thanks for your response quickly. 
but I would hope there would be a long term plan:)

**Comment by daverodgman** [comment]
We are unlikely to add support for MISRA in the foreseeable future.
