### ISSUE TITLE
Documentation of MBEDTLS_SHAxxx_ALT misleading

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#2307]
The documentation of `MBEDTLS_XXX_ALT` in `config.h` on the one hand states
```
 * MBEDTLS__MODULE_NAME__ALT: Uncomment a macro to let mbed TLS use your
 * alternate core implementation of a symmetric crypto, an arithmetic or hash
 * module (e.g. platform specific assembly optimized implementations). Keep
 * in mind that the function prototypes should remain the same.
```
but also
```
 * This replaces the whole module. If you only want to replace one of the
 * functions, use one of the MBEDTLS__FUNCTION_NAME__ALT flags. 
```
This seems contradictory. Which functions _are_ replaced in the end? The second part reads as if the entire module is replaced, but e.g. defining `MBEDTLS_SHAxxx_ALT` doesn't remove the definition of `mbedtls_shaxxx_ret()` from `shaxxx.c`. 

The documentation must be clarified here.

**Comment by tom-daubney-arm** [comment]
Closing as we are moving away from alt implementations in favour of the PSA with drivers approach so this will have little relevance soon.
