### ISSUE TITLE
Allow omitting mbedtls_x509_crt_info (and mbedtls_x509_crt_verify_info)

### ISSUE THREAD

**Issue by pkolbus** [Mbed-TLS/mbedtls#2308]
### Description
- Type: Enhancement\Feature Request
- Priority: Major

**Justification - why does the library need this feature?**  

On small systems (e.g. Cortex-M4) every KB of code footprint counts, and these functions only seem to be needed in certain debugging/tools contexts. I've noticed that when building with -ffunction-sections, -fdata-sections, and gc-sections, there are a few KB of wasted code space because constant strings are entangled to types in a way that makes it hard for a linker to omit them.

**Suggested enhancement**  

Add two configuration options MBEDTLS_X509_CRT_INFO and MBEDTLS_X509_CRT_VERIFY_INFO to config.h; both enabled by default. When enabled, there is zero change in behavior. When disabled, these APIs and anything that only those APIs use are omitted from the build.

In most cases this is a simple #ifdef wrap of the bits. For the OID descriptors in oid.c, I'm thinking that mbedtls_oid_descriptor_t should not have the string members at all, so that would likely involve adding  OID_DESCRIPTOR and NULL_OID_DESCRIPTOR macros that either include or exclude the two strings. This may mean that builds with and without MBEDTLS_X509_CRT_INFO aren't ABI compatible, but I'm not sure that matters- any system that would favor sharing a library (Linux, Windows) is probably big enough that this optimization wouldn't be of interest.

Notes:
* I have patches for the above approach that are working on my product, although I haven't attempted to create any tests. I'm thinking to fork an existing test and make sure things build when these options are omitted. I'll open a PR once I get those tests created.
* I am, of course, open to improvements for any of this.

**Comment by hanno-arm** [comment]
Hi @pkolbus,

thank you very much for your comprehensive report!

You're right that we're currently investing a significant amount of ROM in what is usually not needed outside of debugging contexts, and which therefore should be made optional, and we are aware that the X.509 module in particular is amenable to significant improvements in this regard. We will look into your suggestion and will hopefully address it soon alongside other X.509 memory consumption improvements, though I can't make promises at the moment on when exactly this will be.

That said: If you already have a fix available, please feel free to open a PR for it. The PR need not be perfect - we're willing to help you filling in on things like tests.

Kind regards, and thanks again for your exemplary report,
Hanno

**Comment by tom-cosgrove-arm** [comment]
Closed by #3777 which implements a new config option `MBEDTLS_X509_REMOVE_INFO` to do exactly this
