### ISSUE TITLE
Memory leak in test_suite_x509write with PSA enabled

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#2475]
__Issue:__ The suite `test_suite_x509write` has a memory leak in the PSA test `x509_csr_check_opaque()`. Specifically, the helper `x509_crt_verifycsr` creates a temporary CSR but doesn't free it properly (it's allocated on the stack, but may contain references, so `mbedtls_x509_csr_free()` must be called on it):
https://github.com/ARMmbed/mbedtls/blob/86016a03a1c28b5d4ddd4d27aa950794e3b51143/tests/suites/test_suite_x509write.function#L37-L60

**Comment by hanno-arm** [comment]
Fixed by #2469.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2795

**Comment by tom-cosgrove-arm** [comment]
Closing this as fixed by #2469, which was merged over 3 years ago
