### ISSUE TITLE
ASan bypassed in all.sh test for PSA-builds

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#2476]
__Issue:__ The `all.sh` component `component_test_use_psa_crypto_full_cmake_asan` tests PSA-builds in the full config, and enables `ASan` to detect memory errors. The full config, however, also enables the memory buffer allocator via `MBEDTLS_MEMORY_BUFFER_ALLOC`, which replaces system `free() / calloc()` by custom implementations, hence bypassing `ASan`s checks.

The memory leak #2475 was hidden by that.

**Comment by hanno-arm** [comment]
#2469 fixes this.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2794

**Comment by daverodgman** [comment]
Fixed by #2469
