### ISSUE TITLE
mbedtls_net_free() is missleading.

### ISSUE THREAD

**Issue by dbaarda** [Mbed-TLS/mbedtls#2544]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Enhancement\Feature Request
- Priority: Minor

---------------------------------------------------------------
## Bug

**Expected behavior**   

The documentation for mbedtls_net_free() says "Gracefully shutdown the connection and free associated data." which to me implies that it will free the mbedtls_net_context structure.

**Actual behavior**  

It doesn't free the mbedtls_net_context structure, it just closes the socket gracefully and sets the field fd=-1.

**Steps to reproduce**  

Look at code.

----------------------------------------------------------------
## Enhancement\Feature Request

My preferred API naming approach is as follows;

void foo_init(foo *f, ...) - initialize a pre-allocated struct into a consistent state.
void foo_done(foo *f) - close/destroy a struct, freeing any internal allocated memory, but does not free the struct itself.
foo *foo_new(...) - Allocate a struct and initialize it into a consistent state. May call foo_init() under the hood after allocating the struct.
void foo_free(foo *f) - Destroy and free a struct. May call foo_done() under the hood before freeing the struct.

Depending on the use-case for the struct, you would normally define only foo_init()/foo_done() or foo_new()/foo_free(), with the latter being the only option for anonymous structs.

SO IMHO the current mbedtls_net_free() would be better named mbedtls_net_done().

**Justification - why does the library need this feature?**  

It's just a minor nit... I had to dig down to the code to figure out what this function actually does because the docs are missleading.

**Suggested enhancement**  

At the very least the docs should be updated to make it clear that mbedtls_net_free() doesn't actually free the struct.

**Comment by dbaarda** [comment]
Actually, digging around the code it appears that mbedtls uses foo_free() pretty consistently to behave the way I normally use foo_done(). So mbedtls is self consistent, and I probably should have noticed that this behaves the same as all the other mbedtls_*_free() functions.

I note that the documentation for mbedtls_net_free() is a little different from mbedtls_ssl_free() which is a little clearer that only internally allocated memory is freed;

"Free referenced items in an SSL context and clear memory."

So maybe this is still a minor nit about the documentation... otherwise feel free to close as "Working as intended".

**Comment by RonEld** [comment]
@dbaarda Thank for reporting this issue!
Yes, the API behaves as expected. Quoting our [coding standards](https://tls.mbed.org/kb/development/mbedtls-coding-standards):
>The `free()` function must free any allocated memory within the context, but not the context itself; it must zeroize any data in the context or substructures.

And `mbedtls_net_free()` does free the internal member (`fd`) and sets it to invalid(-1), sincw zeroizing a fd have different meanings.
However, I agree with you that the documentation might need to be improved, so labeling this as a bug.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-2828
