### ISSUE TITLE
Creating links only when ENABLE_TESTING is ON

### ISSUE THREAD

**Issue by renzbagaporo** [Mbed-TLS/mbedtls#2608]
There are two places in the build code that looks like symbolic links should only be created when ENABLE_TESTING is ON based on comments:

https://github.com/ARMmbed/mbedtls/blob/1cd7bea2b1db288e64824b1fca842e6510da028d/CMakeLists.txt#L234-L240

https://github.com/ARMmbed/mbedtls/blob/1cd7bea2b1db288e64824b1fca842e6510da028d/include/CMakeLists.txt#L13-L16

Creating links seem to cause some trouble (https://github.com/ARMmbed/mbedtls/pull/1699, https://github.com/ARMmbed/mbedtls/issues/1496), so if these are testing-only related maybe a check for ENABLE_TESTING can be done in these parts?

**Comment by renzbagaporo** [comment]
Closing issue in favor of PR https://github.com/ARMmbed/mbedtls/pull/2654

**Comment by RonEld** [comment]
Reopening.
to bne closed only when the PR that resolves this issue is closed

**Comment by daverodgman** [comment]
Addressed in linked PR
