### ISSUE TITLE
Defining _POSIX_C_SOURCE in library/threading.c is problematic

### ISSUE THREAD

**Issue by cringti** [Mbed-TLS/mbedtls#2625]
### Build failure when moving from LTS 2.7 to 2.16 related to _POSIX_C_SOURCE and library/threading.c
- Type: Question (though maybe bug)
- Priority: Major

We're struggling with a recent change, specifically to library/threading.c (this commit - https://github.com/ARMmbed/mbedtls/commit/e9b10b21f11a84a8fbf74ce663935c7caea563fa) which unconditionally defines `_POSIX_C_SOURCE`.

The comments state this change was done to enable a gmtime-related change, though I don't understand how that relates to library/threading.c.  I'm wondering if this `_POSIX_C_SOURCE` definition can be removed from library/threading.c.

The reason this is particularly painful for our port to our embedded platform, is that we provide our own 'alt' threading implementation, based on _our_ (not gcc's!) POSIX pthread implementation (that knows about our RTOS environments).  To disable gcc's POSIX definitions from coming in, we throw `-std=c99` and ensure explicitly that `_POSIX_C_SOURCE` is _not_ defined.  That seems to be the way to disable GCC's headers infrastructure from bringing in it's POSIX implementation, but it conflicts with the change in question.

FWIW, removing that `_POSIX_C_SOURCE` definition in library/threading seems to work for our environment, though I don't understand any gmtime()-related implications of that change.

For now, I'm just looking to better understand why the change was made, and whether it is really necessary in library/threading.c.

Chris

**Comment by RonEld** [comment]
Hi @cringti 
Thank you for your question!

Doesn't 94b540ac63c0c8d9d87edff9772dc7754bd4d220 help you? This defines `_POSIX_C_SOURCE` conditionally.

Can you define your `_POSIX_C_SOURCE` globally, prior to `threading.c` compile time?

**Comment by cringti** [comment]
@RonEld, thanks for your reply.

The change in that newer commit is an improvement (it lets me define `_POSIX_C_SOURCE` to my own value if I want), however it doesn't change the fact that `_POSIX_C_SOURCE` is always defined.  I don't want it defined at all.

**Comment by cringti** [comment]
Fingers still crossed for a reply on this.  I'm currently working around this by explicitly deleting these 3 lines from `library/threading.c`:

-#if !defined(_POSIX_C_SOURCE)
-#define _POSIX_C_SOURCE 200112L
-#endif

This resolves my build issues, though I'm not sure of any runtime side effects.  I'd feel a lot better if someone chimed in with "Yep, those lines aren't used in `library/threading.c` and we'll remove them in the mainline".

**Comment by RonEld** [comment]
Hi @cringti 
i apologize for  not getting back to you.

> I'd feel a lot better if someone chimed in with "Yep, those lines aren't used in library/threading.c and we'll remove them in the mainline".

This is used in `library/threading.c` for the gmtime functionality. So, unfortunately, this won't be removed in the mainline. 

How about undefining `_POSIX_C_SOURCE` in your configuration file? I believe this will work for you.

>The comments state this change was done to enable a gmtime-related change, though I don't understand how that relates to library/threading.c.

The change was to use the thread safe `gmtime_r` instead of `gmtime`, however not all platforms have `gmtime_r` so there was a need to add a mutex to be generally used, unless you have your own alternative implementation for `gmtime_r()` by defining `MBEDTLS_PLATFORM_GMTIME_R_ALT`

**Comment by cringti** [comment]
Thanks, I appreciate the continued discussion.

A couple things:
1. I still don't see where the `gmtime_r()` definition is ever needed in threading.c.  I see where a _mutex_ (that happens to protect `gmtime_r()` calls) is conditionally defined/managed, but that mutex definition doesn't require the definition of `gmtime_r()`, so I still question why this `_POSIX_C_SOURCE` is needed in threading.c.  Again, I'm no expert on the gmtime-related changes, so if I'm just missing where that dependency is, I appreciate that detail.
2. My understanding is that the `gmtime_r()` dependency is by design conditional, and I can remove that dependency by providing my own implementation and defining `MBEDTLS_PLATFORM_GMTIME_R_ALT`.  So is that `_POSIX_C_SOURCE` chunk of code unnecessary if `MBEDTLS_PLATFORM_GMTIME_R_ALT` is defined (in threading.c and every file this was done in)?  And we should wrap it in something like:

```c
/*
 * If the configuration isn't using an alt gmtime_r() implementation,
 * unconditionally bring in the toolchain's.
 */
#ifndef MBEDTLS_PLATFORM_GMTIME_R_ALT
#if !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200112L
#endif
#endif
```

I'll look into undefining it in my config file - but that feels like a hack (which means I'm nervous future code changes will break that approach), but I can give it a shot.

**Comment by gilles-peskine-arm** [comment]
Would defining `_POSIX_C_SOURCE` to 0 work for you? I think glibc treats it identically to being undefined.

`threading.c` doesn't call `gmtime_r` but I'm not sure that it doesn't need `_POSIX_C_SOURCE` for some other purpose. And even if we could remove it now, there'd be no guarantee that we wouldn't add it back later for the sake of some other platform or if we need to shuffle functions around. On the other hand, if you define `_POSIX_C_SOURCE` to something, you should know what you're doing, so we'll respect it.

**Comment by daverodgman** [comment]
Closing this - please re-open if you are still experiencing issues here.
