### ISSUE TITLE
if compiler expose __BYTEORDER__ (e.g. gcc) then use it  for defined

### ISSUE THREAD

**Issue by nihilus** [Mbed-TLS/mbedtls#2707]
Looking through the aes.c I found GET_UINT32_LE being defined despite my platform being little endian, so we should not define to shifting if the compiler exposé __BYTEORDER__, same with the macros for big-endian.

### Description
- Type: Enhancement\Feature Request
- Priority: Minor

**Comment by tom-cosgrove-arm** [comment]
This should be fixed by #6666; note that the read-byte-and-shift-to-get-32-bit-value-idiom is often optimised by the compiler to a simple load anyway
