### ISSUE TITLE
fresh build of `program/ssl_client1` failed

### ISSUE THREAD

**Issue by sammyne** [Mbed-TLS/mbedtls#2763]
### Description
- Type: Question
- Priority: Blocker

## Question

**Why the new build of `ssl_client1` program failed?**

### reproduction

```
# 0. clone the project
git clone https://github.com/sammyne/mastering-mbedtls.git
cd mastering-mbedtls

# 1. build the docker environment 
cd docker 
docker build -t ubuntu:mbedtls-2.18.1 .
cd -

# 2. build the ssl_client1 in the container 
./develop.sh
mkdir build && cd build
cmake ..

# 3. start the server in the programs
export LD_LIBRARY_PATH=/usr/local/lib/
/usr/local/bin/ssl_server

# 4. enter the container from another terminal
docker exec -it mbedtls bash

# 5. check the official ssl_client1 
export LD_LIBRARY_PATH=/usr/local/lib/
/usr/local/bin/ssl_client1
# we should see the message is exchanged correctly

# 6. check the one built by us, where the ssl_client1 is built from examples/tls/ssl_client1.c copied from the 'program' folder of official mbedtls project
build/tls/ssl_client1

# and output goes as 

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
Segmentation fault
```

**Comment by RonEld** [comment]
Hi @sammyne 
Thank you for your question!
I have tried running the program on my Ubuntu machine, and no issue found.
I would suggest you check your environment and configuration.
Perhaps there is some mismatch in the installed library shared object and the programs running.
For better debugging, I would suggest you enable logs, to see further details.
Can you specify with a debugger where you got the segmentation fault?

**Comment by sammyne** [comment]
sorry for the late reply. I'm unfamiliar with GDB. But with the steps described in reproduction section, the segmentation fault would reproduce exactly. I'll try GDB later. 

And I found  that if leaving the `install` command, and just link and include the file in project directory would work. So I guess it's probably the switches on `config.h` is changed during installing the library to system path. @RonEld

**Comment by RonEld** [comment]
Hi @sammyne 
The `install` command only copies the output files into you `DESTDIR`, which is `/usr/local` .
I doubt that it is a matter of switches in `config.h` file.

However, you are probably correct that it is a matter of versions of the library, or perhaps permissions of using the library.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue since it came from inconsistent files during the build.
