### ISSUE TITLE
mbedtls_ssl_read_record() returned -30592 (-0x7780) after clienthello

### ISSUE THREAD

**Issue by cs3sw** [Mbed-TLS/mbedtls#2772]
Hi,

I have problem about ssl handshank after clienthello, I use MTK mt7697 platform to do https get 
with server, and appear below error log, I thought it is the cipher suites server not supported,
so I use curl do http get request from PC, and PC return serverhello correctly. I saw cipher suites
server choose ECDHE-RSA-AES128-GCM-SHA256, In my mt7697 clienthello package, I also use this cipher (c02f), but it still handshake failed, could you help us to figure out this issue.
Thank you.

Jack

######curl request result######
* Hostname was NOT found in DNS cache
*   Trying 52.84.248.66...
* Connected to 76wn9q1r57.execute-api.us-east-1.amazonaws.com (52.84.248.66) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256

###mt7697 http request result######
[T: 3521 M: httpclient C: info F: httpclient_connect L: 835]: [HTTPClient]: http?:0, port:443, host:76wn9q1r57.execute-api.us-east-1.amazonaws.com
[T: 3521 M: httpclient C: info F: httpclient_ssl_conn L: 1069]: [HTTPClient]: httpclient_ssl_conn!!!!!!!
.
[T: 3583 M: httpclient C: info F: httpclient_ssl_conn L: 1182]: [HTTPClient]: START mbedtls_ssl_handshake()!!!!! 

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => handshake

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client state: 0

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => flush output

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= flush output

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client state: 1

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => flush output

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= flush output

[T: 3583 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => write client hello

[T: 3589 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, max version: [3:3]

[T: 3600 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: dumping 'client hello, random bytes' (32 bytes)

[T: 3609 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0000:  0c 4d 19 b4 57 2b ab 26 3f 56 13 db 00 74 8b 31  .M..W+.&?V...t.1

[T: 3618 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0010:  4a 33 63 6d 58 74 cc 79 5f f0 e0 a5 f1 24 50 32  J3cmXt.y_....$P2

[T: 3628 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, session id len.: 0

[T: 3637 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: dumping 'client hello, session id' (0 bytes)

[T: 3646 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, add ciphersuite: c02f

[T: 3656 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, add ciphersuite: c02b

[T: 3665 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, got 3 ciphersuites

[T: 3675 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, compress len.: 1

[T: 3685 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, compress alg.: 0

[T: 3737 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, adding signature_algorithms extension

[T: 3748 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, adding supported_elliptic_curves extension

[T: 3759 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, adding supported_point_formats extension

[T: 3770 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client hello, total extension length: 52

[T: 3781 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => write record

[T: 3792 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: output record: msgtype = 22, version = [3:1], msglen = 103

[T: 3803 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: dumping 'output record sent to network' (108 bytes)

[T: 3813 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0000:  16 03 01 00 67 01 00 00 63 03 03 0c 4d 19 b4 57  ....g...c...M..W

[T: 3823 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0010:  2b ab 26 3f 56 13 db 00 74 8b 31 4a 33 63 6d 58  +.&?V...t.1J3cmX

[T: 3833 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0020:  74 cc 79 5f f0 e0 a5 f1 24 50 32 00 00 06 c0 2f  t.y_....$P2..../

[T: 3845 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0030:  c0 2b 00 ff 01 00 00 34 00 0d 00 0e 00 0c 04 03  .+.....4........

[T: 3858 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0040:  04 01 03 03 03 01 02 03 02 01 00 0a 00 18 00 16  ................

[T: 3871 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0050:  00 19 00 1c 00 18 00 1b 00 17 00 16 00 1a 00 15  ................

[T: 3882 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0060:  00 14 00 13 00 12 00 0b 00 02 01 00              ............

[T: 3892 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => flush output

[T: 3905 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: message length: 108, out_left: 108

[T: 3918 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: ssl->f_send() returned 108 (-0xffffff94)

[T: 3932 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= flush output

[T: 3946 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= write record

[T: 3961 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= write client hello

[T: 3975 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: client state: 2

[T: 3989 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => flush output

[T: 4003 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= flush output

[T: 4017 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => parse server hello

[T: 4027 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => read record

[T: 4037 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => fetch input

[T: 4049 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: in_left: 0, nb_want: 5

[T: 4058 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: in_left: 0, nb_want: 5

[T: 4068 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

[T: 4078 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= fetch input

[T: 4087 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: dumping 'input record header' (5 bytes)

[T: 4096 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0000:  15 03 03 00 02                                   .....

[T: 4105 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: input record: msgtype = 21, version = [3:3], msglen = 2

[T: 4115 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => fetch input

[T: 4124 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: in_left: 5, nb_want: 7

[T: 4134 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: in_left: 5, nb_want: 7

[T: 4143 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: ssl->f_recv(_timeout)() returned 2 (-0xfffffffe)

[T: 4153 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= fetch input

[T: 4166 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: dumping 'input record from network' (7 bytes)

[T: 4175 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: 0000:  15 03 03 00 02 02 28                             ......(

[T: 4186 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: got an alert message, type: [2:40]

[T: 4199 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: is a fatal alert message (msg 40)

[T: 4212 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: mbedtls_ssl_handle_message_type() returned -30592 (-0x7780)

[T: 4221 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: mbedtls_ssl_read_record() returned -30592 (-0x7780)

[T: 4231 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= handshake

[T: 4241 M: httpclient C: info F: httpclient_ssl_conn L: 1188]: [HTTPClient]: mbedtls_ssl_handshake() failed, ret:-0x7780.
[T: 4253 M: httpclient C: info F: httpclient_ssl_conn L: 1210]: [HTTPClient]: ret=-1.
[T: 4262 M: httpclient C: info F: httpclient_connect L: 850]: [HTTPClient]: httpclient_connect() result:-1, client:0x2001ad88
[T: 4274 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => write close notify

[T: 4288 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= write close notify

[T: 4299 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: => free

[T: 4312 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: <= free

**Comment by RonEld** [comment]
Hi @cs3sw 
As you can see from the log, the error you are receiving is a fatal alert:
>[T: 4199 M: httpclient C: info F: httpclient_debug L: 1039]: [HTTPClient]: 0x20020a80: is a fatal alert message (msg 40)

Message 40 is `MBEDTLS_SSL_ALERT_MSG_HANDSHAKE_FAILURE`, which is returned by the server when it can't handle one of the parameters in the client hello.
The ciphersuite *seems* to be correct, however have you checked other parameters, such as the elliptic curves?

I believe [this post](https://forums.mbed.com/t/trouble-with-aws-api-gateway/4379) should assist you, as it mentions that aws requires Server Name Indication.
Please try adding to your client the following call before handshake:
~~~
mbedtls_ssl_set_hostname(&ssl, "76wn9q1r57.execute-api.us-east-1.amazonaws.com")
~~~

**Comment by daverodgman** [comment]
Closing - please re-open with more info if this is still an issue.
