### ISSUE TITLE
Test with UBsan, not just ASan

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#2780]
### Description
- Type: Enhancement
- Priority: Major

---------------------------------------------------------------
## Enhancement

I thought that our “Asan” tests always used UBSan as well (`-fsanitize=address,undefined`). But in fact this is only true when using CMake+clang. In `CMakelists.txt`, the `ASAN` build type passes `-fsanitize=address -fno-common -fsanitize=undefined -fno-sanitize-recover=all` if the compiler is Clang, but only `-fsanitize=address -fno-common` if the compiler is GCC. In `all.sh`, when we enable ASan manually via plain make with `CFLAGS`, we only pass `-fsanitize`.

We should always enable UBSan as well. I don't know why we're doing it that way, maybe because GCC didn't have UBSan when the makefile was written (it [appeared in gcc 4.9](https://developers.redhat.com/blog/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/))? But our de facto minimum version has been gcc 5.4 for over two years (the version in Ubuntu 16.04) and it does have `-fsanitize=undefined`.

I'm filing this as “Priority: Major” because I thought we were testing this, and we aren't, and it's hiding bugs (https://github.com/ARMmbed/mbed-crypto/issues/203).

**Comment by AndrzejKurek** [comment]
Created a PR here: https://github.com/ARMmbed/mbed-crypto/pull/239

**Comment by gilles-peskine-arm** [comment]
Fixed in Mbed Crypto https://github.com/ARMmbed/mbed-crypto/pull/239 for CMake. This was merged into Mbed TLS with the Mbed Crypto merge, but is missing backports to 2.16 and 2.7.

Fixed in https://github.com/ARMmbed/mbed-crypto/pull/304 and https://github.com/ARMmbed/mbedtls/pull/2898 and backports for make in `all.sh`.

**Comment by gilles-peskine-arm** [comment]
With the merge of Mbed Crypto into Mbed TLS, this is fixed in Mbed TLS.
