### ISSUE TITLE
Extend support for VIA Padlock engine

### ISSUE THREAD

**Issue by hardfalcon** [Mbed-TLS/mbedtls#28]
PolarSSL already has code to use the Padlock engine for AES on VIA CPUs, but those CPUs also feature HW accelerated SHA1, SHA256, 2 HW RNGs and an HW accelerated Montgomery multiplier which can be used to accelerate RSA and DSA.

The OpenSSL folks have quite optimized code for all of this (except the RNG):
http://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=engines/asm/e_padlock-x86.pl
http://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=engines/asm/e_padlock-x86_64.pl
http://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=crypto/bn/asm/via-mont.pl

**Comment by gilles-peskine-arm** [comment]
It's been almost a decade and the ecosystem has changed quite a bit. Do you still care about VIA Padlock support? We currently [intend to remove it in the next version of Mbed TLS](https://github.com/Mbed-TLS/mbedtls/issues/5903).

**Comment by hardfalcon** [comment]
> It's been almost a decade and the ecosystem has changed quite a bit. Do you still care about VIA Padlock support? We currently [intend to remove it in the next version of Mbed TLS](https://github.com/Mbed-TLS/mbedtls/issues/5903).

No hard feelings about this from me, I don't really use that hardware anymore. Kudos for asking first, though! :)

**Comment by daverodgman** [comment]
Closing, we won't extend support and will remove existing support in the future.
