### ISSUE TITLE
mbedtls_ssl_read returns MBEDTLS_ERR_SSL_INVALID_RECORD if the application requests more than MBEDTLS_SSL_MAX_CONTENT_LEN

### ISSUE THREAD

**Issue by sarenameas** [Mbed-TLS/mbedtls#2818]
### Description
- Type: Question
- Priority: Minor

## Question

**Please first check for answers in the [Mbed TLS knowledge Base](https://tls.mbed.org/kb), and preferably file an issue in the [Mbed TLS support forum](https://forums.mbed.com/c/mbed-tls)**  

In our configuration we only have MBEDTLS_SSL_MAX_CONTENT_LEN defined and not MBEDTLS_SSL_IN_CONTENT_LEN and not MBEDTLS_SSL_OUT_CONTENT_LEN.

Is it expected that calling mbedtls_ssl_read() requires that the length to read be less than MBEDTLS_SSL_MAX_CONTENT_LEN? This is not documented in mbedtls_ssl_read(). 

If the application wants MBEDTLS_SSL_MAX_CONTENT_LEN + 1 from mbedtls_ssl_read(), then mbedtls_ssl_read() will return with MBEDTLS_ERR_SSL_INVALID_RECORD because the length to read is greater than MBEDTLS_SSL_IN_CONTENT_LEN.

Are you expecting wrappers around mbedtls_ssl_read() to ask only for up to MBEDTLS_SSL_MAX_CONTENT_LEN at a time until the total read length is reached? Excuse me if I am being ignorant, but is this possibly something that is common in the ssl_read() world that developers just have to deal with? 

This forces the application layer to know about the MBEDTLS_SSL_MAX_CONTENT_LEN, which doesn't seem right.

**Comment by sarenameas** [comment]
I am still wondering about this?

**Comment by gilles-peskine-arm** [comment]
Hi @sarenameas,

I'm sorry for the late reply. We seem to have missed this issue.

At first glance, I don't see anything wrong with calling `mbedtls_ssl_read` with a large buffer. It makes sense that the function would return the available data, and it shouldn't matter that the buffer is larger than `MBEDTLS_SSL_MAX_CONTENT_LEN`.

In fact, as far as I can tell, this is already the case. I don't see an obvious place where a large buffer passed to `mbedtls_ssl_read` would cause it to return `MBEDTLS_ERR_SSL_INVALID_RECORD`. Furthermore, I see places in our test code where we do call `mbedtls_ssl_read` with a buffer that's larger than `MBEDTLS_SSL_MAX_CONTENT_LEN`.

There may be configurations or code paths where this is a problem, but if so, we aren't hitting them in our tests. Could you please share code that demonstrates the problem?

**Comment by gilles-peskine-arm** [comment]
It's possible that there's a bug in the library. However, it's not clear when the bug would be triggered. The library code looks correct on the surface.

If you still think there's a bug, please post working code to reproduce it, and we can reopen this issue.
