### ISSUE TITLE
Is it possible to let VS IDE be able to enable CPU hardware AES?

### ISSUE THREAD

**Issue by haobinnan** [Mbed-TLS/mbedtls#2832]
The mbedtls 2.16.2 built in Microsoft VS IDE does not enable Intel NI AES by default.
It might be caused by this. Is it possible to let VS IDE be able to enable CPU hardware AES?

https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.16.2/include/mbedtls/aesni.h

#if defined(MBEDTLS_HAVE_ASM) && defined(__GNUC__) &&  \
    ( defined(__amd64__) || defined(__x86_64__) )   &&  \
    ! defined(MBEDTLS_HAVE_X86_64)
#define MBEDTLS_HAVE_X86_64
#endif

**Comment by haobinnan** [comment]
Hi @Patater 
Would it be possible to consider enabling CPU hardware AES in MSVC? Otherwise the executing performance in Windows is affected.

**Comment by shuffle2** [comment]
Both gcc and msvc can use intrinsics for this, there is no reason to use inline asm. (i came across this issue because I was very surprised mbedtls still does not support aes-ni on msvc).

**Comment by daverodgman** [comment]
Closing as we don't plan to implement support for an alternative style of assembly.
