### ISSUE TITLE
Feature request: Functions to allocate context objects

### ISSUE THREAD

**Issue by malmaud** [Mbed-TLS/mbedtls#290]
Currently, it's difficult to safely create context objects (such as mbedtls_entropy_context) from a dynamic language that is linking to mbedtls since the wrapper doesn't have access to the size of the context struct. The wrapper is forced to allocate an upper bound to the the number of bytes the struct will take, and then pass a pointer to those bytes to eg `mbedtls_entropy_init`. 

Might it make sense to add functions on the C side to heap-allocate context objects and return a pointer to them? I could write the PR.

**Comment by tom-daubney-arm** [comment]
This is a job for the wrapper generation framework and so the issue will be closed.

**Comment by gilles-peskine-arm** [comment]
This is also useful even in C for environment that want a stable ABI. Mbed TLS could offer a more stable ABI if types were opaque, but that would also mean that allocations would have to use whatever heap allocator the library is configured for. We prioritize constrained targets where heap allocation is frowned upon, so ABI stability isn't a priority.

We've considered standardizing this for PSA contexts (but so far we haven't actually done so).

I don't think it makes sense to force every C or FFI wrapper to reinvent this wheel. It would make sense to have this in our code base, but we (the core Mbed TLS maintenance team) are unlikely to do so ourselves. I don't see why we wouldn't accept a contribution though, if it's maintainable and tested.

So I think that keeping this issue open and `help-wanted` was the right thing.
