### ISSUE TITLE
Subject Alternate Name of type IP or URI isn't supported

### ISSUE THREAD

**Issue by joelpalsson74** [Mbed-TLS/mbedtls#2981]
Is there any reason why IP and URI subject names aren't supported?

https://github.com/ARMmbed/mbedtls/blob/252faff19f938f6b9b107b289c750786a5abecdc/library/x509_crt.c#L1879

**Comment by davidhorstmann-arm** [comment]
Closing as fixed by #7025, #7575 and #7436.
