### ISSUE TITLE
typo in mbedtls_ssl_config_defaults

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#2985]
## Description
- Type: Bug 
- Priority: Minor

Raised in the [forum](https://forums.mbed.com/t/typo-in-the-comment/6732) by David Timber

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.16.3

**Expected behavior**   
No typo in function description

**Actual behavior**  
[typo](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L4020): "Load reason**n**able default SSL configuration values."

**Comment by tom-cosgrove-arm** [comment]
This has been fixed
