### ISSUE TITLE
UWP has no lstrlenW function

### ISSUE THREAD

**Issue by borrrden** [Mbed-TLS/mbedtls#2994]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug
- Priority: Unable to compile means Blocker I guess, but the way to fix in a fork is pretty easy so maybe minor?

---------------------------------------------------------------
## Bug

**OS**  
Windows (Compiling for Windows Store)

**mbed TLS build:**  
Version: 2.19.1 (But same thing is still present in master)
OS version: 10.0.18362
Configuration: https://gist.github.com/borrrden/e9e01b5703c450e789c8b2566709c2af
Compiler and options:  MSVC 19.16.27034.0
Additional environment information:  

**Peer device TLS stack and version**  
OpenSSL|GnuTls|Chrome|NSS(Firefox)|SecureChannel (IIS/Internet Explorer/Edge)|Other  
Version:  ???

**Expected behavior**   

Compiles correctly

**Actual behavior**

Doesn't compile, no function definition for `lstrlenW`  (x509_crt.c)

**Steps to reproduce**  

Make a CMake build as in the following:

`cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION="10.0" -DCMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION="10.0.16299.0"`

**Comment by erossetto** [comment]
I was having the same issue, check:

https://github.com/ARMmbed/mbedtls/issues/1227#issue-283783664

**Comment by gilles-peskine-arm** [comment]
Hi @borrrden , @erossetto ,

There's a fix pending for this issue in https://github.com/ARMmbed/mbedtls/pull/1453 . Unfortunately, that pull request does many things, got delayed several times and has accumulated a lot of conflicts. We don't have much Windows expertise on the team, and we don't have much time to spend on it.

Would you mind helping us with this by contributing a fix?

* The smaller the code change, the easier it is to review.
* Please make sure not to break support for older Windows environments. We currently support Visual Studio back to Visual Studio 2013.
* That cmake command line is very helpful. We should add a Windows build to our CI that catches this problem. What versions of Visual Studio, cmake and other tools does it require? We currently have up to Visual Studio 2017. Would we need to install a more recent version?
