### ISSUE TITLE
Get rid of "Press Enter to exit this program"

### ISSUE THREAD

**Issue by mabuze** [Mbed-TLS/mbedtls#3031]
a number of command line tools in programs/ share the following code snippet:

`#if defined(_WIN32)`
`    mbedtls_printf( "  + Press Enter to exit this program.\n" );`
`    fflush( stdout ); getchar();`
`#endif`

since i'm not particularly exercised in using windows ... what is the idea behind this?

background:
i'm running `cert_write` and `gen_key` from inside an _inno setup_ based installer
and both tools block the installer.  this is a bit annoying, especially when the terminal
that runs each tool is hidden behind the installer window.

**Comment by mpg** [comment]
I think the idea it for prevent the terminal from closing as soon as the program has finished running and give the user a chance to read the output before the terminal closes. Clearly this was written with interactive use in mind, and isn't very well suited to non-interactive use.

I think in the beginning the programs were intended mainly as examples. Over time, it turned out that some of them are actually useful as programs, not just examples. So perhaps we should revisit that.

**Comment by gilles-peskine-arm** [comment]
If you click on a console program in the Windows file manager, it runs the program and closes the console window as soon as the program exits. The [official advice from Microsoft](https://support.microsoft.com/en-gb/help/99115/info-preventing-the-console-window-from-disappearing) is to modify applications to wait for the user to press a key, which is useful only in this specific circumstance. Most of our sample and utility programs require command line arguments to be useful, so this specific circumstance doesn't even apply.

We should remove that piece of code from all the programs.

**Comment by mabuze** [comment]
> We should remove that piece of code from all the programs.

d'accord! furthermore a number of utility programs handle `argc` incorrectly:
```
$ git rev-parse HEAD
a0c164a2d455d850ebdc2a6c03b1a83cff829232
$ git grep 'argc\s*==\s*0'
programs/pkey/dh_genprime.c:90:    if( argc == 0 )
programs/pkey/gen_key.c:221:    if( argc == 0 )
programs/pkey/key_app.c:110:    if( argc == 0 )
programs/pkey/key_app_writer.c:219:    if( argc == 0 )
programs/ssl/ssl_client2.c:1228:    if( argc == 0 )
programs/ssl/ssl_mail_client.c:398:    if( argc == 0 )
programs/ssl/ssl_server2.c:1894:    if( argc == 0 )
programs/util/pem2der.c:202:    if( argc == 0 )
programs/x509/cert_app.c:184:    if( argc == 0 )
programs/x509/cert_req.c:178:    if( argc == 0 )
programs/x509/cert_write.c:254:    if( argc == 0 )
programs/x509/crl_app.c:87:    if( argc == 0 )
programs/x509/req_app.c:87:    if( argc == 0 )
```
so they currently do not show a usage message when you fe. double-click them inside explorer
but do their job with default settings.

**Comment by josesimoes** [comment]
Any update on this? 
I'm trying to use these CLI in github actions and this is making it harder just because they never "exit" and I end up having to kill the application.

Would you accept a PR removing all these `#if defined(_WIN32)` from the apps in `programs`?

**Comment by gilles-peskine-arm** [comment]
@josesimoes This is something we want, but it isn't a critical product requirement and it hasn't itched any maintainer enough to fix it (we don't use Windows much). We'd welcome a PR!
