### ISSUE TITLE
Add libarchive to projects-using-mbedtls

### ISSUE THREAD

**Issue by mmatuska** [Mbed-TLS/mbedtls#3047]
Since 3.4.2, libarchive supports mbedtls. I propose adding it to https://tls.mbed.org/kb/generic/projects-using-mbedtls

Thanks.

**Comment by mpg** [comment]
Hi, and thanks for sharing this information!

We have projects of reworking our website structure in the next few months, and it's unclear if we'll keep this page in the new structure. If we keep the page, we'll add libarchive to the list as suggested, but in the meantime we're probably not going to touch the page (one of the reasons we want to rework our website is the current one is harder to maintain than it should be).

Thanks for sharing the good news anyway!

**Comment by tom-cosgrove-arm** [comment]
Closing as we don't have the "Projects using Mbed TLS" page any more
