### ISSUE TITLE
"scripts/config.py crypto" does not include CMAC and may lack PSA features

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3058]
The default configuration of Mbed Crypto includes CMAC and most PSA features. The default configuration of Mbed TLS excludes CMAC because it's a backward-incompatible change to `mbedtls_cipher_context_t`. The default configuration of Mbed TLS may .

Should `scripts/config.py crypto` include CMAC and all reasonable-in-default PSA features to be as close as possible to Mbed Crypto? Or should it be just what it is now, which is the default Mbed TLS configuration minus non-crypto features?

In the long term, `scripts/config.py crypto` will include CMAC and PSA will be the default crypto interface. But what about the short term?

**Comment by daverodgman** [comment]
`scripts/config.py crypto` currently defines `MBEDTLS_PSA_CRYPTO_C` and `MBEDTLS_CMAC_C`. Is this issue still relevant?

**Comment by gilles-peskine-arm** [comment]
The specific example of `MBEDTLS_CMAC_C` is for 2.28 only. Arguably this is still a bug in 2.28 but we may not want to change this in an LTS. Currently in `development` there are no options where we'd want the sensible default to be different from the historical-mandated default, and it's unlikely that some will arise during the lifetime of 3.x.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because by this time, 2.28 LTS is what it is, and this is not an issue in 3.x.
