### ISSUE TITLE
Configurable debug output line end feature request

### ISSUE THREAD

**Issue by ashesman** [Mbed-TLS/mbedtls#3068]
### Description
- Type: Enhancement\Feature Request
- Priority: Minor

---------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
Currently line end for all debug output is '\n'.  It would be desirable to have the option to remove this line end or perhaps in some cases change it to '\r\n'.  For example, our application routes mbed_tls debug output to its internal debug output and logging which always appends a line end.  So all mbed_tls items have an extra newline.

**Suggested enhancement**  

This could be easily achieved in debug.c by replacing all newlines with a preprocessor macro that is defined in the config file along side enabling debug output.

e.g.  (debug.c line 134)
mbedtls_snprintf( str, sizeof( str ), "%s() returned %d (-0x%04x)\n", text, ret, -ret );

could be changed to 

mbedtls_snprintf( str, sizeof( str ), "%s() returned %d (-0x%04x)" MBED_TLS_DEBUG_ENDLINE, text, ret, -ret );

where MBED_TLS_DEBUG_ENDLINE is by default defined as "\n"but could easily be defined as "" or "\r\n".

There is maybe a dozen places in this same file where this would need to be applied ad seems like a low risk change.

**Comment by mpg** [comment]
Hi, and thanks for your interest in Mbed TLS!

Unless I'm mistaken, you should already be able to achieve the desired effect by removing the `\n` in your debug callback: our debug module sends output to the callback line by line, so your debug callback would only have to remove the last character or its input string before routing it to your debug output. However this would require making a copy, so is sub optimal in terms of resource usage, and the solution you suggest would be more efficient.

Given all the other tasks we've got on our hands, I can't say we're going to implement this feature, but if you'd like to prepare and submit a PR implementing it, we'll be sure to review it!
