### ISSUE TITLE
TLS1 and SSLv3 handshake test exchanges no application data

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#3070]
Due to a 1n-1 split against BEAST and the way fragments are counted in the `test_suite_ssl`, the server and client exchange no data in the SSLv3 and TLS1 handshake tests. The number of fragments read/sent differ on both sides, so to make this work a refactor is needed in the way fragments are counted in the tests.
Note: this issue describes a state of repository after https://github.com/ARMmbed/mbedtls/pull/3069 is merged.

**Comment by mpg** [comment]
This looks like this has been fixed in 438bf3b6672186a9dc425c672c9166f7406e75e7 so closing this issue.
