### ISSUE TITLE
Undefined behavior in mbedtls_ssl_read

### ISSUE THREAD

**Issue by ashesman** [Mbed-TLS/mbedtls#3076]
### Description
- Type: Bug 
- Priority: Blocker

---------------------------------------------------------------
## Bug

**OS**  
linux

**mbed TLS build:**  
Version: 2.21.0
OS version: Ubuntu 1
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  
GCC 9

**Expected behavior**   

Calling mbedtls_ssl_read(socketInfo->SSLContext, NULL, 0); should decrypt and readable socket data to its internal buffer without actually reading anything to user buffer.  This is useful in order to do before a call to mbedtls_ssl_get_bytes_avail to make sure it is accurate.

**Actual behavior**  

in mbedtls_ssl_read( mbedtls_ssl_context *ssl, unsigned char *buf, size_t len ), buf is unchecked and eventually passed to memcpy at line 5378.  Passing a NULL pointer to memcpy is undefiened behavior (AFAIK, refer [HERE](https://stackoverflow.com/questions/5243012/is-it-guaranteed-to-be-safe-to-perform-memcpy0-0-0)), even if the size parameter is 0.  In practice, this is not likely to cause an issue as most memcpy implementations will probably not read from src if size is 0, but GCC 9 debug build caused an abort if memcpy is called with buf == NULL.

Suggested fix:

Surround these lines with an if that tests buf for NULL

Line 5378:    memcpy( buf, ssl->in_offt, n );
Line 5379:    ssl->in_msglen -= n;

if (buf)
{
     memcpy( buf, ssl->in_offt, n );
     ssl->in_msglen -= n;
}

Also it may help to add an assertion at the start of the function to check that if buf is NULL, len must also be NULL, but I dont know if this adds any real value.

**Steps to reproduce**  
Can be seen just by looking at the code

**Comment by gilles-peskine-arm** [comment]
Even with older GCC versions, UBSan detects calls to `memcpy` and friends with a null pointer and a size of 0, and we test with UBSan on our CI. I guess that we don't happen to have a test case with `mbedtls_ssl_read(ssl, NULL, 0)`. @Patater Can this be added as part of the SSL unit tests that your team is working on?

**Comment by ashesman** [comment]
I just got caught by this issue again a few years on!  I checked in the current master and the same issue is still present.  Last time I found the issue by chance.  This time I found it due to asan error message.  It would be great if this could be fixed given that it is the addition of one line of code that has no negative consequences.

**Comment by gilles-peskine-arm** [comment]
@ashesman Unfortunately we have a huge backlog. Many of the 863 open issues are one-line fixes. Our pull request backlog is also bad but we are generally keeping up with small stuff, would you mind making a pull request with the bug fix and a unit test?

**Comment by ashesman** [comment]
I thought from in the past I was not able to submit a PR without being approved by Mbed?  I seem to remember in the past my work would not be accepted as I was not approved?  Maybe this has changed.

**Comment by gilles-peskine-arm** [comment]
In the past you had to agree to a copyright assignment, maybe that's what you're thinking of? Not an approval per se, but there was this formality before we could merge code. This no longer exists: contributors now retain copyright, and only need to accept the [developer contributor agreement](https://github.com/ARMmbed/mbedtls/blob/development/dco.txt) (basically, you allow the code to be licensed under Apache and GPL, and you affirm that you have the right to do so), which you do by including a signoff line in git commit messages (`git commit -s`).

**Comment by ashesman** [comment]
PR is [here](https://github.com/ARMmbed/mbedtls/pull/5527).  I would have liked to add a unit test but dont understand the test framework and most likely would do more harm than good.  Even without a test, this is still an important fix to this function.
