### ISSUE TITLE
Question: Improving X.509 certificate validation errors

### ISSUE THREAD

**Issue by mukrop** [Mbed-TLS/mbedtls#3099]
Hi,

I’m the lead of a university project investigating (and improving) the usability of certificate validation errors. Our goal is to simplify the ecosystem by consolidating the errors and their documentation in one place, providing replicable example certificates for all validation errors and by explaining better what the individual errors mean. The project is live at https://x509errors.org/

Now we are reaching out to library developers and users (you) to ask for feedback.

Currently, we base the system on OpenSSL errors (as it’s the most common). We have example certificates for 30+ OpenSSL errors and in-progress mapping for corresponding errors error for OpenSSL, GnuTLS, Botan and MbedTLS.
In the future, we plan the possibility of web reorganization based on the other libraries (currently, the web is organized by OpenSSL), adding the error frequencies based on IP-wide scans and elaborating on the consequences of individual errors.
Ultimately, we want to propose better (ideally user-tested) errors and their documentation. (Just recently, we made a survey among 180 developers regarding their error documentation preference with good reception).

As developers/users of TLS libraries, what do you think of the idea?

Which part(s) do you find the most/least useful?
Is there anything you see missing?
What are your thoughts on unifying the error taxonomy? (a very long-term goal, if at all possible)
During spring, we would like to start creating pull requests improving the documentation and error messages in some of the libraries. Would you welcome such contributions?

For transparency: My PhD is done at Masaryk University (Czech Republic) and I’m partially supported by Red Hat Czech.

**Comment by danh-arm** [comment]
This looks like a useful initiative. We'd be happy to accept any contributions that improve clarity without breaking compatibility.

Unifying the error taxonomy sounds ambitious but not impossible. The difficulty for any library is the timing of such breaking changes. For Mbed TLS we try to maintain compatibility where possible and we wouldn't want to break solely for this reason. There tends to be small and occasional windows of opportunity to get such changes in. We'd be happy to comment on any proposals here (before any actual pull requests). If that gets positive feedback, we can advise on when the next break window is.

**Comment by gilles-peskine-arm** [comment]
Re-triaging this two years later: how is this project going?

As we indicated back then, we're happy to participate in an initiative that improves security across the whole ecosystem. This can be both backward-compatible changes, as well as considerations for backward-incompatible changes in the next major release of the library. However, Arm does not intend to take the lead on this particular topic. So Mbed TLS won't change unless a push comes from outside.

**Comment by mukrop** [comment]
The project continues but the direction slightly shifted. Regarding error messages, we still focus mainly on OpenSSL. There will probably be improvements applicable to other libraries but that will take some time (and we'll let you know, probably open a pull request with reformulation suggestions).

The new direction includes guides to properly implement TLS connection (as this turned out to be a frequent use case that developers often struggle with). The currently proposed guide for mbed TLS can be found at https://x509errors.org/guides/mbedtls
Does this fit your documentation somewhere? Would it help improve your own tutorials with this? (Or should be propose the change directly?)

**Comment by daverodgman** [comment]
Closing; as @gilles-peskine-arm points out above, we won't take the lead on this (although we would be open to contributions).
