### ISSUE TITLE
`ecp_internal.h` naming is misleading

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#3129]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
## Bug

Generally, all header files in Mbed TLS that end `*_internal.h` are internal to the library and are not part of the public interface.

Those users including in their application code `ssl_internal.h` (or one of the other headers) is using an interface which was not intended to be external or part of the public API.

An exception to this is `ecp_internal.h` which provides an internal API, but an API necessary to provide a user implementation of the ECC crypto primitives. So it's not truly internal to the library - just specialised.

This is likely a petty issue, but it's confusing to users if `*_internal.h` headers are not supposed to be used when there's an exception. The exception may be an exception and is an instance of us allowing users to extend or replace part of the library (and so conceptually it is still 'internal') but it is still confusing and misleading.

**Comment by hanno-arm** [comment]
A similar point applies to https://github.com/ARMmbed/mbed-crypto/blob/development/include/mbedtls/rsa_internal.h, but it's explicitly mentioned at least.

**Comment by tom-cosgrove-arm** [comment]
Closing as file was moved into `library/` and then deleted some time ago
