### ISSUE TITLE
Testing of psa_import_key API 1- Describe the steps to import a key

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#3171]
Describe the steps to import a key (both SE and non-SE cases) : what are the volatile and persistent resources involved, in which sequence they are allocated, modified, destroyed. Each creation, modification or destruction of a persistent resource should be in a specific step.                              
                                                                                 
The result of this task is aimed to be the input to define systematically the negative test cases to test the resilience of the library (both SE and non SE cases) to errors and arbitrary interruption: for each step, there should be at least one test to cover each possible error that can occur at that step.
      
Furthermore, at each step involving a creation or modification or destruction of a persistent resource, there should be one test that simulate a system reset when the step is in progress (corrupted value for the persistent resource) and just after the step completed successfully.                                      
                                                                                 
This systematic approach to define test cases will hopefully ease the maintenance of the tests. When the implementation is changed, the process by which test cases are defined has just to be replayed.

**Comment by gilles-peskine-arm** [comment]
Rather than analyze the source code and come up with a test plan, I think we can test this systematically. Instrument each of the storage functions (`psa_its_xxx`) with something like
```
#if MBEDTLS_TEST_HOOKS
if (--mbedtls_test_hooks.storage.fail_after_steps == 0)
    return mbedtls_test_hooks.storage.fail_status;
#endif
```
Run the test with successive increasing values of `fail_after_steps` until no failure occurs.

This isn't a complete design: we also need to handle failures during recovery. But I think it isn't too complicated to do something that is exhaustive by construction (assuming that ITS functions are atomic, which they're supposed to be).

**Comment by gilles-peskine-arm** [comment]
Note that with a white-box approach, the non-SE case is obvious: there's only one ITS write call. So we only really need to test the SE case.

**Comment by ronald-cron-arm** [comment]
@gilles-peskine-arm                                                              
                                                                                 
The description of the steps to import a key in question here is not only related to persistent data. It is aimed to cover as well input parameters, static memory resources, dynamic memory allocation ... It is a fairly short and high level description of the various steps involved in psa_import_key(). It helps in structuring, documenting the test cases and to reach a point where we are quite confident we can list all possible error cases.
                                                                                 
Concerning, the testing of storage failures, the plan was to do something along the line you are mentioning. I don't know yet if this is going to be only one test case or one test for each storage access based on the same test function though. By the way, we can adopt the same strategy for dynamic allocations in the heap by wrapping calloc and free.

**Comment by ronald-cron-arm** [comment]
Not relevant anymore
