### ISSUE TITLE
open /dev/urandom at startup and keep open

### ISSUE THREAD

**Issue by jkarneges** [Mbed-TLS/mbedtls#322]
Hey folks,

We are using mbedtls in the Mongrel2 webserver. The recommended setup is to run the server in a chroot environment. This makes /dev/urandom inaccessible to the server process unless the dev filesystem is also mounted within the chroot. However, some may consider mounting dev within a chroot to be defeating the point.

For us it would be great if mbedtls could be told to open /dev/urandom on startup, before the process initiates the chroot, and then keep the file handle open so it can be reused for the lifetime of the process. What do you think?

**Comment by mpg** [comment]
Of course the best solution on GNU/Linux is to use a kernel >= 3.17 so that the `getrandom` syscall is used, but your solution indeed looks interesting in other cases.

**Comment by gilles-peskine-arm** [comment]
A patch was submitted in #323 and has undergone further rework in #1545. Unfortunately, we have not managed to get this patch into a shape where it could be merged (passing CI, having proper testing and review).

It's been several years and the relevance of platforms without a getrandom/getentropy system call is shrinking. If you're still using such a platform and would like to push this improvement through, please rework #1545 to get it to a point where it's mergeable, it passes CI, there is a proper plan for ad hoc testing (we don't currently have a CI platform where `/dev/urandom` would be used) and the commits are properly structured for an easy review.

**Comment by tom-daubney-arm** [comment]
Closing since this issue becomes less relevant as time goes on and won't be worked on.
