### ISSUE TITLE
Testing of psa_import_key API 6 - Transaction temporary file in internal storage

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#3223]
After allocating a key slot in a SE and before importing a key into it, a temporary file is created in internal storage to state that an import of a key into a SE is in progress.

The import of a key in a SE involves the creation of several persistent data and a clean-up of those persistent data is necessary if the import does not proceed until the end because of a reset of the system. Thus, the creation in internal storage of a temporary file to mark the beginning of persistent data operation to import a key.

The goal of this task is to tests the cases where:
1) The creation of the temporary file fails.
2) The creation of the temporary file is interrupted by a system reset and a corrupted file is created in internal storage.
3) The creation of the temporary file succeeds and the system reset before the launch of the creation of the first persistent data for the purpose of the key import.

**Comment by gilles-peskine-arm** [comment]
Isn't this covered by https://github.com/ARMmbed/mbedtls/issues/3171?

Note that the sequence of steps for a transaction is likely to change soon to work better with secure elements that delegate the storage of the key (in wrapped form) to the caller.

**Comment by ronald-cron-arm** [comment]
#3171 is purely descriptive and no test are developed as part of this task. Thus no, this is not covered by #3171. Otherwise, I am aware that things are going to change. It will be a good test of the maintainability of the tests.

**Comment by ronald-cron-arm** [comment]
Not relevant anymore
