### ISSUE TITLE
Review archived issues

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#3237]
In June 2019, several issues were archived because they had been inactive for a long time. The  [announcement](https://tls.mbed.org/tech-updates/blog/a-new-defect-management-approach) noted: "Archiving is, of course, a very blunt tool and we have probably set aside some topics worthy of attention. Anything important enough can be unarchived, made into an active issue, and reprioritized."

We need to go though archived issues and see if any of them was important enough to be made active again.

**Comment by tom-cosgrove-arm** [comment]
I'm closing this as we're going through issues and PRs > a year old separately; those that were archived nearly 3 years ago have had enough time to be re-raised if they were wanted.

It's not likely at all that we would ever go through the archived issues.
