### ISSUE TITLE
DES key derivation: reject weak keys

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3259]
For DES, `psa_key_derivation_output_key` (formerly `psa_generator_import_key()`) should reject weak keys.

This is a theoretical bug since the chance of generating a weak key is 2^{-52}. It's only a problem for compliance and DES is no longer compliant in the US.

**Comment by tom-cosgrove-arm** [comment]
Given we are going to [deprecate the entire DES module](https://github.com/Mbed-TLS/mbedtls/issues/7024) relatively soon, we're not going to do this
