### ISSUE TITLE
Write a sample dynamically registered secure element driver with no on-SE state

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3290]
Write a sample driver for a secure element that does not store keys, but hands a wrapped key to the generic code. See https://github.com/ARMmbed/mbedtls/issues/3287 for the design and https://github.com/ARMmbed/mbedtls/issues/3289 for the implementation.

This is similar in purpose to the [sample driver for ATECC608A](https://github.com/ARMmbed/mbed-os-atecc608a) (which is used by the [Mbed OS Examples for the ATECC608A](https://github.com/ARMmbed/mbed-os-example-atecc608a)), but it does not need to be similar in implementation. In particular this does not need to be tied to Mbed OS (but can be).

The goal of this task is to write a driver, and enough infrastructure around it to at least smoke-test it. This infrastructure can be either some basic testing or a sample application.

**Comment by stevew817** [comment]
I'd be happy to contribute, since we're trying to do this exact thing for the EFR32MG21's SE driver.

**Comment by gilles-peskine-arm** [comment]
There is a new secure element interface in https://github.com/ARMmbed/mbedtls/pull/3313 with statically registered drivers only. The corresponding task for this new interface is https://github.com/ARMmbed/mbedtls/issues/3343. We should keep the current interface at least for a short time to keep backward compatibility, and we may keep it for a long time because it allows dynamic registration of drivers. But this is not a current priority.
