### ISSUE TITLE
mbedtls_gcm_setkey add mode parameter

### ISSUE THREAD

**Issue by frankie-zeng** [Mbed-TLS/mbedtls#3314]
### Description
- Type: Feature Request
- Priority:  Minor

I am porting gcm to hardware accelerate, the api mbedtls_gcm_setkey without mode parameter, so i don't know how to setup the key priority. In software situation, mabye only need encrypt way.

**Comment by yanesca** [comment]
Hi @frankie-zeng , thank you for taking interest in Mbed TLS!

Indeed, in software we only need to use AES for encryption only. I assume that your hardware accelerator API requires you to set the mode when you set the key.

Have you tried storing the key in the context in `mbedtls_gcm_setkey()` and calling the hardware accelerator api with the mode and the key in `mbedtls_gcm_starts()`?

**Comment by frankie-zeng** [comment]
> Hi @frankie-zeng , thank you for taking interest in Mbed TLS!
> 
> Indeed, in software we only need to use AES for encryption only. I assume that your hardware accelerator API requires you to set the mode when you set the key.
> 
> Have you tried storing the key in the context in `mbedtls_gcm_setkey()` and calling the hardware accelerator api with the mode and the key in `mbedtls_gcm_starts()`?

Hi, yanesca, thank your quickly reply. the start can get the mode parameter. but for my hardware, can't change key priority anywhere. right now. I just set the key both encrypt and decrypt flag in setkey stage, it's not very security.

**Comment by yanesca** [comment]
Well, in Mbed TLS the reason for determining the direction of the operation is performance and memory optimisation. When the key is set we just generate and store the key schedule in one direction and not both. It is not meant to provide security regarding the use of the key.

What you are looking for seems to be enforcing a security policy on the key. Does your hardware store the keys and enforce policies on them?

**Comment by gilles-peskine-arm** [comment]
We aren't going to change classic mbedtls crypto APIs any more than we have to, since we're migrating to PSA crypto APIs. The PSA driver API allows drivers to see the key policy and the operation direction, so this feature is already available in the driver API. So this is a wont-fix for the classic API, and already-there in the PSA API.
