### ISSUE TITLE
Document clearly that 16-bit systems are not supported

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3323]
Mbed TLS does not support systems where `int` or `size_t` is less than 32 bits. (The actual cutoff is probably around 27 bits, reached by adding 24-bit numbers in some of the TLS code without checking for overflow.)

There is a fairly large subset of the library that compiles cleanly on a 16-bit machine. There is a much smaller subset that does actually work securely on a 16-bit machine: for example some of the code (e.g. TLS extensions) is vulnerable to integer overflows if compiled for a 16-bit `size_t`. But since some modules do work on 16-bit machines, we may be giving the wrong impression that all of them do.

We should document that 16-bit `int` or `size_t` is not officially supported, that anybody using the library on such a system does so at their own risk, and arrange for known-non-16-bit-safe code to break the build. The `selftest` program should fail if `int` or `size_t` is not a 32-bit type.

Considerations of padding in integer types are out of scope of this issue. https://github.com/ARMmbed/mbedtls/pull/2104 takes care of that.

**Comment by gilles-peskine-arm** [comment]
I have this as part of a bigger rework of `check_config.h`. The current state is https://github.com/gilles-peskine-arm/mbedtls/tree/include-common-h-development-2 . I'm breaking this down into https://github.com/ARMmbed/mbedtls/pull/3454 , https://github.com/ARMmbed/mbedtls/pull/3453 , and one or more pieces yet to come.

**Comment by daverodgman** [comment]
This is documented in `README.md`, which states `int and size_t must be at least 32 bits wide`. Checking in `selftest` would be nice-to-have, but I don't think it's worth a PR just for this.

**Comment by daverodgman** [comment]
Actually, since I was in the area for #7084 , I've included the self-test updates there.
