### ISSUE TITLE
Application context in mbedtls_ssl_context

### ISSUE THREAD

**Issue by embedthis** [Mbed-TLS/mbedtls#347]
We need a field in mbedtls_ssl_context to store an application context pointer.

Some APIs like the mbedtls_ssl_conf_sni callback are passed a mbedtls_ssl_context reference. We need to be able to track this back to an owning connection object. Currently we need to search through a list of sockets to find the right SSL context.

Could we please have a void\* data reference in mbedtls_ssl_context with an API to set/get this field. This would be an application specific data reference that users are free to set/get.

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSSL-540

**Comment by sbutcher-arm** [comment]
Sorry - I should have responded when I marked this as an enhancement. As a feature request, we've added it to our backlog and we will keep this issue open to track it. 

We have a lot of features pending at the moment, so anything you can say on how much you need it, or how much it's breaking you will help prioritise what should be a small feature change.

**Comment by embedthis** [comment]
Thanks. The reason is that the SNI callback cannot access the application context. It has an mbedtls context, but you end up having to search through a global list of SSL configurations. With an application context pointer, you could just reference directly.

I'm not sure, but this may well be the case for other callbacks as well.

Even without the get/set APIs, having a void* appData pointer would be a very low risk addition to the context and the user could get/get themselves.

Currently, we are patching the mbedtls context source to do exactly this.

**Comment by mpg** [comment]
I'm probably missing something obvious, but it seems to me the SNI callback has its own context (`p_sni` argument to `mbedtls_ssl_conf_sni()` and first argument to the callback itself), and I'm not sure why you can't use that and how an application context pointer inside the ssl context would be better.

**Comment by embedthis** [comment]
We setup the sni callback at configuration time (app startup). Then we know the SSL details, but we don't have access to the connection/socket structure which is created in response to a client HTTP request. The connection structure owns the mbedtls context. So we need at runtime, to get our connection object. i.e. basically a back pointer to the parent owning the mbedtls context.

The reason the SNI callback cannot be used is that is must be fixed per mbedtls_ssl_config which must serve many actual requests. What we need is a per-request context.

Does this make sense?

**Comment by mpg** [comment]
Right, it does make sense, thanks for your explanation.

**Comment by gilles-peskine-arm** [comment]
This has been implemented (finally!) [in Mbed TLS 3.2.0](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.0/include/mbedtls/ssl.h#L2407). Both `mbedtls_ssl_context` and `mbedtls_ssl_config` have a user data field which can be either a pointer or an integer.
