### ISSUE TITLE
mbedtls_mpi_read_string unnecessary limb creation

### ISSUE THREAD

**Issue by averyoefinger** [Mbed-TLS/mbedtls#3538]
Note: This is just a template, so feel free to use/remove the unnecessary things

### Description
- Type: Bug / Feature Request
- Priority: Minor

Hello,
I thing the function mbedtls_mpi_read_string in bignum.c has a non-ideal behavior for a corner case I came across.  I ran into this while unit testing. 
The problem is created when a string that perfectly fits into n amounts of limbs is then negated by appending '-' to the front of the string, the negative mpi has a resulting n+1 limbs where the most significant limb's value is zero. 

Generally having an mpi with one extra zero limb is not a big deal but that extra limb did cause me to run into this problem. For example, I ran into this discovery when using mbedtls_mpi_lt_mpi_ct; I was trying to compare the mpi of hex "EFE021C2645FD1DC586E69184AF4A31E" to its negative counterpart "-EFE021C2645FD1DC586E69184AF4A31E". From this use I received a MBEDTLS_ERR_MPI_BAD_INPUT_DATA error since these two hex values do not technically have the same limb size (the negative value has an extra zero limb).

Obviously I can do an extra step and shrink the negative hex mpi to rid the extra limb but is that the only fix currently? 

I guess the request portion of this post is to have mbedtls_mpi_read_string check for the '-' character before it assign a limb size to the mpi.

Example code:

    unsigned int r;
    mbedtls_mpi_init( &A );
    mbedtls_mpi_init( &C );
    MBEDTLS_MPI_CHK( mbedtls_mpi_read_string( &A, 16, "5AE9FF77D42D523FC19CF3C8C951441D" ) );
    MBEDTLS_MPI_CHK( mbedtls_mpi_read_string( &C, 16, "-EFE021C2645FD1DC586E69184AF4A31E"  ) );
    MBEDTLS_MPI_CHK( mbedtls_mpi_shrink( &C, 1 ) );
    MBEDTLS_MPI_CHK( mbedtls_mpi_lt_mpi_ct( &A, &C, &r) );
    check( r != 0 );
    mbedtls_mpi_free( &A );
    mbedtls_mpi_free( &C );

**OS**  
Mbed windows 10

**mbed TLS build:**  
Version: 2.23.0   
Compiler: GCC

**Comment by danh-arm** [comment]
Hi @averyoefinger. Thanks for your interest in Mbed TLS. We discussed this issue among the core team. While we acknowledge this is not optimal behaviour, there does not seem to be a functional correctness issue here. We do not currently plan to address this but welcome contributions that do. Regards, Dan.

**Comment by averyoefinger** [comment]
Thank you very much for your response!

**Comment by tom-cosgrove-arm** [comment]
Sorry, but as stated by @danh-arm above we won't be making this change
