### ISSUE TITLE
SRTP Extension for DTLS

### ISSUE THREAD

**Issue by laandersson** [Mbed-TLS/mbedtls#357]
Is there any work ongoing or planned for providing support for SRTP extension in DTLS? Currently I am using my own addition to mbedtls but it would be great to get SRTP supported in the main release. I did a fork of the 2.0.0 release and made my additions available at https://github.com/laandersson/mbedtls-SRTP. I have quite limited time to offer but I hope the fork could be of help. No compile option for SRTP is available and no test examples are included in the source.

Tests have been done using mbedtls client connected to a mbedtls server to authenticate and generate keys for SRTP and SRTCP. In the real set-up an mbedtls client was connected to a Nokia Border Gateway (Open BGW).

**Comment by jeannotlapin** [comment]
Hi,
I made a pull request on the same topic [#361](https://github.com/ARMmbed/mbedtls/pull/361). It's on his way.

**Comment by tom-daubney-arm** [comment]
This issue was resolved by PR [#3235](https://github.com/Mbed-TLS/mbedtls/pull/3235) and so will be closed.
