### ISSUE TITLE
Pre-emptive defense: #define mbedtls_free to free + NULL

### ISSUE THREAD

**Issue by guidovranken** [Mbed-TLS/mbedtls#359]
As you're aware, I recently found a bunch of double-free's in mbed TLS.

You might want to change this:

``` c
#define mbedtls_free       free
```

into something like this: https://github.com/torproject/tor/blob/master/src/common/util.h#L102

``` c
#define tor_free(p) STMT_BEGIN \
    if (PREDICT_LIKELY((p)!=NULL)) {                \
      dmalloc_free(SHORT_FILE__, __LINE__, (p), 0); \
      (p)=NULL;                                     \
    }                                               \
  STMT_END
```

This will basically guarantee the absence of double-free's, as long as the macro is used sensibly.

Just like using `calloc` for every memory allocation to guarantee that memory is initialized to zeroes to forestall leaking of sensitive information even when bugs in the code over-read buffers, my proposed change could have prevented the double-free's found, and prevent any other double-free instances currently present or introduced in the future.

**Comment by olsner** [comment]
Perhaps a more interesting definition would be to set the pointer to an explicitly poisoned value like `(void*)-1` - then instead of a silent no-op, double-frees would become obvious crashes.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-555

**Comment by mpg** [comment]
I like this suggestion. As you say, it's in line with what we did when moving to `calloc()`, and it's the kind of thing we want to do: kill entire classes of bugs when we can rather than just fixing particular instances when they are found. We'll see how and when we can implement that.

@olsner I think I prefer setting to `NULL`. If I remember correctly, in the instances found by Guido, the problem was the double-free itself (so setting to `NULL` is the correct fix), instead of the double-free being a mere symptom of a deeper problem (in which case I'd indeed prefer an obvious crash).

**Comment by guidovranken** [comment]
In case you are still considering this, I recommend creating a function instead of a macro. Something like:

```c
void freezero(void** ptr)
{
   free(*ptr);
   *ptr = 0;
}
```

because using a macro like in my first post could give a false sense of security to the developer.

```c
void func2(char* ptr)
{
   tor_free(ptr);  // frees ptr, and sets LOCAL variable ptr to 0
}

void func1(void)
{
   char* ptr = malloc(100);
   func2(ptr);
   // ptr is freed, but is still non-zero
}
```

Guido

**Comment by tom-cosgrove-arm** [comment]
After discussion with a few others, I am closing this.

It's certainly a way of doing things, but it would require updating all the places that call `mbedtls_free()`. It doesn't remove the requirement to think about memory management, and "set the pointer to NULL if we're going to jump to an exit handler that might free this again" isn't hard to do.

We run tests under various sanitisers, so any errors in new code (where we are quite stringent about writing tests) are likely to be caught there.

And then it increases the delta between `development` and the LTS, which increases the cost of making backports.
