### ISSUE TITLE
The build fails out of the box with GCC 4

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3631]
Older versions of GCC (before 5.0) default to C89, and the build fails with `-Wall -Wextra -Werror` with some C99 constructs. In particular, the Travis build is failing in Mbed TLS 2.24.0 ([example](https://travis-ci.org/github/ARMmbed/mbedtls/builds/723019367)) in `tests/scripts/all.sh -k build_arm_none_eabi_gcc_arm5vte build_arm_none_eabi_gcc_m0plus`:
```
ssl_msg.c: In function 'mbedtls_ssl_cf_memcpy_if_eq':
ssl_msg.c:1085:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for( size_t i = 0; i < len; i++ )
     ^
ssl_msg.c:1085:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile:263: recipe for target 'ssl_msg.o' failed
```

We deliberately allow the use of most C99 features in recent versions of Mbed TLS, but not in the currently existing LTS branches (2.7 and 2.16 stick to C89).

We plan to [support GCC 4.x as long as it's in a maintained RHEL version](https://github.com/ARMmbed/mbedtls/issues/2896#issuecomment-603471273). So we should modify `CMakeLists.txt` to pass `-std=c99` if the compiler is GCC (it shouldn't hurt for newer GCC). And we should either do it in `Makefile` (but there we can't customize the flags per compiler version) or in the `all.sh` jobs that call an older compiler.

Goals, which we may want to do separately:

* Fix the Travis CI → https://github.com/ARMmbed/mbedtls/pull/3632
* Fix the cmake build out of the box on platforms such as RHEL 6 where the C compiler is GCC 4.x.

**Comment by edsiper** [comment]
Facing the same issue here when compiling for Centos 7.

The quick and easiest fix is just to declare the variable outside of the ```for``` loop:

```diff
diff --git a/mbedtls-2.24.0/library/ssl_msg.c b/mbedtls-2.24.0/library/ssl_msg.c
index 2ea35808..537e7609 100644
--- a/mbedtls-2.24.0/library/ssl_msg.c
+++ b/mbedtls-2.24.0/library/ssl_msg.c
@@ -1082,7 +1082,8 @@ static void mbedtls_ssl_cf_memcpy_if_eq( unsigned char *dst,
 #endif
 
     /* dst[i] = c1 != c2 ? dst[i] : src[i] */
-    for( size_t i = 0; i < len; i++ )
+    size_t i;
+    for( i = 0; i < len; i++ )
         dst[i] = ( dst[i] & mask ) | ( src[i] & ~mask );
 }

```

**Comment by gilles-peskine-arm** [comment]
@edsiper Depending on your configuration, there may be a lot to patch. Mbed TLS is written in C99, and we aren't going to move back to C89. You need to invoke the compiler in C99 mode. For GCC 4.x, this means `gcc -std=c99`; for GCC ≥5.x it's the default.
