### ISSUE TITLE
Find a better way to detect pull requests with one approval

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3634]
We want to prioritize reviews on pull requests that already have one approval, to avoid them bitrotting. Unfortunately there's no easy way to find them.

We have a board https://github.com/orgs/ARMmbed/projects/3 with a “1 approval” column, but moving to this column isn't automated, so it's often out of date.

The goal of this task is to find a better solution, such as a GitHub search query that we haven't discovered yet, a bot to move pull requests on the project board, or a client-side script.

**Comment by daverodgman** [comment]
This also applies to issues - for planned issues, we'll have an issue that is usually 1-1 with a PR and should (IMO) sit in the same column as its PR.

**Comment by gilles-peskine-arm** [comment]
Moving to the "Has approval" column is now automated thanks to @bensze01's bot.
