### ISSUE TITLE
PR3588 needs backporting

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#3666]
The PR multi line string literals in a way that's acceptable both to clang-12-version-to-be-determined -Wstring-concatenation and to gcc -pedantic.

We merged https://github.com/ARMmbed/mbedtls/pull/3588 to fix OSSFuzz as soon as possible, backports still need to be created.

**Comment by tom-cosgrove-arm** [comment]
It seems a shame that clang doesn't let us use a feature that improves readability of long strings :(

Anyway, the original issue was #3586, which was fixed in #3588, and the backport was done in #4787, which is merged
