### ISSUE TITLE
Extend MBEDTLS_PSA_CRYPTO_CONFIG to MBEDTLS_USE_PSA_CRYPTO: asymmetric

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3674]
Extend #3671 (and #3672?) to use `PSA_WANT_xxx` instead of `MBEDTLS_xxx` in code that is guarded by `MBEDTLS_USE_PSA_CRYPTO`. This issue is scoped for asymmetric cryptography; https://github.com/ARMmbed/mbedtls/issues/3677 continues it for symmetric cryptography.

In `all.sh`, change the existing applicable job(s) to enable `MBEDTLS_USE_PSA_CRYPTO` (there's no need to test without it).

Note: this may not be the best approach since there is code that is common to use-psa-crypto and not-use-psa-crypto and uses `MBEDTLS_xxx` guards. This code can't switch to `PSA_WANT_xxx` guards because that wouldn't work when `MBEDTLS_USE_PSA_CRYPTO` is disabled, but it can't keep using the old `MBEDTLS_xxx` guards because that doesn't work when both `MBEDTLS_USE_PSA_CRYPTO` and `MBEDTLS_PSA_CRYPTO_CONFIG` are enabled. So maybe we need to introduce _yet another_ set of guards for crypto features available to X509/TLS code? I am not filled with joy at the prospect of another set of guards, but I don't see another solution. We'd have things like
```
#if defined(MBEDTLS_USE_PSA_CRYPTO)
#define MBEDTLS_CRYPTO_HAVE_ECDSA (PSA_WANT_ALG_ECDSA || PSA_WANT_ALG_ECDSA_DETERMINISTIC)
#else
#define MBEDTLS_CRYPTO_HAVE_ECDSA defined(MBEDTLS_ECDSA_C)
#endif
```
and then use `#if MBEDTLS_CRYPTO_HAVE_ECDSA` instead of `#if defined(MBEDTLS_ECDSA_C)` throughout X.509 and TLS code (including code guarded by `MBEDTLS_USE_PSA_CRYPTO`).

**Comment by mpg** [comment]
This is too large to be a single task. An EPIC has been created for just the ECC part: [Use PSA: code size optimisation via PSA_CRYPTO_CONFIG - part 2: ECC](https://github.com/orgs/Mbed-TLS/projects/1#column-18986128) and another EPIC will be created for the rest of asymmetric crypto when the time comes.

So, I'm closing this ticket as the work is now tracked elsewhere.
