### ISSUE TITLE
Extend MBEDTLS_PSA_CRYPTO_CONFIG to MBEDTLS_USE_PSA_CRYPTO: symmetric

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3677]
Continuation of https://github.com/ARMmbed/mbedtls/issues/3676. Complete the work started in https://github.com/ARMmbed/mbedtls/issues/3674.

**Comment by mpg** [comment]
This is too large to be a single task. An EPIC has been created for just the ECC part: [Use PSA: code size optimisation via PSA_CRYPTO_CONFIG - part 1: symmetric](https://github.com/orgs/Mbed-TLS/projects/1#column-18883163) and another EPIC will be created for the rest of asymmetric crypto when the time comes.

So, I'm closing this ticket as the work is now tracked elsewhere.
