### ISSUE TITLE
Update the storage format documentation

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3737]
The storage format documentation https://github.com/ARMmbed/mbedtls/blob/development/docs/architecture/mbed-crypto-storage-specification.md has not been updated since before the merge of Mbed Crypto.

* Update “TBD” to the application Mbed Crypto version.
* Indicate Mbed TLS versions corresponding to Mbed Crypto versions.
* Check that the file layout description is still accurate.
* Indicate historical changes to the semantics of values in the contained types: `psa_key_type_t`, `psa_algorithm_t`, …
* Document the format used for new-style (unified interface) opaque drivers.
* Fill in missing parts in some version sections (at least the last one added by https://github.com/ARMmbed/mbedtls/pull/3748/files).

This task is for historical and current information about storage version 0, which has had incompatible changes. Since we have not had recent support queries about old versions, and we do not intend to support old version, we do not need to get all the details right for before the last incompatible changes. We do need fully accurate information at least about Mbed TLS 2.28.0 onwards.

**Comment by mpg** [comment]
Based on discussions elsewhere, backfilling historical information for versions earlier than the first stable one does not seem worth the effort. As a result, this issue was resolved by merging #5994.
