### ISSUE TITLE
Incorrect documentation of psa_its_get in comment

### ISSUE THREAD

**Issue by egrimley-arm** [Mbed-TLS/mbedtls#3773]
This line describing the return value `PSA_ERROR_INVALID_SIZE` for `psa_its_get` should be deleted: 

https://github.com/ARMmbed/mbedtls/blob/development/library/psa_crypto_its.h#L102

* There is no error code `PSA_ERROR_INVALID_SIZE`.
* There is no argument `data_size`.
* It is not an error to ask for just part of the data.

(Also, the description of `PSA_ERROR_INVALID_ARGUMENT` does not agree with the implementation but I'm not sure which is wrong.)

**Comment by daverodgman** [comment]
Also, PSA_DATA_CORRUPT is a possible return value that's not mentioned.

**Comment by aditya-deshpande-arm** [comment]
Fixed by PR #3872
