### ISSUE TITLE
PSA unit tests should account for hardware not supporting AES-192

### ISSUE THREAD

**Issue by stevew817** [Mbed-TLS/mbedtls#3824]
### Description
- Type: Enhancement\Feature Request
----------------------------------------------------------------
## Enhancement\Feature Request

**Justification - why does the library need this feature?**  
The mbed TLS tests using AES as a primitive contain a check that skips the test in case it is based on AES-192 and the return code is `UNSUPPORTED`. This is done in order to allow testing on hardware targets that don't necessarily have AES-192 support, but do support the more widely-used 128 and 256 bit versions.
E.g. from multiple places inside `mbedtls_aes_self_test`:
```
if( ret == MBEDTLS_ERR_PLATFORM_FEATURE_UNSUPPORTED && keybits == 192 )
{
    mbedtls_printf( "skipped\n" );
    continue;
}
```

**Suggested enhancement**  
Add the same logic throughout the library test suites (both mbed TLS in e.g. `cmac.c` and the PSA unit tests in e.g. `test_suite_psa_crypto.function`) as mbed TLS is using in its AES selftest, in order to standardise the behaviour of skipping AES-192 tests in case `UNSUPPORTED`/`NOT_SUPPORTED` is returned.

**Comment by gilles-peskine-arm** [comment]
Resolved by `MBEDTLS_TEST_PSA_SKIP_IF_ALT_AES_192` introduced in https://github.com/Mbed-TLS/mbedtls/pull/4010.
