### ISSUE TITLE
IAR compiler warnings in bignum.c

### ISSUE THREAD

**Issue by autinerd** [Mbed-TLS/mbedtls#3835]
### Description
- Type: Compiler warning
- Priority: Minor

Hey folks!

The IAR Compiler (IAR ANSI C/C++ Compiler V8.50.1.245/W32 for ARM) has some remarks in bignum.c.

1. Remark: the unary minus operator is applied to an unsigned expression

https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L269
https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L302

2. Remark: integer conversion resulted in a change of sign

https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L1683-L1685
https://github.com/ARMmbed/mbedtls/blob/935b4f96f9fb9d47158c988a1acaf9e1fa042e67/library/bignum.c#L1824

One possibility would be to add additional type casts to the lines.

**Comment by gstrauss** [comment]
The first two instances in "1." above no longer appear in the library.
The items for "2." can portable set all bits with a bitwise complement after casting to the appropriately-sized type.
(The `u` on the `0u` is not strictly required)
```
--- a/library/bignum.c
+++ b/library/bignum.c
@@ -1563,9 +1563,9 @@ static mbedtls_mpi_uint mbedtls_int_div_int( mbedtls_mpi_uint u1,
      */
     if( 0 == d || u1 >= d )
     {
-        if (r != NULL) *r = ~0;
+        if (r != NULL) *r = ~(mbedtls_mpi_uint)0u;
 
-        return ( ~0 );
+        return ( ~(mbedtls_mpi_uint)0u );
     }
 
 #if defined(MBEDTLS_HAVE_UDBL)
@@ -1704,7 +1704,7 @@ int mbedtls_mpi_div_mpi( mbedtls_mpi *Q, mbedtls_mpi *R, const mbedtls_mpi *A,
     for( i = n; i > t ; i-- )
     {
         if( X.p[i] >= Y.p[t] )
-            Z.p[i - t - 1] = ~0;
+            Z.p[i - t - 1] = ~(mbedtls_mpi_uint)0u;
         else
         {
             Z.p[i - t - 1] = mbedtls_int_div_int( X.p[i], X.p[i - 1],
```
