### ISSUE TITLE
Use PSA_KEY_LIFETIME_IS_VOLATILE instead of lifetime == PSA_KEY_LIFETIME_VOLATILE

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3857]
Since #3302, there are volatile lifetimes other than `PSA_KEY_LIFETIME_VOLATILE`. So testing whether a key is volatile should now use `PSA_KEY_LIFETIME_IS_VOLATILE` instead of just comparing the lifetime to `PSA_KEY_LIFETIME_VOLATILE`.

At least one place was missed in #3302 in `mbedtls_psa_get_stats`. There may be others.

**Comment by ronald-cron-arm** [comment]
Argh, you're right I missed to fix the one in `mbedtls_psa_get_stats`.

**Comment by aditya-deshpande-arm** [comment]
Fixed by PR #4713
