### ISSUE TITLE
Broken build with ECDSA enabled but ECDH disabled

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#3891]
If I disable ECDH and all cipher suites that use ECDH, but keep ECDSA enabled, the build fails.
```
$ scripts/config.py unset MBEDTLS_ECDH_C
$ scripts/config.py unset MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
$ scripts/config.py unset MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
$ scripts/config.py unset MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
$ scripts/config.py unset MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
$ scripts/config.py unset MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
$ make lib
…
library/ssl_cli.c: In function ‘ssl_parse_supported_point_formats_ext’:
library/ssl_cli.c:1718:27: error: ‘mbedtls_ssl_handshake_params’ {aka ‘struct mbedtls_ssl_handshake_params’} has no member named ‘ecdh_ctx’
 1718 |             ssl->handshake->ecdh_ctx.point_format = p[0];
      |                           ^~
make: *** [Makefile:3313: library/ssl_cli.o] Error 1
```

Observed on cac5536b4545f5affadb461254ff15bccf176083 but I think it's been the case ever since https://github.com/ARMmbed/mbedtls/pull/304/commits/136884c29b3148f9eeb24e744069ade60755aa99.

This configuration is missing from `depends-pkalgs.pl` (it doesn't try to disable ECDH, or for that matter DHM which would be a little more useful).

This is a minor issue since there is no cipher suite with ECDSA but without ECDH, so this configuration is not very useful (which I guess is why nobody complained). But in principle it does make sense (e.g. if you reject all ECC except that you want to accept some legacy ECDSA certificates). And [it's messing up the migration to PSA](https://github.com/ARMmbed/mbedtls/pull/3830#discussion_r523461471).

**Comment by daverodgman** [comment]
Fixed in 2.25.0
