### ISSUE TITLE
EC J-PAKE driver dispatch implementation

### ISSUE THREAD

**Issue by daverodgman** [Mbed-TLS/mbedtls#4001]
Following the spec defined in #4000, implement the driver dispatch layer for EC J-PAKE

**Comment by AndrzejKurek** [comment]
Does this task also require adding acceleration through the driver dispatch code, similar to https://github.com/Mbed-TLS/mbedtls/pull/5871, or is it just about moving the logic around so that `psa_pake` calls `psa_driver_wrapper_pake` and it in turn calls `mbedtls_psa_pake_setup`?

**Comment by mpg** [comment]
The task description was quite terse, but as a general principle new features need to come with tests. When it comes to driver dispatch, I think that means (1) testing with "internal driver" (`PSA_CRYPTO_DRIVER_TEST`) _and_ (2) testing with external driver from libtestdriver1 and the software implementation excluded.

@superna9999 That means #5889 still needs relatively significant work (mostly writing `tests/src/drivers/test_driver_pake.c` which will probably be a few hundred lines of code). If you're still happy to do that, that would of course be very appreciated. If however, that's more than you have time for, please let us know and we'll take it from here.

**Comment by superna9999** [comment]
@mpg I won't haver time to implement the missing work, so please take the work over, I'll try find time in order review the following work.

**Comment by mpg** [comment]
Ok, thanks for letting us know!

**Comment by mpg** [comment]
I had assigned this to myself as I intended to work on it, but I have less time than anticipated, and others might be more available than me to work on this, so I'm un-assigning myself, so it can be picked up by someone else.
