### ISSUE TITLE
Document what parts of MBEDTLS_USE_PSA_CRYPTO are implemented

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4023]
The compile-time option `MBEDTLS_USE_PSA_CRYPTO` causes parts of the X.509 and TLS code to use PSA crypto primitives instead of classic ones.

What parts? I have no idea…

The goal of this task is to document what happens when `MBEDTLS_USE_PSA_CRYPTO` is enabled. Which calculations use PSA code and which calculations use legacy code? Do any limitations apply (things that work without `MBEDTLS_USE_PSA_CRYPTO` but not with it)?

Example of cases where this documentation is needed:

* As a developer of Mbed TLS (or of an application using Mbed TLS), when I'm debugging some code that uses TLS, I want to know what crypto code underlies it.
* As a user of Mbed TLS, I want to know which parts of the code can be replaced by PSA drivers, and where I need to keep the classic implementation enabled.

**Comment by mpg** [comment]
> As a user of Mbed TLS, I want to know which parts of the code can be replaced by PSA drivers, and where I need to keep the classic implementation enabled.

Note: currently PSA is only used for crypto operations themselves, so if you have a PSA driver for a hardware accelerator you will get the speed improvement, but I'm not sure the replacement has been done (so far!) in a way the allows the classic implementation to be disabled, as I think we still rely on it for things like enumerating algorithms, curves, etc.

For example for an ECDHE-ECDSA key exchange, unless I'm mistaken if you enable `USE_PSA_CRYPTO` and provide an opaque private key backed by PSA (see `MBEDTLS_PK_OPAQUE` in `pk.h`), then all the ECC computations in the handshake will be done by PSA, but the content of the `supported_elliptic_curves` extension in the ClientHello (and the logic for handling it on the server, and so on) are based on the list of curves supported by the built-in implementation and calling support function from the built-in implementation, such as `mbedtls_ecp_curve_info_from_grp_id()`.

So currently I think the goal has only been to allow _supplementing_ the built-in implementation with PSA drivers (to improve performance, and security in case of opaque keys), but not _replacing_ it (to save on code size). I agree this is a important goal in the long run, but it wasn't part of the initial steps - we have to start somewhere.

**Comment by stevew817** [comment]
> but I'm not sure the replacement has been done (so far!) in a way the allows the classic implementation to be disabled

I can confirm that it hasn't been done. We're experimenting on our end with `MBEDTLS_USE_PSA_CRYPTO` and have experienced the same: turning it on does not remove dependencies on Mbed TLS software crypto primitive code, and thus results in a pretty hefty chunk of dead code if the underlying PSA drivers do support everything requested.

Probably the way to go about it would be to re-target the SSL library to fully use PSA crypto and make its dependency-checking look at `PSA_WANT_xxx` instead of `MBEDTLS_xxx_C` (and let PSA handle the underlying algorithm dispatch to either drivers or Mbed TLS software crypto), but that seems like a daunting task.

**Comment by gilles-peskine-arm** [comment]
> re-target the SSL library to fully use PSA crypto and make its dependency-checking look at PSA_WANT_xxx instead of MBEDTLS_xxx_C

That's the long-term plan. How we'll go about it depends on what we prioritize. There will definitely be a transition period where both PSA and classic crypto code paths exist.

We're removing old protocol versions (SSL3, TLS1.0, TLS1.1, DTLS1.0) in Mbed TLS 3, so there'll be a little less crypto code to handle.

**Comment by gilles-peskine-arm** [comment]
Resolved by #4961.
