### ISSUE TITLE
Add prefixes to function definitions

### ISSUE THREAD

**Issue by pieceofsummer** [Mbed-TLS/mbedtls#406]
It would be nice to add configurable prefixes to function definitions to allow easily adding attributes to them. 

For example, on ESP8266 you might want to mark functions with `ICACHE_FLASH_ATTRIBUTE` macro (which is essentially `__attribute__((section(".irom0.text")))` ) to prevent placing them into instruction cache and wasting memory. Currently I use a script which runs through mbedtls sources and adds `MBEDTLS_API` prefix to public functions and `MBEDTLS_LOCAL` to private ones, and define those in my config.h. This causes a lot of modifications in sources, and it becomes hard to tell actual changes from these minor adjustments. So it would be great to have them from the start.

Same goes for static constants, which can be placed into program memory on embedded systems instead of wasting RAM. But here we will need several different prefixes, because on many platforms program memory can be accessed only with 32-bit aligned read instructions, so placing a byte array there will cause an error, but placing an int32 or int64 array is fine. So it might be something like `MBEDTLS_CONST_UNALIGNED`, `MBEDTLS_CONST_ALIGN32` etc.

Thanks.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-604

**Comment by pieceofsummer** [comment]
Also it would be nice if optional strings (like error messages and OID descriptions) would be wrapped in some macro to allow undefine them if not needed and save some memory on embedded.

**Comment by BurningEnlightenment** [comment]
:+1: this would also enable us to use mbedTLS as a DLL on windows and [gcc's visibilty feature](https://gcc.gnu.org/wiki/Visibility) (which is also supported by clang).
@pieceofsummer  are you willing to share your script in the meanwhile?

**Comment by pieceofsummer** [comment]
@BurningEnlightenment if to strip platform-specific hacks from my script, it would be quite simple:
```python
import os, sys, re

if len(sys.argv) < 2:
  exit(0)

extra_arg = sys.argv[2] if len(sys.argv) > 2 else None

if sys.argv[1].startswith("."):
  exit(0)

if os.path.isdir(sys.argv[1]):
  exit(0)

if not os.path.exists(sys.argv[1]):
  exit(-1)

cleanupRegex = re.compile(r"\bMBEDTLS_(LOCAL|API)\b")
funcRegex = re.compile(r"^\s*(static\s+)?(?P<type>(?:\b[a-z0-9_]+\b\s*[*]*)+)\s*(?P<name>\b[a-z0-9_]+\b)\s*\(", re.M | re.I)

def prefix_func(name, type, isStatic):
  # some exceptions might be handled here
  # for example, do not prefix *_zeroize functions
  if name.endswith("_zeroize"):
    return None

  if not isStatic and name.startswith("mbedtls_"):
    return "MBEDTLS_API"
  else:
    return "MBEDTLS_LOCAL"

def process_line(filename, line, clean):
  s = line.lstrip()
  if s.startswith("#") or s.startswith("//") or s.startswith("/*") or s.startswith("typedef "):
    # preprocessor definition, or typedef, or comment, ignore it
    return line
  
  # unroll any previous modifications made by this script
  cleanupMatch = cleanupRegex.match(line)
  if cleanupMatch:
    line = cleanupRegex.subn("", line)[0].lstrip()
    
  if clean:
    return line
    
  # check if it looks like function definition
  funcMatch = funcRegex.match(line)
  if not funcMatch:
    return line

  # ensure it is really a definition, not false positive
  returnType = funcMatch.group("type").strip()
  if returnType in [ "return", "else" ]:
    return line

  funcName = funcMatch.group("name")
  typePrefix = funcMatch.group(1)

  prefix = prefix_func(funcName, returnType, typePrefix is not None)
  if prefix:
    return prefix + " " + line

  return line

print "processing %s..." % sys.argv[1]

src = ""
changed = False

with open(sys.argv[1], "r") as f:
  for line in f.readlines():
    newline = process_line(sys.argv[1], line, "clean" == extra_arg)
    if newline and newline != line:
      line = newline
      changed = True
    src += line

if changed:
  with open(sys.argv[1], "w") as f:
    f.write(src)
```

It only takes a single file as an argument (doesn't support wildcards) because I was too lazy to handle that, and because it can be easily handled by `find` command-line utility. There's also an optional second argument "clean" to remove the prefixes added by this script.

**Comment by BurningEnlightenment** [comment]
@pieceofsummer thank you very much :smiley:

**Comment by sbutcher-arm** [comment]
Thanks for the feedback. I think it's a good idea, and we'll try and look at this in the future.

**Comment by sbutcher-arm** [comment]
This feature has been requested again in #465, with an offer of a pull request from @wilberforce.

**Comment by tom-cosgrove-arm** [comment]
I am closing this.

I would personally be in favour of `MBEDTLS_PUBLIC_API` etc, but that is handled by the directory a header file is in, not a label on the function definition.

Adding a mechanism to rename functions would just increase our API, increasing the cost of ongoing maintenance, for a very few use cases.

We even do a complete rename ourselves for the PSA driver testing, and didn't find it necessary to implement something like this then.
