### ISSUE TITLE
Skip or separate the API/ABI check on the development_3.0 branch

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4113]
We expect API changes on the `development_3.0` branch, so it would be nice if they weren't treated as CI failures.

This can either be done by tweaking the CI scripts or (probably simpler but ugly) changing `scripts/abi_check.py` to return 0 even if there are changes.

**Comment by mpg** [comment]
Now that `development_3.0` is no longer active, I assume this can be closed?

**Comment by gilles-peskine-arm** [comment]
Since 3.0 has been released, this is no longer relevant.

[I do think we should report ABI-check separately](https://github.com/Mbed-TLS/mbedtls-test/issues/48) but that's a task for mbedtls-test and we will definitely not allow an ABI change to mark the CI as a whole as passed.
