### ISSUE TITLE
the elliptic curve should be chosen by the order the ecc groups extension in "client hello" handshake message

### ISSUE THREAD

**Issue by gaoqingshui** [Mbed-TLS/mbedtls#4244]
### Description
- Type: Enhancement
- Priority: Minor
- version: mbedtls-2.25.0
-----------------------------------------------------------------
when the key exchange methos is ECDHE, one elliptic curve should be choosen based on both the supportage of client and server, but the processing order is wrong. The TLS server should choose one curve by the client side priority (the ecc group externsion in "client hello" message), not its own priority.

In code, it realized in function ssl_prepare_server_key_exchange of file tls_srv.c
Line 3403 - 3407
        /* Match our preference list against the offered curves */
        for( gid = ssl->conf->curve_list; *gid != MBEDTLS_ECP_DP_NONE; gid++ )
            for( curve = ssl->handshake->curves; *curve != NULL; curve++ )
                if( (*curve)->grp_id == *gid )
                    goto curve_matching_done;

should change like blow:
        /* Match our preference list against the offered curves */
        for( curve = ssl->handshake->curves; *curve != NULL; curve++ )
            for( gid = ssl->conf->curve_list; *gid != MBEDTLS_ECP_DP_NONE; gid++ )
                if( (*curve)->grp_id == *gid )
                    goto curve_matching_done;

**Comment by gilles-peskine-arm** [comment]
Why do you think the order is wrong? Why would the server not apply its own preferences?

If we change this, shouldn't we change the order for other preferences as well (e.g. hash and signature algorithms)?

For ciphersuites, the default is to use the server preference, but there's a compile time option `MBEDTLS_SSL_SRV_RESPECT_CLIENT_PREFERENCE` to use the client preference instead. It would make sense for this option to control curve, hash algorithm and signature algorithms as well.

**Comment by aditya-deshpande-arm** [comment]
Fixed by PR #4606
