### ISSUE TITLE
PSA: implement support for CBC-MAC

### ISSUE THREAD

**Issue by bensze01** [Mbed-TLS/mbedtls#4260]
We currently do not support [`PSA_ALG_CBC_MAC`](https://armmbed.github.io/mbed-crypto/html/api/ops/macs.html#c.PSA_ALG_CBC_MAC) through the PSA crypto API.

**Comment by gilles-peskine-arm** [comment]
I don't think Mbed TLS should implement CBC-MAC. It's a legacy algorithm which has a major caveat: it requires all messages signed with the same key to have the same length, and the API cannot enforce this. I added it to the specification without thinking it through and now regret it.

**Comment by gilles-peskine-arm** [comment]
Arm does not intend to implement CBC-MAC, which is an obsolete algorithm with known pitfalls. Therefore I am closing this issue.

We would accept a contributed implementation of CBC-MAC if there is demand for using Mbed TLS with a protocol that requires the use of CBC-MAC.
