### ISSUE TITLE
Cmake: cmake file hierarchy is not clean

### ISSUE THREAD

**Issue by gyuri-szing** [Mbed-TLS/mbedtls#4270]
### Description
- Type: Bug
- Priority: Minor

---------------------------------------------------------------
The project contains several CMakeLists.txt files and the relation between them is not clean.

#### Long term suggestions
In general I suggest using CMakeLists.txt files to indicate "build system entry points". Only use this file-name if the directory is planned to be used to start the build from, or to be used by external projects with `add_subdirectory()`.

Use `add_subdirectory()` for integration your own components only if:
- you need the name-spacing provided by the command.
- the component can be built stand-alone (see above).
If none of the above is true, use simple `include()`.

This would clearly indicate for users of the project what is expected to work and what is not, and would avoid the complicated name spacing of cmake if not strongly needed.

================
I suggest coming up with a clear specification which cmake integration feature is used for what purpose. Example:
- use `include(xxx.cmake)` for "structured programming" (to break up large cmake script to smaller more manageable components).
- use `include(xxx)` for code sharing (getting access to "cmake modules"). Cmake modules capture non-project specific functionality and allow sharing code with other projects. Modules are included relative to `CMAKE_MODULE_PATH` which allows re-mapping the modules to external locations.
- use `add_subdirectory()` for sub-projects owned by the mbedtls project (components having the same owner and lifecycle). 
- use `find_module()` for external C/C++ dependencies (different owner and/or different lifecycle). 

================

See: [how TF-A](https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/4603/16/docs/cmake/concepts.rst) plans to handle the same topic.

#### Issues
I list here some specific issues:
1. [3rdparty/CMakeLists.txt](https://github.com/ARMmbed/mbedtls/blob/development/3rdparty/CMakeLists.txt) is not a real cmake project. It only changes some variables and does some processing. it even has to use `set(....GLOBAL SCOPE)` to work around incorrectly being a sub-project.
2. [include/CMakeLists.txt](https://github.com/ARMmbed/mbedtls/blob/development/include/CMakeLists.txt) is not a real project file. This is a "module" which configures the install target, well sometimes. This should be a `<whatever.cmake` file included from CMakeLists.txt files.
3. [include/CMakeLists.txt](https://github.com/ARMmbed/mbedtls/blob/development/include/CMakeLists.txt) It is not clean what is the purpose of this file. I.e. if I only build the `library` sub-project, and want to get headers installed, then how do I use this file?

**Comment by CJKay** [comment]
I think there's a misconception here about the purpose of `CMakeLists.txt` - there's no indication in any documentation that it's intended solely to represent build system entrypoints, and a cursory search doesn't pull anything up. It's just a convenient way to enter a subdirectory to process path-relative information, which [this mailing list thread](https://cmake.org/pipermail/cmake/2007-November/017896.html) seems to back up:

> Use ADD_SUBDIRECTORY when the subdirectory has a CMakeLists.txt file.
>
> Use INCLUDE to include *.cmake script files (that find files, libraries or
programs, for example, or perhaps that contain macros independent of the
directory, or that have common SET statements that you need in more than
once place...)

So I think `include` is more akin to C's `#include` for re-using code, whereas `add_subdirectory` is more intended to represent each component (and having a dedicated build directory reflects that).

One other problem with using `include` for this sort of thing is relativised paths. For example, using `add_library()` with `include()` requires that you prefix every file with `${CMAKE_CURRENT_LIST_DIR}`:

```
add_library(xyz STATIC
    "${CMAKE_CURRENT_LIST_DIR}/src/lib.c")
```

With `add_subdirectory`, CMake sets `CMAKE_CURRENT_SOURCE_DIR` to the list file directory, and relativises any paths to it:

```
add_library(xyz STATIC
    "src/lib.c")
```

This also allows you to keep your logic compartmentalised without worrying whether anything you're doing in `CMAKE_CURRENT_BINARY_DIR` might collide with logic elsewhere in the build system. This is very convenient for larger projects, and I honestly think switching to `include` would have the opposite effect of cleaning up the hierarchy.

WRT TF-A: we are no longer following the `include()`-only scheme - components are split into individual `CMakeLists.txt` files (see [`bl1/CMakeLists.txt`](https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/8132/8/bl1/CMakeLists.txt) for an example subcomponent). This is the same scheme as [SCP-firmware](https://github.com/ARM-software/SCP-firmware/tree/master/framework), [vulkan-sdk](https://github.com/ARM-software/vulkan-sdk/blob/8f892c4edb4b440349f18ca0961387cb1d50621f/platform/CMakeLists.txt), [perfdoc](https://github.com/ARM-software/perfdoc/blob/718ab65de48b964c3355df33f8d7a5f4253cf7c7/tests/util/CMakeLists.txt), etc., so I think it's worth keeping the projects structurally in-line.

**Comment by gyuri-szing** [comment]
I understand that this is not a widely spread pattern in cmake world, but let's see some benefits and drawbacks.
Benefits:
- it clearly expresses what works and what does not (from which directory you can build something). Other files would just add noise. You don't have to write and update documentation, CI scripts can easily know where the build shall work.
- add_subdirectory() comes with the false promise of giving you a name space and separation from other modules, but really it is quite limited. You still have to keep an eye on global settings (i.e. build type specific variables, command modifying build flags globally, etc...), and your module is not a real module as it can not be re-used unless being carefully written. This name spacing in cmake is more an organically grown hack than a designed feature, and it is just better to stay away.
- You avoid complex, non-intuitive behavior, and avoid people working on cmake scripts needing to be cmake experts. Less surprises, less maintenance work.

Drawbacks:
- CMAKE_CURRENT_SOURCE_DIR family of variables are not updated. So it's harder to use file relative paths in commands which use these (add_library(), add_executable(), target_sources(), etc..). This makes your scripts uglier but is there a real issue with this? I encountered none.
- Organization of binary directory. Well I don't think this is a real issue. The content of the binary directory is internal to cmake, you have to build an interface using the install() command anyways. If in any case you have to start digging in the binary directory things are already seriously wrong. I had to dive in a few times, but not using add_subdirectory() was not making it harder. I never encountered a conflict between file names due to this, and this risk does not seem to be high.
- The solution might be alien to folks using cmake with other projects. It this a real issue?

So I think it is better to restrict add_subdirectory() to cases where it is really needed. No false promises, no complex, non intuitive operation. If you integrate your own components I don't see an issue with using include() instead.
When you actually need this kind of separation is mostly if you want to use external projects. But in such cases the separation provided by the commend is too weak. This is why ExternalProject() was born.
