### ISSUE TITLE
mbedTLS needs a logo

### ISSUE THREAD

**Issue by bel2125** [Mbed-TLS/mbedtls#4299]
## Enhancement / Feature Request

**Suggested enhancement**  

Create a logo and add it to the main README.md and to https://tls.mbed.org/
If there already is one, please add it to these pages, so it can be found.
If there is non, please create one. It could be something as simple as the name of the library in a certain font/color/writing style - or something more fancy.

**Justification - why does the library need this feature?**  

Everything of importance needs a logo.
A quick Google search for "why is a logo important" will give you dozens of reasons.
A memorable visual symbol for each element will also allow an efficient communication of a complete technology stack.

**Comment by chris-jones-arm** [comment]
Thanks for the suggestion @bel2125.

We are currently not maintaining https://tls.mbed.org/ as is noted on the homepage as we are now governed as part of https://www.trustedfirmware.org/ where our project logo can be found alongside the other Trusted Firmware projects. That being said I personally think adding our logo to the README.md is a great idea and I will raise it with the rest of the team.
