### ISSUE TITLE
IAR build fails when MBEDTLS_HMAC_DRBG_C is defined

### ISSUE THREAD

**Issue by smjackson** [Mbed-TLS/mbedtls#4300]
---------------------------------------------------------------
### Description
- Type: Bug 
- Priority: Minor

---------------------------------------------------------------
## Bug

**mbed TLS build:**  
Version: 2.26.0
  
Configuration: Generated by `config.py` targeting `baremetal`. The key is that `MBEDTLS_HMAC_DRBG_C` is defined in config.h
Compiler and options:  IAR 8.22.1 via supplied CMake

**Expected behavior** 
Able to compile mbedtls

**Actual behavior**  
Build fails with the following output:

    $ ninja
    [20/92] Building C object library\CMakeFiles\mbedcrypto.dir\ecp.c.obj
    FAILED: library/CMakeFiles/mbedcrypto.dir/ecp.c.obj
    C:\PROGRA~2\IARSYS~1\EMBEDD~1.1\arm\bin\iccarm.exe  --silent ..\library\ecp.c  -I..\include -I..\library --warn_about_c_style_casts --warnings_are_errors -Ohz -e --dependencies=ns library\CMakeFiles\mbedcrypto.dir\ecp.c.obj.d -o library\CMakeFiles\mbedcrypto.dir\ecp.c.obj
    
          const mbedtls_md_type_t md_type = mbedtls_md_list()[0];
                                            ^
    "D:\git\mbedtls\library\ecp.c",175  Error[Pe188]: enumerated type mixed with
              another type

IAR warns when assigning to enums if the enum type does not match. In this case, it is warning about an `int` being assigned to enum type `mbedtls_md_type_t`.

**Steps to reproduce**  
Run CMake, targeting an IAR toolchain and build. I used this:
    
    cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="../iar_toolchain.cmake" ..
    ninja

Where the contents of iar_toolchain.cmake are as follows:

    ### BEGIN CMAKE_TOOLCHAIN_FILE
    # "Generic" is used when cross compiling
    set(CMAKE_SYSTEM_NAME Generic)
    
    # Set the EW installation root directory
    #(Avoid spaces in the path or you need to escape them)
    set(EW_ROOT_DIR "C:/Program Files (x86)/IAR Systems/Embedded Workbench 8.22.1/arm")
    
    
    # Disable creating test programs and testing the algorithms
    option(ENABLE_PROGRAMS "Build mbed TLS programs." OFF)
    option(ENABLE_TESTING "Build mbed TLS tests." OFF)
    
    # Set up the CMake variables for compiler and assembler
    # (The reason for both C and CXX variables is that CMake
    # treats C and C++ tools individually)
    set(CMAKE_C_COMPILER "${EW_ROOT_DIR}/bin/iccarm.exe" " --dlib_config normal")
    set(CMAKE_CXX_COMPILER "${EW_ROOT_DIR}/bin/iccarm.exe" " --dlib_config normal")
    set(CMAKE_ASM_COMPILER "${EW_ROOT_DIR}/bin/iasmarm.exe")
    
    ### END CMAKE_TOOLCHAIN_FILE

**Comment by chris-jones-arm** [comment]
Thanks for the report @smjackson.

Unfortunately I can't seem to reproduce the issue however I can't currently test with IAR or on windows which would likely explain the issue. Although I can't verify the problem exactly, from the error message it seems like it is a potential bug and so we will need a more thorough investigation to pinpoint and fix the problem.

**Comment by minosgalanakis** [comment]
Closing as the issues has been addressed
