### ISSUE TITLE
Upstream documentation and prototype for TLS 1.3 0-RTT API

### ISSUE THREAD

**Issue by hanno-arm** [Mbed-TLS/mbedtls#4331]
This issue tracks the upstreaming of parts of the TLS 1.3 specific 0-RTT functionality, specifically:
* The documentation and function prototypes for all 0-RTT related APIs, incl. configuration and data read/write APIs.
* Potentially the implementation of the configuration APIs and the required fields.

Upstreaming the implementation of the 0-RTT functionality itself is left for a separate issue.

__Work:__ 1 engineering day + review & rework

**Comment by hanno-arm** [comment]
@mpg @yanesca @gilles-peskine-arm Before doing work on the code, I'd like to hear your opinion on our options here.

On the server, we have multiple options for how to notify it about the receipt of 0-RTT:
* Let the server specify a callback which is triggered during the handshake. 
* Let the server specify a target buffer to hold 0-RTT which is filled during the handshake.
* Add a new read-API which is specific to 0-RTT, forcing Mbed TLS to buffer the 0-RTT internally.

Currently, the TLS 1.3 prototype uses the first option, a server-specified callback. This seems reasonable, but deviates from how classical application data is received.

Do you have some thoughts? Any arguments for either of the above options, or even suggestions for further alternatives?

**Comment by ronald-cron-arm** [comment]
Covered by https://github.com/Mbed-TLS/mbedtls/issues/4902 and https://github.com/Mbed-TLS/mbedtls/issues/6310 now.
