### ISSUE TITLE
Adapt GCM tests to ALT implementations with delayed output

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4354]
The new `gcm.h` API in Mbed TLS 3.0 (https://github.com/ARMmbed/mbedtls/issues/4350) allows `mbedtls_gcm_update` to delay its output when given a fractional block. The software implementation in Mbed TLS emits all output immediately, but some alternative implementations cannot due to hardware restrictions.

The GCM unit tests assume that `mbedtls_gcm_update` returns its output immediately. The goal of this task is to allow `MBEDTLS_GCM_ALT` implementations to delay up to the next block boundary in the unit tests and the GCM self-tests.

**Comment by tom-cosgrove-arm** [comment]
There's not much point updating tests for an interface that will become deprecated as we move to PSA drivers
