### ISSUE TITLE
Adapt cipher module and tests to ALT implementations of CCM/GCM with delayed output

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4356]
The new `cipher.h` API in Mbed TLS 3.0 (https://github.com/ARMmbed/mbedtls/issues/4355) allows GCM and CCM update to delay their output when given a fractional block. The software implementation in Mbed TLS emits all output immediately, but some alternative implementations cannot due to hardware restrictions.

The goal of this task is to make `cipher.c` and the cipher tests work with alternative implementations that delay partial input blocks.

**Comment by mpg** [comment]
@gilles-peskine-arm I've added this to the "3.0 optional" epic for the sake of consistency with the label, but it's unclear to me why this label mbedtls-3.

**Comment by gilles-peskine-arm** [comment]
This is about testing a feature which cannot be implemented with the current API. The API change needs to go into 3.0, but the additional tests for that feature can be done in a later 3.x. Hence the label `mbedtls-3`, but no epic because there's no particular deadline.

**Comment by gilles-peskine-arm** [comment]
`mbedtls_cipher_finish` will now need to call `mbedtls_gcm_finish`. Currently, that's done in `mbedtls_cipher_write_tag` and `mbedtls_cipher_check_tag`, but those functions have no way to output the last block.

Since `mbedtls_gcm_finish` calculates the tag, `mbedtls_cipher_finish` will need to store it for the sake of later retrieval with `mbedtls_cipher_xxx_tag`. It can use the cipher context for that, for example a union with IV fields which are no longer useful at that point in the lifecycle of the operation.

**Comment by tom-cosgrove-arm** [comment]
There's not much point updating tests for an interface that will become deprecated as we move to PSA drivers
