### ISSUE TITLE
Document that AES ALT implementations may omit AES-192

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4410]
Since a while ago (I'm sure it was before 2.16), we effectively allow alternative implementations of AES to omit support for AES-192. However, this decision was not properly documented.

The goal of this task is to ensure that the library documentation properly indicates that AES-192 support is optional when `MBEDTLS_AES_ALT` is enabled. (The function-specific `MBEDTLS_AES_xxx_ALT` do not allow this freedom.) The audience of this documentation is both `MBEDTLS_AES_ALT` implementers (so that they know they can omit AES-192, and also to reinforce that they must provide support for both AES-128 and AES-256), and users of the library who may get an ALT implementation as part of a platform image.

Places do modify: at least the description of `MBEDTLS_AES_C` in `config.h`; probably also parts of `aes.h`.

**Comment by tom-cosgrove-arm** [comment]
We're not going to update documentation for an interface that will become deprecated as we move to PSA drivers
