### ISSUE TITLE
Upstream TLS 1.3 0-RTT functionality

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#4421]
This issue tracks the upstreaming of the 0-RTT feature of TLS 1.3:
* Negotiation of the use of 0-RTT in ClientHello and ServerHello, building on #4417 and #4418 
* 0-RTT send/receive, forward to user via API developed in https://github.com/ARMmbed/mbedtls/issues/4331 
* EndOfEarlyData writing/parsing

Precise acceptance criteria TBD.

Source: https://github.com/hannestschofenig/mbedtls/tree/tls13-prototype

**Comment by ronald-cron-arm** [comment]
Closing as we have an EPIC for that now: https://github.com/orgs/Mbed-TLS/projects/5#column-19369183.
