### ISSUE TITLE
Threefish and Skein (enhancement request)

### ISSUE THREAD

**Issue by udf2457** [Mbed-TLS/mbedtls#443]
Any plans to add ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-679

**Comment by sbutcher-arm** [comment]
mbed TLS is a [SSL library](https://tls.mbed.org/ssl-library) and as a consequence, the crypto primitives it supports are there to support TLS. Threefish and Skein are not yet part of the TLS standards, so are not something we are planning to support.

However, if someone in the community wished to work on this and propose it as a Pull Request, we would certainly consider adopting it, if it met our requirements (test cases, documentation, style, etc). Therefore I'll leave this item open.

**Comment by daverodgman** [comment]
We have no plans to include these algorithms, as we don't hear much demand for them. If someone has a valid use-case, we'd be happy to accept a contribution or re-open this issue to track the request.
