### ISSUE TITLE
forge `gen_key` and `cert_write` into library

### ISSUE THREAD

**Issue by azadkuh** [Mbed-TLS/mbedtls#450]
it would be great if `mbedtls` provide a key / cert generator right into a **high-level api** as other libs like `botan`, `cryptopp` and `openssl` do. this allows programmers to directly generate keys and certs easily or without spawning another process or ...

then the `gen_key` and `cert_write` would be thin app-wrappers around those api.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-695

**Comment by sbutcher-arm** [comment]
Thanks for the feedback!

This is something we've considered in the past and would like to do something similar in the future, so I'm leaving this issue open as a feature request.

**Comment by tom-daubney-arm** [comment]
This is not something that we wish to bring into the library and so this issue will be closed.
