### ISSUE TITLE
Provide parsing of all types of subjectAltName

### ISSUE THREAD

**Issue by NWilson** [Mbed-TLS/mbedtls#459]
Currently, we have a pile of custom X.509 parsing that sits on top of mbedTLS, in order to extract otherName subjectAltNames from certificates (Microsoft's ActiveDirectory certificates put the user names in the otherName format).

Even if mbedTLS only provides "full" parsing for dNSName and iPAddress subjectAltNames, it would help just to provide a way to extract the raw ASN.1 bytes of the names. Currently, using the public functions you have to actually manually parse the entire list of extensions in the cert to hunt for subjectAltName, then parse that to hunt for each individual name, which is code that mbedTLS already ships.

If there's appetite for it, I'd be happy to contribute the code.

The suggested API would be to extend the `mbedtls_x509_sequence subject_alt_names` in `mbedtls_x509_crt` to contain all the names, rather than stripping the non-dNSName ones. Alternatively, you could just make the local/static parsing functions in x509_crt.c public, so that there's a way to extract the names from `v3_ext` if you want them.

**Comment by sbutcher-arm** [comment]
Hi @NWilson!

I'd welcome the contribution, but as you know we still have a backlog of PRs to absorb, so it may take a little time to accept.

**Comment by sbutcher-arm** [comment]
For clarity, @yanesca has just pointed out to me that IP addresses in subjectAltNames is a feature we support and will be merged in the next day or two.

**Comment by knap1930** [comment]
@sbutcher-arm Any idea when support for ipAddresses in the subjectAltNames will be merged?

**Comment by mman** [comment]
I'd love to see support for rfc822Name as well.

**Comment by jobbflykt** [comment]
+1
All names should be stored in subject_alt_names. Filtering printable names could be done in `x509_info_subject_alt_name` but at least rfc822Name, dNSName and uniformResourceIdentifier can be printed.

**Comment by RonEld** [comment]
I believe this is addressed in #2530

**Comment by AndrzejKurek** [comment]
I'm closing this issue, as this is possible with the current state of code. Please see https://github.com/Mbed-TLS/mbedtls/blob/74d6e59e152dda5d4b5e85d2b9efca83ad32619c/tests/suites/test_suite_x509parse.function#L419 for an example.
Further improvements for SAN parsing will be comming in the following PR's:
- https://github.com/Mbed-TLS/mbedtls/pull/6882 (bugfix/tests);
- https://github.com/Mbed-TLS/mbedtls/pull/6475 (IP address parsing);
- https://github.com/Mbed-TLS/mbedtls/pull/6900 (directoryName parsing);
- https://github.com/Mbed-TLS/mbedtls/pull/6847 (URI parsing);
If there's something else to request or you would like to add something, please reopen this issue or create a new one.
Thanks for bearing for so long!
