### ISSUE TITLE
Check_config: Reevaluate dependency of `MBEDTLS_USE_PSA_CRYPTO` on `MBEDTLS_PSA_CRYPTO_C`

### ISSUE THREAD

**Issue by urutva** [Mbed-TLS/mbedtls#4597]
---------------------------------------------------------------
### Description
- Type: Bug
- Priority: Major

In Zephyr, we are using Mbed TLS on NS side to generate device CSR (Certificate Signing Request) and to use TF-M backend in Mbed TLS we had to enable the macro `MBEDTLS_USE_PSA_CRYPTO`. But this macro depends on `MBEDTLS_PSA_CRYPTO_C` which control PSA crypto implementation in Mbed TLS. Therefore, when we’ve TF-M and Mbed TLS with TF-M backend, there will be two implementations of PSA Crypto (even though same/similar depending on the version of Mbed TLS used in TF-M and Zephyr). The dependency of `MBEDTLS_USE_PSA_CRYPTO` on `MBEDTLS_PSA_CRYPTO_C` mandates using local implementation instead of TF-M PSA crypto. This is observed in Zephyr, the PSA crypto calls from application will be linked to the library that comes first on the linker command. So, if Mbed TLS library comes first then all the PSA crypto calls from application will be linked to Mbed TLS instead of TF-M.

The [PR](https://github.com/ARMmbed/mbedtls/pull/4092) introduced `MBEDTLS_PSA_CRYPTO_CLIENT ` that allows `MBEDTLS_PSA_CRYPTO_C` to be disabled. But the dependency of `MBEDTLS_USE_PSA_CRYPTO` on `MBEDTLS_PSA_CRYPTO_C` was not updated as part of the PR.

Additional information:
With TF-M on secure side and Mbed TLS on non-secure side, enabling `MBEDTLS_PSA_CRYPTO_CLIENT` causes linker failure with duplicate definition of key attribute modification APIs. `psa_reset_key_attributes` , `psa_set_key_domain_parameters` and `psa_get_key_domain_parametersare` defined in both `psa_crypto_client.c` and `tfm_crypto_ipc_api.o`.

---------------------------------------------------------------
## Bug

**OS**  
Zephyr

**mbed TLS build:**  
Version: 2.26.0
OS version: 6e2522d3de8596571d98f01bb17e7f50bf640255 (tag: v2.6.0-rc2)
Configuration: please attach config.h file where possible  
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information:  

**Expected behavior** 
Enable `MBEDTLS_USE_PSA_CRYPTO` without enabling `MBEDTLS_PSA_CRYPTO_C`.

**Actual behavior**
Compiler error when only `MBEDTLS_USE_PSA_CRYPTO` is enabled and enabling both `MBEDTLS_USE_PSA_CRYPTO` and `MBEDTLS_PSA_CRYPTO_C` causes PSA API calls from application to linked against Mbed TLS PSA crypto instead of TF-M.

**Steps to reproduce**

**Comment by gilles-peskine-arm** [comment]
Blocking the compilation if `MBEDTLS_USE_PSA_CRYPTO` is enabled but not `MBEDTLS_PSA_CRYPTO_C` was not a bug: there were many things in pk/x509/ssl that don't work without some helper functions that end up on the secure side in TF-M. Throughout the evolution of Mbed TLS 3.x, we have made a lot of progress in removing these dependencies.

In Mbed TLS 3.6 LTS, we still cannot promise that all the ways to configure `MBEDTLS_USE_PSA_CRYPTO` with only `MBEDTLS_PSA_CRYPTO_CLIENT` will work, and we are currently not testing this. However, we have worked with TF-M to ensure that at least in the default TF-M configurations (and possibly with some TF-M patches), this does work. As a consequence, we have changed `check_config.h` to have `MBEDTLS_USE_PSA_CRYPTO` require only `MBEDTLS_PSA_CRYPTO_CLIENT` and not `MBEDTLS_PSA_CRYPTO_C`. Therefore, I am marking this issue as done.

Please don't hesitate to raise new issues if a particular configuration doesn't work. However, do note that we'll likely treat them as feature requests, so unlikely to add them to the 3.6 LTS branch unless they can be resolved very easily.
