### ISSUE TITLE
Threading should have a default Windows implementation

### ISSUE THREAD

**Issue by simonbutcher** [Mbed-TLS/mbedtls#471]
In the file `library/threading.c`, a default implementation of the mutex is implemented for use on a Unix/POSIX platform that supports pthreads, but no other defaults are provided. A default Windows implementation would be a good idea, as it can be tested as part of the mbed TLS CI system, saves others reimplementing a common feature and would provide consistent support.

Suggested by Fredrik Axelsson, and open for community contribution.

**Comment by tom-daubney-arm** [comment]
There won't be any time allocated in the roadmap for this, so will close. If someone wants this then please feel free to raise a PR.
