### ISSUE TITLE
Support alternate name when generating CSR

### ISSUE THREAD

**Issue by dannybackx** [Mbed-TLS/mbedtls#4732]
### Suggested enhancement

It would be good to document how to use mbedtls to generate certificates for multi-homed hosts via ACME.
See sample code below, doesn't work. Help appreciated.
(Already tried https://github.com/ARMmbed/mbedtls/issues/1878#issuecomment-846990661 but this was off-topic)

### Justification

Mbed TLS needs this because only simple single-homed cases are documented

My code is in http://svn.code.sf.net/p/esp32-acme-client/code/trunk/libraries/acmeclient/Acme.cpp (see function Acme::CreateAltUrlList) :

int Acme::CreateAltUrlList(mbedtls_x509write_csr req) {
  int l = 20;
  int ret;

  for (int i=0; alt_urls[i]; i++) {
    l += strlen(alt_urls[i]) + 20;
  }
  unsigned char *buf = (unsigned char *)malloc(l), *p = buf + l;

  int len = 0;
  for (int i=0; alt_urls[i]; i++) {
    MBEDTLS_ASN1_CHK_ADD(len, mbedtls_asn1_write_raw_buffer(&p, buf, (const unsigned char *)alt_urls[i], strlen(alt_urls[i])));
    MBEDTLS_ASN1_CHK_ADD(len, mbedtls_asn1_write_len(&p, buf, strlen(alt_urls[i])));
    MBEDTLS_ASN1_CHK_ADD(len, mbedtls_asn1_write_tag(&p, buf, MBEDTLS_ASN1_CONTEXT_SPECIFIC | 2));
  }

  MBEDTLS_ASN1_CHK_ADD(len, mbedtls_asn1_write_len(&p, buf, len));
  MBEDTLS_ASN1_CHK_ADD(len, mbedtls_asn1_write_tag(&p, buf, MBEDTLS_ASN1_CONSTRUCTED | MBEDTLS_ASN1_SEQUENCE));

  if ((ret = mbedtls_x509write_csr_set_extension(&req,
        MBEDTLS_OID_SUBJECT_ALT_NAME, MBEDTLS_OID_SIZE(MBEDTLS_OID_SUBJECT_ALT_NAME),
        (const unsigned char *)p, len)) != 0) {
    char errbuf[80];
    mbedtls_strerror(ret, errbuf, sizeof(errbuf));
    ESP_LOGE(acme_tag, "%s: mbedtls_x509write_csr_set_extension failed %s (0x%04x)", __FUNCTION__, errbuf, -ret);
  }

  free(buf);
  ESP_LOGD(acme_tag, "%s: ret %d", __FUNCTION__, ret);
  return ret;
}

**Comment by yanesca** [comment]
Hi @dannybackx, have you considered asking your question on the mailing list?
https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls.
(There are a lot of people on the list and there might be people who had similar issues or can help.)

**Comment by mprse** [comment]
This issue looks like duplication of https://github.com/Mbed-TLS/mbedtls/issues/4732 and `SubjectAltName` extension is included to a CSR in PR https://github.com/Mbed-TLS/mbedtls/pull/6852.
Closing this one. Work will be traced under #4732.
