### ISSUE TITLE
PSA J-PAKE API has missing elements and confusing documentation

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#4745]
Issues found in the J-PAKE API proposal by @athoelke:

- `PSA_PAKE_CIPHER_SUITE_INIT` not provided by Mbed TLS.
- `psa_pake_cipher_suite_init()` not provided by Mbed TLS.
- `PSA_PAKE_OPERATION_INIT` not documented by Mbed TLS
- The `cipher_suite` parameter to `psa_pake_setup()` should be passed by reference as const `psa_pake_cipher_suite_t *`, instead of by value as `psa_pake_cipher_suite_t`.
- The `input` parameter to `psa_pake_input()` should be const `uint8_t *`, instead of `uint8_t *`.
- The `input` and `input_length` parameters to `psa_pake_input()` are documented as [out] parameters in the doxygen comments in Mbed TLS.
- `psa_pake_abort()` is not defined (but referenced) in Mbed TLS.
- In Mbed TLS, `psa_pake_cs_get_family()` and `psa_pake_cs_get_bits()` are referenced by `PSA_PAKE_PRIMITIVE_TYPE_DH` and `PSA_PAKE_PRIMITIVE_TYPE_ECC`, but not defined.
- In the buffer size macro `PSA_PAKE_OUTPUT_SIZE()` , the return value description still talks about 'cipher suite' and 'output type', instead of the 'primitive' and 'output step'.
- The same holds for `PSA_PAKE_INPUT_STEP()`
- The `output_size` parameter for `psa_pake_output()` refers to `PSA_PAKE_OUTPUT_SIZE(alg, cipher_suite, type)` to calculate the buffer size. Clearly this should be `PSA_PAKE_OUTPUT_SIZE(alg, primitive, step)`. The spec documentation also defines alg and primitive as these are not local to the function being called (in the cipher-suite used to set up the operation).
- PSA_ALG_JPAKE itself, the description of how the password is processed has not been properly updated to reflect that only way to input a password is via a key. e.g.:
   - "the password is read as a byte array" - might be better to describe the 'key material' or 'key content'.
   - ".. must be non-empty" - redundant, keys cannot have size zero.
   - "The psa_pake_set_password_xxx() functions - there is only one for now, psa_pake_set_password_key().

**Comment by athoelke** [comment]
Some further changes have been made to the PSA API specification, that differ from the mbedtls API:

*   Verification failure is reported by `psa_pake_input()` using `PSA_ERROR_INVALID_SIGNATURE` instead of `PSA_ERROR_INVALID_ARGUMENT`.
*   Change from 'side' to 'role' in the API:
    
    -   `psa_pake_side_t` -> `psa_pake_role_t`
    -   `psa_pake_set_side()` -> `psa_pake_set_role()`
    -   `PSA_PAKE_SIDE_XXX` -> `PSA_PAKE_ROLE_XXX`

**Comment by superna9999** [comment]
I can't find the changes to do for:
```
The same holds for PSA_PAKE_INPUT_STEP()
```

**Comment by mpg** [comment]
Hmm, I can't find any trace of `PSA_PAKE_INPUT_STEP()` in our code or [the spec](https://armmbed.github.io/mbed-crypto/1.1_PAKE_Extension.0-bet.0/psa_crypto_api_pake_ext.pdf). From the context, perhaps it was actually about `PSA_PAKE_INPUT_SIZE()`?

**Comment by superna9999** [comment]
OK, right it was about description of `PSA_PAKE_OUTPUT_MAX_SIZE` & `PSA_PAKE_INPUT_MAX_SIZE` using the wrong parameters to `PSA_PAKE_OUTPUT_SIZE` & `PSA_PAKE_INPUT_SIZE`
