### ISSUE TITLE
Cleanup use of ECDHE in TLS 1.3 prototype

### ISSUE THREAD

**Issue by hanno-becker** [Mbed-TLS/mbedtls#4824]
There are slight differences between the encoding of ECC curves in TLS 1.2 and TLS 1.3, which lead to duplication of most ECDHE-API in TLS 1.3 for prototyping. For upstreaming, study the precise differences and consolidate TLS 1.2 and TLS 1.3 ECDHE implementations.

**Comment by yuhaoth** [comment]
Possible subtasks:
[ ] mbedtls_ecdh_tls13_make_params .

**Comment by ronald-cron-arm** [comment]
I am moving this out of the TLS 1.3 MVP EPIC to the TLS 1.3 EPIC. The current TLS 1.3 ECDH code does what we need for the MVP, its limitations have been described in tls13-experimental.md (no support for restartable and everest) and there is not a lot of additional TLS 1.3 specific code. Currently, we lean towards switching quickly to PSA APIs for ECDHE key agreement which would make the cleanup defined by this issue useless.

**Comment by ronald-cron-arm** [comment]
There is no ECDHE code specific to TLS 1.3 anymore thus this issue can be closed.
