### ISSUE TITLE
Activate new documentation platform

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#4862]
This is a followup to https://github.com/ARMmbed/mbedtls/issues/3643.

The task is done once

- [x] a Read the Docs project is set up for Mbed TLS
- [x] version independent (https://github.com/ARMmbed/mbedtls-docs) documentation is displayed

**Comment by gilles-peskine-arm** [comment]
This has been done for a few months now. https://mbed-tls.readthedocs.io/en/latest/ is live and serving content from https://github.com/ARMmbed/mbedtls-docs .
