### ISSUE TITLE
Implement new code style with clang-format

### ISSUE THREAD

**Issue by mstarzyk-mobica** [Mbed-TLS/mbedtls#4887]
After code-styles investigation done in #4668 which resulted in draft #4794, this task is about implementing the new code-style in whole library.

We agreed to use clang-format, version 12.
New style is based on K&R and follows it as closely as possible.
- 4 spaces indentation (instead of 8, used in Linux Kernel)
- Formatting disabled on:
    - Doxygen comments - clang-format cannot handle doxygen blocks exceeding 80 char limit (if allowed to format them, the lines will be re-flown and these comment blocks might not be correctly parsed by Doxygen)
    - ASN.1 object identifier comments - even if exceeding 80 char limit, these should not be reformated, clang-format might split the line and corrupt the object identifiers
    - BEGIN_CASE/END_CASE test blocks comments - test code generator expects them to be as they are. Clang-format might reformat the comment block rendering the test case unrecognizable
    - no-check-names comments - clang-format should not split lines containing this comment, or they might not be recognized by `check-names.sh`
    - assembler code - not sure why, clang-format does not recognize `__asm` as assembler inline and tries formatting it as C code. 

Before the code could be formatted with clang-format, several issues have to be taken care of:
- Removal of parentheses from `return` and `sizeof` statements (Done in draft: https://github.com/ARMmbed/mbedtls/pull/4794/commits/e36f5b1c11841ce564c652dc574c252de6265c28). Clang format does not have configuration option which would do this for us
- Moving the trailing comments from commented macros to separate line (done in draft: https://github.com/ARMmbed/mbedtls/pull/4794/commits/16fec33e59be63925efe8ba6fa902ade86dfa652) Clang format is very confused by commented macros followed by another comment on the same line: `// #define MACRO_NAME 123 /** < some comment */`.
- Prevent formatting of `__asm` inline code (Done in draft: https://github.com/ARMmbed/mbedtls/pull/4794/commits/e8bd0f2ed0a3d61a78781e34a328383cf8d0e38a). Clang format does not recognize `__asm` and cannot correctly format it (code will not compile)
- Updating the `check-names.sh` (which is ment to be replaced by `check-names.py`: #1638). (The draft PR is disabling it completely: https://github.com/ARMmbed/mbedtls/pull/4794/commits/d30917c65add24d33983ae4234af02777e0889a5 but it was done as temporary work-around)

Once the code is prepared for formatting, clang-format can be launched on the whole code base: https://github.com/ARMmbed/mbedtls/pull/4794/commits/c0eabdc63657f784dee45167b010534cd3924cfa

Feel free to cherry-pick any commits from the draft, I would strongly recommend starting with https://github.com/ARMmbed/mbedtls/pull/4794/commits/200f58c07e5a1a9d16a97428e22d2bea912fffa5 and follow with any necessary changes to prepare the code for clang-formatting. It's possible that script code-fixing-scripts used in draft might not work anymore, when this task is started.

Before merging, a repo-wide code-freeze will be mandatory (to avoid dealing with the constantly occurring conflicts).

**Comment by gilles-peskine-arm** [comment]
Following https://github.com/Mbed-TLS/mbedtls/issues/6345#issuecomment-1317739765, we've decided to use uncrustify, not clang-format.
