### ISSUE TITLE
RNG not set when calling mbedtls_ssl_setup()

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#4911]
### Summary
In some Mbed TLS tests (at least some unit tests), `mbedtls_ssl_setup()` is called with a configuration where no RNG is defined. 

### System information

Mbed TLS version (number or commit id): development
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): full
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gcc 

### Expected behavior
If a check is added in `mbedtls_ssl_setup()` that an RNG has been configured, all CI tests pass.

### Actual behavior
If a check is added in `mbedtls_ssl_setup()` that an RNG has been configured, some CI tests fail.

### Steps to reproduce
Add a check that an RNG has been configured in 'ssl_conf_check' in ssl_tls.c like the check in `ssl_tls13_prepare_client_hello` in ssl_tls13_client.c in #4882 (not merged at time of writing). Build the library in full configuration and run the unit tests, some test suites fail.

### Follow up
Add in  'ssl_conf_check' in ssl_tls.c a check that an RNG has been configured and remove the check introduced in #4882 in ssl_tls13_client.c.

**Comment by gilles-peskine-arm** [comment]
I'm not sure I understand the impact of this bug. Does this mean that if an application tries to establish a TLS connection without having called `mbedtls_ssl_conf_rng`, the handshake will fail? Or that the code will crash due to attempting to call a null function pointer?

**Comment by ronald-cron-arm** [comment]
This issue is to fix the tests such that we can add the check that a random generator has been configured where we think it best fits (see https://github.com/ARMmbed/mbedtls/pull/4882#discussion_r696002535). Then is it a bug/problem that there is no check that an RNG has been configured when `mbedtls_ssl_setup()` is called, I have not investigated that.
