### ISSUE TITLE
Unify the definitions of ARRAY_LENGTH

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#4976]
We have a definition of `ARRAY_LENGTH` in the test suite, one in `library/psa_crypto.c`, one in `library/psa_crypto_slot_management.c`, one in `sha512.c`, and yet another one (without the name) coming up in https://github.com/ARMmbed/mbedtls/pull/4981. Unify them in a single place, e.g. `library/common.h`.

**Comment by yuhaoth** [comment]
@gilles-peskine-arm Do you mean the code in `ssl_debug_helps_generated.c` ? It has been moved to #4981

**Comment by Harry-Ramsey** [comment]
Fixed in pull request #7665.
