### ISSUE TITLE
Design how to access the fields of `mbedtls_ecp_keypair` and `mbedtls_ecdsa_context`

### ISSUE THREAD

**Issue by gabor-mezei-arm** [Mbed-TLS/mbedtls#5017]
This is a design task, as part of #4683 and #5441, to solve the private field access of `mbedtls_ecp_keypair` (and inclusively `mbedtls_ecdsa_context`) by `MBEDTLS_PRIVATE` macro in programs.

Possible option to solve the private access:
1. Make the private fields public
   - good for inner structures
   - locks the representation of the built-in typed data
2. Create getter and setter APIs for field access
    - locks the representation of the built-in typed data
    - requires more memory and more CPU time
3. Some mixture of the previous two option. Some fields are public, some are using getter and setter APIs 

The advantages and downsides of this problem explained in detail [here](https://github.com/ARMmbed/mbedtls/issues/4838#issuecomment-892918852).

This is intended to be the design task and the implementation should be done in #4838.

**Comment by paul-elliott-arm** [comment]
ECP Keypair export function added in https://github.com/ARMmbed/mbedtls/pull/5642 as per discussion in #4838
