### ISSUE TITLE
Driver dispatch code auto gen 

### ISSUE THREAD

**Issue by silabs-ArchanaM** [Mbed-TLS/mbedtls#5137]
### Suggested enhancement
It has been the Mbed TLS project's goal to have the driver dispatch layer ( interchangeably referred to as a driver wrapper layer ) auto generated. This issue is meant to track the same with work based on the design proposal submitted by @silabs-ArchanaM in #5067.

### Justification

Mbed TLS needs this because ( at the risk of sounding trite ) it's part of the mbed TLS project's goal to have the code generated as per drivers supported on a given device and configuration, which hugely reduces maintenance burden and improves readability.

**Comment by silabs-ArchanaM** [comment]
### Versioning Plan subject to approval

- [ ] @gilles-peskine-arm 
- [ ] @ronald-cron-arm 
- [ ] @stevew817 

### _Version 1.0_

1. Move the chunk of code that resides in _psa_crypto_driver_wrappers_.c to the base template file without any auto generation logic, herein the _psa_crypto_driver_wrappers_.c file will be rendered from the template.
2. Include base Python script to render the template, hardening version of Jinja and Python.
3. Documentation updates as required.
4. Migration guide rev 1.0 talking about how an end user who synchs to the new version needs to prepare and what's to come.

### _Version 1.1_

1. Bring in a driver list JSON, test driver JSONs.
2. Auto gen templating support for key management, transparent and opaque keys  ( import/export/copy )
3. Include some general JSON validation, and more specifically for the given entry points.
4. Supporting documentation and Migration guide updates.

### _Version 1.2_

1. Accelerated addition of templating for one shot and multipart functions for cipher .
2. Corresponding JSON updates for test drivers (I need to check how much of this is actually supported by the test driver today). 
3. Include some general JSON validation, and more specifically for the given entry points.
5. Config trickle based on the ALG supported (support to mute out SW fallbacks based on the ALGs supported).
6. Driver ID auto gen 
7. Test support (am undecided on what additional tests we want to add here).
8. Supporting documentation and Migration guide updates.
 
### _Version 1.3_

1. By now all templates should already be in place
2. Accelerated expansion to other one shot or multi part functions, with custom templating add-ons as required. 
3. Supporting documentation and Migration guide updates.

### _Version 2.0_

Other improvements, that save us code space, build time/ generation time / new templates.

**Comment by gilles-peskine-arm** [comment]
The overall plan looks good to me.

I strongly recommend splitting steps a little more. For example:

* 1.0a: `psa_crypto_driver_wrappers.c` generated from template
* 1.0b: `include/psa/crypto_driver_contexts_*.h` generated from template
* 1.1a: import and export for opaque drivers based on JSON support declarations
* 1.1b: import and export for transparent drivers based on JSON support declarations, mandatory fallback
* 1.1c: support non-fallback case, i.e. generate `MBEDTLS_PSA_ACCEL_xxx` definitions
* 1.2a: one-shot cipher
* 1.2b: multipart cipher
* 1.1c: key generation, copy
* …

Smaller steps are more likely to converge quickly. It's easier to review small PR than large ones.
