### ISSUE TITLE
Overhaul GitHub label system

### ISSUE THREAD

**Issue by davidhorstmann-arm** [Mbed-TLS/mbedtls#5221]
Our current GitHub label system is useful but sometimes unfriendly. There are currently 50 labels listed on GitHub, and not all of them are well-documented. Some have unclear and subtle semantics that may be inconsistent across the team. For example, recent discussions found that "Ready for merge" was used differently by different people, and its documentation was different again. This resulted in changing its name to "approved", to better match the meaning that it was being used to convey.

To make it easier for newcomers and external contributors to understand our label system, and to make it easier to comply with it effectively, we should:
- Reduce the number of labels if possible
- Simplify label semantics
- Document all labels properly

This issue includes the following tasks:
- [x] Have internal discussions of the label system, and how it can be simplified
- [x] Create a reduced set of labels with their semantics and usage
- [x] Have further discussions about this set of labels and semantics, and revise it
- [x] Document the final set of labels

**Comment by daverodgman** [comment]
Proposals here: https://confluence.arm.com/display/BSGSoftware/Proposal+for+label+changes
