### ISSUE TITLE
TLS 1.3 connection not aborted on unexpected change_cipher_spec record reception

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#5227]
### Summary

TLS 1.3 spec:
"If an implementation detects a change_cipher_spec record received before the first ClientHello message or after the peer’s Finished message, it MUST be treated as an unexpected record type (though stateless servers may not be able to distinguish these cases from allowed cases)."

When MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE is enabled, TLS 1.3 implementation (both client and server side) just ignore received change_cipher_spec records independently of the connection state.

### System information

Mbed TLS version (number or commit id): development
Operating system and version: N/A
Configuration (if not default, please attach `mbedtls_config.h`): default  + MBEDTLS_SSL_PROTO_TLS1_3_EXPERIMENTAL + MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE.
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): N/A 
Additional environment information: -

### Expected behavior
When a change_cipher_spec record is received at an unexpected time, terminate the connection with an "unexpected_message" alert.

### Actual behavior
When a change_cipher_spec record is received at an unexpected time, the record is just ignored.

### Additional information
Not easy to fix with the way the TLS 1.3 state machine is implemented, at least without MPS, not sure in MPS case. No time evaluation for that reason.

**Comment by yuhaoth** [comment]
It is part of #6803 . Close this one.
