### ISSUE TITLE
GOST 34.10 and 34.11 upstreaming

### ISSUE THREAD

**Issue by parport0** [Mbed-TLS/mbedtls#5248]
Hi,

Open Mobile Platform is a member of the [Trusted Firmware](https://www.trustedfirmware.org) and a contributor to the OP-TEE project.                                                                                                                   

We have implemented a pair of Russian cryptoalorithms within Mbed TLS:
* GOST 34.10, also known as ECRDSA, which is a Russian ECC algorithm;
* GOST 34.11, also known as Streebog/Stribog, which is a Russian hash function.

The implementation adheres to the latest standards (GOST 34.10-2018 and GOST 34.11-2018).
It also implements all seven standardized ECRDSA parameter sets.

The algorithms are defined by open standards and are widely used in Russia and CIS countries. Hence they are already implemented in the Linux kernel and libgcrypt. There is also a de-facto standard OpenSSL engine, [gost-engine](https://github.com/gost-engine/engine).

We have implemented the algorithms from scratch and are considering the opportunities to upstream this code; we are ready to become responsible for the code as maintainers. We are aware of the Mbed TLS Contributing guide.

Is the Mbed TLS community interested in reviewing and accepting the changeset?

For more information, please have a look:

* https://www.ietf.org/rfc/rfc7091.txt
* https://www.ietf.org/rfc/rfc7836.txt
* https://www.ietf.org/rfc/rfc4357.txt
* https://www.ietf.org/archive/id/draft-smyshlyaev-tls12-gost-suites-15.txt
* https://www.ietf.org/archive/id/draft-deremin-rfc4491-bis-06.txt

**Comment by daverodgman** [comment]
We are unlikely to implement this algorithm at this time.
