### ISSUE TITLE
Intermittent failure of "DTLS client reconnect from same port: reference" (retry)

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#5279]
This is the same bug as https://github.com/ARMmbed/mbedtls/issues/3377. It's essentially a random timeout in the OS which we resolved by retrying on failure. We're still seeing the test failure, but more rarely. [Here's](https://jenkins-mbedtls.oss.arm.com/job/mbed-tls-restricted-pr/job/PR-849-merge/5/execution/node/4064/log/?consoleFull) a case where it happened:
```
09:55:23 DTLS client reconnect from same port: reference ........................ RETRY(resend) FAIL
09:55:23   ! pattern 'resend' MUST NOT be present in the Client output
09:55:23   ! outputs saved to o-XXX-467.log
09:55:35 DTLS client reconnect from same port: reconnect ........................ RETRY(resend) PASS
```
The first test case failed after one retry. When I made the patch to retry on this specific failure, I had intended to allow two retries. I must have made an off-by-one error.

**Comment by mpg** [comment]
Another occurrence [here](https://ci.trustedfirmware.org/blue/rest/organizations/jenkins/pipelines/mbed-tls-pr-merge/branches/PR-5519-merge/runs/4/nodes/271/steps/940/log/?start=0):

```
[2022-03-16T15:16:22.213Z] DTLS client reconnect from same port: reference ........................ PASS
[2022-03-16T15:16:43.275Z] DTLS client reconnect from same port: reconnect ........................ RETRY(resend) FAIL
[2022-03-16T15:16:43.275Z]   ! pattern 'resend' MUST NOT be present in the Client output
[2022-03-16T15:16:43.275Z]   ! outputs saved to o-XXX-486.log
```

**Comment by superna9999** [comment]
It occurred on #5611 [log](https://ci.trustedfirmware.org/blue/organizations/jenkins/mbed-tls-pr-merge/detail/PR-5611-merge/6/pipeline)
