### ISSUE TITLE
MD: TLS 1.3 hashing & HMAC

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5326]
There are a number of places in the TLS 1.3 handshake where hashes/HMACs are computed. This should be done using `psa_hash_`/`psa_mac_` functions rather than `mbedtls_md_` or `mbedtls_shaNNN` functions. (Regardless of the value of `MBEDTLS_USE_PSA_CRYPTO`, which only affects 1.2, as 1.3 should always use PSA.)

- [ ] In `ssl_tls13_parse_certificate_verify()`: use `psa_hash_compute()` instead of `mbedtls_shaNNN()`.
- [x] In `mbedtls_ssl_tls13_derive_secret()`: use `psa_mac_compute()` instead of `mbedtls_md_hmac()`.
- [x] Provide an implementation of `mbedtls_ssl_get_handshake_transcript()` in the case where `MBEDTLS_USE_PSA_CRYPTO` is enabled.

Note: this task is only about computations as opposed to bookkeeping / algorithm management. This means replacing calls to `mbedtls_md_info_xxx()` and `mbedtls_md_get_xxx()`, and moving away from using `mbedtls_md_type_t` for storing information is _out of scope_ for this task; it will be the goal of a future task (see #5209). However, it some instances can be removed/replaced conveniently in the course of this task, of course this can be done, but that's not an explicit goal for now.

Note: while based on hashing/HMAC, HKDF is outside the scope of this task, see #5334

**Comment by silabs-PeterK** [comment]
Testing waits for https://github.com/ARMmbed/mbedtls/pull/5362.

**Comment by mpg** [comment]
I'm not sure I understand why testing depends on 1.3-only builds? We should be able to test in a build with both 1.3 and 1.2 enabled, or am I missing something?

**Comment by silabs-PeterK** [comment]
You are right, I can write a new test. But if I want to use ssl test suite, and test it in the bigger scope, I need to go through mbedtls_ssl_handshake_step in ssl_tls.c. From line 5265 there are callers that takes action in TLS1.3 or 1.2 only config. Or am I missing something?
![hs_transcript_callers](https://user-images.githubusercontent.com/97240204/152123074-6361a0ec-c6f0-4d2e-bebd-da4a49b41a3e.jpg)

**Comment by mpg** [comment]
Before looking at the details, here's my general reasoning: this task is about replacing existing code with a new implementation based on PSA; hopefully the code being replaced was already covered by tests, so the existing tests should cover the new implementation as well. (Though if you think existing tests should be expanded, then by all means say so and expand the testing!)

>  From line 5265 there are callers that takes action in TLS1.3 or 1.2 only config. 

Thanks for the specific reference. After taking a look, I'm thinking perhaps there is some confusion between runtime config and compile-time config: `mbedtls_ssl_conf_is_tls13_only()` checks if the runtime config (the `mbedtls_ssl_config` object that was configured with `mbedtls_ssl_conf_xxx_version()`) is 1.3 only. OTOH, #5362 is about supporting 1.3 only builds, that is with `MBEDTLS_SSL_PROTO_TLS1_3` defined  but `MBEDTLS_SSL_PROTO_TLS1_2` undefined in `mbedtls_config.h`.

In principle, the possibilities are the following:

- 1.3 only builds (`PROTO_TLS1_2` undefined): the runtime config will always be 1.3 only. (This type of build is currently broken and #5362 is fixing that.)
- 1.2 only builds (`PROTO_TLS1_3` undefined): the runtime config will always be 1.2 only.
- dual builds (both `PROTO_TLS1_x` defined): the runtime config can be either:
  - 1.3 only (call `mbedtls_ssl_conf_min_version()` to set the minimum to 1.3) 
  - 1.2 only (call `mbedtls_ssl_conf_max_version()` to set the maximum to 1.2)
  - both enabled: the version used in the handshake depends on what the peer supports - this is currently not implemented (as you noted, the dispatch in `handshake_step` currently relies on `ssl->config` being 1.2-only or 1.3-only), but will be in the future, see https://github.com/ARMmbed/mbedtls/issues/4823

So, there's three levels constraining the version that will eventually be used in a handshake: compile-time config, runtime config, and in-protocol negotiation.

Anyway, back to our problem, I think for testing you only require a 1.3-only runtime config (`ssl->config`), which can be achieved in a dual build. Feel free to point out if I'm missing something.

**Comment by mpg** [comment]
Oh, right, I forgot a very important point about the state of our TLS 1.3 implementation: [so far we only implement the client side](https://github.com/ARMmbed/mbedtls/blob/development/docs/architecture/tls13-support.md) - server side is [planned for the next quarter](https://github.com/orgs/ARMmbed/projects/18#column-17228366). So, indeed this prevents testing in `test_suite_ssl`, and I should have noticed as soon as you mentioned it, sorry. (Historically SSL/TLS testing was done in `tests/compat.sh` and `tests/ssl-opt.sh` only, but now indeed we prefer to have tests in `test_suite_ssl` too for new features - there's just a temporary exception for TLS 1.3 while we haven't implemented the server side.)

But TLS 1.3 is still tested (we wouldn't have released Mbed TLS 3.1 otherwise), just in another place: `tests/ssl-opt.sh` (some of the test cases are in `tests/opt-testcases/tls13-compat.sh`) - because in that script we can test our client against an OpenSSL or GnuTLS server.

By the way, we have a script, `tests/scripts/basic-build-test.sh` to measure test coverage with `lcov`. I usually run it inside a Docker image built from of [the Dockerfile that we use on the CI](https://github.com/ARMmbed/mbedtls-test/blob/master/resources/docker_files/ubuntu-16.04/Dockerfile. Of course it's also possible to run a more targeted campain, for example `make CFLAGS=--coverage LDFLAGS=--coverage && tests/ssl-opt.sh -f 'TLS 1.3' && make lcov`, and to run it on your machine if you have the required versions of GnuTLS and OpenSSL installed, with the right variables set in the environment (see the Dockerfile).

**Comment by mpg** [comment]
@silabs-PeterK I think the third item in the description has actually be done independently by @ronald-cron-arm in the meantime: #5532 - specifically [here](https://github.com/ARMmbed/mbedtls/pull/5532/files#diff-76b73bf2a8157ee95fdd3b688384812654c63878be4ecce6ee56402eb52b1f4fR7479). So, I suggest when you create a PR for this issue, that you only address the first two items, in order to avoid conflicts with #5532.

**Comment by mpg** [comment]
Hi @silabs-PeterK ! I just wanted to check if everything is OK regarding this task - I hope I've answered your questions above and I can't see any dependency blocking this, but please let me know if I missed something or if you have any further questions!
