### ISSUE TITLE
Add wrapper for assigning and unassigning own socket handle and use UINT_PTR instead of int for socket handle

### ISSUE THREAD

**Issue by TBOpen** [Mbed-TLS/mbedtls#535]
I'd like to request adding a wrapper functions for taking over an already open socket and giving it up so that any future changes won't break just assigning the fd mbedtls_net_context struct member. Something like xxx_assign_socket() and xxx_unassign_socket().

Also, Winsock2 defines a socket handle as UINT_PTR so the mbedtls_net_context structure should be updated to reflect that instead of using an int.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-869

**Comment by NWilson** [comment]
Just a comment, this issue doesn't affect me, but... Winsock sockets are
guaranteed to fit into an int, and do not be stored in a pointer-sized
variable. The value of a SOCKET is guaranteed to be less than 2^24.

Note that UINT_PTR is an integer type with the same width as a pointer (ie
uint_ptr_t) so no casts or other source-level changes are needed when
assigning to an int variable, which matches Microsoft's policy: Winsock is
supposed to be source-compatible with BSD sockets (although it isn't
entirely, sadly).

**Comment by tom-daubney-arm** [comment]
This is not something that we will be adding to the library, so closing this issue now.
