### ISSUE TITLE
mbedtls_ctr_drbg_seed failed -0x34

### ISSUE THREAD

**Issue by lanhao-lh** [Mbed-TLS/mbedtls#5352]
### Summary
I want to use mbedtlsk library to generate ECDSA  key pair to complete signature and signature verification in optee TA

### System information
optee TA
Mbed TLS version (number or commit id): 
Operating system and version: optee
Configuration (if not default, please attach `mbedtls_config.h`): 

mbedtls/config.h:

#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_PKCS1_V15

#define MBEDTLS_CIPHER_C
#define MBEDTLS_DES_C
#define MBEDTLS_AES_C

#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD5_C

#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_NO_PLATFORM_ENTROPY

#define MBEDTLS_BIGNUM_C
#define MBEDTLS_RSA_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_DP_BP256R1_ENABLED
#define MBEDTLS_ECP_DP_BP384R1_ENABLED
#define MBEDTLS_ECP_DP_BP512R1_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED

#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_PK_WRITE_C
#define MBEDTLS_OID_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CSR_PARSE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CHECK_KEY_USAGE
#define MBEDTLS_X509_USE_C
#define MBEDTLS_BASE64_C
#define MBEDTLS_CERTS_C
#define MBEDTLS_PEM_PARSE_C
#define MBEDTLS_PEM_WRITE_C

#include <mbedtls/check_config.h>

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

#define MBEDTLS_ENTROPY_HARDWARE_ALT

#if !defined(MBEDTLS_CONFIG_FILE)
#include <mbedtls/config.h>
#else
#include MBEDTLS_CONFIG_FILE
#endif
#include <mbedtls/entropy.h>
#include <mbedtls/ctr_drbg.h>
#include <mbedtls/ecdsa.h>
#include <mbedtls/sha256.h>
#include <mbedtls/pk.h>
#include <mbedtls/platform.h>
### Actual behavior

	mbedtls_entropy_context entropy;
	mbedtls_ctr_drbg_context ctr_drbg;
	const uint8_t *pers = "ecdsa_genkey";

	mbedtls_ctr_drbg_init(&ctr_drbg);
	mbedtls_entropy_init(&entropy);
	ret = mbedtls_ctr_drbg_seed(&ctr_drbg,mbedtls_entropy_func,&entropy,
							   (const unsigned char *)pers,
							   strlen(pers));
	if(0 != ret){
		IMSG("mbedtls_ctr_drbg_seed error! ret = %x\n",ret);
		goto go_exit;
	}
The error message of   mbedtls_ctr_drbg_seed（）is MBEDTLS_ERR_CTR_DRBG_ENTROPY_SOURCE_FAILED        -0x0034

**Comment by minosgalanakis** [comment]
Hi could you please provide some more context on the system information?

Specifically the Mbed TLS version you are building, the operating system which is doing the build and where the configuration file was aquired from or composed? It that part of the example's provided by the board?

I have noticed that this \#define is present, which could potentially compile out the entropy source.

~~~
#define MBEDTLS_NO_PLATFORM_ENTROPY
~~~

**Comment by lanhao-lh** [comment]
@minosgalanakis 
Thank you for your reply. I found that the macro definition was in the wrong position. When I put the definition in the right position, I still didn't get the correct result, so I had to write a my_ entropy_ dummy_ Source for temporary use And in mbedtls_ entropy_ add_ Source() calls it,

**Comment by minosgalanakis** [comment]
Would it be possible to provide the mbedtls version you are tryng to build, and what operating system are you using ? It would be usefull to have a way to reproduce that behaviour.

 To my understanding this error appears when mbedtls_entropy_func() call fails so having a look at why could help.

**Comment by TheBigFish** [comment]
In optee using the  `f_entropy` instead of `mbedtls_entropy_func` can avoid this, but I don't know why。
```c
int f_entropy(void *data, unsigned char *output, size_t size) {
    ((void) data);
    TEE_GenerateRandom(output, size);
    return 0;
}
```
then change the function pointer
```c
ret = mbedtls_ctr_drbg_seed(&ctr_drbg,f_entropy,&entropy,
						   (const unsigned char *)pers,
						   strlen(pers));
```

**Comment by minosgalanakis** [comment]
Closing because of inactiviy. 

Please re-open if you think there is a bug on the mbedtls side and have new info. 

For support requests, the [Mbed-TLS mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/) may be the best place to ask a question.
