### ISSUE TITLE
Rotation of LTS branches

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5364]
We recently had our last release of the 2.16 LTS branch, and our first release of the 2.28 LTS branch. There are a number of changes we need to make following that event.

**Creation of 2.28 LTS:**

- [x] All PRs that targeted `development_2.x` need to target `mbedtls-2.28` now (same with restricted).
- [x] `mbedtls-2.28` needs updating to include things that we merged in `development_2.x` in the meantime (same with restricted).
- [x] We probably want to remove `development_2.x` now that it's no longer being updated, but this needs to be discussed.
- [x] The CI's nightly job should use `mbedtls-2.28`, not `development_2.x`.

**Removal of 2.16 LTS:**

- [x] PRs targeting `mbedtls-2.16` should be either closed (if they're a backport of a PR on a live branch) or re-targeted (if they're not backports but original work that was started on 2.16 rather than development for some reason) (same with restricted)
- [x] The CI's nightly job no longer needs to test 2.16.

**Internal documentation:**

- [ ] Update branches in all pages that refer to them.
- [ ] Create checklists for creation / removal of an LTS branch?

**Comment by tom-cosgrove-arm** [comment]
@mpg @daverodgman Is there anything else left to be done on this issue, or can it be closed?

**Comment by mpg** [comment]
I think this issue can be closed. I doubt that all of our internal documentation has been updated, but even so, it's the sort of out-of-date condition that's very easy to correct mentally while reading, so not a big problem, and IMO not worth keeping this issue open. Let's close unless @daverodgman objects.

**Comment by daverodgman** [comment]
Agreed, let's close
