### ISSUE TITLE
Enhancement: Create ready-to-go development environment

### ISSUE THREAD

**Issue by yuhaoth** [Mbed-TLS/mbedtls#5427]
### Suggested enhancement

Below is my suggestion. That can reduce the maintain loading.
- [x] Publish docker images build by [mbedtls-test](https://github.com/ARMmbed/mbedtls-test/tree/master/resources/docker_files) 
   -  https://hub.docker.com/u/armmbed has some docker images. I think we should replace them .
- [x] Remove `tests/docker/bionic/Dockerfile`
- [ ] Update or remove `*-in-docker.sh` and `docker-env.sh`
 

### Justification

Mbed TLS test environment depends on different version of OpenSSL, GnuTLS and compiler. It is not easy for developer to reproduce and figure out CI fail. We'd better provide a script or image to reproduce CI fail locally.

[Docker files in mbedtls-test ](https://github.com/ARMmbed/mbedtls-test/tree/master/resources/docker_files) can be used as  environment. But to build them locally still need some time.   published images should be better choice.
And `tests/docker/bionic/Dockerfile` might confuse developer, it should be removed.

**Comment by gilles-peskine-arm** [comment]
> tests/docker/bionic/Dockerfile might confuse developer, it should be removed.

Done in https://github.com/Mbed-TLS/mbedtls/pull/8131

**Comment by gilles-peskine-arm** [comment]
> update `*-in-docker.sh` and `docker-env.sh`

Or remove. We don't use them within the team, and they haven't worked properly in years (since they're using an obsolete docker image).
