### ISSUE TITLE
Turn off re-generation of source files in releases

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#5432]
In Mbed TLS 3.0, we decided to stop committing generated files in Git if they don't depend on the configuration or the platform. However, the generation of these files require tools that not everybody have (perl, python, a host C compiler, and starting with 3.2 some python modules to generate PSA driver wrapper code). So we had this idea that we'd include generated files in releases, so that users would not need to rebuild them.

We've updated our release process to commit the generated files. However, the build scripts still have dependencies on the source files, so depending on the timestamps of extracted files, they might end up getting rebuilt. ([Example](https://github.com/ARMmbed/mbedtls/issues/5374))

The goal of this issue is to completely turn off the generation of these files in a release. For CMake, the feature is present but not activated: we should toggle the default value of `GEN_FILES`. For Make, we need to create a similar option.

When this is done, update the [release process](https://confluence.arm.com/display/BSGSoftware/Shift+1) (Arm private link) accordingly.

**Comment by minosgalanakis** [comment]
Is that still a valid requirement? #4514  has added the `DEV MODE` config option as seen [here](https://github.com/Mbed-TLS/mbedtls/commit/e90e405e15195414e50505c364183eba858763ff). 

Would that satisfy the ask's requirements? Or should we extend it?

 @gilles-peskine-arm , @mpg @davidhorstmann-arm what are your thoughts?

**Comment by gilles-peskine-arm** [comment]
The point of this issue is that this should be the default in a release.

Also, `DEV_MODE` is only a cmake thing, we don't have something similar for make.

**Comment by davidhorstmann-arm** [comment]
Just for clarity, `DEV_MODE` was later renamed to `GEN_FILES` which is mentioned in the description.
