### ISSUE TITLE
Accessor function for public key structure in mbedtls_ecp_keypair

### ISSUE THREAD

**Issue by stevew817** [Mbed-TLS/mbedtls#5441]
### Suggested enhancement
Either a direct accessor function to retrieve the public component of an `mbedtls_ecp_keypair`, or a function to write out the public key to a binary buffer. Similarly, a way to create an `mbedtls_ecp_keypair` structure containing only the public part of the key.

### Justification

Mbed TLS needs this because the public key component was made private.

**Comment by miklRus** [comment]
@stevew817, Just to clarify the issue, the public part of the key consists of three `ECP point` coordinates, do you suggest returning them separately or concatenate them to one common binary buffer?
