### ISSUE TITLE
Add build version output to programs/ssl ssl_client2/ssl_server2 

### ISSUE THREAD

**Issue by boaks** [Mbed-TLS/mbedtls#5443]
### Suggested enhancement

Please generally add the build version to the output of `ssl_client2` and `ssl_server2`.
Maybe additionally, if "build-version=1" is given, prints the build version only an stop.

### Justification

I would like to use these both binaries to ensure DTLS interoperability with [Eclipse/Californium](https://github.com/eclipse/californium/tree/master/californium-tests/californium-interoperability-tests) (see my pending [PR 1882](https://github.com/eclipse/californium/pull/1882) there). 
Using the build version makes it much easier to adapt such interoperability test according the usable functions of each build version. It also helps in case of reported issues to know the build version.

**Comment by paul-elliott-arm** [comment]
Hi!

I am unsure what the priority of this would be for the team, but in the meantime, I invite you to submit a PR implementing this, as this would be the quickest way of achieving this.

Also, I am sure you are aware but as yet, we do not support DTLS1.3, however this is on the roadmap for the near future.

**Comment by boaks** [comment]
> I am unsure what the priority of this would be for the team, but in the meantime, I invite you to submit a PR implementing this, as this would be the quickest way of achieving this.

Thanks for your answer! It's no problem, if it takes longer.

(For me it requires the permission for contribution of my employer, that would take even longer :-). Time I better spend in Eclipse/Californium).

> Also, I am sure you are aware but as yet, we do not support DTLS1.3, however this is on the roadmap for the near future.

For Eclipse/Californium it was frequently requested, but not that frequently. 
For now, I don't see, that the current committer team of Eclipse/Californium will be able to provide a implementation in a near future. So we will see, how long it takes ;-).

**Comment by paul-elliott-arm** [comment]
An extra thought I had - if you are compiling the executables (which I presume you are), then its possible you could work around by parsing version.h to find the given version, in the mean time.

**Comment by boaks** [comment]
> if you are compiling the executables

Sure, and I know the version. So, I personally don't need to read that version from the output.
In fact I'm using PR #5061 in order to test the compatibility according (upcoming) [RFC9146](https://www.rfc-editor.org/rfc/authors/rfc9146.html), with that, my version will be anyway a wrong one.
I also don't know, If someone else will really try to use the [Eclipse/Californium - Interoperability Tests](https://github.com/eclipse/californium/tree/master/californium-tests/californium-interoperability-tests) to ensure, that a special use-case/parameter-set or a future update is working. Therefore, it's not that urgent.

But in the end, I think, it will be also valuable for mbedTLS, if that version is printed.

(Sometimes I'm not sure, why adding four lines to a demo takes in some projects longer discussions than it would take to add them. At least for the project I work for, I also like, if someone contributes something. Bur for the very small stuff, it's also OK for me to add that by myself. )

**Comment by xkqian** [comment]
The related PRs #6580 and #6436 has been merged
