### ISSUE TITLE
Add a separate config option for TLS DN hints

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5541]
### Context

In TLS, the server can optionally request a certificate from the client. If it chooses to do so, the server can also send the client a list of names of CAs its trusts, to guide the client's selection of a certificate. In TLS 1.2, that's done using the `certificate_authorities` field of the CertificateRequest message, and in TLS 1.3, that's done using the `certificate_authorities` extension in the CertificateRequest message.

Currently, the list of DNs to send [is extracted from the list of trusted CAs](https://github.com/ARMmbed/mbedtls/blob/a1b506996d76fa8fe1483e2d5fb6a87efa3d990c/library/ssl_srv.c#L2854) configured with `mbedtls_ssl_conf_ca_chain()` or `mbedtls_ssl_set_hs_ca_chain()`, and an empty list is used if `mbedtls_ssl_conf_ca_cb()` is in use.

### Suggested enhancement

Add a separate configuration option, in the form of two function `mbedtls_ssl_conf_dn_hint()` (for basic use) and `mbedtls_ssl_set_hs_dn_hint()` (for use from the SNI / certificate selection callback) that allows to configured the DN hint separately from the list of trusted CAs. If none of these functions are called, then the current behaviour is retained; otherwise the configured DN hint takes precedence.

### Justification

Mbed TLS needs this because:

1. A need has been identified in #4383, some servers want to send a smaller list of DNs while using a larger list of CAs for verification (see quote below).
2. This will also be an improvement for users of `mbedtls_ssl_conf_ca_cb()`.

>  For example, lighttpd configured with client certificate verification might replace the certificate chains after the [CertificateRequest] has been sent, but before client certificate verification since I did not find a better way to send DN hints in the [CertificateRequest] to the client for client certificate selection, and then after [`MBEDTLS_SSL_HS_CERTIFICATE_REQUEST`] to configure a larger trust chain for (server-side) client certificate verification.

**Comment by mpg** [comment]
This looks fairly simple to implement, and I guess the only question is about the API: in what form should the new function take their input? What we want is a list a DER-encoded DNs, and there are several very different potential ways to go about this:

1. Take a `mbedtls_x509_crt *` and extract the DNs from the certificate. Pro: similar to the existing API `mbedtls_ssl_conf_ca_chain()`. Con: not convenient for people who don't have their trusted CAs handy as a `mbedtls_x509_crt` objects - which is one of the reasons why `mbedtls_ssl_conf_ca_cb()` was created in the first place.
2. Take an array of `mbedtls_x509_buf *` pointers - in each entry, `tag` is ignored, and only `len` and `p` are used; `p` should point to the DER encoding of the DN. Pro: more flexible, and can be easily extracted from a list of CAs. Con: may require more work for some users.
3. Take a single buffer whose content is exactly the contents of `DistinguishedName authorities<3..2^16-1>` that is used by both TLS 1.2 and TLS 1.3. Pro: makes the library code super simple/small. Con: users are unlikely to have the input just in that format, so will need to prepare it. Con: 1.2 and 1.3 happen to use the same format, what if 1.4 does not?

**Comment by mpg** [comment]
@gstrauss As the person who requested this, do you have an opinion on the API questions above?

So far I'm inclined toward (2) which I think requires a reasonable amount of work for most classes of users.

I think implementing the feature is easy enough once we've agreed on what the API should look like.

**Comment by paul-elliott-arm** [comment]
I am definitely inclined toward (2), however a helper function to convert from `mbedtls_x509_crt *` to array of `mbedtls_x509_crt * `would probably remove some extra work for those using `mbedtls_x509_crt *`.

**Comment by gstrauss** [comment]
My initial impression is a combination of 1 and 2.  For 1, a convenience function might take `mbedtls_x509_crt *` and return the input to 2, and then 2 could be the interface to set the DN hints, as you noted that is necessary for people who do not have trusted CAs handy as `mbedtls_x509_crt` objects.  I have not yet had a chance to try mocking things up.

**Comment by gstrauss** [comment]
Hmm.  Another option is to create a new interface to extend and (eventually) replace `mbedtls_ssl_set_hs_ca_chain()` and `mbedtls_ssl_set_hs_authmode()` to handle client certificate verification, e.g. `void mbedtls_ssl_set_hs_client_verify( mbedtls_ssl_context *ssl, int authmode, mbedtls_x509_crt *ca_chain, mbedtls_x509_crl *ca_crl, mbedtls_x509_crt *dn_hint)`

**Comment by gstrauss** [comment]
I pushed #5620 for discussion.  It implements @mpg options 1, 2, and (internally) 3.
