### ISSUE TITLE
Add missing accessor for mbedtls_x509_crt.ext_types for uacme

### ISSUE THREAD

**Issue by ndilieto** [Mbed-TLS/mbedtls#5585]
### Suggested enhancement

Add missing accessor functions to the following

- [x] 1) mbedtls_ecp_keypair.MBEDTLS_PRIVATE(grp)
- [x] 2) mbedtls_ecp_keypair.MBEDTLS_PRIVATE(Q)
- [ ] 3) mbedtls_x509_crt.MBEDTLS_PRIVATE(ext_types)
- [x] 4) mbedtls_pem_context.MBEDTLS_PRIVATE(buf)
- [x] 5) mbedtls_pem_context.MBEDTLS_PRIVATE(buflen)
- [x] 6) SSL.MBEDTLS_PRIVATE(state)

Edit: For 1) and 2) a new mbedtls_ec_export function could be introduced, similar to mbedtls_rsa_export which already exists.

### Justification

Commit https://github.com/ndilieto/uacme/commit/64d1b3c260c782c037246ef63e16492f20c6fd9d adds support for mbedTLS v3.0 to uacme, but accessor functions to the above are missing and therefore I had to resort to MBEDTLS_PRIVATE.

**Comment by daverodgman** [comment]
The first two (ECP keypair) are covered by #4838. 4 & 5 (PEM context) are covered by #5414 (fix merged in #5504). 6 (SSL handshake state) is covered by #4383. So I think the only new item is relating to mbedtls_x509_crt.ext_types (I'll rename this issue for clarity).
