### ISSUE TITLE
Update "use PSA" documentation

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5621]
### Suggested enhancement

This documents the effects of the config option `MBEDTLS_USE_PSA_CRYPTO` in detail. It is not updated in each PR that extends `USE_PSA_CRYPTO` because that would be an endless source of conflicts. However, it should be updated before releasing.

Note: if we have achieved most of the "part 2" EPIC before the next release, we'll probably want to switch the description from "does A, B and C" to "does everything except for X, Y and Z".

Edit: all documents in `docs/architecture/psa-migration` need to be reviewed to make sure they're up to date.

### Justification

Mbed TLS needs this because out-of-date documentation is bad.

**Comment by gilles-peskine-arm** [comment]
“Custom key derivations for mixed-PSK handshake” — implemented in https://github.com/Mbed-TLS/mbedtls/pull/5726. The API spec has been extended, to be published in the next release after 1.1.0.
