### ISSUE TITLE
RSA sign 3a: X.509 integration testing

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5627]
Test use of `MBEDTLS_PK_OPAQUE` RSA keys in the X.509 library. A large part of X.509 (parsing and verification) is only concerned with public keys; since opaque keys are private, there are only a few places to test.

- [x] Test generating CSRs using an opaque RSA key. There's already a test function `x509_csr_check_opaque` and a test case using that function with an ECDSA key; adding a test case with the same function and an RSA key should work.
- [x] Test generating certificates using an opaque key (RSA and ECDSA). There's no function doing that yet. The existing function `x509_crt_check()` can probably be adapted easily: it already has an option to test with `MBEDTLS_PK_RSA_ALT`, and we can test with `MBEDTLS_PK_OPAQUE` in a very similar way (perhaps even re-using the same parameter and renaming it to `key_wrap` - 0 for none, 1 for `PK_RSA_ALT`, 2 for `PK_OPAQUE`).

Depends on: #5626 as `mbedtls_pk_wrap_opaque()` will be used in the tests.

**Comment by superna9999** [comment]
@mpg I'm trying to test generation of x509 ECDSA certificates.

CRT generation works with a slighly modified `x509_crt_check()` with RSA, but with the `server5` subject key & `ca2` issuer key, I get a slighly different CRT than the already present `data_files/server5.crt` files.

The generated CRT has:
```
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                50:61:A5:8F:D4:07:D9:D7:82:01:0C:E5:65:7F:8C:63:46:A7:13:BE
            X509v3 Authority Key Identifier: 
                keyid:9D:6D:20:24:49:01:3F:2B:CB:78:B5:19:BC:7E:24:C9:DB:FB:36:7C
```

The check CRT has:
```
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Subject Key Identifier: 
                50:61:A5:8F:D4:07:D9:D7:82:01:0C:E5:65:7F:8C:63:46:A7:13:BE
            X509v3 Authority Key Identifier: 
                keyid:9D:6D:20:24:49:01:3F:2B:CB:78:B5:19:BC:7E:24:C9:DB:FB:36:7C
                DirName:/C=NL/O=PolarSSL/CN=Polarssl Test EC CA
                serial:C1:43:E2:7E:62:43:CC:E8
```

While looking at the x509 library, I didn't find where `DirName` & `serial` for `X509v3 Authority Key Identifier` could be written.

**Comment by superna9999** [comment]
With regenerated `tests/data_files/server5.req.sha1` and `tests/data_files/server5-sha1.crt` from Makefile with:
```diff
+server5.req.sha1: server5.key
+       $(MBEDTLS_CERT_REQ) output_file=$@ filename=$< subject_name="C=NL,O=PolarSSL,CN=PolarSSL Server 1" md=SHA1
+all_final += server5.req.sha1
+
+
+server5-sha1.crt: server5.req.sha1
+       $(MBEDTLS_CERT_WRITE) request_file=server5.req.sha1 serial=1 issuer_crt=$(test_ca_crt_file_ec) issuer_key=$(test_ca_key_file_ec) issuer_pwd=$(test_ca_pwd_ec) not_before=20190210144406 not_after=20290210144406 md=SHA1 version=3 output_file=$@
+all_final += server5-sha1.crt
```

I can successfully pass x509write crt check with EC key, but obviously it makes all x509parse fails on these 2 files.

**Comment by superna9999** [comment]
With EC Opaque cert generation, I hit the same issue as #5518 because of the uncontrollable rng. Is there a way to check the CRT like done in `x509_crt_verifycsr()` when using `x509_csr_check_opaque()` ?

**Comment by mpg** [comment]
Aw, this is annoying, we may need a new strategy for testing cert generation (though now I'm surprised it worked even with non-opaque keys). I'll think about it and come back to you, and of course feel free to suggest a strategy as well if you come up with something.

**Comment by superna9999** [comment]
I implemented the same strategy as #5518 by checking the CRT when using opaque EC, but crts would still need to be re-generated for non-opaque test: https://github.com/superna9999/mbedtls/commit/e1431730f8c61a1a5855974b071c009226cac7cc

**Comment by mpg** [comment]
Ok, I haven't had the opportunity to look at the details yet, but this sounds reasonable. I'll check in more detail when reviewing the PR, then.

**Comment by gilles-peskine-arm** [comment]
FYI it is possible to arrange a deterministic RNG for PSA crypto functions when `MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG` is enabled. But that's very fragile since the RNG can be used in basically unpredictable ways, e.g. for blinding, so I would consider this a last resort.
