### ISSUE TITLE
abnormal behavior when server receive too big plaintext from client

### ISSUE THREAD

**Issue by ManuZhu** [Mbed-TLS/mbedtls#5643]
### Summary
Abnormal behavior when server receive too big plaintext from client.

### System information

Mbed TLS version: 3.1.0
Operating system and version: macOS 12.0.1
Configuration: default

### Expected behavior
When the actual (decrypted) record content length against configured maximum(default is 2^14), the server should close the connection and sends a fatal alert which is decompression_failure or record_overflow to the client.

### Actual behavior
The server normally receive and exchange messages with client.

### Steps to reproduce
Just run the suite "too big plaintext" in "./scripts/test-aesccm.py" of [tlsfuzzer](https://github.com/tlsfuzzer/tlsfuzzer) and you'll see the abnormal behavior of the example server program "ssl_server2.c".

### Additional information
The bug is produced just because In the function ssl_prepare_record_content of the "library/ssl_msg.c", it uses the variable "ssl->in_msglen" to check whether the content length is against 2^14 bytes.
`
    if( ssl->in_msglen > MBEDTLS_SSL_IN_CONTENT_LEN )
`
But actually at that time, the variable "ssl->in_msglen" hasn't been valued until the function returns back to the function ssl_get_next_record of "library/ssl_msg.c" at line 4405.
`ssl->in_msglen = rec.data_len;`
So the correct implementation should use the variable "rec->data_len" to check the actual (decrypted) content length rather than "ssl->in_msglen".

**Comment by paul-elliott-arm** [comment]
Fixed in commit 668b31f210356ef26b1ca26bced775b3d36f63f9
