### ISSUE TITLE
Mixed PSK 1: Extend PSK-to-MS algorithm in PSA

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5662]
**Context:** TLS 1.2 has a variety of key exchanges that are based on a pre-shared key (PSK) - that is, both parties already hold a shared secret. However this shared secret is not used directly to encrypt/authenticate messages, but instead concatenated to other things to form the pre-master secret (PMS), used to derived a master secret (MS) from which session encryption/authentication keys are finally derived.

Since the PSK is a long-term secret, it is desirable for it to be held as a non-exportable PSA key, meaning the TLS code would have no access to its content, in particular it cannot manipulate it to form the PMS and then derive the MS, so this has to happen on the PSA side when an opaque PSK is used. For this purpose, an ad hoc key derivation function (KDF) algorithm was added to the PSA Crypto API, going directly from the PSK to the MS. On the TLS side, a configuration function `mbedtls_ssl_conf_psk_opaque()` was added so that users can provision a PSA-held PSK.

However, currently only the "pure" PSK key exchange is supported; this leaves out the RSA-PSK, DHE-PSK, ECDHE-PSK key exchanges, which all use another secret (the output of RSA key wrapping or of (EC)DHE key agreement) in addition to the PSK to form the PMS and derive the MS. Currently those "mixed PSK" key exchanges can only be used with non-opaque PSKs. This task is the first in a series aimed a supporting the "mixed PSK" key exchanges with opaque PSKs.

References:
- [RFC 4279](https://datatracker.ietf.org/doc/html/rfc4279) for the definition of PSK, RSA-PSK and DHE-PSK
- [RFC 5489](https://datatracker.ietf.org/doc/html/rfc5489) for the definition of ECDHE-PSK
- [`PSA_ALG_TLS12_PSK_TO_MS` documentation](https://armmbed.github.io/mbed-crypto/html/api/ops/kdf.html#c.PSA_ALG_TLS12_PSK_TO_MS)
- [`mbedtls_ssl_conf_psk_opaque()` documentation](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L3209)

**This task** is to extend the existing `PSA_ALG_TLS12_PSK_TO_MS()` algorithm so that it accepts an _optional_ input (presumably of type `PSA_KEY_DERIVATION_INPUT_SALT`) holding the `other_secret` part of the PMS. For "pure PSK", this input would be omitted and the implementation would use all-zeroes as it currently does; for "mixed PSK" key exchanges, the (EC)DHE shared secret / RSA decryption result could be passed. The documentation should be clear about both use cases.

- [x] Extend and update the existing documentation in `psa/crypto_values.h`
- [x] Validate that API extension with @gilles-peskine-arm and other PSA Crypto maintainers
- [x] Implement that extension
- [x] Add known-answer tests (I don't think there are any official/standard test vectors, so we'll probably have to make our own, either from a capture of a successful handshake with another implementation, or from an independent python implementation, or any other suitable way tbd).

Follow-ups: #5663, #5664, #5665

**Comment by mprse** [comment]
Just to confirm if I'm going in the right direction.

`PSK` - Pre-Shared Key (long term secret)
`PMS` - Pre Master Secret (created by concatenation: output_len(2) + (output of: RSA key wrapping or (EC)DHE key agreement) + psk_len(2) + PSK)
`MS`  - Master Secret (derived from PMS, from MS final session keys are derived)

1. PSA Mixed mode with no-opaque PSK (ECDHE) is handled by https://github.com/ARMmbed/mbedtls/issues/5318 when PSK is set using `mbedtls_ssl_conf_psk()` and `ssl_conf_has_static_raw_psk( ssl->conf )` returns `true`. PMS is form using TLS code.

2. PSA Mixed mode with opaque PSK is the goal of this task. PSA PSK key is set using `mbedtls_ssl_conf_psk_opaque()` => TLS code does not have access to its content, so it cannot manipulate it to form the PMS. This has to be done on PSA side.

PSA side currently supports only "pure" PSK. In PMS the space for output of: RSA key wrapping or (EC)DHE key agreement is [filled with zeros](https://github.com/ARMmbed/mbedtls/blob/39f2f73e69269bdf716e6b82fd42a2b79bd28141/library/psa_crypto.c#L5277-L5293). And as far as I understand we need to provide API to fill it with the output of: RSA key wrapping or (EC)DHE key agreement.

To do that we need to add extra step to `PSA_ALG_TLS12_PSK_TO_MS` algorithm to be able to put into PMS another secret (the output of RSA key wrapping or of (EC)DHE key agreement):

- `PSA_KEY_DERIVATION_INPUT_SEED` is the seed.
- `PSA_KEY_DERIVATION_INPUT_SECRET` is the PSK. The PSK must not be larger than PSA_TLS12_PSK_TO_MS_PSK_MAX_SIZE.
- `PSA_KEY_DERIVATION_INPUT_LABEL` is the label.
- `PSA_KEY_DERIVATION_INPUT_SALT` **the output of RSA key wrapping or of (EC)DHE key agreement**.

**Comment by mpg** [comment]
That's a 100% correct!

**Comment by mprse** [comment]
Potential solution:
 - Add fields to store the secondary key to `psa_tls12_prf_key_derivation_t` [structure](https://github.com/ARMmbed/mbedtls/blob/571f1187b647b75bc8fb9aa8b02681cfa8c5a201/include/psa/crypto_struct.h#L213-L239):
  `uint8_t *MBEDTLS_PRIVATE(salt);`
  `size_t MBEDTLS_PRIVATE(salt_length);`
- Add optional step for the key derivation function (KDF) algorithm:
`PSA_TLS12_PRF_STATE_SALT_SET`
- New derivation flow: `PSA_TLS12_PRF_STATE_INIT -> PSA_KEY_DERIVATION_INPUT_SEED -> (PSA_KEY_DERIVATION_INPUT_SALT) -> PSA_KEY_DERIVATION_INPUT_SECRET -> PSA_KEY_DERIVATION_INPUT_LABEL -> PSA_TLS12_PRF_STATE_OUTPUT` where `PSA_KEY_DERIVATION_INPUT_SALT` is optional step to set secondary key (salt).
- Add implementation of `psa_tls12_prf_set_salt()` to set the secondary key (salt).
- Modify `psa_tls12_prf_psk_to_ms_set_key()` to write secondary key (salt) to `PMS` if current state is `PSA_TLS12_PRF_STATE_SALT_SET`, otherwise use current implementation.
- Modify `psa_tls12_prf_set_key()` to allow also `PSA_TLS12_PRF_STATE_SALT_SET` state.

cc @gilles-peskine-arm @mpg

**Comment by mpg** [comment]
> question: Do we need to adapt size of the [pms ](https://github.com/ARMmbed/mbedtls/blob/abed05f33550faa87883f04ebccfafa9e1c66889/library/psa_crypto.c#L5271) buffer ? If secondary key length can exceed `PSA_TLS12_PSK_TO_MS_PSK_MAX_SIZE` then I think we need to use dynamic allocation or use different macro for max size of the secondary key.

Good point. Let me try to summarize sizes:
- Pure PSK: `other_secret` has the same size as the PSK itself, so bounded by `PSA_TLS12_PSK_TO_MS_PSK_MAX_SIZE`
- RSA-PSK: `other_secret` is always 48 bytes always, so in practice that's less than `PSA_TLS12_PSK_TO_MS_PSK_MAX_SIZE` (which defaults to 128 but the doc says it must no be lower than 64)
- ECDHE-PSK: `other_secret` is the size of the chosen elliptic curve, so in practice at most 66 bytes (for P-521).
- DHE-PSK: `other_secret` is the size of the chosen DH params - these days a minimum of 2048 bits (256 bytes) is recommended, and 3072 bits (384 bytes) is also popular; the maximum that Mbed TLS supports is `MBEDTLS_MPI_MAX_SIZE`, which defaults to 1024 bytes.

For reference, we're using a static buffer for the PMS in TLS, see [`MBEDTLS_PREMASTER_SIZE`](https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/ssl.h#L573). But the situation in PSA is different as PSA constants shouldn't depend on `MBEDTLS_KEY_EXCHANGE_xxx_ENABLED` macros - TLS depends on PSA, not the other way round (and in the future we plan on having more separation between the PSA Crypto implementation and the rest of the library).

This might need further thought (perhaps Gilles will want to weight in when he comes back from holiday next week), but right now I'm inclined to say that static, with a configurable size defaulting to 384, should be good enough (at least for starters).

Regarding the rest of your plan, I'll have a closer look tomorrow!

**Comment by mpg** [comment]
> Regarding the rest of your plan, I'll have a closer look tomorrow!

Oh well, I see you opened a PR in the meantime, so I guess that means the plan worked :) I'll have a look at the PR soon, then.

**Comment by mprse** [comment]
> Oh well, I see you opened a PR in the meantime, so I guess that means the plan worked :) I'll have a look at the PR soon, then.

Yes, that is why I started looking into follow-ups. Got it working and tested, but the design needs to be approved. Not sure if the way I generated test vectors is acceptable.
