### ISSUE TITLE
Mixed PSK 2a: support ECDHE-PSK

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5663]
This task is to add support for ECDHE-PSK using PSA-held (aka opaque) keys, that is, keys provisioned with `mbedtls_ssl_conf_psk_opaque()` or ` mbedtls_ssl_set_hs_psk_opaque()` (used in the PSK callback).

The task is done when there are passing tests in `ssl-opt.sh` using ECDHE-PSK with `psk_opaque=1` with sufficient coverage (client and/or server, static conf and/or callback, see existing tests for pure PSK).

Depends on: #5662 (also provides context and references) and #5318 (for the PSA-based non-opaque ECDHE-PSK code path).
Related: #5664, #5665

**Comment by mprse** [comment]
Started working on this one, but it seems that it would be good to have first https://github.com/Mbed-TLS/mbedtls/issues/5318 closed and then add path for opaque ECDHE-PSK key exchange.

**Comment by mpg** [comment]
Agreed, I should have documented that as a dependency as well, thanks for noticing! I _think_ the RSA-PSK and DHE-PSK tasks should be free, though, if you don't mind starting before #5685 has been approved - otherwise something from the "part 3" column I guess.
