### ISSUE TITLE
Mixed PSK 2b: support DHE-PSK

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5664]
This task is to add support for DHE-PSK using PSA-held (aka opaque) keys, that is, keys provisioned with `mbedtls_ssl_conf_psk_opaque()` or ` mbedtls_ssl_set_hs_psk_opaque()` (used in the PSK callback).

The task is done when there are passing tests in `ssl-opt.sh` using DHE-PSK with `psk_opaque=1` with sufficient coverage (client and/or server, static conf and/or callback, see existing tests for pure PSK).

Depends on: #5662 (also provides context and references).
Related: #5663, #5665

**Comment by mprse** [comment]
Got a question regarding this one. 
I'm reworking this [PR](https://github.com/Mbed-TLS/mbedtls/pull/5704) and I want to handle RSA/ECDHE/DHE-PSK key exchange in one PR. 
I got it working for RSA and ECDH, but got problem with DHE-SPK.

The PSA Mixed-PSK master key derivation is handled here (in this version only RSA-PSK is handled):
https://github.com/Mbed-TLS/mbedtls/blob/36dc5b3707a3a57ee5414f1f210b863c1a14f4c2/library/ssl_tls.c#L5150-L5199

The other secret needed for master key derivation is kept in `premaster`:
- RSA
https://github.com/Mbed-TLS/mbedtls/blob/09dc05b880b1b32972bf1052b558dbc0aaca92db/library/ssl_tls12_client.c#L3207-L3208
- ECDHE
https://github.com/Mbed-TLS/mbedtls/blob/09dc05b880b1b32972bf1052b558dbc0aaca92db/library/ssl_tls12_client.c#L3111-L3117

But for DHE seems that premaster is not filled in this part of code:
https://github.com/Mbed-TLS/mbedtls/blob/development/library/ssl_tls12_client.c#L3238-L3241

I focused here on client side only.

**Comment by gilles-peskine-arm** [comment]
The PSA crypto layer doesn't support DH yet. USE_PSA_CRYPTO code can't support DHE until that's done.

I haven't followed when we've scheduled to do that — probably later, because non-EC DH isn't used much anymore.

**Comment by mpg** [comment]
Yes, sorry, I should have mentioned that bit of context in the task's description. For DHE-PSK, the DHE part will still be done by the legacy API, and only the derivation "DHE output + PSK -> MS" will be done by PSA. (More generally, for all the xxx-PSK tasks, no change is intended in the xxx part: either it has already been done in previous EPICs, or to be done later.)

The DHE part of the DHE-PSK key exchange goes as follows client-side:

- In `ssl_parse_server_key_exchange()` we parse the server parameters and remember them.
- In `ssl_write_client_key_exchange()` we pick our ephemeral private key and send the public part with `mbedtls_dhm_make_public()` and then later call `mbedtls_ssl_psk_derive_premaster()`
- In `mbedtls_ssl_psk_derive_premaster()` (in `ssl_tls.c`!) we compute the shared secret with `mbedtls_dhm_calc_secret()` and write it to the PMS buffer.

The thing is, `mbedtls_ssl_psk_derive_premaster()` won't work unmodified with an opaque PSK key, so we probably need to arrange for it to skip the PSK part when we have an opaque key, and just leave the DHM shared secret in `handshake->premaster` when we'll pick it up later to pass to the PSA KDF.
