### ISSUE TITLE
Cipher cleanup: abstract TLS mode

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5668]
TLS 1.2 has 3 types of [record protection](https://datatracker.ietf.org/doc/html/rfc5246#section-6.2.3):

- Null or Standard Stream Cipher
- CBC Block Cipher
- AEAD Ciphers

Later, [RFC 7366](https://datatracker.ietf.org/doc/html/rfc7366) added a variant of the "CBC Block Cipher" known as encrypt-then-MAC (EtM), for a total of 4 types of record protection.

Currently we don't have a clean way to represent that. We used to use `MBEDTLS_MODE_xxx` constants from the Cipher module, but they were never a proper match. No we also have a PSA version, which is closer but not an exact match either (things like EtM and NULL cipher are TLS-specific). This results in conditions like [this](https://github.com/ARMmbed/mbedtls/blob/development/library/ssl_msg.c#L656) which are hard to read (and confuse non-preprocessor-aware editor into think parentheses are not balanced).

This could be made cleaner by creating a new enum (say, in `ssl_misc.h`) with values representing "stream", "cbc", "cbc-etm", and "aead", and helper functions like `mbedtls_get_mode_from_tranform()` (and, if necessary, `mbedtls_get_mode_from_ciphersuite()`).

This task is to create that enum and any helper function that's useful, and using them to simplify all the places in the code that currently use `MBEDTLS_MODE_xxx` / `cipher_get_mode()`.

**Comment by mpg** [comment]
We should use this to replace calls to `mbedtls_cipher_info_from_type()` + `mbedtls_cipher_get_type()` whenever it makes sense. I haven't looked at all the places, but `ssl_tls12_populate_transform()` is definitely a candidate, and I had in mind `ssl_write_encrypt_then_mac_ext()` (in `ssl_srv.c` - the client-side version is different) too, though I suspect those two would need a variant taking a ciphersuite as input rather than the transform, which hasn't been populated yet, and probably the EtM state as a separate argument too.

Regarding `mbedtls_md_info_from_type()` I think the replacement would be a different function since it's MD not Cipher, but as a matter or principle yes, we want to reduce and ultimately remove our dependency on `mbedtls_cipher_xxx` and `mbedtls_md_xxx` functions. If I didn't miss anything, we no longer* depend on them for any crypto operations, but we still depend on them for "information management". While removing those uses is not the most immediate goal right now, it is a medium-term goal, so whenever you notice opportunities to make progress on that front, feel free to do so!

*I mean in the near future when #5326 is done.

**Comment by superna9999** [comment]
@mpg thanks, I'll study how it can be done.

For `mbedtls_md_info_from_type` removal, it has been pushed to https://github.com/Mbed-TLS/mbedtls/pull/5647
