### ISSUE TITLE
Requires a read function that can distinguish between different format parameters

### ISSUE THREAD

**Issue by mygit0327** [Mbed-TLS/mbedtls#5687]
### Suggested enhancement
There is "format" in write function to indicate whether it has been compressed；
But no this parameter in read function.

int mbedtls_ecp_point_write_binary( const mbedtls_ecp_group *grp,
                                    const mbedtls_ecp_point *P,
                                    int format, size_t *olen,
                                    unsigned char *buf, size_t buflen )
int mbedtls_ecp_point_read_binary( const mbedtls_ecp_group *grp,
                                   mbedtls_ecp_point *pt,
                                   const unsigned char *buf, size_t ilen )

### Justification
The two functions do not seem to correspond.

Mbed TLS needs this because 
The data in buf needs to be reused, both compressed and uncompressed.

**Comment by paul-elliott-arm** [comment]
Hi,

There is no need to have to pass the compressed state into the read functions, as it is incoded in the input stream - see section 2.3.4 in https://www.secg.org/sec1-v2.pdf.

We have also never supported reading a compressed ECP point in this case, and we are unlikely to add support for it, as it is no longer wisely used.

Regards,
Paul.

**Comment by paul-elliott-arm** [comment]
Do you have an actual use case that requires reading of compressed points, or is this a more general request?
