### ISSUE TITLE
C90 forbids mixed declarations and code

### ISSUE THREAD

**Issue by Kurruk007** [Mbed-TLS/mbedtls#5702]
### Summary

Compiling the `2.28` release with forced option for `C99` is throwing an error about mixed declarations.

### System information

Mbed TLS version (number or commit id): `2.28` (_from `2.16.10`_)
Operating system and version: Ubuntu with gcc `6.5.0 20181026` (_but mainly arm toolchain on gcc `4.7.3`_) 
Configuration (if not default, please attach `mbedtls_config.h`): _more limited, but should(tm) also work on default_
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): `-Wall -Wnonnull -Werror -std=c99` (_are probably most relevant_)
Additional environment information: 

### Expected behavior

Compilation succeeds without throwing an error and `C99` is being respected.

### Actual behavior

Compilation fails due to lose approach towards standardisation.

### Steps to reproduce

Compile forcing `C99` standard.

### Additional information

Errors (8fd95c67?):
```
src/lib/mbedtls/bignum.c: In function 'mbedtls_mpi_mul_int':
src/lib/mbedtls/bignum.c:1515:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
src/lib/mbedtls/bignum.c:1527:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
```

With the debug enabled there's one more (2ddec430?):
```
src/lib/mbedtls/ssl_msg.c: In function 'mbedtls_ssl_decrypt_buf':
src/lib/mbedtls/ssl_msg.c:1491:13: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
```

Seeing as my configuration is limited, it's possible for other places to have similar problems.

**Comment by gilles-peskine-arm** [comment]
Which compiler are you using exactly? You mention two gcc versions. You list options as including `-std=c99`, but then the error message mentions “ISO C90”, so it looks like this message comes from trying to build as C90, not C99.

Mbed TLS dropped compatibility with C90 in the 2.19.0 release. All supported versions of Mbed TLS require a C99 compiler. It doesn't have to support all the new C99 features, but it needs at least declarations after statements.
