### ISSUE TITLE
RSA-PSS sign 2: TLS 1.3 integration testing

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5712]
Test use of RSA opaque keys for client authentication with TLS 1.3.

Similar to #5628 except:
- only client-side (we haven't implemented TLS 1.3 server-side [yet](https://github.com/orgs/Mbed-TLS/projects/1#column-17950131))
- only TLS 1.3, since 1.2 always uses PKCS#1v1.5 for handshake signatures, and 1.3 always PSS.

Depends on: #5711

**Comment by superna9999** [comment]
@mpg what `sig_alg` is required to be tested here ?
- MBEDTLS_TLS1_3_SIG_RSA_PSS_RSAE_SHA256
- MBEDTLS_TLS1_3_SIG_RSA_PSS_RSAE_SHA384
- MBEDTLS_TLS1_3_SIG_RSA_PSS_RSAE_SHA512

But I can't find any test for those in ssl-opt.sh, can you point me to something ? As I look, ssl-opt. uses EC certs & keys with OpenSSL server for 1.3

**Comment by mpg** [comment]
Hmm, I'm not very familiar with 1.3 testing yet, so I don't know offhand. Did you notice that a lot of the test cases for 1.3 are in `tests/opt-testcases/tls13-compat.sh` (included from `ssl-opt.sh`)? TLS 1.3 should have good test coverage, so I assume there's already a test for client authentication somewhere, and hopefully it goes over all the possible algorithms.

Oh wait, we can look at the PR that introduced `pk_sign_ext()` and see what tests it added or modified: https://github.com/Mbed-TLS/mbedtls/pull/5559/files#diff-54a2261aca14ebb2491a1584cc3351a458487c23c25f90df08de2573cd705e32 - at first glance I think that's a good basis for what we want to do - just creating copies with the key made opaque should do the trick. Does that sound right to you?

**Comment by mpg** [comment]
On a different note, we should probably have some integration testing for opaque ECDSA keys with TLS 1.3, and I don't think that's the case so far...

**Comment by superna9999** [comment]
> Oh wait, we can look at the PR that introduced `pk_sign_ext()` and see what tests it added or modified: https://github.com/Mbed-TLS/mbedtls/pull/5559/files#diff-54a2261aca14ebb2491a1584cc3351a458487c23c25f90df08de2573cd705e32 - at first glance I think that's a good basis for what we want to do - just creating copies with the key made opaque should do the trick. Does that sound right to you?

Oh indeed, thanks for the pointer, I'll have a look what I can do, same for opaque ECDSA keys

**Comment by mpg** [comment]
For now this is only positive testing, we'll add negative testing later as part of a different task (github issue not created yet, but there's a [placeholder](https://github.com/orgs/Mbed-TLS/projects/1#card-80932215) in the EPIC for that, and also I think it depends on #5761 if we want to do it properly). But thanks for raising the question, it's way too easy to forget about negative testing, and this has bitten us several times in the past, so it's good that reviewers are asking about it!
