### ISSUE TITLE
SHA512/256 build fail   on arm64 PC

### ISSUE THREAD

**Issue by yuhaoth** [Mbed-TLS/mbedtls#5752]
### Summary
This issue is found in Arm64 PC. To run ` all.sh` in aarch64 ubuntu 20.04, it reports sha512/256 error.

- By default, `./tests/scripts/all.sh build_psa_accel_alg_sha*` will report compiler options error.
   - And I check `all.sh` , I did not found any  `aarch64-linux-gnu` cross compile test . I think the test coverage is not enough. we should add `aarch64-linux-gnu` cross compiler, and add tests for it.

- Test command: `./tests/scripts/all.sh build_no_std_function`, it reports below error. With `-march=armv8.2-a+sha3+crypto`
```
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:530:5: error: no previous prototype for 'mbedtls_internal_sha512_process_a64_crypto' [-Werror=missing-prototypes]
  530 | int mbedtls_internal_sha512_process_a64_crypto( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:548:5: error: no previous prototype for 'mbedtls_internal_sha512_process_c' [-Werror=missing-prototypes]
  548 | int mbedtls_internal_sha512_process_c( mbedtls_sha512_context *ctx,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/haoyu01/work/mbedtls/mbedtls/library/sha512.c:679:5: error: no previous prototype for 'mbedtls_a64_crypto_sha512_has_support' [-Werror=missing-prototypes]
  679 | int mbedtls_a64_crypto_sha512_has_support( void )
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- Test command : `./tests/scripts/all.sh check_names --force` report below errors. With `-march=armv8.2-a+sha3+crypto`
```
All symbols in header: FAIL

    > 'mbedtls_a64_crypto_sha512_has_support' was found as an available symbol
      in the output of nm, however it was not declared in any header files.
    > 'mbedtls_internal_sha512_process_a64_crypto' was found as an available
      symbol in the output of nm, however it was not declared in any header
      files.
    > 'mbedtls_internal_sha512_process_c' was found as an available symbol in
      the output of nm, however it was not declared in any header files.
```

### System information

Mbed TLS version (number or commit id): 09dc05b880b1b32972bf1052b558dbc0aaca92db
Operating system and version: ubuntu 20.04 
Machine ARCH: Arm64

### Expected behavior
Test PASS

### Actual behavior
Test Fail

### Additional information
To add `-march=armv8.2-a+sha3+crypto` with below patch.
```diff
diff --git a/include/mbedtls/build_info.h b/include/mbedtls/build_info.h
index 3dd944c76..8d4830d91 100644
--- a/include/mbedtls/build_info.h
+++ b/include/mbedtls/build_info.h
@@ -80,6 +80,9 @@
 #if defined(MBEDTLS_PSA_CRYPTO_CONFIG)
 #include "mbedtls/config_psa.h"
 #endif
+#if defined(__aarch64__)
+#pragma GCC target ("arch=armv8.2-a+sha3+crypto")
+#endif
 
 #include "mbedtls/check_config.h"
```

**Comment by tom-cosgrove-arm** [comment]
@yuhaoth I only get this error if I add `-Wmissing-prototypes`, which doesn't seem to come from any of `-Wall`, `-Wextra` or `-Wpedantic`. Also, when I add this option, I also get a failure

```
  CC    src/asn1_helpers.c
src/asn1_helpers.c:30:5: error: no previous prototype for 'mbedtls_test_asn1_skip_integer' [-Werror=missing-prototypes]
   30 | int mbedtls_test_asn1_skip_integer( unsigned char **p, const unsigned char *end,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by yuhaoth** [comment]
My environment is based on below command.
```
docker build -f Dockerfile -t mbedtls-dev-ubuntu:20.04 . \
                --build-arg IMAGE=yuhaoth/mbedtls-dev:ubuntu-20.04 --build-arg USER=$USER     \
                --build-arg GROUP=$( id -gn) \
                --build-arg uid=$(id -u) --build-arg gid=$(id -g)
```
Dockerfile
```
ARG IMAGE
From ${IMAGE}

RUN set -e; \
    apt-get update -q; \
    apt-get upgrade -qy; \
    apt-get install -yq sudo ; \
    apt-get clean ; \
    rm -rf /var/lib/apt/lists/

# Add user
ARG uid
ARG gid
ARG GROUP
ARG USER
RUN set -e; groupadd -g ${gid} ${GROUP}; \
    useradd -g ${gid} -u ${uid} -m ${USER}; \
    usermod -aG sudo ${USER}; sed -i s'/ALL$/NOPASSWD:ALL/' /etc/sudoers

# Create workspace
USER ${USER}
WORKDIR /home/${USER}
```

**Comment by tom-cosgrove-arm** [comment]
And yes, I agree, we need a more modern compiler for aarch64 cross-compilation - we only have ARM Compiler 6, which can do `armv8.2-a+crypto`, but can't do the SHA-512 stuff (note: we do cross-compile for `aarch64-arm-none-eabi`)

**Comment by yuhaoth** [comment]
To run with above environment, at top directory.
`docker run --rm -it -v $PWD:$PWD -w $PWD mbedtls-dev-ubuntu:20.04 ./tests/scripts/all.sh build_no_std_function`

**Comment by yuhaoth** [comment]
And just found , `check_name` fail is found on x86_64 ubuntu 20.04 also

**Comment by tom-cosgrove-arm** [comment]
@yuhaoth can you share the `check_names` failure you are seeing on x86_64, since none of the accelerated SHA-2 functions are built there - or do you mean this is when cross-compiling for aarch64 on x86_64?

**Comment by yuhaoth** [comment]
#5758 is created and assign to @tom-cosgrove-arm
