### ISSUE TITLE
RSA decrypt 0: Rework `mbedtls_pk_wrap_as_opaque()`

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5761]
The function `mbedtls_pk_wrap_as_opaque()` is a test utility that was initially working only for ECDSA keys, but now needs to handle more key types; as a result, it's desirable for it to have more parameters.

- ~The function's documentation currently has a warning that it may change or be removed at any time. Since it's only a test utility, it's cleaner not to expose it at all in the library. The function should be defined in a new file under `tests/src` and declared in a new file under `tests/include/test`.~ Let's keep it in the library for now, after all.
- [ ] Currently the algorithm(s) and key usage are hardcoded in the function, deduced from the key type. This is limited for RSA keys, where 3 algorithms should be possible (PKCS1v1.5 sign, PSS sign, decrypt). It also does not support fine-grained testing, where for example an ECC key would allow only one of sign or key exchange, and the TLS code should handle that gracefully. Change the signature of the function so that instead of `psa_algorithm_t hash_alg` it accepts `psa_algorithm_t alg, psa_key_usage_t usage, psa_algorithm_t alg2`. If `alg2` is `PSA_ALG_NONE`, then `psa_set_key_enrollment_algorithm()` is not called. Adjust calling sites.
- [ ] Update the function's documentation.

Note: this will probably conflict with #5728 which also modifies this function, so we might want to wait for #5728 to be merged first.

Follow-up: #5761

**Comment by superna9999** [comment]
@mpg I have a few design questions:
- `ssl_server2` & `ssl_client2` are also users of `mbedtls_pk_wrap_as_opaque`, can they use code in `test/src` ?
- `mbedtls_pk_wrap_as_opaque` depends on `mbedtls_pk_error_from_psa`, `MBEDTLS_PK_RSA_PRV_DER_MAX_BYTES` defined in `library/pk_wrap.h` and `library/pkwrite.h`. Can we use those from `test/src` ?

**Comment by gilles-peskine-arm** [comment]
Programs under `programs` are currently not linked with code under `test`. We could do this, but even the test programs (`programs/ssl/*2`, `programs/test/*`) don't use the same error reporting mechanisms as the test suites, so there's not a lot of room for common code.

Looking at the places where the function is used, moving it to test code seems like a code smell: it's needed to generically plug X.509/TLS into PSA crypto, and that's something application code is just as likely to need as our test code. So it seems to me that it should stay library code — but since it's clearly marked as an experimental function, we can evolve its API if we didn't get it right the first time.

**Comment by mpg** [comment]
> Programs under `programs` are currently not linked with code under `test`.

Ah, before writing this issue I was wondering about that, so I went a looked, in `programs/Makefile` we have:
```
MBEDTLS_TEST_PATH:=../tests/src
MBEDTLS_TEST_OBJS:=$(patsubst %.c,%.o,$(wildcard ${MBEDTLS_TEST_PATH}/*.c ${MBEDTLS_TEST_PATH}/drivers/*.c))
# [...]
DEP=${MBEDLIBS} ${MBEDTLS_TEST_OBJS}
# [...]
SSL_TEST_DEPS = $(SSL_TEST_OBJECTS) \
        test/query_config.h \
        ssl/ssl_test_lib.h \
        ssl/ssl_test_common_source.c \
        $(DEP)
# [...]
ssl/ssl_server2$(EXEXT): ssl/ssl_server2.c $(SSL_TEST_DEPS)
    echo "  CC    ssl/ssl_server2.c"
    $(CC) $(LOCAL_CFLAGS) $(CFLAGS) ssl/ssl_server2.c $(SSL_TEST_OBJECTS) $(LOCAL_LDFLAGS) $(LDFLAGS) -o $@
```
and other programs link with `$(DEP)` instead of `$(SSL_TEST_DEPS)`. There's something similar with CMake using `$<TARGET_OBJECTS:mbedtls_test>` so it looks to me like we are linking programs with code under tests. 

Am I missing or misreading something?

> Looking at the places where the function is used, moving it to test code seems like a code smell: it's needed to generically plug X.509/TLS into PSA crypto, and that's something application code is just as likely to need as our test code.

I think what's needed to generically plug X.509/TLS into PSA Crypto is `mbedtls_pk_setup_opaque()`: it takes a PSA key and wraps it into a PK context that X.509/TLS can use.

What `pk_wrap_as_opaque()` does is quite different: it takes a PK context (that's already perfectly suitable for use in X.509/TLS), then creates a PSA key out of it, then wraps the result again in a PK context (that X.509/TLS can use again) using `mbedtls_pk_setup_opaque()`. We use it for testing that keys created by `mbedtls_pk_setup_opaque()` indeed work as expected in X.509/TLS.

Going full circle PK -> PSA -> PK is convenient for our tests as we get our keys as PK contexts. I'm not convinced it's something an application would want to do: either the key is already on the PSA side what you want is `mbedtls_pk_setup_opaque()`, or it's already a PK context and you can already use it with X.509/TLS as is. Is there a reason I'm missing why an application would want to go PK -> PSA -> PK?

> So it seems to me that it should stay library code — but since it's clearly marked as an experimental function, we can evolve its API if we didn't get it right the first time.

I think if it stays as library code because we think applications may want to use it, then we need to make it a stable API (at least starting from the next version), otherwise it's not really usable.

**Comment by gilles-peskine-arm** [comment]
> > Programs under programs are currently not linked with code under test.
> Ah, before writing this issue I was wondering about that, so I went and looked, in programs/Makefile we have:

:facepalm: I thought we did, so I went to check, and I missed that `MBEDTLS_TEST_OBJS` is included in `DEP`. I think we did that to support builds with PSA test drivers. And checking `programs/*/CMakeLists.txt` this is also implemented for CMake builds. So yes, all programs (not just test programs) _can_ use test functions (but only the test programs, such as `ssl_*2`, should).

> > So it seems to me that it should stay library code — but since it's clearly marked as an experimental function, we can evolve its API if we didn't get it right the first time.
> I think if it stays as library code because we think applications may want to use it, then we need to make it a stable API (at least starting from the next version), otherwise it's not really usable.
My point is that it looks like it should eventually become a stable API, but it seems that at the moment we know we want a public API but we don't know exactly what it should be, so it's ok if we wait until we're confident to declare it stable.

**Comment by mpg** [comment]
> My point is that it looks like it should eventually become a stable API, but it seems that at the moment we know we want a public API but we don't know exactly what it should be, so it's ok if we wait until we're confident to declare it stable.

I don't think at the moment we know we want a public API. My point above is precisely that I do not think this should be a public API, because I think this is only useful for testing the library, as opposed to actually using it. Which is why I wanted to remove it from the library. My opinion is that the only public API we want is `mbedtls_pk_setup_opaque()` which is fine and stable, and that I don't see why an application would want to use `pk_wrap_as_opaque()` instead.

Now, I might be wrong about that, and I'm open to counter-arguments, but that's what I'm thinking right now, so it definitely is not the case that "we know we want a public API" (for PK -> PSA -> PK as opposed to PSA -> PK).

**Comment by mpg** [comment]
@gilles-peskine-arm Can you clarify if you think `pk_wrap_as_opaque()` should remain public, and it so, why? From the conversation above I'm not sure if we were having a disagreement or a misunderstanding, but either way let's resolve it.

**Comment by mpg** [comment]
Ok, thanks for clarifying. Let's keep it in the library for now, then, with the existing warning. It might not be what we want in the long run, but if you think it can be needed by some users then it's better than nothing.

**Comment by mpg** [comment]
(Updated the task description accordingly.)

**Comment by gilles-peskine-arm** [comment]
Eventually there will be a PSA layer to parse a key in e.g. X.509 and adjacent formats and import it. I don't yet have a precise view of the concrete interface. It may end up replacing `mbedtls_pk_wrap_as_opaque` (or its successor), or it may use it as a building block.

Seeing what we find useful for testing is informative in this regard (but it's not all, of course, since test code tends to both have unusually general requirements because it wants to inject bad data, and not cover all common production requirements because it does things in a very structued way).
