### ISSUE TITLE
Bring VS build up to date

### ISSUE THREAD

**Issue by josesimoes** [Mbed-TLS/mbedtls#5807]
### Suggested enhancement
Bring VS build up to date by removing the old (deprecated) VS2013 style and projects. 
I have a working prototype of this working locally and I'm happy to elaborate on the details if this is something that you'll accept a PR for.

### Justification
CMake build system is supported out-of-the-box in Visual Studio since v2019, so there is no need to keep an ancient build system around.

**Comment by josesimoes** [comment]
Not exactly 😁 I was suggesting on using exactly what you already have: CMake. VS "now" supports that natively, so everything its already in place.

This means:
- Get rid of the vcxproj files (all visualc directory, actually)
- Update .gitignore to filter out VS working files and build artifacts.
- Add a CMakeSettings.json file (or alternatively a CMakePresets.json).
- Update README accordingly.

This move will ensure support for building in VS in the current versions and future ones without any adicional effort (as long as CMake is supported, of course, which I'm betting will be for the long run).

BTW, I've made a typo above (which I've corrected now) I meant VS2019, not 2029

**Comment by josesimoes** [comment]
vcxproj files are still valid and _a thing_ in VS 2022. No issues with keep using them.
It's just that VS now supports CMake projects which is already there for MbedTLS, as you know.
Build work out of the box. Debugging works out of the box.

Main advantage is that you don't have to generate and worry about the vcxproj because all works through CMake.
Follows some screen shoots to better illustrate this.

Solution explorer
![image](https://user-images.githubusercontent.com/1881520/166989675-08341786-5160-45eb-84c6-4bdc71180470.png)

Config CMake step
![image](https://user-images.githubusercontent.com/1881520/166989985-055e484f-406b-4990-8e61-0e94a75fb6fc.png)

Build start
![image](https://user-images.githubusercontent.com/1881520/166990509-c5548b2f-1f27-4f56-a258-1f52b35385aa.png)

Build completed
![image](https://user-images.githubusercontent.com/1881520/166990711-8288531a-8156-4c31-aa42-73616e2383f7.png)

Debugging 
![image](https://user-images.githubusercontent.com/1881520/166991294-cd1142f0-1b08-4c43-83ff-38a110342a5e.png)

**Comment by tom-cosgrove-arm** [comment]
I see

> Bring VS build up to date by removing the old (deprecated) VS2013 style and projects.

and

> vcxproj files are still valid and a thing in VS 2022. No issues with keep using them.

So current VS users can use the project-file mechanism or CMake. Users of older versions, which we need to continue to support, can use the project-file mechanism.

I don't understand what you're suggesting to do.

**Comment by josesimoes** [comment]
OK. Never mind about this. I'm good with what's here now so I'll just keep using it. 🙂
