### ISSUE TITLE
Permissions 1: create `mbedtls_pk_can_do_ext()`

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5826]
**Context:** The TLS code needs to know which operations it can do with the private key(s) provisioned with `mbedtls_ssl_conf_own_cert()`, in order to negotiate a corresponding ciphersuite. For example, depending on whether we have an RSA or ECC key we'll choose an ECDHE-RSA or ECDHE-ECDSA key exchange. Currently the TLS code calls `mbedtls_pk_can_do()` in order to check the capabilities/type of the key.

With PSA-held keys (wrapped into a PK context with `mbedtls_pk_setup_opaque()`) this becomes more subtle, as the operations that a key can do are now determined not just by its type, but also by its policy. For example, with old-style keys, an RSA key can always do decryption, PKCS#1 v1.5 signatures and PSS signatures, with PSA-held keys it might only be able to do one or two of them. In addition, if the key can do signatures, with old-style key any hash could be used, while PSA-held key may either allow any hash or only a specific one, which would also influence what ciphersuites can successfully be used with that key.

Currently (roughly, as of #5762-#5764) things work with PSA-held keys as long as a matching ciphersuite is forced. However, when properly negotiating ciphersuites, it's currently possible for the server to select a ciphersuite incompatible with the policy of its private key, which will result in a handshake failure, which is clearly suboptimal: it would be better to continue looking in the list of ciphersuite until we either find a compatible one, or fail early with a clean "no suitable ciphersuite" error.

This task is the first in a series leading to that.

**This task** is to create a new function `mbedtls_pk_can_do_ext()` similar to `mbedtls_pk_can_do()` but that, instead of `mbedtls_pk_type_t` takes a `psa_algorithm_t` plus a `psa_key_usage_t` (with a most one bit set) and says whether the corresponding operation is possible with that key.

The function should work both for PSA-held and old-style keys (for those, it might disregard the usage and just convert the algorithm to a key type before calling `mbedtls_pk_can_do()`).

It only needs to correctly handle the following input values (should be documented):

- algs: `PSA_ALG_RSA_PKCS1V15_SIGN(hash)`, `PSA_ALG_RSA_PSS(hash)`, `PSA_ALG_RSA_PKCS1V15_CRYPT`, `PSA_ALG_ECDSA(hash)`, `PSA_ALG_ECDH`, where `hash` is a specific hash;
- usage: `PSA_KEY_USAGE_SIGN_HASH`, `PSA_KEY_USAGE_DECRYPT`, `PSA_KEY_USAGE_DERIVE`

The function needs to be unit-tested with enough cases to ensure good coverage (positive and negative).

Note: the implementation of the function may be similar in part to `psa_key_policy_permits()` / `psa_key_algorithm_permits()` with the following differences: (1) it needs to check usage as well, (2) the algorithm checking part will be much simpler thanks to the restriction on allowed algorithms, (3) it will have to retrieve metadata from the key first using functions like ` psa_get_key_algorithm()` and `psa_get_key_enrollment_algorithm()`.

**Comment by gilles-peskine-arm** [comment]
> usage: PSA_KEY_USAGE_SIGN_HASH, PSA_KEY_USAGE_DECRYPT, PSA_KEY_USAGE_DERIVE

I don't understand why it would be useful to have a function that only accepts these usage values. If the function checks the actual key policy, it also needs to accept keys that have more allowed usage. (`PSA_KEY_USAGE_SIGN_HASH` alone isn't even a possible policy: `PSA_KEY_USAGE_SIGN_MESSAGE` is always set as well.) If the function only cares about the type of operation, that's redundant with the algorithm: a given algorithm can only be used for one of sign/verify, encrypt/decrypt or key agreement. The usage flags matter to distinguish a key that can only verify from a key that can both sign and verify, for example, but for asymmetric cryptography this is not very useful since private vs public already establishes such a distinction.

**Comment by mpg** [comment]
> If the function only cares about the type of operation, that's redundant with the algorithm [ ... ]

Ah, silly me, completely missed that. So, the function doesn't need this argument. Thanks for noticing! I'm editing the description then.

**Comment by superna9999** [comment]
`The function should work both for PSA-held and old-style keys` would'nt this falsely induce non-opaque context could do PSA operations ?

**Comment by mpg** [comment]
> >The function should work both for PSA-held and old-style keys
>
> would'nt this falsely induce non-opaque context could do PSA operations ?

Good question. I don't think so. In the PK API there's no distinction between "PSA operation" and "other operations" as far as callers are concerned - one of the goals of the PK layer, with the `pk_setup_psa()` function, is precisely to abstract this away from caller. People can call `pk_decrypt()` and not worry whether the key is held in by PSA or not. Also, even if the key's not held by PSA, the PK layer will still call a PSA function to perform the operation when `USE_PSA` is enabled - again, I consider this a feature that callers don't have to know.

What the caller wants to know is "If I later call `pk_sign_ext()` to get a PSS signature with SHA-256, does this have a chance to work, or do we already know it won't? What if I call `pk_sign()` to sign a SHA-384 hash? What if I call `pk_decrypt()`?" etc. That's the question this new function should answer.

The existing `pk_can_do()` is not good enough because you can only ask it "can I do RSA?" but you can't distinguish between decrypt, sign-pkcs1v1.5, sign-PSS. That's actually not a limitation of just the function, but of the argument type: `mbedtls_pk_type_t` can't convey precisely enough what operation the caller will want to do.

We could introduce a new enum for that, but I thought it wasn't worth it considering we already have PSA constants that can express what we want just fine.

Btw, I was undecided between calling the new function `pk_can_do_ext()` or `pk_can_do_psa()`, and considering you question, perhaps `_ext` would be better then?

**Comment by gilles-peskine-arm** [comment]
Bouncing back on usage: you motivate this function by the use of private keys for signing and decrypting. However, the name of the function is general and it would make sense for it to also apply to public-key operations. It would make sense for a “can do” function to e.g. return true for “can it encrypt with algorithm A?” but false for “can it decrypt with algorithm A?”. So it does make sense to take a usage argument, but the “at most one bit” and omission of `SIGN_MESSAGE`, `VERIFY` and `DECRYPT` in the original specification are odd. How about accepting a full usage mask? There is already an internal function for comparing usages (used for `psa_copy_key` which is only allowed to narrow down usage) so not much new implementation work.

**Comment by mpg** [comment]
Good point. Currently opaque (PSA-held) keys are always private, but in the future they might not always be. And as you say, while the immediate intended usage is only for private keys, the function may be more general than that.

The reason I suggested this "one bit restriction" is that I think it's enough to check one capability at a time. Also, if we passed a value with more than one bit set, should it means "can the key do all of these?" or "can the key do at least one of these?". Said otherwise, I find it clearer for callers to write:
```c
mbedtls_pk_can_do_ext( mykey, alg, PSA_ALG_RSA_PKCS1V15_SIGN(PSA_ALG_SHA256) ) ||
mbedtls_pk_can_do_ext( mykey, alg, PSA_ALG_RSA_PKCS1V15_CRYPT );
```
or 
```c
mbedtls_pk_can_do_ext( mykey, alg, PSA_ALG_RSA_PKCS1V15_SIGN(PSA_ALG_SHA256) ) &&
mbedtls_pk_can_do_ext( mykey, alg, PSA_ALG_RSA_PKCS1V15_CRYPT );
```
than a hypothetical
```c
mbedtls_pk_can_do_ext( mykey, alg,
    PSA_ALG_RSA_PKCS1V15_SIGN(PSA_ALG_SHA256) | PSA_ALG_RSA_PKCS1V15_CRYPT );
```
where you'd have to check the documentation to be sure which of the above it's equivalent to.

Again, this is influenced by the intended use in TLS where you're only going to perform one operation per handshake, so you only want to check if that operation is allowed, but even taking into account more general uses of the function, I think the above readability argument applies.

> omission of `SIGN_MESSAGE`, `VERIFY` and `DECRYPT` in the original specification

Yes, that's because I was trying to describe the minimum we need for use in TLS 1.2 and 1.3. If we want to make the function more general, these would absolutely make sense as well.

**Comment by superna9999** [comment]
I pushed a first draft or work at https://github.com/Mbed-TLS/mbedtls/pull/5833 so we can discuss if we need to change the API.

**Comment by mpg** [comment]
I had a look at #5833 and I think it's good except it doesn't check if the key usage flags allow the operation: for example if someone sets up a key with `alg == PSA_ALG_ECDH` and `usage = PSA_KEY_USAGE_DECRYPT` (which I think we all agree is a pretty stupid thing to do, such a key can't be used for anything), then currently the function will return 1 when asked about `ECDH`, while I think it should return 0. This could be done without getting an explicit `usage` parameter, but just inferring it from the value of the `alg` argument.

However, and perhaps more realistically: if an ECC key allows `PSA_KEY_USAGE_SIGN_MESSAGE` but we intend to use it with `psa_sign_hash()` then we have a problem, and we want this function to let us know about it. And the function can't infer from the alg if the intention is to all `psa_sign_message()` or `psa_sign_hash()`, so we need an explicit `usage` parameter for that.

Also, as pointed out by Gilles, this parameter will be useful if/when we add support for Opaque public keys.

So, I suggest going back to the original plan, and adding a `usage` parameter as follows:
```
/**
 * \brief           Tell if context can do the operation given by PSA algorithm and usage flag
 *
 * \param ctx       The context to query. It must have been initialized.
 * \param alg       PSA algorithm to check against, the following are allowed:
 *                  PSA_ALG_RSA_PKCS1V15_SIGN(hash),
 *                  PSA_ALG_RSA_PSS(hash),
 *                  PSA_ALG_RSA_PKCS1V15_CRYPT,
 *                  PSA_ALG_ECDSA(hash),
 *                  PSA_ALG_ECDH, where hash is a specific hash.
 * \param usage  PSA usage flag to check against, must be one of:
 *                 PSA_KEY_USAGE_SIGN_HASH
 *                 PSA_KEY_USAGE_DECRYPT
 *                 PSA_KEY_USAGE_DERIVE
 *
 * \return          1 if the context can do operations on the given type.
 * \return          0 if the context cannot do the operations on the given
 *                  type. This is always the case for a context that has
 *                  been initialized but not set up, or that has been
 *                  cleared with mbedtls_pk_free().
 */
int mbedtls_pk_can_do_ext( const mbedtls_pk_context *ctx, psa_algorithm_t alg, psa_key_usage_t usage );
```

Of course we can always lift the "must be one of the following" restrictions / enlarge the allowed sets in the future as needed.

@gilles-peskine-arm Is that OK for you?

**Comment by mpg** [comment]
One part of me is now thinking that if instead of going with `psa_algorithm_t, psa_key_usage_t` was the way to indicate the operation, I had suggested creating a new enum with values `op_rsa_sign_pkcs1`, `op_rsa_sign_pss`, `op_rsa_decrypt`, `op_ecdsa_sign`, `op_ecdh` and passing that + a hash, then we wouldn't be having all these discussions about the `psa_key_usage_t` argument.

I though that `psa_algorithm_t, psa_key_usage_t` was the most natural way to represent what we want to do with the key, but perhaps it isn't.

On another front, perhaps this should not be a public API, just library-internal, to reflect that we're just trying to support what TLS needs? (The bit about ECDH goes in this direction: PK can't do ECDH, so what we're really asking here is if the TLS code that does ECDH will work - and that code distinguishes between PSA and non-PSA keys.)

**Comment by mpg** [comment]
@gilles-peskine-arm Unless you strongly object, I plan on merging 5833 with its current API as soon as it's ready.

That is, only allowing the 5 algorithms in the description, and any combination of the 3 usage flags in the description, but also making it clear in the documentation that the set of allowed algorithms and usage flags may be expanded in the future.

If you have a strong objection, please say so and we'll work it out.

**Comment by gilles-peskine-arm** [comment]
Ok by me. I don't think those constraints really simplify the implementation, but whatever works.
