### ISSUE TITLE
Clear master secret from mbedtls_ssl_session after handshake is ready

### ISSUE THREAD

**Issue by MaartenMJR** [Mbed-TLS/mbedtls#5832]
### Suggested enhancement
I'm working with an mbed TLS server with small memory foot print, and I'm wondering whether the mbedtls_ssl_session.master property is useful after the handshake is ready. I think it is not, also by investigation of the code. I'd suggest to:

- either replace `master[48]` with a pointer to be cleared when the handshake is ready. 
- move `master[48] to the ssl->handshake structure which automatically is cleaned when the handshake is ready 

### Justification
As the master secret is stored twice in the mbedtls_ssl_context it saves about 100B per SSL context. 

As far as I could see the master secret isn't of any use when the handshake is over. It is however used for serialization purposes but I doubt if that is useful currently (I.e. when using MBEDTLS_SSL_CONTEXT_SERIALIZATION). 

I need some advice to proceed. For example, is my assumption correct that the master secret isn't of use when the handshake is over, and if yes, what of the above suggestions should I work out?

**Comment by tom-cosgrove-arm** [comment]
I'm not sure where the master secret is stored twice in `mbedtls_ssl_context`, but I don't think it would be trivial to move it to the handshake structure anyway, as (for example) it is needed in `ssl_session_save_tls12()`.

You might try asking on the mailing list (`mbed-tls@lists.trustedfirmware.org`) which is a probably better place to ask questions such as these.

**Comment by MaartenMJR** [comment]
Thanks, I'll use the mailing list then, but I'll first verify how this is related to `ssl_session_save_tls12`.
