### ISSUE TITLE
Add ability to peek at incoming packets before processing them

### ISSUE THREAD

**Issue by Thibautartis** [Mbed-TLS/mbedtls#5843]
### Suggested enhancement

Add a function to peek at an incoming packet

### Justification

I have implemented a DTLS server using mbedtls, I recently added the connection ID feature but I have had to resort to some ugly tricks in order to be able to process the connection ID, I'll explain

The server I implemented has a main thread listening for new incoming connections, each time it receives a packet coming from a new UDP connection it creates a thread to which it gives the ownership of the associated fd. The thread then handles the handshake and all subsequent communication with the client

In order to test the connection ID I created a basic client that connects to my server and after a while closes and reopens its mbedtls_net_context, making its DTLS packets travel from a new UDP port to the server

And here is the problem, at this point we have a packet that belongs to an existing DTLS context but coming from a new UDP connection, and I have found no way in the library to discriminate whether this packet is a new ClientHello or a connection ID'd Application Data before attempting a handshake.
The solution I came up with for now is to try a handshake on that new UDP connection and, if it fails (which is the case here), I check for `ssl.private_in_hdr[0] == MBEDTLS_SSL_MSG_CID`, if this condition is satisfied then I know I can replace the old file descriptor corresponding to this connection ID by the new one and the DTLS exchanges can continue normally

The problem with this solution, other than accessing private variables of the library is that it makes the packet triggering this FD change "lost" in the sense that it has already been consumed by the library when attempting to do a handshake and cannot be retrieved in order to be processed again in the right ssl context.
This can be a huge problem in case the packet frequency is lower than the frequency in NAT changes

This is why I think it would be necessary to be able to peek at an incoming packet, or at least be able to look for a connection ID in a packet before having it processed

**Comment by daverodgman** [comment]
I think this is a duplicate (with some new background) of #551 - I've added some info there and closing this issue.

**Comment by Thibautartis** [comment]
Thanks ! sorry for the duplicate
