### ISSUE TITLE
Permissions 2b: TLS 1.3 sigalg selection

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#5844]
TLS 1.3 needs to pick a signature algorithm for the CertificateVerify message based on algorithms offered by the peer, and capabilities of our own private key. Currently this done base on the key type, but for Opaque (PSA-held) keys, this need to take the into account the key policy. For example, we don't want to pick RSA-SHA256 if the key policy only allows RSA-SHA384.

This task is to modify `ssl_tls13_get_sig_alg_from_pk()` so that it takes into account the policy of PSA-held keys.

This function is currently `static`. As part of this task, we should make it `MBEDTLS_STATIC_TESTABLE` so that we can unit-test it with both classical and Opaque PK contexts, with various policies for the later.

In addition, we also want some integration testing in `ssl-opt.sh`, using the `key_opaque_algs` option to `ssl_client2` (and `ssl_server2` if merged by that time, see #5496).

Note: for ECDSA, the TLS 1.3 spec only allows signatures with a hash that matches the size of the key, so there's little wiggle room here. If a key was passed that uses, say P-256 and only allows SHA-384 for signatures, then this key just isn't usable with TLS 1.3, and the function should return an error on such keys.

Note: for RSA, currently the function tries to select a hash that somewhat matches the length of the key. This is purely opportunistic and not mandated by the spec, so that can be overridden by the key policy. Btw, currently the function happens to reject RSA keys > 4096 bits - while such keys are probably super rare in practice, as a matter of principle we should not reject them, so that can be fixed as well in the course of this task.

Depends on: #5826 for `mbedtls_pk_can_do_ext()` which is likely to be useful here (to handle Opaque and non-Opaque in a uniform way).

**Comment by mprse** [comment]
This looks like a bug (`521 -> 512`):
https://github.com/Mbed-TLS/mbedtls/blob/271c3052fb8c46819faaa42bb1efb29ea3129eeb/library/ssl_tls13_generic.c#L872-L873

**Comment by mpg** [comment]
The largest NIST curve is indeed 521 bits, not 512. This is to take advantage of the Mersenne prime `2^521 - 1` which gives fast reduction. The wikipedia page about ECC used to have a "this is not a typo, please stop 'fixing' it" footnote after the 521 :)

**Comment by mprse** [comment]
When using `key_opaque_algs` option the key policy is set by means of `key_opaque_set_alg_usage()/mbedtls_pk_wrap_as_opaque()`. I understand that `mbedtls_pk_can_do_ext()` already fully checks key policy (alg/usage) in case of opaque keys? 

So in `ssl_tls13_get_sig_alg_from_pk()` we need to only use it. Something like (or some other actions are also needed):

```
ECDSA:

            switch( own_key_size )
            {
                case 256:
                    if( mbedtls_pk_can_do_ext( own_key,
                                               PSA_ALG_ECDSA( PSA_ALG_SHA_256 ),
                                               PSA_KEY_USAGE_SIGN_HASH ) == 1 )
                    {
                        *algorithm = MBEDTLS_TLS1_3_SIG_ECDSA_SECP256R1_SHA256;
                        return( 0 );
                    }

RSA:

            if( mbedtls_ssl_sig_alg_is_received( ssl,
                                    MBEDTLS_TLS1_3_SIG_RSA_PSS_RSAE_SHA256 ) &&
                mbedtls_pk_can_do_ext( own_key,
                                       PSA_ALG_RSA_PSS( PSA_ALG_SHA_256 ),
                                       PSA_KEY_USAGE_SIGN_HASH ) == 1 )                    
            {
                *algorithm = MBEDTLS_TLS1_3_SIG_RSA_PSS_RSAE_SHA256;
                return( 0 );
            }
```

**Comment by mprse** [comment]
After merging https://github.com/Mbed-TLS/mbedtls/pull/5817 `ssl_tls13_get_sig_alg_from_pk()` function became a global function. I understand in this case `MBEDTLS_STATIC_TESTABLE` requirement can be skipped here.

**Comment by mpg** [comment]
Absolutely, `STATIC_TESTABLE` is only required for function that are not already globally visible.
