### ISSUE TITLE
Add a test exercising the use of `PSA_ALG_RSA_PKCS1V15_SIGN(PSA_ALG_ANY_HASH)` key policy with `PSA_ALG_RSA_PKCS1V15_SIGN_RAW` signature algorithm

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#5857]
PSA Crypto API 1.1.0 states that the new version:

> Documented the use of [PSA_ALG_RSA_PKCS1V15_SIGN_RAW](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_RSA_PKCS1V15_SIGN_RAW) with the [PSA_ALG_RSA_PKCS1V15_SIGN](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_RSA_PKCS1V15_SIGN)([PSA_ALG_ANY_HASH](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_ANY_HASH)) wildcard policy.

The exact line added states that:

> The wildcard key policy [PSA_ALG_RSA_PKCS1V15_SIGN](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_RSA_PKCS1V15_SIGN)([PSA_ALG_ANY_HASH](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_ANY_HASH)) also permits a key to be used with the [PSA_ALG_RSA_PKCS1V15_SIGN_RAW](https://armmbed.github.io/mbed-crypto/html/api/ops/sign.html#c.PSA_ALG_RSA_PKCS1V15_SIGN_RAW) signature algorithm.

There is already a low-level test for key policy that exercises this:

> PSA key policy: asymmetric signature, wildcard in policy, PKCS#1v1.5 raw

This task aims to add a high level test for this algorithm & policy, simmilar to `PSA sign/verify hash: RSA PKCS#1 v1.5, raw` (which would be the best starting point), but with a wildcard policy.
This task should also update the documentation of `PSA_ALG_RSA_PKCS1V15_SIGN_RAW` to reflect that it can be used with a wildcard key policy.

**Comment by gilles-peskine-arm** [comment]
I don't understand what you mean by “high level test”. What behavior does "PSA key policy: asymmetric signature, wildcard in policy, PKCS#1v1.5 raw" not cover?

**Comment by AndrzejKurek** [comment]
I assumed that for algorithms for signing/verification we would not only like to have a test in the `PSA key policy` set of tests, but also one in the `PSA sign/verify hash`, as I found this to be a pattern. 
If you find the existing test sufficient, this task can be reduced to updating the documentation only.

**Comment by gilles-peskine-arm** [comment]
`asymmetric_signature_key_policy` performs an operation with the key. Looking at those tests, the only extra in `sign_verify_hash` are that it also checks size macros, and that you know at first glance that it's a positive test whereas the policy test functions also handle negative cases.

So I don't see a test gap here. On the other hand, there is some redundancy between functions, and maybe a lack of separation of concerns. There may be additional redundancies between the sign-then-verify code in those functions and `psa_exercise_key()`. And additional redundancies with the storage format tests, which exercise a key upon loading (and with the op_fail and not_supported generated tests, for negative test cases). And probably similar things with other kinds of operations. Those test functions and test cases were written at different times and sometimes by different people, there wasn't a well thought out overall plan.

I could see the value in writing up a test plan that breaks up the various responsibilities (generic test cases for combinations of key type/algorithm/... that should probably be systematically generated, edge cases (e.g. message size vs key/block size, large input, …) that are specific to a given type/alg that need to be written manually, multipart testing, etc.), making sure it's followed and getting rid of redundant test cases/functions. That's a fairly big task but would likely turn up test gaps as well as redundancies.

But I don't see a test gap for this particular case.

**Comment by AndrzejKurek** [comment]
Closing in favor of https://github.com/Mbed-TLS/mbedtls/issues/5862.
