### ISSUE TITLE
Reg : Request to know Minimum version of 2015WDK to build the MbedTLS3.1.0 security library.

### ISSUE THREAD

**Issue by 9SIVA** [Mbed-TLS/mbedtls#5869]
### Summary

I would like to know what is the minimum version of WDK to build MbedTLS3.1.0 as my build is failing when we are building with Visual studio-2015WDK toolset. 

**Note :** MbedTLS3.1.0 version build was succeeded with Visual Studio-2013 and Visual studio-2015 toolsets and In Linux also build was succeeded without any issue.

We are facing issue when toolset is using WDK7600 version. So, please provide your inputs and suggestion and do let me know if any further information is needed.

### System information
ABS Windows 2008 R2 AMD64 Checked Build Environment with visual studio-2015 environment. 

Mbed TLS version (number or commit id): MbedTLS-3.1.0
Operating system and version: Windows 2008 R2 with Visual Studio 2015 installed on it, WDK7600 version.
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
2015WDK Build should also be succeed like 2013 and 2015 toolsets. but its failing with 2015WDK.

### Actual behavior
Build was failing after we integrate MbedTLS-3.1.0 to the existing code.

### Steps to reproduce
N/A

### Additional information
N/A

**Comment by minosgalanakis** [comment]
Having a quick look at the project's [docker ](https://github.com/Mbed-TLS/mbedtls-test/blob/master/resources/docker_files/ubuntu-18.04/Dockerfile) files, I do not believe 2015WDK is tested/supported on the CI. 

Given how wider reach of the communit it has, support questions are better suited to the Mbed TLS [mailing list](https://www.trustedfirmware.org/projects/mbed-tls/)

Would you mind posting the question there?

**Comment by gilles-peskine-arm** [comment]
I don't know what WDK is. If it's different from Visual Studio and MSVC then we neither advertise support for it, nor do testing with it. So it's community-supported.

We can take patches to fix WDK builds if they don't break other platforms.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because there is nothing actionable here, not even error messages.
