### ISSUE TITLE
Reg : We can build MbedTLS-2.7.3 version using Visual studio-2012,2013,2015WDK without issues, But when we upgrade MbedTLS-3.1.0 from MbedTLS-2.7.3 then build was failing with Visual Studio-2012,2015WDK toolsets.

### ISSUE THREAD

**Issue by 9SIVA** [Mbed-TLS/mbedtls#5873]
### Summary

Hi Team,
Thank you so much for your quick response for the previous query.

In this query I want to let you know that with when we integrate MbedTLS-2.7.3 library to our code we are able to build with visual Studio-2012, 2013 and 2015WDK(WDK7600 ) toolsets without any issues, but when we upgrade security library from MbedTLS-2.7.3 to MbedTLS-3.1.0 version then build was failing for Visual studio-2012 and 2015WDK(Toolset: WDK7600 ) and remaining two toolsets i.e. : Visual Studio-2013,2015 build was success without any issues.

So, could you tell me why its failing only with Visual Studio-2012, 2015WDK(Toolset: WDK7600 ) when we upgrade to MbedTLS-3.1.0.

### System information

OS - Windows 2008 R2 with Visual Studio 2015.
Build Environment information : Windows 2008 R2 AMD64 when we are building with 2015WDK(Toolset: WDK7600 ).

Mbed TLS version (number or commit id): MbedTLS-2.7.3
Operating system and version: Windows 2008 R2.
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

MbedTLS-3.1.0 library also should build with Visual studio-2012, 2013 and 2015WDK(windows driver kit) toolsets without any issue like MbedTLS-2.7.3, but its failing to build with Visual Studio-2012 and 2015WDK toolsets.

### Actual behavior

1.  When we integrate MbedTLS-2.7.3 library to our code its building without any issues using  "visual Studio-2012, 2013 and 2015WDK toolsets"
2. But When we integrate MbedTLS-3.1.0 library to our code its only building with "visual Studio-2013 and 2015 toolsets" without any issues, but its failing with Visual Studio-2012 and 2015WDK toolsets.

**Comment by yanesca** [comment]
Dear @9SIVA , Visual Studio 2012 is not supported anymore: https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.1.0/README.md#tool-versions

What version of WDK do you mean by 2015WDK?

Looking at your previous issue: https://github.com/Mbed-TLS/mbedtls/issues/5869, you are using WDK7600 and looks like you are trying to build a driver for Windows 7. Is this the case?

**Comment by 9SIVA** [comment]
We are trying to build on windows server 2008 R2 with WDK7600.
Please find the link for more information for WDK : https://en.wikipedia.org/wiki/Windows_Driver_Kit.

Please find the screen shot for the reference below.
![image](https://user-images.githubusercontent.com/106135836/170313243-d4cbd483-3fcd-406e-89db-4ce3fabf94b3.png)

**Comment by yanesca** [comment]
As @gilles-peskine-arm mentioned on your previous issue, toolchains that are not mentioned on the [list](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.1.0/README.md#tool-versions) are community supported.

This means that we might accept patches that don't break anything, but we won't fix them. You could also ask around on the [mailing list](https://www.trustedfirmware.org/projects/mbed-tls/) as @minosgalanakis suggested, there are a lot of Mbed TLS users there, someone might have encountered this issue before.
