### ISSUE TITLE
need API macro support for AES-CBC alternative implementation

### ISSUE THREAD

**Issue by xzt777** [Mbed-TLS/mbedtls#5874]
### Suggested enhancement

It seems that library/aes.c only has a hardware accelerator API for AES's ECB mode,I've implemented mbedtls_aes_crypt_cbc() via a hardware accelerator, but mbedtls_config.h does not have macro support like MBEDTLS_AES_CBC_ALT,which I need to choose between software and hardware encryption.

### Justification
 
Mbed TLS needs this macro support because the hardware implementation of AES usually does not require the entire module replacement (retain the annotation MBEDTLS_AES_ALT). However, the hardware cannot use mbedtls_internal_aes_encrypt() to complete AES CBC/CTR encryption. So supporting something like MBEDTLS_AES_CBC_ALT/MBEDTLS_AES_CTR_ALT is useful for hardware accelerator implementations.

Thanks
Zitai

**Comment by yanesca** [comment]
Hi @xzt777 , thank you for your suggestion!

Unfortunately we won't be adding any more `_ALT` interfaces as these are in the process of being deprecated.

As you mentioned currently `MBEDTLS_AES_ALT` makes it feasible to integrate your hardware accelerator. (I agree that it is not the most convenient way and that it would be more convenient with a dedicated compile time option.)

Going forward, the [PSA Crypto Device Driver API](https://github.com/ARMmbed/mbedtls/blob/development/docs/proposed/psa-driver-interface.md) is the recommended interface to hardware accelerators and will provide a more robust and convenient way to do this.

**Comment by fanghuaqi** [comment]
Current mbedtls alt way to specify hardware acceleration is a good way for hardware ip to implement, if your team won't maintain it any more, where can I find the status of [PSA Crypto Device Driver API](https://github.com/ARMmbed/mbedtls/blob/development/docs/proposed/psa-driver-interface.md), is PSA Crypto ready for third-party hardware accelerator to implement, and will PSA Crypto seperate from mbedtls in future?

**Comment by yanesca** [comment]
> if your team won't maintain it any more

We are still maintaining it and will be maintaining it for a while: the `ALT_` interface is still part of the `development` branch and this means that this feature will still be still supported in the next LTS branch as well. (LTS branches are supported for three years and I think it will be still a year or two until the next one is created.)

In summary, we are supporting it and will be supporting it for years to come, but we won't add new features/entry points to it.

> where can I find the status of [PSA Crypto Device Driver API](https://github.com/ARMmbed/mbedtls/blob/development/docs/proposed/psa-driver-interface.md),

You can follow all of our development activities on our epic board, this is the main device driver epic:
https://github.com/orgs/Mbed-TLS/projects/1#column-17950148
(There are other epics about device drivers as well with more focused areas of development.)

> is PSA Crypto ready for third-party hardware accelerator to implement,

It is not feature complete, but the features that are present are ready to implement for a third-party hardware accelerator. That said, it is still experimental and the API still might change in future versions.

> will PSA Crypto seperate from mbedtls in future?

[PSA Crypto API ](https://armmbed.github.io/mbed-crypto/html/) is only an API specification and Mbed TLS provides a reference implementation for it. So in this sense they are already separate.

In the future the intent is that Mbed TLS fully relies on the PSA Crypto API for cryptography. So in this sense they won't separate.

**Comment by gilles-peskine-arm** [comment]
In addition to what @yanesca wrote: PSA accelerator drivers are supported for hash, MAC, cipher, AEAD, signature and asymmetric encryption. You need to manually edit `library/psa_crypto_driver_wrappers.c` for now, to dispatch the desired algorithm/key type combination(s) to your driver. We're currently working on a tool to generate this file from JSON as described in the driver interface specification.

For the time being, if you just want AES-CBC acceleration and nothing else, it's easier to implement `MBEDTLS_ALT_C`, copying the mbedtls functions for CTR and other modes if you need them but your accelerator doesn't provide them.

**Comment by fanghuaqi** [comment]
Hi @yanesca @gilles-peskine-arm , thanks for such detailed information sharing about the plan of PSA Crypto API and mbedtls, It helps me understand a lot.
