### ISSUE TITLE
Problem with "mbedtls/chacha20.h"

### ISSUE THREAD

**Issue by Bromar96** [Mbed-TLS/mbedtls#5883]
### System information

Mbed TLS version (number or commit id):  latest
Operating system and version: Windows10 Home 21H1
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  
Additional environment information: using VsCode and ArduinoIDE

### Expected behavior

mbedtls_chacha20_crypt(key,nonce,cnt,sizeInputData,inputData,outputData);

### Actual behavior

Arduino:1.8.19 (Windows Store 1.8.57.0) (Windows 10), Scheda:"ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None"

c:/users/.../documents/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\prova.ino.cpp.o:(.literal._Z4loopv+0x14): undefined reference to `mbedtls_chacha20_crypt'

c:/users/.../documents/arduinodata/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: sketch\prova.ino.cpp.o: in function `loop()':

**C:\Users\povar\Desktop\prova/prova.ino:24: undefined reference to `mbedtls_chacha20_crypt'**

collect2.exe: error: ld returned 1 exit status

exit status 1

### Steps to reproduce

Declared:
const unsigned char nonce[12] = "00000000000";
const unsigned char key[32] = "eYtejsk8ksh9soP8JAth45hslhG5E7u"; //256 bits
uint32_t cnt = 0;
const unsigned char inputData[100] = "My plain text is this";
unsigned char outputData[100];

### Additional information

Repeated error, using two different IDEs (VScode Platformio, ArduinoIDE) on both Windows10 and MacOs

Target board: Esp32 Dev Module

**Comment by yanesca** [comment]
It looks like a linker error, could you please make sure, that your IDE sees `libmbedcrypto` and is linking your program against it?

**Comment by gilles-peskine-arm** [comment]
I am closing this issue because it is likely to be a mistake in the compiler or linker invocation rather than a bug in Mbed TLS, and there is not enough information to pinpoint the problem.

**Comment by mstroven-hiviz** [comment]
I suspect this is a configuration problem with ESP_IDF as I have the same issue building an ESP32c3 application that uses NimBLE from ESP_IDF libraries.  The linker is unable to resolve the function "mbedtls_chacha20_crypt()".  The error listings from the log are here:
/home/mstroven/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: **esp-idf/main/libmain.a(hiviz_ble_beacon.c.obj): in function `hiviz_ble_beacon_transmit_packet':**

/home/mstroven/eclipse-workspace/HiViz-BLE-ESP32/main/hiviz_ble_beacon.c:127:(.text.hiviz_ble_beacon_transmit_packet+0x210): **undefined reference to `mbedtls_chacha20_crypt'**

/home/mstroven/.espressif/tools/riscv32-esp-elf/esp-14.2.0_20241119/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/14.2.0/../../../../riscv32-esp-elf/bin/ld: **esp-idf/main/libmain.a(hiviz_ble_beacon.c.obj): in function `hiviz_beacon_receive_gap_event_cb':**

/home/mstroven/eclipse-workspace/HiViz-BLE-ESP32/main/hiviz_ble_beacon.c:412:(.text.hiviz_beacon_receive_gap_event_cb+0x1d8): **undefined reference to `mbedtls_chacha20_crypt'**

collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by gilles-peskine-arm** [comment]
@mstroven-hiviz Indeed this may be a mismatch between the compile-time configuration and the expected features. It's not something we (maintainers of Mbed TLS) can really diagnose, since we don't know how ESP_IDF configures Mbed TLS. I would suggest to ask for help either on the [mbed-tls mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/) (where hopefully other ESP32 users hang out) or on an ESP32 forum.

**Comment by mstroven-hiviz** [comment]
Okay, thanks for the feedback!

**Comment by mstroven-hiviz** [comment]
I was able to find a place in the IDF menuconfig to enable the Chacha20 encryption algorithm.  So that's working correctly now.  I still have an issue with Eclipse trying to change my ESP32c3 target device to an ESP32c6 device, but that's a separate problem.  Thanks again.
