### ISSUE TITLE
Error in ASN1 parser?

### ISSUE THREAD

**Issue by edmundas919** [Mbed-TLS/mbedtls#5884]
mbedtls version 3.1.0
asn1parse.c

```
int mbedtls_asn1_get_bitstring( unsigned char **p, const unsigned char *end,
                        mbedtls_asn1_bitstring *bs)
{
    int ret = MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED;

   /* Certificate type is a single byte bitstring */
    if( ( ret = mbedtls_asn1_get_tag( p, end, &bs->len, MBEDTLS_ASN1_BIT_STRING ) ) != 0 )
        return( ret );

    /* Check length, subtract one for actual bit string length */
    if( bs->len < 1 )
        return( MBEDTLS_ERR_ASN1_OUT_OF_DATA );
    bs->len -= 1;

    /* Get number of unused bits, ensure unused bits <= 7 */
    bs->unused_bits = **p;
    if( bs->unused_bits > 7 )
        return( MBEDTLS_ERR_ASN1_INVALID_LENGTH );
    (*p)++;

    /* Get actual bitstring */
    bs->p = *p;
    *p += bs->len;

    if( *p != end )
        return( MBEDTLS_ERR_ASN1_LENGTH_MISMATCH );

    return( 0 );
}
```

I believe problem lies in 
```    
    if( *p != end )
         return( MBEDTLS_ERR_ASN1_LENGTH_MISMATCH );
```

Shouldn't it be `( *p > end )`? 
Since there might be more elements after bitstring element in ASN1 structure, we'll always will get `MBEDTLS_ERR_ASN1_LENGTH_MISMATCH ` even if bitstring element size is not out of bounds of provided ASN1 structure data.

I believe `mbedtls_asn1_traverse_sequence_of` and `mbedtls_asn1_get_alg` has the same issue.

**Comment by yanesca** [comment]
Hi, as far as I can tell, this is exactly the documented behaviour for `mbedtls_asn1_get_bitstring()` and for  `mbedtls_asn1_traverse_sequence_of()`:
https://github.com/Mbed-TLS/mbedtls/blob/v3.1.0/include/mbedtls/asn1.h#L324-L342
https://github.com/Mbed-TLS/mbedtls/blob/v3.1.0/include/mbedtls/asn1.h#L514-L516

In the case of `mbedtls_asn1_get_alg()` the documentation doesn't call this out, but this is still what we want here.

> Since there might be more elements after bitstring element in ASN1 structure, we'll always will get MBEDTLS_ERR_ASN1_LENGTH_MISMATCH even if bitstring element size is not out of bounds of provided ASN1 structure data.

Where we call these functions in Mbed TLS we want to make sure that there are no trailing bytes present and it is more efficient to check this here. In theory we could make it more permissive, but then the caller would need to perform the same check everywhere.

Do you have a specific use case where you would need make this check more permissive?

**Comment by gilles-peskine-arm** [comment]
The behavior is inconsistent (some ASN.1 function require an exact `end`, others don't) but documented except for `get_alg`.

For `get_bitstring` and `get_alg`, but not for `traverse_sequence_of`, if the function returns `MBEDTLS_ERR_ASN1_LENGTH_MISMATCH`, it currently works as in the success case except that there is trailing data in the input buffer. We could change the documentation to guarantee this, if we add corresponding unit tests. 

The ASN.1 library in Mbed TLS is pretty much only intended as a component of the X.509 implementation (even though it's in the libmbedcrypto and not libmbedx509, because a small part of it is used for RSA and ECDSA). We are unlikely to add any functionality that isn't useful for X.509.

**Comment by edmundas919** [comment]
I work on a project which uses ASN.1 for data serialization. And since we use mbedTLS and it has ASN.1 writer/parser, I though I could reuse it for our purposes. And since input buffer in most cases have trailing data I'm getting `MBEDTLS_ERR_ASN1_LENGTH_MISMATCH`, so I just wondered if it's correct behavior or it's a bug.

So if getting `MBEDTLS_ERR_ASN1_LENGTH_MISMATCH` is correct behavior, no need for any changes in mbedTLS. i'll adapt in my code.

Thank you for your answers.
