### ISSUE TITLE
Incorrect dependencies on MD and HKDF in config_psa.h

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#5890]
The HMAC and HKDF implementations via the PSA API do not rely on code from `md.c` or `hkdf.c`. Therefore `include/mbedtls/config_psa.h` should not refer to `MBEDTLS_MD_C` (except for asymmetric crypto where RSA/ECP do need MD) or to `MBEDTLS_HKDF_C`.

This is a frequent source of confusion (I've fielded support questions about it several times) and we didn't even get it right ourselves, so there should be comments explaining this in `config_psa.h`.

**Comment by mpg** [comment]
> This is a frequent source of confusion

I can confirm it is confusing for me :) `include/psa/crypto_config.h` says:

```
 * When \c MBEDTLS_PSA_CRYPTO_CONFIG is disabled in mbedtls_config.h,
 * this file is not used, and cryptographic mechanisms are supported
 * through the PSA API if and only if they are supported through the
 * mbedtls_xxx API.
```

This seems to justify enabling `PSA_WANT_ALG_HKDF` based on `MBEDTLS_HKDF_C`. I agree it would be better to enable `PSA_WANT_ALG_HKDF` as soon as its requirements are satisfied, but then we'll probably want to update the comment.

So, it seems to me that the only requirement for our builtin implementation of HKDF in PSA are `PSA_WANT_KEY_TYPE_HMAC` and `PSA_WANT_ALG_HMAC`. (We don't even strictly depend on `PSA_WANT_KEY_TYPE_DERIVE` as `input_bytes()` can be used.) Based on this, we could have the following, late enough in the file that the macros in the conditions are already set if they should be:
```c
#if defined(PSA_WANT_KEY_TYPE_HMAC) && defined(PSA_WANT_ALG_HMAC)
#define MBEDTLS_PSA_BUILTIN_ALG_HKDF 1
#define PSA_WANT_ALG_HKDF 1
#define MBEDTLS_PSA_BUILTIN_ALG_HKDF_EXTRACT 1
#define PSA_WANT_ALG_HKDF_EXTRACT 1
#define MBEDTLS_PSA_BUILTIN_ALG_HKDF_EXPAND 1
#define PSA_WANT_ALG_HKDF_EXPAND 1
#endif
```

@gilles-peskine-arm does that sound right to you?

**Comment by gilles-peskine-arm** [comment]
With `MBEDTLS_PSA_CRYPTO_CONFIG`, it might have made sense to not automatically enable the PSA HKDF implementation, because of the code size impact. But it makes sense to do it so as to have a simple rule “cryptographic mechanisms are supported through the PSA API [if] they are supported through the mbedtls_xxx API”. And we're already doing it and we can't stop or we'd break backward compatibility.

`HKDF_EXxxx` have minimal cost when HKDF itself is enabled, so it makes sense to enable them as well whenever HKDF gets enabled.

So let's keep `MBEDTLS_HKDF_C` implying `PSA_WANT_ALG_HKDF*`.

We do need to document this clearly in `config_psa.h`.

**Comment by mprse** [comment]
> HKDF_EXxxx have minimal cost when HKDF itself is enabled, so it makes sense to enable them as well whenever HKDF gets enabled.
So let's keep MBEDTLS_HKDF_C implying PSA_WANT_ALG_HKDF*.
We do need to document this clearly in config_psa.h.

I understand that conclusion is to keep current version:
https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/config_psa.h#L609-L618
and add extra information to `config_psa.h` ?

**Comment by gilles-peskine-arm** [comment]
Yes, keep the current code, and add a comment to explain why it's this way.
