### ISSUE TITLE
Drop VIA Padlock support

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#5903]
Mbed TLS supports AES acceleration on 32-bit x86 chips with [VIA Padlock](https://en.wikipedia.org/wiki/VIA_PadLock) (`MBEDTLS_PADLOCK_C`).

This processor feature has lost a lot of its popularity now that x86 chips are mostly 64-bit and have Intel's AES acceleration. The Arm maintainer team doesn't have the knowledge or hardware to maintain this feature. As a consequence, unless there is significant demonstrated interest, we intend to remove `MBEDTLS_PADLOCK_C` and `library/padlock.c` in Mbed TLS 4.0. It will still be possible to use VIA padlock via a PSA accelerator driver (which will not be part of Mbed TLS).

**Comment by ronald-cron-arm** [comment]
Not supported in psa-crypto and not planned to be supported thus this should probably be a MUST rather than a SHOULD.
