### ISSUE TITLE
Allow mbedtls_ssl_conf_cert_cb to pass an opaque pointer to the callback, like mbedtls_ssl_conf_sni

### ISSUE THREAD

**Issue by ndilieto** [Mbed-TLS/mbedtls#5910]
### Suggested enhancement

Allow mbedtls_ssl_conf_cert_cb to pass an opaque pointer to the callback, like mbedtls_ssl_conf_sni.

### Justification

Necessary when the ssl context is contained in a struct that needs to be accessed by the callback.

**Comment by gstrauss** [comment]
@ndilieto a more generic solution was committed in #5426

**Comment by ndilieto** [comment]
Ah ok, that will do the job nicely.
