### ISSUE TITLE
Cannot access Mbedtls API Documentation from the website

### ISSUE THREAD

**Issue by ahmedibrahim6** [Mbed-TLS/mbedtls#5955]
I am trying to access the MbedTLS documentation from [tls.mbed.org](https://tls.mbed.org/) for more than one week but it seems it is not currently working. Can someone explain what is wrong there?

**Comment by manup** [comment]
The website appears to be down for some days now.
As workaround the docs can be locally with Doxygen.

**Comment by gilles-peskine-arm** [comment]
We are aware of the problem, but we don't know when it will be fixed. In the meantime, please use a cached version, for example [archive.org](https://web.archive.org/web/*/https://tls.mbed.org/). The site at tls.mbed.org is mostly no longer updated: now all the activity is on GitHub.

For the reference documentation, please build the documentation in your copy with `make apidoc` so you'll have the documentation for your version and your configuration. (If you need the documentation of the full library including all build options, you can run `scripts/apidoc_full.sh` .)

**Comment by davidhorstmann-arm** [comment]
Closed by #7307. The API documentation is up at:

https://mbed-tls.readthedocs.io/projects/api/en/latest/
