### ISSUE TITLE
FIPS 140-2 certification

### ISSUE THREAD

**Issue by UrsKSec** [Mbed-TLS/mbedtls#5995]
### Suggested enhancement
Get FIPS 140-2 certification

### Justification
Mbed TLS needs this because competition products have this as their main only advantage, e.g. WolfSSL

**Comment by daverodgman** [comment]
Hi - this is not on our roadmap - we don't have plans to do this in the foreseeable future.

**Comment by UrsKSec** [comment]
Sad to see that you don't consider putting it on the roadmap. But okay

**Comment by gilles-peskine-arm** [comment]
A FIPS certification for a library hardly ever has an advantageous cost/benefit ratio. It's a formality if you're selling to the US government, and we aren't selling Mbed TLS to the US government. A third party may include Mbed TLS in a product that's sold to the US government, but then the third party would have to get their own certification, and starting from an already-certified Mbed TLS would hardly save any preparation work.

You can easily configure Mbed TLS to only use FIPS-approved mechanisms. Mbed TLS implements the one security requirement of FIPS 140 level 1, which is to clear sensitive material after use (zeroization). Mbed TLS provides self-test functions for cryptographic mechanisms. These are the only features I can think of that live inside the crypto library and that helps for FIPS 140 level 1. Offhand I don't remember what levels 2+ require (I'm more familiar with CC than FIPS 140). So I think Mbed TLS is already doing everything that's reasonable to help third parties who want to use it in a FIPS 140 certified product.
