### ISSUE TITLE
Include Montgomery moduli directly

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6027]
Currently the moduli for Montgomery curves are calculated on the fly:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L4649-L4652
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L4655-L4658
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L4700-L4705
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L4714-L4718

The task is to remove these computations and include them directly, similar to how it is done with NIST curves:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L545-L550
(use [ecp_mpi_load()](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.2.1/library/ecp_curves.c#L4515-L4520)).

No need to add new tests, it is enough if existing tests pass.

**Comment by minosgalanakis** [comment]
Relevant [PR6939](https://github.com/Mbed-TLS/mbedtls/pull/6939)
