### ISSUE TITLE
Building v3.2.1 on ARM fails

### ISSUE THREAD

**Issue by Aethedor** [Mbed-TLS/mbedtls#6089]
### Summary
I tried to build the Hiawatha webserver, which uses mbed TLS, on a Raspberry Pi v4. It fails with errors like these:

/tmp/ccWJfJUb.s:3868: Error: unexpected character `w' in type specifier
/tmp/ccWJfJUb.s:3868: Error: bad instruction `ldr.w r5,[r3]'
/tmp/ccWJfJUb.s:3870: Error: unexpected character `w' in type specifier
/tmp/ccWJfJUb.s:3870: Error: bad instruction `str.w r5,[r3],#4'

### System information

Mbed TLS version (number or commit id): 3.2.1
Operating system and version: Raspberry Pi v4
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
Compliation successful

### Actual behavior
Compilation failed

### Steps to reproduce
Compile Hiawatha v11.2 on a Raspberry Pi.
https://www.hiawatha-webserver.org/files/hiawatha-11.2.tar.gz

### Additional information
In bn_mul.h, I changed ldr.w and str.w to ldr and str at line 752 and further. That solved my issue.

**Comment by tom-cosgrove-arm** [comment]
Could you please give us output of `cat /etc/os-release`, `uname -a` and `cc --version`?

**Comment by Aethedor** [comment]
**/etc/os-release:**
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**uname -a:**
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

**cc --version:**
cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Aethedor** [comment]
Never mind this issue. Got it fixed. My bad.

**Comment by tom-cosgrove-arm** [comment]
Hmm, actually this is an issue when compiling with optimisation (i.e. anything > `-O0` on Armv7 with older gcc

**Comment by tom-cosgrove-arm** [comment]
Yes, these changes are optimisations introduced in April 2022 in #5706

**Comment by hanno-arm** [comment]
Thanks for the report @Aethedor.

A change was made to a piece of assembly under the assumption that this assembly would be used on M-profile systems only, but strangely (I don't know if intentionally, initially), it was also used and valid on Armv7-A systems. The change, however, was strictly M-profile only, and that's what's leading to the issue you're seeing.

I guess the solution will be to reintroduce an A-class version of the code under correct compile time guards.

**Comment by Aethedor** [comment]
If you have a patch that needs testing, let me know.

**Comment by hanno-arm** [comment]
@Aethedor Can you check https://github.com/Mbed-TLS/mbedtls/pull/6090 please?

**Comment by Aethedor** [comment]
@hanno-arm The changes to bn_mul.h are as I mentioned in the first post. That works for me. Good to hear that my manual patch is indeed the right one.

**Comment by hanno-arm** [comment]
@Aethedor This is rather a workaround than the final solution -- the suffixes serve performance optimization purposes for M-class code, but compiler support seem brittle so we're removing them for now.

**Comment by valord577** [comment]
Do you try to use ARM instruction mode? @tom-cosgrove-arm @Aethedor @hanno-arm 

When I build for `Android armeabi-v7a`, I can build successfully by adding flag `-D ANDROID_ARM_MODE=arm`.

If you use LLVM/GNU compiler toolsets, I think you can add `-march=armv7-a` to your `CFLAGS`.
