### ISSUE TITLE
MbedTLS-3.1.0 build fails with WDK tool set

### ISSUE THREAD

**Issue by 9SIVA** [Mbed-TLS/mbedtls#6105]
### Summary
 Reg : MbedTLS-3.1.0 build was failing when I build with WDK tool set. #6063.
Added under addition information section.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Additional information
As we discussed, in #6063 query to update the WDK patches in MbedTLS-3.1.0, can you please provide me any support to update the patch for WDK build environment issue.

**Comment by tom-cosgrove-arm** [comment]
As @gabor-mezei-arm said on #6063, we don't support WDK-7600 - see [the list of toolchains we do support](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.1.0/README.md#tool-versions).

You will need to create the patch yourself, or find someone in the community who can do this. If you ask on the [Mbed TLS mailing list](https://www.trustedfirmware.org/projects/mbed-tls) you might find someone who can help.

Once you have this, raise a PR. If it is clear that the PR won't break anything we do support, we will consider merging it.

Please don't raise more issues about this.
