### ISSUE TITLE
Driver-only hashes: TLS 1.3

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6132]
TLS 1.3 unconditionally uses PSA Crypto for all of its crypto computations, except the ones where the code is shared with TLS 1.2 (running handshake hash, record encryption/decryption) where it use of PSA is controlled by the macro `MBEDTLS_USE_PSA_CRYPTO`. So, when this macro is enabled, TLS 1.3 should have no problem building and running in a configuration where all hashes are provided by drivers; this task is about achieving that, with appropriate testing.

The parts of the code that use PSA unconditionally should use `PSA_WANT_ALG_SHA_xxx` to check if a hash is available; the parts that use if conditionally on `USE_PSA` should use `MBEDTLS_HAS_SHA_xxx_VIA_MD_OR_PSA_BASED_ON_USE_PSA`, see `library/legacy_or_psa.h`.

- [x] Fix guards in `ssl_tls13_generic.c` - `MBEDTLS_HAS_SHA_xxx_VIA_MD_OR_PSA_BASED_ON_USE_PSA` should be used in parts governed by `USE_PSA`.
- [x] Enable TLS 1.3 (and related options, see `component_test_tls13`) in `component_test_psa_crypto_config_accel_hash_use_psa` in `all.sh`
- [x] Fix any failures that may arise
- [x] Check that there is no test gap when comparing that component to a similar software-based config, or when comparing the default & full configs before and after this PR. (See similar item in #6128, and in #6130 if it has been done before this.)

**Depends on:** #6128

**Comment by mprse** [comment]
I analysed the code and I'm not sure if I'm going in the right direction as the changes from my perspective are not fully consistent with the task description:

- `ssl_tls13_generic.c`: hash guards are used only in function `mbedtls_ssl_reset_transcript_for_hrr()`. We have guards for `MBEDTLS_SHA256_C` and `MBEDTLS_SHA384_C` and if specific hash is available then based on `MBEDTLS_USE_PSA_CRYPTO` it is handled using PSA or low level function (usually we did the other way around if legacy way is available then use it otherwise use psa).
As far as I understand I should use `MBEDTLS_HAS_ALG_SHA_xxx_VIA_LOWLEVEL_OR_PSA` instead `MBEDTLS_SHAxxx_C` and then dispatch based on `MBEDTLS_USE_PSA_CRYPTO` (as it is done now)?
- configuration requirements for `MBEDTLS_SSL_PROTO_TLS1_3` are currently:
  `MBEDTLS_HKDF_C and (MBEDTLS_SHA256_C or MBEDTLS_SHA384_C) and MBEDTLS_PSA_CRYPTO_C`.
  It seems that now `MBEDTLS_SHA256_C or MBEDTLS_SHA384_C` are optional because `MBEDTLS_PSA_CRYPTO_C` is mandatory?
- configuration requirement for `MBEDTLS_HKDF_C` is `MBEDTLS_MD_C` and it looks like we will have to first provide psa implementation for HKDF functions (also API will have to be changed as `mbedtls_md_info_t` is used as functions parameter) and then change the requirements to `MBEDTLS_MD_C or MBEDTLS_PSA_CRYPTO_C`?

**Comment by mpg** [comment]
Ah, you're raising tough questions. The case of TLS 1.3 is hard because most parts are using PSA unconditionally, but some parts (those common with TLS 1.2) dispatch based on `USE_PSA` and they're not always easy to identify in the code.

Let me start with the last one:

> configuration requirement for `MBEDTLS_HKDF_C` is `MBEDTLS_MD_C` and it looks like we will have to first provide psa implementation for HKDF functions (also API will have to be changed as `mbedtls_md_info_t` is used as functions parameter) and then change the requirements to `MBEDTLS_MD_C or MBEDTLS_PSA_CRYPTO_C`?

TLS 1.3 no longer depends on `MBEDTLS_HKDF_C` since https://github.com/Mbed-TLS/mbedtls/pull/5838 - looks like in that PR we forgot to update the dependency. I think the correct dependency is now `PSA_WANT_ALG_HKDF_EXTRACT and PSA_WANT_ALG_HKDF_EXPAND`. We should fix this now. (And we don't have to change anything inside `hkdf.c`.)

That was the easy one, let me think a bit more about the other two before I reply :)

**Comment by mpg** [comment]
> * `ssl_tls13_generic.c`: hash guards are used only in function `mbedtls_ssl_reset_transcript_for_hrr()`. We have guards for `MBEDTLS_SHA256_C` and `MBEDTLS_SHA384_C` and if specific hash is available then based on `MBEDTLS_USE_PSA_CRYPTO` it is handled using PSA or low level function (usually we did the other way around if legacy way is available then use it otherwise use psa).
>       As far as I understand I should use `MBEDTLS_HAS_ALG_SHA_xxx_VIA_LOWLEVEL_OR_PSA` instead `MBEDTLS_SHAxxx_C` and then dispatch based on `MBEDTLS_USE_PSA_CRYPTO` (as it is done now)?

I agree, except I think we should use `MBEDTLS_HAS_ALG_SHA_xxx_VIA_MD_OR_PSA_BASED_ON_USE_PSA` instead, because (1) we dispatch based on `USE_PSA` and (2) that's what controls the presence of the `fin_shaXXX_psa` fields in the handshake structure (`ssl_misc.h`).



> * configuration requirements for `MBEDTLS_SSL_PROTO_TLS1_3` are currently:
>       `MBEDTLS_HKDF_C and (MBEDTLS_SHA256_C or MBEDTLS_SHA384_C) and MBEDTLS_PSA_CRYPTO_C`.
>       It seems that now `MBEDTLS_SHA256_C or MBEDTLS_SHA384_C` are optional because `MBEDTLS_PSA_CRYPTO_C` is mandatory?

I think still need a way to indicate that we need those algs - it's possible to build with `PSA_CRYPTO_C` and only SHA-512, and we can't have TLS 1.3 in such a build. So, I think what we want is: `(PSA_WANT_ALG_SHA_256 or PSA_WANT_ALG_SHA_348) and (MBEDTLS_USE_PSA_CRYPTO or (MBEDTLS_MD_C and (MBEDTLS_SHA256_C or MBEDTLS_SHA384_C))))`.

Reasoning: we need SHA-256 or SHA-384 via PSA because they're used by HKDF which is now always done via PSA. If in addition to that `USE_PSA` is enabled, then everything is done via PSA so that's enough. Otherwise, we need the software implementation of SHA-256 or SHA-384, plus `MD_C` because we're using a `VIA_MD_OR_PSA_BASED_ON_USE_PSA` as discussed above.

Strictly speaking, we could have a more fine-grained dependency here by introducing a new family of macros `VIA_LOWLEVEL_OR_PSA_BASED_ON_USE_PSA`, but we already have more families of dependency macros than we'd like, and since before this work we had a hard dependency on `MD_C` anyway, this is still a strict improvement: now we only require `MD_C` when `USE_PSA` is disabled. Also, the priority (what we get asked by users and partners) is to improve builds based on PSA. For "legacy" builds (not based on PSA), maintaining the status quo is acceptable.

Do you think that makes sense? Dependencies are always tricky, but they're probably at their trickiest here, with the fact that part of TLS 1.3 always uses PSA, and part decides based on `USE_PSA`, so we need to consider so many different cases.

**Comment by mprse** [comment]
> TLS 1.3 no longer depends on MBEDTLS_HKDF_C since https://github.com/Mbed-TLS/mbedtls/pull/5838

Yes, I wasn't sure why it is still needed. This will make thinks easier.

> Do you think that makes sense? Dependencies are always tricky, but they're probably at their trickiest here, with the fact that part of TLS 1.3 always uses PSA, and part decides based on USE_PSA, so we need to consider so many different cases.

Thanks for all hints. It make sense. I will try follow your hints now and will see the results soon.

**Comment by mprse** [comment]
>  So, I think what we want is: (PSA_WANT_ALG_SHA_256 or PSA_WANT_ALG_SHA_348) and (MBEDTLS_USE_PSA_CRYPTO or (MBEDTLS_MD_C and (MBEDTLS_SHA256_C or MBEDTLS_SHA384_C)))).

Can `PSA_WANT_xxx` symbols be used in `check_config.h`? I don't see other occurrences. 

```
In file included from ../include/mbedtls/build_info.h:84,
                 from common.h:26,
                 from error.c:20:
../include/mbedtls/check_config.h:768:2: error: #error "MBEDTLS_SSL_PROTO_TLS1_3 defined, but not all prerequisites"
  768 | #error "MBEDTLS_SSL_PROTO_TLS1_3 defined, but not all prerequisites"
```

`config_psa.h` with  `PSA_WANT_xxx` symbols is included in `build_info.h` only if `MBEDTLS_PSA_CRYPTO_CONFIG` is defined and it seems in full config it is disabled.

**Comment by gilles-peskine-arm** [comment]
> Can PSA_WANT_xxx symbols be used in check_config.h?

I don't see why not. We just have to be careful how we fiddle with inclusions. If  `MBEDTLS_PSA_CRYPTO_CONFIG` is active, `mbedtls/config_psa.h` is included before `check_config.h`, and it has to since `mbedtls/config_psa.h` influences `MBEDTLS_xxx` definitions. If `MBEDTLS_PSA_CRYPTO_CONFIG` is disabled, then `mbedtls/config_psa.h` influences `PSA_xxx` definitions, so it would have to now be included before `check_config.h` as well. But we shouldn't bring `PSA_xxx` definitions into the namespace unless `MBEDTLS_PSA_CRYPTO_C` or `MBEDTLS_PSA_CRYPTO_CLIENT` is enabled. (For example, you should be able to use Mbed TLS 3.x alongside an independent implementation of PSA crypto, as long as you don't activate `MBEDTLS_PSA_CRYPTO_C`. It's not something we'll support in Mbed TLS 4, but right now it's allowed.)

So changing the inclusion of `mbedtls/config_psa.h` in `build_info.` to this should work:
```
/* Make sure all configuration symbols are set before including check_config.h,
* even the ones that are calculated programmatically. */
#if defined(MBEDTLS_PSA_CRYPTO_CONFIG) /* PSA_WANT_xxx influences MBEDTLS_xxx */ || \
    defined(MBEDTLS_PSA_CRYPTO_C) /* MBEDTLS_xxx influences PSA_WANT_xxx */
#include "mbedtls/config_psa.h"
#endif
```

**Comment by mpg** [comment]
I think what Gilles suggested should work, and is the right way of doing it. However if we run into issues, as a backup plan it's always possible to put the check in `ssl_tls13_generic.c`, where we clearly have all the symbols available already, but that's less clean, so let's go for `check_config.h` first and only keep that in mind in case of unforeseen issues.

**Comment by AndrzejKurek** [comment]
Why not simply move it to `check_crypto_config.h`, like so: https://github.com/AndrzejKurek/mbedtls/commit/1310c6b727f7e1cfe88bbab8307ac88c3492875b? This is already a designated place to check other PSA-related defines, and requires no change in includes? Am I missing something?

**Comment by mprse** [comment]
> Why not simply move the checks to check_crypto_config.h, like so: https://github.com/AndrzejKurek/mbedtls/commit/1310c6b727f7e1cfe88bbab8307ac88c3492875b? This is already a designated place to check other PSA-related defines, and requires no change in includes? Am I missing something?

As `MBEDTLS_PSA_CRYPTO_C` is mandatory maybe this is these checks can be moved to `check_crypto_config.h`.
It seems that `MBEDTLS_xxx` symbols can be used in `check_crypto_config.h`. For TLS.1.2 we have:

```
check_config.h

#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && !defined(MBEDTLS_USE_PSA_CRYPTO) && \
    !( defined(MBEDTLS_SHA1_C) || defined(MBEDTLS_SHA256_C) || defined(MBEDTLS_SHA512_C) )
#error "MBEDTLS_SSL_PROTO_TLS1_2 defined, but not all prerequisites"
#endif

check_crypto_config.h

#if defined(MBEDTLS_SSL_PROTO_TLS1_2) && defined(MBEDTLS_USE_PSA_CRYPTO) && \
    !( defined(PSA_WANT_ALG_SHA_1) || defined(PSA_WANT_ALG_SHA_256) || defined(PSA_WANT_ALG_SHA_512) )
#error "MBEDTLS_SSL_PROTO_TLS1_2 defined, but not all prerequisites"
#endif

```

It seems it should be possible to do the same for TLS 1.3:

```
check_config.h

#if defined(MBEDTLS_SSL_PROTO_TLS1_3) && ( !defined( defined(MBEDTLS_PSA_CRYPTO_C) || ( !defined(MBEDTLS_USE_PSA_CRYPTO) &&   \
    !( ( defined(MBEDTLS_MD_C) && ( defined(MBEDTLS_SHA256_C) || defined(MBEDTLS_SHA384_C) ) ) ) ) ) )
#error "MBEDTLS_SSL_PROTO_TLS1_3 defined, but not all prerequisites"
#endif



check_crypto_config.h

#if defined(MBEDTLS_SSL_PROTO_TLS1_3) && \
        !( defined(MBEDTLS_USE_PSA_CRYPTO) && defined(PSA_WANT_ALG_HKDF_EXTRACT) && defined(PSA_WANT_ALG_HKDF_EXPAND) )
#error "MBEDTLS_SSL_PROTO_TLS1_3 defined, but not all prerequisites"
#endif

#if defined(MBEDTLS_SSL_PROTO_TLS1_3) && defined(MBEDTLS_USE_PSA_CRYPTO) &&   \
    !( ( defined(PSA_WANT_ALG_SHA_256) || defined(PSA_WANT_ALG_SHA_348) )  )
#error "MBEDTLS_SSL_PROTO_TLS1_3 defined, but not all prerequisites"
#endif

```

**Comment by AndrzejKurek** [comment]
> I'm afraid there's a problem: in the medium/long term, we're going to separate the crypto library from the X.509 & TLS libraries. So, we should really avoid introducing references to TLS or X.509 from any crypto file, as such "upwards references" run against the plan of making the crypto library its own independent things.

I wasn't aware that such separation was planned and I thought of the `check_crypto_config.h` file as a better place to add PSA checks, as according to its description, it's a place for:
`* \brief Consistency checks for PSA configuration options`.

> What's the problem with the approach suggested by Gilles [above](https://github.com/Mbed-TLS/mbedtls/issues/6132#issuecomment-1235442374)?

Comparing this solution to Gilles` one - I thought that the latter was more of a workaround, but taking this separation into consideration - sure, I'm OK with it :)
