### ISSUE TITLE
Mbed TLS coding standards link is broken

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#6148]
https://github.com/Mbed-TLS/mbedtls/blob/development/CONTRIBUTING.md#coding-standards mentions https://tls.mbed.org/kb/development/mbedtls-coding-standards but this link is broken.
Following https://developer.trustedfirmware.org/w/mbed-tls/:
- [Old Mbed TLS website](https://tls.mbed.org/)
- Documentation: [Mbed TLS API Reference](https://tls.mbed.org/api); [Knowledge base](https://tls.mbed.org/kb); [Dev corner](https://tls.mbed.org/dev-corner);

All redirect to the same page, thus it's impossible to get to the coding standards.

**Comment by gilles-peskine-arm** [comment]
While we work on fixing this, please use the [Wayback Machine](https://web.archive.org/web/20220605163652/https://tls.mbed.org/) to access old website content such as the [coding standards](https://web.archive.org/web/20220119131920/https://tls.mbed.org/kb/development/mbedtls-coding-standards).

@bensze01 Can we make an emergency fix where any URL on `tls.mbed.org` redirects to the wayback machine, rather to the home page of the new site?

**Comment by AndrzejKurek** [comment]
@bensze01 - could you please update the issue with information about what has been fixed already? I can see that https://tls.mbed.org/kb/development/mbedtls-coding-standards now works.

**Comment by gilles-peskine-arm** [comment]
So far, we've added knowledge base articles and security advisories to the new site, and redirections from their old URLs should be working.

**Comment by davidhorstmann-arm** [comment]
This link has since been updated, closing.
