### ISSUE TITLE
status of Mbedtls EdDSA support request with ed25519/ed448 curve

### ISSUE THREAD

**Issue by xzt777** [Mbed-TLS/mbedtls#6166]
### Suggested enhancement
When I wanted to use the ED25519 curve, I found that the mbedtls development branch had no relevant implementation, so I wanted to know how the current mbedtls considered the API of EdDSA, what was the maintenance status and related plan, and why EdDSA had not been implemented before. Is this stuff unimportant or is there an alternative?

I see that PR #5819 is under review. May I ask whether this PR is expected to be integrated into development branch.

**Comment by yanesca** [comment]
Hi @xzt777 , it is being reviewed and we would like to integrate it into the development branch.

That said, that PR alone won't provide full EdDSA support yet. You can see the work needed for that and follow the progress in the corresponding epic:
https://github.com/orgs/Mbed-TLS/projects/1#column-17950143

EdDSA is pencilled in for early next year:
https://developer.trustedfirmware.org/w/mbed-tls/roadmap/
(This is just a vague estimate, and could easily slip or be de-prioritised.)

We usually prefer to discuss questions like this on the mailing list:  [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org), could you please in the future post your questions there?

**Comment by yanesca** [comment]
I hope that is helpful. If I didn't manage to answer your question, or if you have followup questions, could you please ask them on the mailing list ([mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org))?

**Comment by xzt777** [comment]
Hi @yanesca , thanks for such detailed information sharing about the plan of EdDSA,I will further discuss this topic with you via email.
