### ISSUE TITLE
quic feature consultation

### ISSUE THREAD

**Issue by xcgj** [Mbed-TLS/mbedtls#6178]
### Suggested enhancement
QUIC

### Justification

I found that mbedtls has integrated tls1.3 in the recent versions. But in the latest version I did not find the support for the quic, which is a feature that relies on tls1.3 and its protocols is introduced in documents such as rfc9000.
I found an old discussion about the quic feature: https://github.com/Mbed-TLS/mbedtls/issues/4731. But there doesn't seem to be any further progress in the end.
I continued to track @hanno-arm's project (https://github.com/hannestschofenig/mbedtls), and found that @lhuang04 had initiated a quic feature pull request to @hanno-arm's project, but the pull request was not applied since 12 months ago. I don't know if there is a problem with the patch or some other reasons leading the patch not applied.
I want to switch the openssl library to mbedtls library in my program, but the lack of quic feature hinders this task, so I want to know if there is any plan to integrate the quic feature in the recent future mbedtls version?

**Comment by daverodgman** [comment]
QUIC is something we have had interest in before, and may look at supporting in Mbed TLS in the future. We have a bunch of tasks related to the TLS messaging layer (the MPS tasks here https://github.com/orgs/Mbed-TLS/projects/1#column-17950144 ) which are a pre-requisite before we could look at QUIC. So it is unlikely we would get to this in the near future (definitely not in 2022).

@ronald-cron-arm might be able to give a more detailed answer, or you are welcome to join our regular community call ( https://www.trustedfirmware.org/meetings/mbed-tls-technical-forum/ ) to discuss this further

**Comment by xcgj** [comment]
got it.Thank you!

**Comment by daverodgman** [comment]
Closing this as it's more a discussion than an issue - please carry on the discussion via the mailing list or community call if you'd like to discuss further.
