### ISSUE TITLE
Enable runtime configuration of ciphersuites and elliptic curves using strings

### ISSUE THREAD

**Issue by hardfalcon** [Mbed-TLS/mbedtls#619]
Hi, it would be really great of there was a possibility to configure things like the list of enabled ciphersuites or the list of elliptic curves (both the suites/curves and the order in which they are advertised) using a string.

This would enable server software (webservers and the like) to let advanced users configure these parameters themselves while still being able to use the binary packages that their distribution ships.

It wouldn't have to be as complicated as OpenSSL's "ciphers" notation, just a simple string containing the "description" names from IANA's TLS parameter list, separated by colons or spaces, would be enough.

https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

**Comment by tom-daubney-arm** [comment]
This isn't something we want to implement in the near future.
