### ISSUE TITLE
Undefined MBEDTLS_SELF_TEST blocks loading platform.h

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#6196]
### Summary

The commit da0913ba6b3ddd5708189df8115d85bbd0ff2be3 added calls of `mbedtls_setbuf` function for improved security.
`mbedtls_setbuf` is defined in `platform.h` file.
However, at least in `ctr_drbg.c`, `entropy.c` and `hmac_drbg.c` this header file would not be included unless `MBEDTLS_SELF_TEST` was defined in `mbedtls_config.h`
Mbed TLS version 3.2.1 and later were affected.

### System information

Visual Studio 2022.

### Expected behavior

The library should  be usable without self test code (as it was previously).

### Actual behavior

`mbedtls_setbuf` becomes an unresolved external.

**Comment by gilles-peskine-arm** [comment]
Thanks! This has already been reported in https://github.com/Mbed-TLS/mbedtls/issues/6118.
