### ISSUE TITLE
Can't compile 3.2.1 on xcode xcrun --sdk iphoneos15.5 clang++

### ISSUE THREAD

**Issue by codeservice** [Mbed-TLS/mbedtls#6217]
### Summary
Can't compile 3.2.1 on xcode xcrun --sdk iphoneos15.5 clang++ for ios (no issue when compiling library for Mac os, only ios issue)
Older version 3.1.0 compiles without problem.

ERROR:
ssl_tls12_server.c 
&lt;inline asm>:4:2: error: invalid instruction, any one of the following would fix this:
        ldr.w    r6, [r8,  #-4]                
        ^
cannot compile inline asm
<inline asm>:4:22: note: too few operands for instruction
                            ^
note: cannot compile inline asm
<inline asm>:4:15: note: invalid operand for instruction
                     ^
<inline asm>:5:2: error: invalid instruction, any one of the following would fix this:
        ldr.w    r1, [r10, #-4]                
<inline asm>:5:22: note: too few operands for instruction
<inline asm>:5:15: note: invalid operand for instruction
<inline asm>:8:2: error: invalid instruction, any one of the following would fix this:
        str.w    r3, [r10, #-8]                
<inline asm>:8:22: note: too few operands for instruction
<inline asm>:8:15: note: invalid operand for instruction
<inline asm>:9:2: error: invalid instruction, any one of the following would fix this:
        str.w    r1, [r10, #-4]                
<inline asm>:9:22: note: too few operands for instruction
<inline asm>:9:15: note: invalid operand for instruction
<inline asm>:13:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:13:22: note: too few operands for instruction
<inline asm>:13:15: note: invalid operand for instruction
<inline asm>:14:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:14:22: note: too few operands for instruction
<inline asm>:14:15: note: invalid operand for instruction
<inline asm>:17:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:17:22: note: too few operands for instruction
<inline asm>:17:15: note: invalid operand for instruction
<inline asm>:18:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:18:22: note: too few operands for instruction
<inline asm>:18:15: note: invalid operand for instruction
<inline asm>:22:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:22:22: note: too few operands for instruction
<inline asm>:22:15: note: invalid operand for instruction
<inline asm>:23:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:23:22: note: too few operands for instruction
<inline asm>:23:15: note: invalid operand for instruction
<inline asm>:26:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:26:22: note: too few operands for instruction
<inline asm>:26:15: note: invalid operand for instruction
<inline asm>:27:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:27:22: note: too few operands for instruction
<inline asm>:27:15: note: invalid operand for instruction
<inline asm>:31:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:31:22: note: too few operands for instruction
<inline asm>:31:15: note: invalid operand for instruction
<inline asm>:32:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:32:22: note: too few operands for instruction
<inline asm>:32:15: note: invalid operand for instruction
<inline asm>:35:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:35:22: note: too few operands for instruction
<inline asm>:35:15: note: invalid operand for instruction
<inline asm>:36:2: error: invalid instruction, any one of the following would fix this:
<inline asm>:36:22: note: too few operands for instruction
<inline asm>:36:15: note: invalid operand for instruction
<inline asm>:4:2: error: invalid instruction, any one
 of the following would fix this:
        ldr.w    r3, [r10,  #-4]                
<inline asm>:4:23: note: too few operands for instruction
                             ^
        ldr.w    r2, [r0, #-4]                
<inline asm>:5:21: note: too few operands for instruction
                           ^
        str.w    r6, [r0, #-8]                
<inline asm>:8:21: note: too few operands for instruction
        str.w    r2, [r0, #-4]                
<inline asm>:9:21: note: too few operands for instruction
<inline asm>:13:23: note: too few operands for instruction
<inline asm>:14:21: note: too few operands for instruction
<inline asm>:17:21: note: too few operands for instruction
<inline asm>:18:21: note: too few operands for instruction
<inline asm>:22:23: note: too few operands for instruction
<inline asm>:23:21: note: too few operands for instruction
<inline asm>:26:21: note: too few operands for instruction
<inline asm>:27:21: note: too few operands for instruction
<inline asm>:31:23: note: too few operands for instruction
<inline asm>:32:21: note: too few operands for instruction
<inline asm>:35:21: note: too few operands for instruction
<inline asm>:36:21: note: too few operands for instruction
<inline asm>:4:2: error: invalid instruction, any one of the following would fix this:
        ldr.w    r9, [r5,  #-4]                
        ldr.w    r11, [r3, #-4]                
<inline asm>:5:16: note: invalid operand for instruction
                      ^
        str.w    r2, [r3, #-8]                
        str.w    r11, [r3, #-4]                
<inline asm>:9:16: note: invalid operand for instruction
<inline asm>:14:16: note: invalid operand for instruction
<inline asm>:18:16: note: invalid operand for instruction
<inline asm>:23:16: note: invalid operand for instruction
<inline asm>:27:16: note: invalid operand for instruction
<inline asm>:32:16: note: invalid operand for instruction
<inline asm>:36:16: note: invalid operand for instruction
        ldr.w    r2, [r4,  #-4]                
<inline asm>:4:22: note: too few op
erands for instruction
        ldr.w    r10, [r6, #-4]                
        str.w    r5, [r6, #-8]                
        str.w    r10, [r6, #-4]                
        ldr.w    r4, [r0,  #-4]                
        ldr.w    r4, [r0,  #-4]              
  
        ldr.w    r3, [r11, #-4]                
        str.w    r5, [r11, #-8]                
        str.w    r3, [r11, #-4]                
80 errors generated.
Build failed

### System information

Mbed TLS version (number or commit id): 3.2.1
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by gilles-peskine-arm** [comment]
I believe this is the same issue as https://github.com/Mbed-TLS/mbedtls/issues/6089. We just merged the [fix](https://github.com/Mbed-TLS/mbedtls/issues/6089) into the [development](https://github.com/Mbed-TLS/mbedtls) branch.

**Comment by tom-cosgrove-arm** [comment]
Yes, agreed, the fix is in #6090
