### ISSUE TITLE
Bignum: extract core_sub from the prototype

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6221]
The task is to extract `core_sub` from the [prototype](https://github.com/hanno-arm/mbedtls/tree/ecp_prototype):
https://github.com/hanno-arm/mbedtls/blob/ecp_prototype/library/bignum_core.c#L165-L179

There should be separate commits containing the code from the prototype, with the absolute minimum of modifications that make the library compile. (It is Ok if this function is not called at all at this point.) These commits should have Hanno as the author (git commit --author="Hanno Becker <hanno.becker@arm.com>")

The function declaration should go to `library/bignum_core.h` and implementation to `library/bignum_core.c`.

The task includes making the legacy Bignum functions call the extracted functions where the functionality is duplicated. (To minimise impact on code size.)

The prototype is too macro heavy. Most new macros should be expanded/removed or replaced with static functions if possible. (Pre-existing macros should not be touched.) The macro `MPI_CORE` should expand to `mbedtls_mpi_core_ ## func ##` instead of `mbedtls_mpi_core_ ## func ## _minimal`.

**Comment by tom-cosgrove-arm** [comment]
This had to be taken as part of #6083 to complete #6015
