### ISSUE TITLE
The mbedtls_ecdh_compute_shared generate keys is not the same as java

### ISSUE THREAD

**Issue by cucibala** [Mbed-TLS/mbedtls#6266]
PriKey: cBL9Xt9RusDw6XaFiONf4kGG1+73kORL7iDcZIvAOyg=
pubKey: BEqcKiryd983WcG9uxfkhQu6JbL1AU0wf5AgXHVb3fqXOYJIO+nbIx+EiApyg14ebBbunDrJogoTIQdeCYwrZ80=
ShareKey in c++: 3VAHrN6uC4WrfGn6reu5OdykgJejA0Xl3jztT7ckMg==
ShareKey in java: AN1QB6zerguFq3xp+q3ruTncpICXowNF5d487U+3JDI=

I don't know what causes this, and not every pair of public and private keys will generate a different share key, this question is accidental, is there something special about this pair of public and private keys

**Comment by davidhorstmann-arm** [comment]
Can you please share a summary of your code so that we can try to reproduce the issue? Which Java library are you using to compute shared secrets?

**Comment by gilles-peskine-arm** [comment]
The difference between the C++ ShareKey and the Java data is that the C++ ShareKey is that the Java ShareKey has a leading null bytes and that leading null byte is missing from the C++ ShareKey.

When you convert the ECDH shared secret from a number to a string, you should treat it as a fixed-size string: n/8 bytes for an n-bit curve, e.g. 32 bytes for p256r1. The first byte will be zero almost 1/256 of the times. Don't treat that case specially: it can cause vulnerabilities even if the code is functionally correct.

After `mbedtls_ecdh_compute_shared(grp, z, …)`, you should typically call `mbedtls_mpi_write_binary(z, shared_secret, n)` where `n` is determined from the key size (`n = (grp->nbits + 7) / 8`). Do not strip leading zeros.

@BenBaratte For the TLS session secret calculation, with ECDH, you don't treat leading zeros specially. You only do that for FFDH, which was a protocol design mistake (hey, it was a century ago) and led to a [vulnerability](https://raccoon-attack.com/).

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because it is a support request, and the problem is in the code that's calling Mbed TLS, not in Mbed TLS.
