### ISSUE TITLE
Split bignum tests and re-do in python framework

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#6274]
A couple of significant changes need to be made to the bignum tests:

* The tests for bignum functions should be split into test cases by module (e.g. `bignum_core`, `bignum_mod_raw`, etc).
* Whenever possible, test cases should be generated automatically.

We have [a PR for Python code to generate the test cases](https://github.com/Mbed-TLS/mbedtls/pull/6093). Once it is merged, the split can be performed, and the test cases for at least the following bignum functions should be revisited:

* `mbedtls_mpi_core_add_if()`
* `mbedtls_mpi_core_sub()`
* `mbedtls_mpi_core_mla()`
* `mbedtls_mpi_core_montmul()`

**Comment by yanesca** [comment]
https://github.com/Mbed-TLS/mbedtls/pull/6083 might be merged with some reservations regarding the test cases. The hope is that having automated test case generation in python will make them easier to review.

Either way, as part of this task, the test cases for https://github.com/Mbed-TLS/mbedtls/pull/6083 need to be reviewed with full scrutiny, like they were newly added here.

**Comment by yanesca** [comment]
These tests were generated and the scripts and the approach can be found in these commit messages: https://github.com/Mbed-TLS/mbedtls/pull/6083/commits/0cc78658c3728a318478e6777cfd683b7df62e29 https://github.com/Mbed-TLS/mbedtls/pull/6083/commits/2a65b8592856430b5d8c837d88d5699195788705 https://github.com/Mbed-TLS/mbedtls/pull/6083/commits/659c84add930ba9529fa3858aba977a7c37b06ef https://github.com/Mbed-TLS/mbedtls/pull/6083/commits/f334d9622b4c327c56ff081c39fd4b5cb3a92753

The tests might have changed at later commits, but the generating principles and steps are a good starting point.
