### ISSUE TITLE
Fix mbedtls_ssl_is_handshake_over() in TLS 1.3 case

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#6312]
`mbedtls_ssl_is_handshake_over` is based on the comparison of `ssl->state` with MBEDTLS_SSL_HANDSHAKE_OVER. In TLS 1.3 for ticket support some post-handshake states have been added thus the handshake may be over but `ssl->state != MBEDTLS_SSL_HANDSHAKE_OVER`. The purpose of this issue is to fix this.

Note: there are probably places in the code where currently `mbedtls_ssl_is_handshake_over` is used to actually check that `ssl->state` is MBEDTLS_SSL_HANDSHAKE_OVER and if `mbedtls_ssl_is_handshake_over` is changed to return 1 for other states those calls should be changed (in mbedtls_ssl_handshake() for example).

**Comment by yuhaoth** [comment]
https://github.com/Mbed-TLS/mbedtls/pull/6180#discussion_r977526343 , relative discusses
