### ISSUE TITLE
Enable testing of AEAD drivers with libtestdriver1

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6315]
Currently, driver dispatch for AEAD is only tested using "internal drivers", that is by building with `-DPSA_CRYPTO_DRIVER_TEST` so that calls to AEAD functions are dispatched to the driver defined in `tests/src/drivers/test_driver_aead.c` (which in turns calls library functions).

This is only the first level of testing for driver dispatch, and most areas have a second level of testing: with libtestdriver1. It starts the same, but when we get to driver functions from `test_driver_aead.c`, instead of calling a function from `libmbecrypto.a`, it calls a function from a different, special-purpose library: `libtestdriver1.a`, that has been built independently (from an edited copy of Mbed TLS where all functions have been renamed). This allows testing the case where AEADs are not present in `libmbedcrypto` but only provided by a driver.

This task is to make testing via `libtestdriver1` work for AEADs. The task is done when there is a new component in `all.sh`, similar to `component_test_psa_crypto_config_accel_cipher` (but named `_accel_aead`) where GCM, CCM and ChachaPoly are provided only by libtestdriver1, and it passes.

This will involve expanding `ests/src/drivers/test_driver_aead.c` - other files in the same directory can be used for inspiration.

There's one known bug in driver dispatch code for AEADs (see comment below) which will have to be fixed. It is not unlikely that this task will uncover others.

The test and fixes need to be backported to 2.28. ChangeLog entries should be written for any bugs found that are visible to users.

**Comment by mpg** [comment]
Quoting from Ronald [on Slack](https://arm-ce.slack.com/archives/C01CC4Y1T1P/p1663593817897339?thread_ts=1663584857.633009&cid=C01CC4Y1T1P):

> It seems to me that the code in `psa_driver_get_tag_len` is wrong. First there should be a switch over `operation->id` (like in `psa_driver_wrapper_aead_set_nonce()`) to address the built-in implementation or the driver. Then `psa_driver_get_tag_len` should NOT access the driver context but rather call the driver with a call like `mbedtls_test_transparent_aead_get_tag_len( &operation->ctx.transparent_test_driver_ctx, tag_len )` (again see `psa_driver_wrapper_aead_set_nonce()` as an example).

**Comment by mprse** [comment]
Question to the bug. If we want to add `mbedtls_test_transparent_aead_get_tag_len(  )` function. Should we also add full support for `psa_get_tag_len` function (extending psa crypto API)?

**Comment by mpg** [comment]
Cc @ronald-cron-arm and @gilles-peskine-arm  as discussed in the team meeting - thanks for your help on this!

**Comment by mprse** [comment]
OK, so `psa_driver_get_tag_len()` can be completely removed.
