### ISSUE TITLE
TLS 1.3 client: Add support for early data writing

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#6340]
This issue tracks the addition of the support for writing early data on client side.

What to implement depends on the result #4902 and thus cannot be fully defined yet.
Things we already know they have to be done:

- [ ] Compute the early data transform and switch to it for outbound data after sending the ClientHello

Testing:
The MbedTLS client sends early data as part of a session resumption to an MbedTLS server. The MbedTLS server receives the early data. The handshake may fail if the server is not yet capable of handling early data. 

Depends on: #4902, #6329 and #6339

**Comment by yuhaoth** [comment]
https://github.com/Mbed-TLS/mbedtls/pull/6486#discussion_r1011224116 is discussing the command line change. It should be think about here.

**Comment by tom-cosgrove-arm** [comment]
Reopening as there is still #8760 to go
