### ISSUE TITLE
Add named moduli setup

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6342]
Add a `mbedtls_ecp_modulus_setup()` function to `ecp_curves`. This should take a curve id and an indication whether we want to create the coordinate modulus (P) or the scalar modulus (N).

The implementation should call `mbedtls_mpi_mod_modulus_setup()` and it is the callers responsibility to release any allocated memory by calling `mbedtls_mpi_mod_modulus_free()`. Unit tests should make it sure that this works.

The function should work with all supported curves and it should be tested that the correct moduli are set after calling this function. 

Adding optimised reduction to these moduli is out of scope for this task.

**Comment by minosgalanakis** [comment]
Following up the design discussion tommorow, should that method be static method contained in the `ecp_curves.c` and declared as

~~~~~~
MBEDTLS_STATIC_TESTABLE
int mbedtls_ecp_modulus_setup(...)
~~~~~~

Or should it properly be exposed throught the `ecp.h` interface?

The former seems to be more sensible

**Comment by yanesca** [comment]
Yes, I agree, it should be `MBEDTLS_STATIC_TESTABLE`.

**Comment by minosgalanakis** [comment]
Relevant [PR7044](https://github.com/Mbed-TLS/mbedtls/pull/7044)
