### ISSUE TITLE
Code style change: rebasing script

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6353]
Write a script that takes a git branch and rebases it, applying the [reformatting script](https://github.com/Mbed-TLS/mbedtls/issues/6346) to all commits.

Handle the case where a commit becomes empty.

Provide instructions or companion script or option to verify that the result of applying this script has identical contents to another branch (to review that it was done correctly in a pull request).

**Comment by davidhorstmann-arm** [comment]
Fixed by Mbed-TLS/mbedtls-docs#71.
