### ISSUE TITLE
Add function to fix quasi-reduction

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#6375]
Many optimised reduction routines don't give a canonical (least non-negative) representation, only reduce it to the appropriate limb size. We used to do this adjustment in the `ecp` module.

However according to our new semantic requirement the new Bignum routines need to return a canonical representative. The task is to add a function to  `ecp_curves` that does this step and a unit test to test it:

- The function should take a raw pointer and a modulus as an input and reduce the value at the raw pointer input
- Valid inputs are the same bitlength as the modulus (Optimised reduction routines reduce the result - or will be reducing the result when the refactoring is complete - to the same bitlength as the modulus)
- Eventually we will want to make this constant time, the implementation should take this into account (eg `_sub` and then `_add_if` based on whether there was a carry).

Using this function from optimised reduction routines is out of scope for this task.

**Comment by gilles-peskine-arm** [comment]
Isn't this `ecp_modp` from `ecp.c` (transposed to the new types)? We always call `grp->modp` via this function.

**Comment by yanesca** [comment]
Yes, it serves the same purpose, but is simpler than `ecp_modp()`. With the new fixed width approach we know for sure that the result is <2p and that at most 1 subtraction is enough. `ecp_modp()` needs to loop, because there are more iterations needed.
