### ISSUE TITLE
compile errors when enabling TLS 1.3 without session tickets

### ISSUE THREAD

**Issue by cruxic** [Mbed-TLS/mbedtls#6395]
Compile fails on `development` branch (gcc 11.2.0 on Ubuntu 22.04) if you make these two changes to mbedtls_config.h:

Uncomment:
`#define MBEDTLS_SSL_PROTO_TLS1_3`
Comment-out:
`//#define MBEDTLS_SSL_SESSION_TICKETS`

The first compiler error is trivial to fix, just add a missing const to a function argument.

`ssl_tls.c:3181:50: error: passing argument 2 of ‘ssl_tls13_session_load’ discards ‘const’ qualifier from pointer target type`

However, after fixing this you will get many other errors. I'm trying to configure the library for TLS 1.2 and 1.3 support without session ticket support (reduce attack surface).

**Comment by yuhaoth** [comment]
I think we should add components without `MBEDTLS_SSL_SESSION_TICKETS` in `all.sh`.

**Comment by yuhaoth** [comment]
See #6411.

- [ ] Add test configuration without `MBEDTLS_SSL_SESSION_TICKETS`
