### ISSUE TITLE
Document how to use self signed certificate

### ISSUE THREAD

**Issue by yadavvineet** [Mbed-TLS/mbedtls#6432]
### Need help for usecase - Using self signed certificate hardcoded in code. 
Hi, I am working on extending another library built with MbedTls. This makes use of a self signed certificate which is embedded in the microcontroller while flashing the firmware. This might not be a perfect way, but i wish to understand on how these values are generated. 
Please refer here: https://github.com/pmvr/esp32-u2f-ble/blob/master/u2f.cpp#L14
Line 14-20

I am not sure if this is correct platform to raise (please feel free to close this) but would be great if some documentation is updated around this use case. Or atleast if someone could help me out or point to correct reference. So far the search is not much helpful.

I wanted to understand, how are the values derived for `CERTIFICATE_DER` `PRIVATE_KEY` `AES_KEY` in the file reference link above.

**Comment by daverodgman** [comment]
There are some docs on how to generate a key-pair and a self-signed certificate here:

https://mbed-tls.readthedocs.io/en/latest/kb/how-to/generate-a-self-signed-certificate/

In this example, you could generate the key file with:

`programs/pkey/gen_key type=ec ec_curve=secp256r1`

Note that the value of D printed will give your private key - but obviously compiling a private key into your firmware would leak your private key, so this is probably not the right thing to do.

and then generate a self-signed cert with

`programs/x509/cert_write issuer_key=keyfile.key selfsign=1`

Note that we currently don't support writing DER format certificates, but you could convert the PEM certificate to DER format using `programs/util/pem2der`, or just use it in PEM format.
