### ISSUE TITLE
Depends.py enhancement: key exchange tests

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#6439]
After merging https://github.com/Mbed-TLS/mbedtls/pull/6385, there are configurations using various key exchange types, but there are no performed tests.
This task is to change the current solution:
```
  'kex': ExclusiveDomain(key_exchange_symbols,
                         [build_command + ['lib'],
                          build_command + ['-C', 'programs']]),
```
to
```
  'kex': ExclusiveDomain(key_exchange_symbols, build_and_test),
```
And fix all issues that arise.

**Comment by mpg** [comment]
Moving to the "driver-only 2: ECC" EPIC - in that EPIC we're likely to want to work on key exchanges one by one (or in small groups), that is, we'll need builds with only a subset of key exchanges enabled, and we don't want to end up having to fight missing dependency declarations while we're deep in the middle of something else.

**Comment by mpg** [comment]
Note: in an ideal world, we'd like to run `ssl-opt.sh` as well, in order to ensure it also has correct dependency declarations, but that would probably make that domain too slow for the CI, considering the number of TLS 1.2 key exchanges involved.
