### ISSUE TITLE
Driver-only hashes: test coverage in the CI

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6445]
We have a script, `docs/architecture/psa-migration/outcome-analysis.sh`, that we used manually to measure progress and avoid regressions while adding support for driver-only hashes. However, now that this work is completed, we need to avoid future regressions. That is, the fact that `component_test_psa_crypto_config_accel_hash_use_psa` has no more tests skipped than the equivalent configuration without drivers should be an invariant checked by the CI.

Proposed strategy:
- [ ] Create a new `all.sh` component `component_test_psa_crypto_config_reference_hash_use_psa()` that uses the same configuration as in `docs/architecture/psa-migration/outcome-analysis.sh` (as of #6435) and runs the test suites as well as `ssl-opt.sh`.
- [ ] Extend the existing script `tests/scripts/analyze_outcomes.py` with command-line options to select which analyses to perform; currently the only available analysis available is `analyze_coverage()`.
- [ ] Extend that script with a new analysis function `analyze_driver_vs_reference()` (or any better name) and the corresponding command-line option. This function gives an error for any test that's skipped in `component_test_psa_crypto_config_accel_hash_use_psa` but not in `component_test_psa_crypto_config_reference_hash_use_psa`, except for those that are in a know list of test suites to ignore - so basically, the same as `compare_builds reference drivers` from `outcome-analysis.sh` except it also looks as `ssl-opt.sh` results. The script should return non-zero if there are any errors.

Note: we can test this locally by running:
```
tests/scripts/all.sh -k --outcome-file=outcome.csv test_psa_crypto_config_accel_hash_use_psa test_psa_crypto_config_reference_hash_use_psa
```
(just once, after the new component has been added), then
```
tests/scripts/analyze_outcomes.py outcomes.csv [option to ensure only driver-ref analysis is performed]
```
The reason why I'm suggesting we make the list of analyses configurable is so that during development we aren't flooded with warnings about "Test case not executed". (We could also just comment out the call to `analyze_coverage()` during development, but that seems less clean.)

Note: `tests/scripts/analyze_outcomes.py` already runs in the CI, see [analysis.groovy](https://github.com/Mbed-TLS/mbedtls-test/blob/master/vars/analysis.groovy#L56). I believe the script returning non-zero will result in reporting a failure on github, however that should be tested.

Note: in the future we'll have the same for cipher+aead, for ECC, etc. once we've done the work of making those work with drivers only, so ideally the solution implemented here should support that (for example, `analyze_driver_vs_reference()` could take the names of the components and list of ciphersuites to ignore as parameters, so in the future we would just have to add calls with different arguments).

Note: when the PR is merged, announce it to the rest of the team, as this will be the first time the "Result analysis" CI step possibly report failures.

**Comment by gilles-peskine-arm** [comment]
> I believe the script returning non-zero will result in reporting a failure on github, however that should be tested.

I'm pretty sure I tested that when I implemented this originally, but we should check that this hasn't bit-rotted.
