### ISSUE TITLE
Depends.py enhancement: test without `USE_PSA_CRYPTO` and remove old scripts

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#6453]
As found in https://github.com/Mbed-TLS/mbedtls/pull/6385, the last missing coverage parity between old scripts (`curves.pl`, `key-exchanges.pl`, `depends-pkalgs.pl`, `depends-hashes.pl`, and `https://github.com/ARMmbed/mbedtls/pull/1919`) and `depends.py` is the lack of testing without `USE_PSA_CRYPTO`. 
The aim of this task is to:

- Add an option to `depends.py` to turn off `USE_PSA_CRYPTO` in `set_reference_config`;
- Fix any issues that arise by running all tasks with `USE_PSA_CRYPTO` off;
- Verify that the coverage is the same as with the scripts mentioned above;
- Remove these scripts;
- Remove all references to these scripts (mainly `all.sh`, but maybe also some docs);
- Add new `all.sh` jobs that will run the tests with `USE_PSA_CRYPTO` off.

**Comment by mpg** [comment]
Note: unless I'm mistaken, we start from the full config, which has `USE_PSA` enabled. So, I think we are already testing with it and need to test without it. Either way, we need an option to control that indeed.

**Comment by AndrzejKurek** [comment]
> Note: unless I'm mistaken, we start from the full config, which has `USE_PSA` enabled. So, I think we are already testing with it and need to test without it. Either way, we need an option to control that indeed.

Thanks, fixed the description!

**Comment by mpg** [comment]
@AndrzejKurek I'm assigning this to you as you already have a PR up for it :)
