### ISSUE TITLE
curl built with mbedtls fails on https://1.1.1.1/ (IP address in SubjectAltName)

### ISSUE THREAD

**Issue by busylog** [Mbed-TLS/mbedtls#6473]
### Suggested enhancement

support ip address in x509_crt_verify_name, for curl https://1.1.1.1

### Justification

https://github.com/openwrt/packages/issues/19677

**Comment by gilles-peskine-arm** [comment]
This has already been requested: https://github.com/Mbed-TLS/mbedtls/issues/5082 . Pull requests welcome.

**Comment by gstrauss** [comment]
> This has already been requested: #5082 . Pull requests welcome.

Please see PR #6475 X509 crt verify SAN iPAddress with code and tests filed back in Oct 2022.

**Comment by gstrauss** [comment]
#6475 and #7436 have been merged into development branch for mbedtls-3.x
