### ISSUE TITLE
legacy_or_psa.h should be documented or private

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6478]
The new public header file [`mbedtls/legacy_or_psa.h`](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/legacy_or_psa.h) (made public by https://github.com/Mbed-TLS/mbedtls/pull/6283) only has the following text in its Doxygen documentation (plus the copyright notice, which should be a non-Doxygen comment):

> Macros to express dependencies for code and tests that may use either the legacy API or PSA in various builds; mostly for internal use.

The individual macros are not documented. There is a long comment that explain the logic behind the macro, but it isn't typeset as Doxygen.

Ok, it's “mostly for internal use”, but if it's not *only* for internal use, it should be documented. Currently, those macros are part of the public API and so they're part of the public API stability promise and we need to make it clear what we're promising here.

I've mentioned [elsewhere](https://github.com/Mbed-TLS/mbedtls/issues/6471) that I consider this interface overly complicated, and I would prefer to *not* release it as a public interface, so that we can get rid of it in its current form without waiting for 4.0. However, when we need a crypto interface in X.509/TLS, it's a code smell to not make it public: it's likely something that implementations of other protocols will need.

Goal of this task: either one of:

* Declare that `legacy_or_psa.h` is strictly an internal API. Then the macros do not need any Doxygen documentation.
* Have at least file-level Doxygen documentation that explains how to use the macros. Currently, the non-Doxygen comment is very hard to understand unless you've read [the architecture document](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/architecture/psa-migration/strategy.md#supporting-builds-with-drivers-without-the-software-implementation).

**Comment by daverodgman** [comment]
Closed by #6487 (@gilles-peskine-arm please re-open if you think there's more to do here)
