### ISSUE TITLE
Remove support for domain parameters

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6495]
Domain parameters are an experimental feature which is:

* Implemented only for RSA keys, in the following ways:
    * On key creation (import or generate), set the public exponent (without this interface, it has to be 65537).
    * In `psa_get_key_attributes`, get the public exponent. This is not useful since you can get it from the public key and you basically never need it separately.
* Specified for DH and DSA with finite fields, which are not implemented in Mbed TLS. (FFDH is coming, but without support for custom groups, so not using domain parameters yet).

At this point, it's unlikely that we'll ever implement custom groups for FFDH. We won't implement FFDSA. So we don't really have a planned use for domain parameters. They might come up again with other algorithms (e.g. for PQC, depending on exactly standardization goes), but it's not a given and if they do a different design might work better.

For RSA, the use of domain parameters was grafted on: we needed a way to select a custom public exponent when generating a key, the key attributes were the only way to pass information, and there was this field in the attributes that wasn't used for anything else and kind of fit. If we remove domain parameters, we need [a different way to specify the public exponent when generating an RSA key](https://github.com/Mbed-TLS/mbedtls/issues/6494).

Goal of this task: remove support for domain parameters from the API. Prerequisite: implement the alternative method for RSA generation (https://github.com/Mbed-TLS/mbedtls/pull/8815), and get to a point where we're comfortable with removing support for the old method. Once that's done, the domain parameter functions will be just stubs that do nothing.

Definition of done: domain parameters are removed from the public interface. If they are still present internally, file a follow-up task to clean up.

Advantages:

* Simplify the code.
* Will make https://github.com/Mbed-TLS/mbedtls/issues/4095 and https://github.com/Mbed-TLS/mbedtls/issues/3887 moot.
* Reduce the code size. See also https://github.com/Mbed-TLS/mbedtls/issues/6496

**Comment by DemiMarie** [comment]
> * Specified for DH and DSA with finite fields, which are not implemented in Mbed TLS. (FFDH is coming, but without support for custom groups, so not using domain parameters yet).

FFDH is deprecated IIUC.

**Comment by mpg** [comment]
Note: when doing this we can also remove the hack that was implemented in #8616 and documented in #8644 around the lack of driver support.
