### ISSUE TITLE
Exist EC point addition function on mbedtls API? Could we use the function "ecp_add_mixed" to do EC point addition "P = A + B"？

### ISSUE THREAD

**Issue by SongPuNew** [Mbed-TLS/mbedtls#6539]
### background
We know EC P-224 point A (but not know corresponding scalar a, A = a * G), and our own EC P-224 scalar b (B = b * G).
==> we could use "mbedtls_ecp_mul" to get corresponding point B (B = b * G).

Now we need to compute final public key P = A + b * G.
Could we use the function "ecp_add_mixed" to do EC point addition "P = A + B" in order to get P？
If not use "ecp_add_mixed", could we use other mbedtls function to do "P = A + b * G"? such as mbedtls_ecp_muladd ?

### Suggested enhancement
Provide EC point addition function on ecp.h.

**Comment by SongPuNew** [comment]
Sorry to trouble you.
Any update about the question ?

**Comment by SongPuNew** [comment]
Any update about the question ?

If current mbedtls cannot support EC point addition, when could support it ?

Thanks

**Comment by mpg** [comment]
I think `mbedtls_ecp_muladd()` is the right tool for what you want to do, as [it computes](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/ecp.h#L982) `R = m * P + n * Q`, so, if you want to compute `P = A + b * G` that's just `P = 1 * A + b * G`. So, `mbedtls_ecp_muladd()`  is the right tool for the job, and no extension is needed.

Note: the best place for questions is the [mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/) not github issues, so I'm closing this issue. However that doesn't prevent you from replying to it if you need further clarifications.

**Comment by SongPuNew** [comment]
Hi @mpg ,

Thanks for your support.

I will try to use "mbedtls_ecp_muladd" to compute P = 1 * A + b * G.

Best Regards,
Song
