### ISSUE TITLE
Could anyone please handle these PR?

### ISSUE THREAD

**Issue by valord577** [Mbed-TLS/mbedtls#6555]
I believe in "upstream priority".  
I am submitting this issue so that PR will not be forgotten.  
I would be honored to provide any other help if needed.  

* https://github.com/Mbed-TLS/mbedtls/pull/6511
* https://github.com/Mbed-TLS/mbedtls/pull/6224

**Comment by gilles-peskine-arm** [comment]
Please don't use issues as chat. Issues are for bug reports and feature requests. If you want to argue that a pull request should be prioritized, you can do it in the pull request itself or on the [mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/).
