### ISSUE TITLE
Coding style change: update coding guidelines

### ISSUE THREAD

**Issue by davidhorstmann-arm** [Mbed-TLS/mbedtls#6603]
Update the [Mbed TLS coding standards](https://github.com/Mbed-TLS/mbedtls-docs/blob/main/kb/development/mbedtls-coding-standards.md) to reflect the new code style.

**Comment by gilles-peskine-arm** [comment]
Will be fulfilled by https://github.com/Mbed-TLS/mbedtls-docs/pull/69 plus adding a reference in `CONTRIBUTING.md`.
