### ISSUE TITLE
Miller-Rabin test: no so correct determination of A boundaries

### ISSUE THREAD

**Issue by matbok** [Mbed-TLS/mbedtls#6605]
I think the following line should contain `k - ( W.n - 1 ) * biL - 1` instead of `k - ( A.n - 1 ) * biL - 1`,
https://github.com/Mbed-TLS/mbedtls/blob/32605b24bebd1ac9f7ce2add3bee0da2cad53c91/library/bignum.c#L2235
Even if I don't think there is so difference, since W and A are both created from X, it would be more correct.

**Comment by wernerlewis** [comment]
Thank you for raising an issue. As `W.n == A.n`, this will not affect behavior in this function, and has minimal benefit in terms of correctness. In addition, there is a known bug related to this masking (#5902), a fix for which would likely supersede this.

I'm closing this issue for now as we are unlikely to make this change.
