### ISSUE TITLE
MSVC: Compilation fails due to "C requires that a struct or union have at least one member"

### ISSUE THREAD

**Issue by boomer41** [Mbed-TLS/mbedtls#6628]
### Summary
When disabling almost every component of mbedtls to only have the required features, Microsoft MSVC 19.30.30706.0 complains for `union mbedtls_ssl_premaster_secret`: `C requires that a struct or union have at least one member`.

GCC/Clang on Linux do not complain.

When looking at this struct, it indeed does not have any member, because all key exchanges have been disabled through the config header.

As  a temporary fix, I enabled `MBEDTLS_KEY_EXCHANGE_RSA_ENABLED`.

mbedtls is built using a submodule within CMake.

### System information

Mbed TLS version (number or commit id): tag v3.2.1
Operating system and version: Windows 10 21H1 19043.2251
Configuration (if not default, please attach `mbedtls_config.h`): Attached as [mbedtls_config.txt](https://github.com/Mbed-TLS/mbedtls/files/10046987/mbedtls_config.txt) (.txt because .h is not an allowed extension)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Microsoft MSVC 19.30.30706.0 
CMake Options:

    set(ENABLE_TESTING OFF CACHE BOOL "Disable tests")
    set(ENABLE_PROGRAMS OFF CACHE BOOL "Disable programs")
    set(ENABLE_ZLIB_SUPPORT OFF CACHE BOOL "Build mbed TLS with zlib library.")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I${CMAKE_CURRENT_LIST_DIR} -DMBEDTLS_CONFIG_FILE=\"<mbedtls_config.h>\"")
    add_subdirectory(mbedtls EXCLUDE_FROM_ALL)`

Additional environment information: Building as a static library

### Expected behavior

Compilation succeeds

### Actual behavior

Compilation does not succeed

### Steps to reproduce

Compile v3.2.1 with MSVC using the given mbedtls config header.

**Comment by LionNatsu** [comment]
By "the required features", do you mean you only need the cryptography functions and want to opt out the networking part? i.e., disabling `mbedtls`, enabling `mbedx509` and `mbedcrypto`?

**Comment by gilles-peskine-arm** [comment]
@LionNatsu This particular compilation error happens if you disable TLS 1.2 support (i.e. only enable some crypto and perhaps some X.509 and TLS 1.3), and you use a compiler that doesn't allow empty unions (which GCC and Clang do unless invoked in pedantic mode).
