### ISSUE TITLE
"ModuleNotFoundError: No module named 'jsonschema'"

### ISSUE THREAD

**Issue by cpp77** [Mbed-TLS/mbedtls#6644]
### Summary
Created a `build` folder in the mbedtls root, `cd`'d in to `build` and then ran `cmake ..` but get:

```
mbedtls/library/../scripts/generate_driver_wrappers.py", line 29, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
make[2]: *** [library/CMakeFiles/mbedcrypto.dir/build.make:134: library/psa_crypto_driver_wrappers.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:951: library/CMakeFiles/mbedcrypto.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
Also get the same if I run `make` from the mbedtls folder.

### System information
CMake 3.16.3
Python 3.8.10
Ubuntu 22.04

Mbed TLS version (number or commit id): 
Operating system and version: Ubuntu 22.04
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by cpp77** [comment]
Need to install pip, then jsonschema and jinja2

**Comment by gilles-peskine-arm** [comment]
Per [README](https://github.com/Mbed-TLS/mbedtls/blob/development/README.md#generated-source-files-in-the-development-branch):

> To install the necessary packages, run
> ```
> python -m pip install -r scripts/basic.requirements.txt
> ```

No packages are needed if you grab a release of Mbed TLS, but in the development branch, you need `jinja2` (for a while now) and `jsonschema` (since recently).

You aren't the first to get bitten by this, so we're looking for a way to make this more apparent.

**Comment by dnovick** [comment]
I am getting the same error on my Mac even after I perform the required python package install. I have tried doing a pip uninstall and reinstall, etc...but no joy. Any help is appreciated.

**Comment by tom-cosgrove-arm** [comment]
@dnovick You're unlikely to get much help adding a comment on an issue that has been closed. Best to raise another issue, but include details of your setup, what you have tried, and specific error message(s) that you get.

**Comment by dnovick** [comment]
Sorry about that. I erringly ignored the fact that the issue was closed. That said, I figured it out. It was just homebrew python nightmares. Once I "notched back" to the system python, all was well.

**Comment by gilles-peskine-arm** [comment]
Make sure you use the same version of Python. On a Mac, you need to run `python3 -m pip …` since `python` is Python 2.

**Comment by gilles-peskine-arm** [comment]
We should be explicit about this in the documentation. Not everyone is familiar with the Python command naming mixup. https://github.com/Mbed-TLS/mbedtls/pull/7224
