### ISSUE TITLE
TLS 1.3: Improve the key generation functions.

### ISSUE THREAD

**Issue by yuhaoth** [Mbed-TLS/mbedtls#6675]
### Suggested enhancement

- [ ] Change `early_secrets` to local variable
- [ ] Re-consider about `tls13_hs_secrets`
- [ ] Change functions to static. There are many functions not used by other module, we should change them to local.

And so on.

### Justification

See https://github.com/Mbed-TLS/mbedtls/pull/6538#discussion_r1030216900

The key generation of TLS 1.3 is changed for time being. Some generation functions is not used outside. And some variables can be local variable. That improvement is target to reduce the code size and memory space, improve readability for current code.

**Comment by yanrayw** [comment]
This issue is resolved by small PRs. #6773 is still in review. The PR to handle [Re-consider about tls13_hs_secrets](https://github.com/Mbed-TLS/mbedtls/issues/6675#issue-1466090907) is still not uploaded.
