### ISSUE TITLE
Document bignum_mod and bignum_mod_raw conventions

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6684]
Document the conventions followed by functions in `bignum_mod` and `bignum_mod_raw`, such as naming, order of arguments, support for aliasing, invariants, validation of arguments, etc. Similar to what's at the top of [`bignum_core.h`](https://github.com/Mbed-TLS/mbedtls/blob/development/library/bignum_core.h).

**Comment by yanesca** [comment]
> Do the input residues all need to have the same modulus?

Yes they do, I can't think of any exceptions.

> Does the output reside need to have the same modulus (I guess so, because how else would we know that it's the right size)?

Yes, it does. We might add an exception later, that will be a dedicated conversion function, specifically to change the modulus associated with the residue.

> What restrictions should functions have on the inputs' representations, and what guarantees should they give on the outputs' representations?

`_mod`: Both the input and the output representation are prescribed by the `int_rep` field of the modulus.

`_mod_raw`: It is the same as `_mod` for arithmetic functions, but there are some utility functions that are meaningful and allow different representation than `int_rep` (and there is an API for the caller to change the representation).
