### ISSUE TITLE
Review PKCS7 module memory management

### ISSUE THREAD

**Issue by bensze01** [Mbed-TLS/mbedtls#6746]
The Fuzzer has caught a couple of memory management issues in the PKCS7 code.
@gilles-peskine-arm has fixed everything that was flagged by it so far, but we should re-review the memory management
to make sure that something else didn't slip by us and the fuzzer.

**Comment by gilles-peskine-arm** [comment]
With pkcs7 disabled by default, it's currently not being fuzzed. We're going to change the fuzzer configuration to run with experimental features enabled, but this might take a few weeks.

**Comment by daverodgman** [comment]
Reviewed all calls made to `mbedtls_calloc()` and confirmed they are always cleaned up properly in case of error, or not leaked (i.e., properly attached to the `mbedtls_pkcs7` struct) if no error occurs.

**Comment by daverodgman** [comment]
Reviewed the loops for freeing up linked lists, i.e. in `pkcs7_free_signer_info()` and `pkcs7_get_signers_info_set()` and `mbedtls_pkcs7_free()` and found no issues.

**Comment by tom-cosgrove-arm** [comment]
I've gone through the three uses of `mbedtls_calloc()`, checking that memory allocated is either free'd or attached to structures, in both success and error paths, and that the same is true for functions that allocate memory indirectly (e.g. `pkcs7_get_certificates()`)

Linked list freeing looks good.

**Comment by tom-cosgrove-arm** [comment]
Overall, memory management looks good now
