### ISSUE TITLE
Bignum: Rename modulus input argument from `m` to `N` in bignum_mod

### ISSUE THREAD

**Issue by minosgalanakis** [Mbed-TLS/mbedtls#6780]
### Suggested enhancement
Replace all references to modulus from `m -> N` in [bignum_mod.c](https://github.com/Mbed-TLS/mbedtls/blob/development/library/bignum_mod.c), [bignum.h](https://github.com/Mbed-TLS/mbedtls/blob/development/library/bignum_mod.h) and [test_suite_bignum_mod.function](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/suites/test_suite_bignum_mod.function)

### Justification

This is a requirement that was discussed in the review of #6743 and aggreed upon as part of the common conventions for the new bignum interface #6684 .

**Comment by Mihir-Raj-Singh** [comment]
Hey , @minosgalanakis  I am getting started  with my open source journey and like to work on this issue.
I am unclear about :
>Replace all references to modulus from ```m -> N```

Can you please explain it further ?

**Comment by minosgalanakis** [comment]
Hi @Mihir-Raj-Singh, and thank you for the interest in the project.

Yes that is precicely the ask. Two different ways to represent the modulus have been introduced to the new interface:
`mbedtls_mpi_mod_modulus *m` and `mbedtls_mpi_mod_modulus *N`. 

The issue is to replace it so that only `mbedtls_mpi_mod_modulus *N` is used for the shake of consistency. 

- Code: `bignum_mod.c, bignum_mod_raw.c, bignum_core.c`
- Documentation: `bignum_mod.h, bignum_mod_raw.h, bignum_core.h`

n order to make it simpler and quicker to review, I would recommend launching a series of small PR's in succession, each responsible for changing `m->N` in single function, and it's documentation. They can all be linked to this task.

**Comment by Mihir-Raj-Singh** [comment]
Thanks @minosgalanakis ,

I would like to work on this. Please assign me this issue.

If anything is needed further, I will let you know.

**Comment by Mihir-Raj-Singh** [comment]
Hello @minosgalanakis  , I tried renaming modulus input argument in a single function in  both files ```bignum_mod.c``` and ```bignum_mod.h```

You can refer it here : a433560897fa502aa586bad251c864eb1b9bb6ad

- Is this the correct way to do that ? 
- When do I need to create pull request ?
- Do i have to edit all the functions separately as I did ?


I'm a little nervous and don't want things to go wrong. 
It would be great If you explain things further or suggest me how to move further.

**Comment by minosgalanakis** [comment]
Yes, something like that should suffice.

But you need to make sure that the embedded tests are still passing:
- Run `ctest` as described in the [documentation](https://github.com/Mbed-TLS/mbedtls)
- Check that the file style is correct by running [check_files.py](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/check_files.py)
- Also in accordance to our [DCO](https://github.com/Mbed-TLS/mbedtls/blob/development/dco.txt) we cannot accept contributions that are not signed off. In order to achive that all commits should have a `Signed-off-by: Name <email>` field in the end. You can add that be rewording the commit. For future commits by using `git commit -s`  syntax will automacially append it to the text message.
- Also it would be good to follow the commit message structure of existing commits, with one short line for the description, a newline, and a small more verbose text explaining what the commit does. If the modification is minor and self explanatory then the commit body can be ommited. `git log --grep='bignum'` or `git log --grep='Bignum'` can give you pointers.

After your personal branch you have made the changes is in good shape, and has passed the tests,  you can make the PR request. Again using [past PR's as reference](https://github.com/Mbed-TLS/mbedtls/pulls?q=is%3Apr+bignum%3A) can be usefull on how to structure the PR's description. 

One the first PR request is ready, and has passed CI you can repeat the process for all functions that need to be renamed.

**Comment by Mihir-Raj-Singh** [comment]
I am unable to work on this issue currently, as I find it little complex to understand this code base. 
Going to unassigned myself.

**Comment by Mihir-Raj-Singh** [comment]
Hey @minosgalanakis , I'm getting this error while running [check_files.py](https://github.com/Mbed-TLS/mbedtls/blob/b17803682e268aae4f6fe0a9634693b13a8c95d9/tests/scripts/check_files.py)
Have a look :

` python3 check_files.py `

```
Traceback (most recent call last):
  File "/home/scorpion/Desktop/mbedtls/tests/scripts/check_files.py", line 409, in <module>
    run_main()
  File "/home/scorpion/Desktop/mbedtls/tests/scripts/check_files.py", line 402, in run_main
    integrity_check = IntegrityChecker(check_args.log_file)
  File "/home/scorpion/Desktop/mbedtls/tests/scripts/check_files.py", line 345, in __init__
    build_tree.check_repo_path()
  File "/home/scorpion/Desktop/mbedtls/tests/scripts/../../scripts/mbedtls_dev/build_tree.py", line 34, in check_repo_path
    raise Exception("This script must be run from Mbed TLS root")
Exception: This script must be run from Mbed TLS root

```
> How can I fix this ?

**Comment by tom-cosgrove-arm** [comment]
> How can I fix this ?

The last line in the output you pasted is `Exception: This script must be run from Mbed TLS root`.

That means the top of the repository, so:

```
$ ls
3rdparty/    ChangeLog.d/    CONTRIBUTING.md	    doxygen/  Makefile	 SECURITY.md
BRANCHES.md  cmake/	     DartConfiguration.tcl  include/  programs/  SUPPORT.md
BUGS.md      CMakeLists.txt  dco.txt		    library/  README.md  tests/
ChangeLog    configs/	     docs/		    LICENSE   scripts/	 visualc/
$ python3 tests/scripts/check_files.py
$ echo $?
0
```

**Comment by Mihir-Raj-Singh** [comment]
Thanks for the information. It works fine now.

May I ask you what echo $? and 0 means ? What's the purpose of writing it ? and why it outputs 0 ? If I get some error while checking the files still the output will be zero ?

**Comment by tom-cosgrove-arm** [comment]
> May I ask you what `echo $?` and `0` means ?

`echo $?` means "tell me the exit status of the last command I just ran". And `0` is the usual exit status for "success".

I will normally include this on examples I post where there is no output (like above) to make it clear that the command that I ran succeeded.

**Comment by Mihir-Raj-Singh** [comment]
Hello , 
I renamed modulus input argument from m to N in give files as suggested : #6903
- bignum_mod.c
- bignum_mod.h
- bignum_mod_raw.c
- bignum_mod_raw.h
- test_suite_bignum_mod.function

### Checkout the PR : 

> * Run `ctest` as described in the [documentation](https://github.com/Mbed-TLS/mbedtls)
> 
> * Check that the file style is correct by running [check_files.py](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/check_files.py)
> 
> * Also in accordance to our [DCO](https://github.com/Mbed-TLS/mbedtls/blob/development/dco.txt) we cannot accept contributions that are not signed off. In order to achive that all commits should have a `Signed-off-by: Name <email>` field in the end. You can add that be rewording the commit. For future commits by using `git commit -s`  syntax will automacially append it to the text message.
> 
> * Also it would be good to follow the commit message structure of existing commits, with one short line for the description, a newline, and a small more verbose text explaining what the commit does. If the modification is minor and self explanatory then the commit body can be ommited. `git log --grep='bignum'` or `git log --grep='Bignum'` can give you pointers.


### Checklist :
- [x]  Run Ctest ( All test passed successfully)
- [x]  Run check_files.py (File system are correct)
- [x]  Signed the commit
