### ISSUE TITLE
Compile with this error:Error: Do not know how to handle: BLOWFISH

### ISSUE THREAD

**Issue by jurry-zhang** [Mbed-TLS/mbedtls#6806]
### Summary
When I compile the libs in a new folder, I get this one error：

Gen   error.c
Error: Do not know how to handle: BLOWFISH
Makefile:303: recipe for target 'error.c' failed

This prompt will appear when the generate_errors.pl file creation time has been changed

### System information

Mbed TLS version (number or commit id): 3.1.0
Operating system and version: ubuntu 16.04 lts
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by gilles-peskine-arm** [comment]
Blowfish was removed in Mbed TLS 3.0. There is a file from Mbed TLS 2.x in your working directory, I guess `include/mbedtls/blowfish.h` (and probably others). This error would not happen in a new working directory.

**Comment by jurry-zhang** [comment]
> I removed the blowfish.h and it compiled fine， Thank you very match ！
