### ISSUE TITLE
Do not dynamically allocate memory for hash functions if possible

### ISSUE THREAD

**Issue by DemiMarie** [Mbed-TLS/mbedtls#6819]
### Suggested enhancement

Hash APIs should not require dynamic memory allocation.

### Justification

Mbed TLS needs this because it is the only part of ARM Trusted Firmware that uses dynamic allocation.

**Comment by gilles-peskine-arm** [comment]
The PSA hash APIs don't require heap allocation, so if that's important to you, please migrate to PSA. (Other PSA crypto APIs do require heap allocation as currently implemented in Mbed TLS; they're designed to allow a reasonable malloc-less implementation, but Mbed TLS is far from that.)

The md APIs are not likely to undergo any improvements at this point except to facilitate the migration to PSA. We do have [plans to change `md.h`](https://github.com/Mbed-TLS/mbedtls/pull/6549), but we don't currently plan to change the memory characteristics of `mbedtls_md_context_t` (where an `mbedtls_md_context_t` is fit for a small stack, and the potentially bigger context is always on the heap).

**Comment by DemiMarie** [comment]
> The PSA hash APIs don't require heap allocation, so if that's important to you, please migrate to PSA. (Other PSA crypto APIs do require heap allocation as currently implemented in Mbed TLS; they're designed to allow a reasonable malloc-less implementation, but Mbed TLS is far from that.)

That ticket should be filed against ARM Trusted Firmware, then.
