### ISSUE TITLE
MS-MPPE-RECV key is not getting correct value in MBEDTLS

### ISSUE THREAD

**Issue by ajaykrmishra** [Mbed-TLS/mbedtls#6864]
### Summary

I am running Mbed TLS as a core security library(2.24.0), in embedded platform.
I am using the FreeRADIUS server for AAA authentication.
I am able to get the PMK values correctly at the supplicant side, however while decrypting the MPPE key at the gateway side I see that the values are incorrect specially in the API(radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt)

Below are my setup details: 
FreeRADIUS server setup on Ubuntu(3.2.1)
openssl :1.1.1f 
Ubuntu version : 20.04.04LTS

Client side setup
Platform : Micro controller based platform
OS : FreeRTOS

### System information

Sample example 

MPPE KEY in clear at RADIUS Server
Fri Dec 30 23:50:13 2022 : Debug: (209)   MS-MPPE-Recv-Key = 0x2f6c3e7e748eb49a598c208af3ef520454f5aa6873bc72f7f32be1053914a566
Fri Dec 30 23:50:13 2022 : Debug: (209)   MS-MPPE-Send-Key = 0xa04539819a272e94782af1818b05878bb0e420d08a51accd6c3cb75baaecbd75

PMK Key values at Supplicant(which is same as MPPE-RECV-KEY)
2022-12-30 23:50:07.313 #1   0000000000000000 <log> 0:28:21.215 [debug] [        tlsp] {Wi-SUN Ev}: >>>> PRINT THE KEY PMK >>>>
2022-12-30 23:50:07.313 #1   0000000000000000 <log> 0:28:21.224 [debug] [        tlsp] {Wi-SUN Ev}: EAP-TLS key material 2f:6c:3e:7e:74:8e:b4:9a:59:8c:20:8a:f3:ef:52:04:54:f5:aa:68:73:bc:72:f7:f3:2b:e1:05:39:14:a5:66

2022-12-30 23:50:07.313 #1   0000000000000000 <log> 0:28:21.240 [debug] [        tlsp] {Wi-SUN Ev}: EAP-TLS key material a0:45:39:81:9a:27:2e:94:78:2a:f1:81:8b:05:87:8b:b0:e4:20:d0:8a:51:ac:cd:6c:3c:b7:5b:aa:ec:bd:75

Decrypted key Value at Authenticator(using radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt)
2022-12-30 23:51:34.763 #1   0000000000000000 <log> 3:09:17.919 [debug] [        hmac] {Wi-SUN Ev}: hmac_md key a9:69:02:e9:3a:1d:cd:05:31:b3:77:cd:d6:d7:c2:c7:2d:52:4b:0a:5b:b1:aa:81:20:67:dd:b8:1c:04:ef:63

Mbed TLS version (number or commit id): 2.24.0 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
The key should be decrypted with correct value.

### Actual behavior
The key is not getting correct value.

### Additional information

Kindly let me know what is missing here ?
Thanks in advance.

**Comment by minosgalanakis** [comment]
Hi @ajaykrmishra.

Have you considered asking the question in the [MbedTLS mailing list](https://lists.trustedfirmware.org/mailman/listinfo/mbed-tls)? 

Given how wider reach it  has (more community members, and users using the same platform/configuration who may have encountered the same question), it may be a more likely to get the appropriate support. 

I will be closing this issue, but feel free to let me know if there is more information to escallate it into a bug.

**Comment by ajaykrmishra** [comment]
Thank you for your response I will ask in the mailing list.   The link that you have attached throws an error. Can you please confirm if this is the mailing list mbed-tls@lists.trustedfirmware.org. Thanks again.

With regards,
Ajay.

**Comment by ajaykrmishra** [comment]
Thank you. I will post the query as soon as possible in the suggested
mailing list.
Can you confirm if this is the mailing list
***@***.*** ?

With regards,
Ajay.

Brentwood, UK.

**Comment by ajaykrmishra** [comment]
Hi @minosgalanakis,
As suggested, I raised the issue in the mbed-tls mailing list but didn't get any response.
https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/X2ZOTOGM3AL5H27QV22CPVAGAZSMVYC2/

Can you please re-open the defect ?
Let me know if you require further information.

Thanks.
With regards,
Ajay.
Brentwood,UK.
