### ISSUE TITLE
TLS 1.3: Add support for version negotiation on server side

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#6867]
### Suggested enhancement
Add support for version negotiation on server side

As for the client side (already implemented) the version negotiation is all around the supported version extension. See section 4.2.1 for what should be done.

Regarding testing, as much as much possible in TLS tests (unit tests and ssl-opt.sh), we should exercise the negotiation and thus not forcing a TLS version on server side.

### Justification
Mbed TLS needs this because this is an valuable feature of a TLS 1.3 and TLS 1.2 capable server.

**Comment by Taowyoo** [comment]
Thank you create this feature request.
This is also quite necessary in our use case. (Server running in a mare metal env needs to handle TLS 1.2&1.3 connections)
