### ISSUE TITLE
Self generated certificate using 'mbedtls_x509write_crt_pem' is invalid in Google Chrome browser

### ISSUE THREAD

**Issue by neja20** [Mbed-TLS/mbedtls#6881]
### Summary
When generating a self signed certificate, the library doesn't comply to [RFC 3279](https://www.rfc-editor.org/rfc/rfc3279), thus the Chrome considers such certificate invalid.

Function [mbedtls_asn1_write_algorithm_identifier()](https://github.com/Mbed-TLS/mbedtls/blob/cd0a5656445bb75e8fe485880b4b00c28522a66f/library/asn1write.c#L190) implicitly adds ASN1_NULL value when par_len == 0.
However according to the [RFC 3279](https://www.rfc-editor.org/rfc/rfc3279) the encoding MUST omit the parameters field when using the ECDSA signature algorithm.

> 
> [2.2.3](https://www.rfc-editor.org/rfc/rfc3279#section-2.2.3) ECDSA Signature Algorithm
> 
>    The Elliptic Curve Digital Signature Algorithm (ECDSA) is defined in
>    [[X9.62](https://www.rfc-editor.org/rfc/rfc3279#ref-X9.62)].  The ASN.1 object identifiers used to identify ECDSA are
>    defined in the following arc:
> 
>       ansi-X9-62  OBJECT IDENTIFIER ::= {
>            iso(1) member-body(2) us(840) 10045 }
> 
>       id-ecSigType OBJECT IDENTIFIER  ::=  {
>            ansi-X9-62 signatures(4) }
> 
>    ECDSA is used in conjunction with the SHA-1 one-way hash function.
>    The ASN.1 object identifier used to identify ECDSA with SHA-1 is:
> 
>       ecdsa-with-SHA1  OBJECT IDENTIFIER ::= {
>            id-ecSigType 1 }
> 
>    **When the ecdsa-with-SHA1 algorithm identifier appears as the
>    algorithm field in an AlgorithmIdentifier, the encoding MUST omit the
>    parameters field.  That is, the AlgorithmIdentifier SHALL be a
>    SEQUENCE of one component: the OBJECT IDENTIFIER ecdsa-with-SHA1.**
> 
>    The elliptic curve parameters in the subjectPublicKeyInfo field of
>    the certificate of the issuer SHALL apply to the verification of the
>    signature.
> 
>    When signing, the ECDSA algorithm generates two values.  These values
>    are commonly referred to as r and s.  To easily transfer these two
>    values as one signature, they MUST be ASN.1 encoded using the
>    following ASN.1 structure:
> 
>       Ecdsa-Sig-Value  ::=  SEQUENCE  {
>            r     INTEGER,
>            s     INTEGER  }

### Steps to reproduce

1. Generate self signed certificate while using eliptic curves.
3. Save it to pem file with `mbedtls_x509write_crt_pem()`
4. start https webserver using that pem file
5. Connect to server using Google Chrome.

### Expected behavior

The library should follow the above stated RFC and omit the parameters when generating certificate using [mbedtls_x509write_crt_der()](https://github.com/Mbed-TLS/mbedtls/blob/cd0a5656445bb75e8fe485880b4b00c28522a66f/library/x509write_crt.c#L389)

### Additional information
![image](https://user-images.githubusercontent.com/22619847/210796784-d5eecd87-a2a3-4c87-8430-e6bc03a68bb4.png)

**Comment by gilles-peskine-arm** [comment]
Thanks for reporting this. This is a known issue: https://github.com/Mbed-TLS/mbedtls/issues/2924

We don't have a fix for that, but the previous thread has a link to a third-party patch (which we unfortunately can't include in Mbed TLS).
