### ISSUE TITLE
Add test for PK parsing of keys using compressed points

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6886]
### Suggested enhancement

Following https://github.com/Mbed-TLS/mbedtls/pull/6282 that added support for reading compressed points in ECP, the PK parse module is supposedly able to read EC keys with compressed points in them. However, that is not tested. This task is to add tests for that.

Note: keys with compressed points can be generated with OpenSSL using `-conv_form compressed`, see the second answer to [this SO question](https://stackoverflow.com/questions/29355027/what-method-does-openssl-use-to-combine-a-public-ec-keys-coordinates).

### Justification

Mbed TLS needs this because everything that's supposed to work needs to be tested.

**Comment by Neustradamus** [comment]
To follow.

**Comment by valeriosetti** [comment]
Actually it seems to me that PR #6282 adds tests for compressed point: see [line 268](https://github.com/Mbed-TLS/mbedtls/blob/74d6e59e152dda5d4b5e85d2b9efca83ad32619c/tests/suites/test_suite_ecp.data#L268) and 272).
Am I missing something here?
