### ISSUE TITLE
Cryptofuzz familiarization

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6887]
This is an investigation task to get familiar with [cryptofuzz](https://github.com/guidovranken/cryptofuzz).

* Get a running environment (in or out of Docker).
* Build with just mbedtls and openssl

The subsequent goal will be to augment cryptofuzz to test the PSA API in addition to the mbedtls API. We'll submit patches to cryptofuzz. We have some guidance from Guido (the author of cryptofuzz): https://github.com/guidovranken/cryptofuzz/issues/47 . Also, at some point, we may want to have a CI job that verifies that our patches aren't breaking cryptofuzz (we'll need that if we also start fuzzing the new bignum interfaces).

**Comment by tom-daubney-arm** [comment]
I put a component-test table on the issue as it seemed like the closest match but please feel free to change it if you disagree.
