### ISSUE TITLE
Two declarations for `psa_set_key_domain_parameters` causes compilation error with [-Werror=redundant-decls]

### ISSUE THREAD

**Issue by govindraj-arm** [Mbed-TLS/mbedtls#6910]
I see 2 declarations for psa_set_key_domain_parameters in:
include/psa/crypto_extra.h
include/psa/crypto_struct.h
This forces users of the mbed-tls to not to enable warnings for redundant-decls  Is this expected?

### System information

Mbed TLS version (number or commit id): 8c8922499 (HEAD -> mbedtls-3.3.0, tag: v3.3.0, tag: mbedtls-3.3.0, origin/master)
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): aarch64-none-elf-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
Additional environment information: Building it with trusted firmware project.

### Expected behavior

we should be able to build without compiler warnings, although current mbed tls causes compiler warning like:
error: redundant redeclaration of 'psa_set_key_domain_parameters' [-Werror=redundant-decls]
  499 | psa_status_t psa_set_key_domain_parameters(psa_key_attributes_t *attributes,
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Actual behavior

No compiler warnings/erros.

### Steps to reproduce

Build mbed tls first:
make -j4 clean; cmake .; CC=aarch64-none-elf-gcc make -j8 lib;

then try using above build mbed tls with tf-a:

make distclean -j8; make -j8 CROSS_COMPILE=aarch64-none-elf- DEBUG=1 V=1 memmap fiptool all MBEDTLS_DIR=<path-to-mbedtls-folder> TRUSTED_BOARD_BOOT=1 DYN_DISABLE_AUTH=1 GENERATE_COT=1 ARM_ROTPK_LOCATION=devel_rsa ROT_KEY=plat/arm/board/common/rotpk/arm_rotprivk_rsa.pem > /dev/null

**Comment by paul-elliott-arm** [comment]
Hi!

The second declaration of `psa_set_key_domain_parameters`, as per the comment in `crypto_struct.h` is to avoid issues with include file order - As it is the code won't actually compile without this, as you get an implicit declaration error.

From the GCC manual, this warning is declared as:

_Warn if anything is declared more than once in the same scope, even in cases where multiple declaration is valid and changes nothing._

As such I am not sure whether we can actually fix this, given that in this case the declaration is entirely valid (and required), but the warning will still fire on this (and the documentation states that it will). If you have a suggestion as to how we could fix this, then I am happy to review a PR, however I think in this case the best option is just to remove that warning.

**Comment by govindraj-arm** [comment]
Thanks Paul, for the reply and clarification.

As an workaround I have used `CFLAGS += -Wno-error=redundant-decls`, But wanted it to be clarified if this was expected.

**Comment by gilles-peskine-arm** [comment]
In the development branch, we will likely resolve this by [removing domain parameters](https://github.com/Mbed-TLS/mbedtls/issues/6495) (which has a technical prerequisite).

For 2.28, we _could_ avoid repeating the declaration in `crypto_extra.h`. Or move the definition of `psa_set_key_type` to a different header (but there isn't really one that fits).

`-Wredundant-decls` is a bit of an annoying warning. It's something you might want to use on your own code base if you're hunting down duplication, but it doesn't really make sense when consuming third-party code. It's a pity there's no easy way to limit it to a scope.

**Comment by gilles-peskine-arm** [comment]
For the sake of gcc, we could use a `#pragma` to temporarily disable the warning around the second declaration.

**Comment by govindraj-arm** [comment]
Hi Paul / Gilles,

Just some observation from my side,
Strangely this compiler error doesn't occur on 2.28 but I see them on 3.3 and is all pointing to recently added file `hash_info.c` file:

[...]
In file included from /work/tfa/mbedtls3.0//include/psa/crypto.h:4062,
                 from /work/tfa/mbedtls3.0//library/hash_info.h:36,
                 from /work/tfa/mbedtls3.0//library/hash_info.c:23:
/work/tfa/mbedtls3.0//include/psa/crypto_extra.h:499:14: warning: redundant redeclaration of 'psa_set_key_domain_parameters' [-Wredundant-decls]

[...]

**Comment by g-tardy** [comment]
Hi there,

I had the same error only when compiling a linked library ([open62541 ](https://github.com/open62541/open62541).
The error only occurs with mbedtls releases 3.*.* and strangely not on version 2.8.*...

To bypass this issue, I manually updated the files:

include/psa/crypto_extra.h
include/psa/crypto_struct.h

 with the following code:
```
#ifndef PSA_SET_KEY_DOMAIN_PARAMETERS
#define PSA_SET_KEY_DOMAIN_PARAMETERS
psa_status_t psa_set_key_domain_parameters(psa_key_attributes_t *attributes,
                                           psa_key_type_t type,
                                           const uint8_t *data,
                                           size_t data_length);
#endif
```

Hope this could help...
