### ISSUE TITLE
Do not tweak the configuration after building libtestdriver1

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6911]
In `all.sh`, several components that test with `libtestdriver1` use the following sequence of actions:

1. Tweak some configuration files, including `tests/include/test/drivers/config_test_driver.h`
2. Build `libtestdriver1.a`
3. Tweak more configuration files, including `tests/include/test/drivers/config_test_driver.h`
4. Build the core.

This makes it difficult to reproduce a build because you have to change `tests/include/test/drivers/config_test_driver.h` midway. When doing development, you can't just rebuild the test driver whenever you want.

The goal of this task is to change the actions to:

1. Tweak some configuration files.
2. Build `libtestdriver1.a`
3. Build the core.

This may require defining new preprocessor symbols that only affect the test driver.

The important consequence is that during development it should be possible to set up the configuration once and for all, then do cycles of edit-recompile-test where the recompile step does not involve modifying configuration files.

Out-of-tree builds and correct dependencies are out of scope of this task.

**Comment by mpg** [comment]
Fixed by #7672
