### ISSUE TITLE
base64 encoded output of mbedtls_rsa_rsassa_pkcs1_v15_sign signature missing the last character and add many repeated unwanted characters.

### ISSUE THREAD

**Issue by noellemar** [Mbed-TLS/mbedtls#6916]
Hello everyone, 

I'm using ESP32-Arduino framework for prototyping a systems use RSA-SHA1 by Mbedtls, the problem is i get signature when i compare from other tools (C#, online tools) find missing final character plus it adds another strange character and other repeated characters which are (paWl).

here is output of signature:
1. (required)
MLI0abvguxVkj0256ALo8t16uBQfONCvg9t3gh5L4rHTU/Tqrj2zI+XOJNK7uJwQXjj4Vkj7u8R7fCQZDA5owAx5fFsgNVbwX/L0fB3Ej/iGE/3665FDRDTyOsr+aLIB6//dGpKig9xCNKqP/MyAhDGvj07fliAxRpMtjcF/ts2OyGpi7UUfx0he3O9hREVFZS/0AiXHam7U1GcVMGxwmcSNwNSBt8Ucoismk6PTXEdPlLjtnXEj/+0wjGUVEOPIYO90RFgK13Zg+nKwmLU8A6avvAY15uTCArP/WgTZCHOlm+HkpQ2nHXuzybppt1z1mKKBFWMZQl4cs/F2FXniwg==

2. (produced)
MLI0abvguxVkj0256ALo8t16uBQfONCvg9t3gh5L4rHTU/Tqrj2zI+XOJNK7uJwQXjj4Vkj7u8R7fCQZDA5owAx5fFsgNVbwX/L0fB3Ej/iGE/3665FDRDTyOsr+aLIB6//dGpKig9xCNKqP/MyAhDGvj07fliAxRpMtjcF/ts2OyGpi7UUfx0he3O9hREVFZS/0AiXHam7U1GcVMGxwmcSNwNSBt8Ucoismk6PTXEdPlLjtnXEj/+0wjGUVEOPIYO90RFgK13Zg+nKwmLU8A6avvAY15uTCArP/WgTZCHOlm+HkpQ2nHXuzybppt1z1mKKBFWMZQl4cs/F2FXniw**qWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpQ**==

// hope you can see missed final g character, and added q character instead of g, and other Wlpa
// you can try on yours by your own key and see the output (ESP32).

here is sample of test code i used:
#include<Arduino.h>
#include "mbedtls/rsa.h"
#include "mbedtls/entropy.h"
#include "mbedtls/ctr_drbg.h"
#include "mbedtls/pk.h"
#include "mbedtls/platform.h"
#include "mbedtls/bignum.h"
#include "mbedtls/base64.h"
#include "mbedtls/sha256.h"
#include "mbedtls/sha1.h"
#include "soc/soc.h"
#include "soc/rtc_cntl_reg.h"
#include<base64.h>

#define mbedtls_printf       printf
#define mbedtls_exit         exit

const char* privKey = 
"-----BEGIN RSA PRIVATE KEY-----\n" // in reality i have a real private key
"-----END RSA PRIVATE KEY-----\n";

void setup() {
  WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);
  Serial.begin(9600);
    printf("Welcome to test the RSA demo!\n");

const char *msg = "<DATA><NAME>DEVELOPER</NAME><MUMBER>123456</NUMBER></DATA>"; //sample of short xml string
    
mbedtls_pk_context pk;
  mbedtls_pk_init(&pk);
  char* pwd = NULL;
  int pwdLen = 0;

  mbedtls_pk_parse_key(&pk, (const unsigned char*) privKey, strlen(privKey)+1, (const unsigned char*) pwd, pwdLen);
  mbedtls_rsa_context *rsa = mbedtls_pk_rsa(pk);

  int keyValid = mbedtls_rsa_check_privkey(rsa);
   unsigned char encryptBuffer[3000]; // my output string length sometime get longs so i put enough size since goes up to 2900 bytes
  if( keyValid == 0 ) {
    byte hashResult[128]; // from docs said 128 bytes in case its 2048 bits hashing
    mbedtls_sha1((const unsigned char*)msg, strlen((char*) msg), hashResult);
    mbedtls_rsa_rsassa_pkcs1_v15_sign( rsa, NULL, NULL, MBEDTLS_RSA_PRIVATE, MBEDTLS_MD_SHA1,  sizeof(hashResult)+1, hashResult,( unsigned char*) encryptBuffer ); 

unsigned char output[2048];
size_t outlen;

//i used both base64 to test if there was errors, and got same output

mbedtls_base64_encode(output, sizeof(output), &outlen, encryptBuffer, sizeof(encryptBuffer)); //base64 from mbedtls

    Serial.println();
    
    Serial.println(base64::encode(String((char*)encryptBuffer)).length());
    Serial.println(base64::encode((const uint8_t *)encryptBuffer,sizeof(encryptBuffer)));//ESP32 base64 outpus
    Serial.println("******************************");
    Serial.println(outlen);
    Serial.println((char*)output); //mbedtls_base64_encode output
    Serial.println();
    
  }
}

void loop() {
}

**Comment by paul-elliott-arm** [comment]
Hi, What version of MbedTLS are you using here - I am presuming some version of 2.28, given the MBEDTLS_RSA_PRIVATE? What config are you using?

**Comment by noellemar** [comment]
> Hi, What version of MbedTLS are you using here - I am presuming some version of 2.28, given the MBEDTLS_RSA_PRIVATE? What config are you using?

mbed TLS 2.6.0

**Comment by paul-elliott-arm** [comment]
Hi,

We do not officially support 2.6.0 unfortunately, you would be best off switching to an LTS branch like 2.28.2. It is entirely possible we have fixed any issue.

The above code snippet has a lot of issues for me, and indeed segfaults in its current state - for starters you are not checking the return on `mbedtls_pk_parse_key()`, which in this case fails with `MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED`.

For seconds you should be doing a `mbedtls_pk_get_type()` on the context prior to calling `mbedtls_pk_rsa()` or checking that `mbedtls_pk_rsa()` does not return NULL, as it does in the current example, prior to passing this in to any of the pk functions.

The Sha1 functions you are using are deprecated, as of 2.7.

Given that this is a private key, you should be passing an `f_rng` to `mbedtls_rsa_rsassa_pkcs1_v15_sign()`

Finally, you can call `mbedtls_base64_encode()` with dlen == 0 to get the size of output buffer required. 

The issue you are seeing feels very much like an input or output buffer size being too small.

If you can provide working code and a key that replicates the issue on 2.28.2 then I will investigate further.

**Comment by noellemar** [comment]
> Hi,
> 
> We do not officially support 2.6.0 unfortunately, you would be best off switching to an LTS branch like 2.28.2. It is entirely possible we have fixed any issue.
> 
> The above code snippet has a lot of issues for me, and indeed segfaults in its current state - for starters you are not checking the return on `mbedtls_pk_parse_key()`, which in this case fails with `MBEDTLS_ERR_ERROR_CORRUPTION_DETECTED`.
> 
> For seconds you should be doing a `mbedtls_pk_get_type()` on the context prior to calling `mbedtls_pk_rsa()` or checking that `mbedtls_pk_rsa()` does not return NULL, as it does in the current example, prior to passing this in to any of the pk functions.
> 
> The Sha1 functions you are using are deprecated, as of 2.7.
> 
> Given that this is a private key, you should be passing an `f_rng` to `mbedtls_rsa_rsassa_pkcs1_v15_sign()`
> 
> Finally, you can call `mbedtls_base64_encode()` with dlen == 0 to get the size of output buffer required.
> 
> The issue you are seeing feels very much like an input or output buffer size being too small.
> 
> If you can provide working code and a key that replicates the issue on 2.28.2 then I will investigate further.

Thanks alot @paul-elliott-arm .

let me upgrade to 2.28.2 version then i will get back to you/here.
