### ISSUE TITLE
How enable HTTPS support in Zephyr RTOS Using mbedtls library build with ciwetweb

### ISSUE THREAD

**Issue by NarendraSonawane1** [Mbed-TLS/mbedtls#6934]
### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by paul-elliott-arm** [comment]
Hi,

I'm afraid I know very little about Zephyr and or ciwetweb, but MbedTLS as a library does not have any code for http connections without TLS.

This really sounds like a question for those projects, not for us.
