### ISSUE TITLE
code_style.py: Apply exclusions when restyling a list of files

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#6947]
https://github.com/Mbed-TLS/mbedtls/pull/6834 added the ability to write `scripts/code_style.py foo.c bar.c` to only restyle `foo.c` and `bar.c`. This unconditionally restyles all the files specified on the command line, even if they should be excluded (e.g. `3rdparty`) or if they aren't C files. I think this is actually the wrong interface: I'd like to be able to write things like
```
scripts/code_style.py $(git diff --name-only HEAD~3)
```
and have the script figure out which subset of files actually needs to be restyled.

The goal of this task is to change `code_style.py` to apply the exclusions to files passed on the command line. I don't know if we should keep the old behavior as an option — currently it's easy enough to run uncrustify manually if you want that.

**Comment by lpy4105** [comment]
I'm going to pick this issue, here are my plan:

- Files to be included: match the pattern `*.[hc]` or `tests/suites/*.function` or `scripts/data_files/*.fmt`, except start with `3rdparty/` and `generated files`.
- Add `--force` option if we'd like to keep the "old behavior".

Please let me know if it is sensible to you.

**Comment by gilles-peskine-arm** [comment]
@davidhorstmann-arm is also working on some patches to `code_style.py`. Please coordinate to avoid conflicts.

Files to be included: same inclusions and exclusions as what's currently in `get_src_files`, except that when there are explicit file names, they don't need to be committed into git.

To keep the old behavior: maybe `--files` should mean “exactly these files” and a new option `--c-files` (or no option) means “only the files to which styling applies”?
