### ISSUE TITLE
EC J-PAKE: confusion about role vs user+peer

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6961]
The PSA Crypto PAKE extension API is quite clear: for (EC) J-PAKE, the application is supposed to call `set_user()` and `set_peer()` but does not have to call `set_role()`. See the [diagram for J-PAKE](https://arm-software.github.io/psa-api/crypto/1.1/ext-pake/AES0058-PSA_Certified_Crypto_API-1.1_PAKE_Extension-bet.1.pdf#page=16) and the text below: "J-PAKE does not assign roles to the participants, so it is not necessary to call psa_pake_set_role()." and "J-PAKE requires both an application and a peer identity."

Our implementation (and its tests) currently do the exact opposite: calls to `set_user()` and `set_peer()` fail and calling `set_role()` is mandatory.

This task is to fix that by aligning our implementation and its tests on the specification.

Note: the description of `set_role` says the following, which applies to (EC) J-PAKE according to the above:

> For PAKE algorithms that do not require a role to be specified, the application can do either of the following:
> ∙ Not call `psa_pake_set_role()` on the PAKE operation.
> ∙ Call `psa_pake_set_role()` with the `PSA_PAKE_ROLE_NONE` role.

~Suggested implementation strategy:~ EDIT: won't work that easily, due to the fact the I/O formats depend on the role, so we'll need to investigate and decide if we go along these lines or go for something completely different, creating a generic (not TLS-specific) API that we can then use to implement PSA.
- In the legacy interface `ecjpake.[ch]`, add a new function `mbedtls_ecjpake_setup_ext()` that instead of `mbedtls_ecjpake_role role` takes two pairs of parameters: one of user, one for peer. The function stores a copy of the string in new fields in the context structure. The existing `mbedtls_ecjpake_setup()` can be implemented as a thin wrapper on top of `mbedtls_ecjpake_setup_ext()`.
- Remove the `role` filed in `mbedtls_ecjpake_context`; replace uses of `ID_MINE` / `ID_PEER` with access to the new fields in the context structure. Replace comparisons with `MBEDTLS_ECJPAKE_SERVER`/`CLIENT` with comparisons of the new fields to the strings "server" and "client".
- In `psa_pake_operation_t` add new fields for copies of the inputs to `set_user()`/`set_peer()` (if those haven't been added already by #6567). Temporarily change `set_role()` to set those fileds to "client" or "server". Change `psa_pake_ecjpake_setup` so that it uses `mbedtls_ecjpake_setup_ext()`. At this points the tests are still unchanged an everything should pass.
- Change the tests, as well as the functions `set_user()`, `set_peer()`, `set_role()`, to conform to the specification. This should all be trivial changes at this point.

Additional tests required compared to the current (non-compliant) API:
- things should work both without calling `psa_pake_set_role()`, or calling it with a value of `NONE`;
- calling `psa_pake_set_role()` with any other value should fail;
- attempting a PAKE operation where both sides do no use the same identifiers (for example, one uses user="client", peer="server" and the uses user="server", peer="oops-not-client") should fail - if I'm not mistaken, during one of the input steps (as some proof will be invalid).

**Dependencies:** while this does not strictly speaking depend on #6567 it seems highly desirable to wait until it's merged in order to avoid conflicts.

**Comment by mprse** [comment]
I think I can take this bug as at this point I'm familiar with J-PAKE. I think we should handle this after driver PR is merged.

**Comment by mpg** [comment]
I've been thinking we could actually divide this in two tasks:

1. one that only touches legacy EC J-PAKE (first two bullet points in the suggested strategy above);
2. one that builds on it to fix the PSA API.

The point being that the first task could be done in parallel with the driver PR with no risk of conflicts, in order to reduce latency. @mprse wdyt?

**Comment by mprse** [comment]
I think we can add `mbedtls_ecjpake_setup_ext()` that takes `user` and `peer` instead `role`, but `role` cannot be removed from `mbedtls_ecjpake_context`.

**Comment by mprse** [comment]
`peer` and `user` can be only `"server"` or `"client"`. Other strings should be rejected by core?

**Comment by mprse** [comment]
> mbedtls_ecjpake_setup_ext() that instead of mbedtls_ecjpake_role role takes two pairs of parameters: one of user, one for peer.

`takes two pairs of parameters: one of user, one for peer` shouldn't this be `two parameters: user and peer`?

**Comment by mpg** [comment]
@mprse Please don't start working on this right now, I'm going to split this issue into "quick partial fix" and "full fix (in two parts).

**Comment by mpg** [comment]
@mprse See #7149 for a the suggested stop-gap hotfix.

Arguably, once #7149 is done, supporting strings other than "client"/"server" could be seen as an enhancement request rather than a bugfix, since this becomes a documented limitation of our implementation as opposed to a full-on non-compliance. (Not quite, see below, there's an impact on the driver API as well.)

Supporting arbitrary ID strings is not going to be easy because the role influences the I/O format of the functions from the legacy interface that the PSA implementation is calling. So, the strategy suggested above does not work as it stands.

If there is no time pressure to support arbitrary ID strings, a cleaner strategy would be for the PSA implementation to directly call the currently-internal functions that correspond to each step (such as `ecjpake_zkp_read()` etc.) rather than calling the current public functions that include several steps at once, grouped and (de)serialized according to what TLS does. However that would be a significant overhaul of the PSA implementation, which we may not want to do now. I'm re-labeling this issue "size-l" to indicate that it needs further study to decide on a strategy and break-down once a strategy is decided.

Note: we should also study the impact on the driver API. For now the quick fix suggested in #7149 has the core rejecting strings other than "client" and "server", and set `role` in `operation->data.inputs`, which is not correct yet: the core should set `user_id`, `user_id_len`, `peer_id` and `peer_id_len` in `operation->data.inputs` without looking at the values (other than making a defensive copy I guess), and then the driver would decide what to do with it - our built-in implementation would reject anything other than a "client"/"server" pair (and internally translate to role) when the core passes the inputs to it during setup.

So, after #7149 I'd say two things remain to be done:
1. Adapt the driver interface so that the core passes the correct inputs to drivers (that is, user/peer rather than role) and let our built-in driver reject what it doesn't support. I expect this should be be too hard, and this is still a bugfix as the driver API is not correct until it's done.
2. Extend our built-in implementation so that it supports arbitrary ID strings rather than just "client"/"server". This might be harder and requires some study to decide on a strategy. However I'd consider this an enhancement request and we could decide to wait until someone requests it (perhaps everyone's using "client"/"server" after all).

Cc @ronald-cron-arm @gilles-peskine-arm regarding the driver API. Looking quickly as the spec, it's not suited to a fully general implementation of J-PAKE as described by the RFC and the PSA Crypto draft spec: we shouldn't need `psa_crypto_driver_pake_get_role()` but we would need `psa_crypto_driver_pake_get_user()` and `psa_crypto_driver_pake_get_peer()`. The hazards of creating the driver specification based on a non-compliant implementation :(

**Comment by gilles-peskine-arm** [comment]
I haven't looked at the details again, but this sounds like a good plan. We don't have to get things right the first time: that's why we're releasing things as beta. I won't be confident we got the PAKE application and driver interfaces right until we implement protocols other than JPAKE, anyway. So they're likely to remain beta for a long time.

(Sorry for not replying earlier.)

**Comment by mpg** [comment]
Closing as this has been broken down into:
1. https://github.com/Mbed-TLS/mbedtls/issues/7149
2. https://github.com/Mbed-TLS/mbedtls/pull/7196
3. https://github.com/Mbed-TLS/mbedtls/issues/7291
