### ISSUE TITLE
record_size_limit extension

### ISSUE THREAD

**Issue by KloolK** [Mbed-TLS/mbedtls#6967]
The `record_size_limit` extension (https://datatracker.ietf.org/doc/html/rfc8449) does not seem to be supported currently.

For TLS 1.3, mbedtls does not support the (deprecated) `max_fragment_length` extension (https://datatracker.ietf.org/doc/html/rfc6066):
https://github.com/Mbed-TLS/mbedtls/blob/8296eabed618351be21f171f5089a0f4c9c5c5e2/docs/architecture/tls13-support.md?plain=1#L48

and neither the `MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH` config option (which depends on the `max_fragment_length` extension):
https://github.com/Mbed-TLS/mbedtls/blob/8296eabed618351be21f171f5089a0f4c9c5c5e2/docs/architecture/tls13-support.md?plain=1#L126

Thus, the only way to reduce I/O buffer sizes in TLS 1.3 is to change `MBEDTLS_SSL_OUT_CONTENT_LEN` and/or `MBEDTLS_SSL_IN_CONTENT_LEN`.
As stated in the documentation, changing `MBEDTLS_SSL_IN_CONTENT_LEN` to anything below its default `16384` requires communicating that change to peers in some other way:
https://github.com/Mbed-TLS/mbedtls/blob/8296eabed618351be21f171f5089a0f4c9c5c5e2/include/mbedtls/mbedtls_config.h#L3684-L3691

Are there any plans on supporting the `record_size_limit` extension? I could not find anything on the [roadmap](https://mbed-tls.readthedocs.io/en/latest/roadmap/).

I might be able to invest development time into this, but I'd like to hear your opinion on this first. Also regarding any potentially conflicting upcoming changes I might not be aware of.

Subtasks:
- #7006 
- #7007 
- #7010 
- #7011 
- #7012 
- #7027

**Comment by yanesca** [comment]
Hi @KloolK thank you for suggesting this enhancement and for offering your help. We think that this would be a valuable addition and would be happy to take it if you would like to contribute.

We prefer to take contributions in small chunks, this for example we could take divided into 4 consecutive PRs. According to our preliminary estimates the first two would be small (around 2 days of work each) and the second two would be medium (around 5 days of work each).

Do you think you would like to invest that kind of development time into this? If so, please let me know and I'll create a task breakdown.

**Comment by KloolK** [comment]
Thanks for the estimate. I expect to be able to invest this amount of time over the course of around 2-3 months and would like to do so.

Please feel free to go ahead and create the task breakdown.

**Comment by yanesca** [comment]
@KloolK thank you again for offering your help! I have raised issues for the subtasks: https://github.com/Mbed-TLS/mbedtls/issues/7006, https://github.com/Mbed-TLS/mbedtls/issues/7007, https://github.com/Mbed-TLS/mbedtls/issues/7010, https://github.com/Mbed-TLS/mbedtls/issues/7011, https://github.com/Mbed-TLS/mbedtls/issues/7012, https://github.com/Mbed-TLS/mbedtls/issues/7027

Please let me know if you need any help or clarification.

**Comment by KloolK** [comment]
@yanesca Thank you for the subtasks. I'm sure they will provide a great starting point / guidance for me. After a first quick look, everything seems to be clear for now.

I'll report about my progress.

**Comment by ronald-cron-arm** [comment]
Changed the label `size-l` to `size-xs` as the work has been broken down into several tasks.

**Comment by tom-cosgrove-arm** [comment]
Closing as the broken-down issues are all complete

**Comment by yanesca** [comment]
> Closing as the broken-down issues are all complete

These two still seem to be open:
https://github.com/Mbed-TLS/mbedtls/issues/7012
https://github.com/Mbed-TLS/mbedtls/issues/7027

**Comment by tom-cosgrove-arm** [comment]
Those two issues were moved to the "TLS 1.3 Misc" epic
