### ISSUE TITLE
MS-MPPE-RECV key is not getting decrypted correctly in MBEDTLS

### ISSUE THREAD

**Issue by ajaykrmishra** [Mbed-TLS/mbedtls#6972]
### Summary
I am running Mbed TLS as a core security library(2.24.0), in embedded platform.
I am using the FreeRADIUS server for AAA authentication.
I am able to get the PMK values correctly at the supplicant side, however while decrypting the MPPE key at the gateway side I see that the values are incorrect specially in the API(radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt)

Also one more observation, in the API(radius_client_sec_prot_receive) the value of the 'recv_response_authenticator' and 'calc_response_authenticator' is not matching.
The 'calc_response_authenticator' is not matching with the received value. The API 'radius_client_sec_prot_response_authenticator_calc' is not calculating the correct value. 
Has someone faced a similar issue ?
Can someone suggest what could be wrong here ?

Below are my setup details:
FreeRADIUS(3.2.1) server setup on Ubuntu(22.04)
openssl :1.1.1f
Ubuntu version : 20.04.04LTS

Client side setup
Platform : Micro controller based platform
OS : FreeRTOS
Sample example

MPPE KEY in clear at RADIUS Server
Fri Dec 30 23:50:13 2022 : Debug: (209) MS-MPPE-Recv-Key = 0x2f6c3e7e748eb49a598c208af3ef520454f5aa6873bc72f7f32be1053914a566
Fri Dec 30 23:50:13 2022 : Debug: (209) MS-MPPE-Send-Key = 0xa04539819a272e94782af1818b05878bb0e420d08a51accd6c3cb75baaecbd75

PMK Key values at Supplicant(which is same as MPPE-RECV-KEY)
2022-12-30 23:50:07.313 https://github.com/Mbed-TLS/mbedtls/issues/1 0000000000000000 0:28:21.215 [debug] [ tlsp] {Wi-SUN Ev}: >>>> PRINT THE KEY PMK >>>>
2022-12-30 23:50:07.313 https://github.com/Mbed-TLS/mbedtls/issues/1 0000000000000000 0:28:21.224 [debug] [ tlsp] {Wi-SUN Ev}: EAP-TLS key material 2f:6c:3e:7e:74:8e:b4:9a:59:8c:20:8a:f3:ef:52:04:54:f5:aa:68:73:bc:72:f7:f3:2b:e1:05:39:14:a5:66

2022-12-30 23:50:07.313 https://github.com/Mbed-TLS/mbedtls/issues/1 0000000000000000 0:28:21.240 [debug] [ tlsp] {Wi-SUN Ev}: EAP-TLS key material a0:45:39:81:9a:27:2e:94:78:2a:f1:81:8b:05:87:8b:b0:e4:20:d0:8a:51:ac💿6c:3c:b7:5b:aa:ec:bd:75

Decrypted key Value at Authenticator(using radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt)
2022-12-30 23:51:34.763 https://github.com/Mbed-TLS/mbedtls/issues/1 0000000000000000 3:09:17.919 [debug] [ hmac] {Wi-SUN Ev}: hmac_md key a9:69:02:e9:3a:1d💿05:31:b3:77💿d6:d7:c2:c7:2d:52:4b:0a:5b:b1:aa:81:20:67:dd:b8:1c:04:ef:63

Mbed TLS version (number or commit id): 2.24.0
Operating system and version:
Configuration (if not default, please attach mbedtls_config.h):
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):
Additional environment information:

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
The key should be decrypted with correct value.

### Actual behavior
The key is not getting correct value.

### Additional information
Kindly let me know what I am missing here ?
Thanks in advance.
Ajay

**Comment by yanesca** [comment]
Hi @ajaykrmishra thank you for using Mbed TLS.

Based on the details you provided I think that you might be looking for some technical support and not trying to report a bug.

The maintainer team doesn't offer technical support, Mbed TLS is community-supported. You can ask the community for help on the mailing list: [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org)

I am going to close this issue now, but feel free to reopen it if I misunderstood and you really wanted to report a bug in Mbed TLS.

**Comment by ajaykrmishra** [comment]
Hi @yanesca 

Thanks for your prompt response. 
It is a defect in the MBED-TLS, where the request authenticator values are not calculated properly and the PMK key is not getting correctly decoded. 
I raised this earlier in the MBED-TLS support forum but couldn't get any response hence raised it here again. Please see below:
https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/X2ZOTOGM3AL5H27QV22CPVAGAZSMVYC2/

Can you please reopen it.
Thanks !

With regards,
Ajay.

**Comment by yanesca** [comment]
> It is a defect in the MBED-TLS, where the request authenticator values are not calculated properly and the PMK key is not getting correctly decoded.

Based on your report, the bug can be anywhere in the system and it is not necessarily in Mbed TLS. Could you please isolate the issue and describe it in terms of Mbed TLS APIs?

I mean something like this: I am calling `mbedtls_xxx()` with X, Y and Z parameters and the function writes A to the output, but that is incorrect, because the result should be B.

**Comment by ajaykrmishra** [comment]
Thank you for getting back.
So there are two issues that I have found and both of them is related to the mbedtls_md5_*  API's.

1) The issue is seen in the API **radius_client_sec_prot_response_authenticator_calc**, where we are calculating the md5 checksum. The receive value of the message authenticator from the RADIUS Server and calculated value is not matching. The value is calculated using the mbedtls_md5_*
The receive value is: 
2023-01-27 17:53:56.344 #1   0000000000000000 <log> 0:34:05.867 [debug] [        radd] {Wi-SUN Ev}: recv_response_authenticator: ( 1/ 1): **ac1150f8a6f2b6cd6b3b75ad7a0fed19**

And the calculated value is:
2023-01-27 17:53:56.517 #1   0000000000000000 <log> 0:34:06.010 [debug] [        radd] {Wi-SUN Ev}: calc_response_authenticator: ( 1/ 1): **76b661aa92e996df1df8c7189b499ea1**

The above value is calculated by using the mbedtls_md5_* API's, as listed in **radius_client_sec_prot_response_authenticator_calc**.

I have checked the input parameters to the **radius_client_sec_prot_response_authenticator_calc** which are expected values. But somehow the correct results are not returned by the mbedtls_md5_ API's.

2) The second issue is related to the PMK key(MS-MPPE-RECV-KEY) not getting decrypted, which is received from the RADIUS Server in ACCESS-ACCPT packet in the **radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt**. 

Below are some logs.

At RADIUS Server 
MPPE KEY in clear at RADIUS Server
Fri Dec 30 23:50:13 2022 : Debug: (209) MS-MPPE-Recv-Key = **0x2f6c3e7e748eb49a598c208af3ef520454f5aa6873bc72f7f32be1053914a566**

Decrypted key Value at Authenticator()
2022-12-30 23:51:34.763 #1   0000000000000000 <log> 3:09:17.919 [debug] [        hmac] {Wi-SUN Ev}: hmac_md key **a9:69:02:e9:3a:1d:cd:05:31:b3:77:cd:d6:d7:c2:c7:2d:52:4b:0a:5b:b1:aa:81:20:67:dd:b8:1c:04:ef:63**
The above value at the authenticator is decrypted by the radius client API **radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt**.
The above uses the mbedtls_md5_* APIs to decrypt the keys.

Kindly let me know if you need any more information.

Thanks again !

With regards,
Ajay.

**Comment by yanesca** [comment]
> And the calculated value is:
2023-01-27 17:53:56.517 https://github.com/Mbed-TLS/mbedtls/issues/1 0000000000000000 0:34:06.010 [debug] [ radd] {Wi-SUN Ev}: calc_response_authenticator: ( 1/ 1): 76b661aa92e996df1df8c7189b499ea1

I see, so that is the output. We still need a bit more information to evaluate/reproduce a bug here:
- Which Mbed TLS function was called to calculate this?
- What were the exact inputs to that function?
- How were these inputs set up?

**Comment by ajaykrmishra** [comment]
Thank you for you r prompt response. 
So we are trying to calculate the MD5 checksum to check the authenticity of messages received from the FreeRADIUS server.
I am using the API,  **radius_client_sec_prot_response_authenticator_calc** which is implemented in the file build/3pp/nanostack/mbed-os/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/**radius_client_sec_prot.c**

Which Mbed TLS function was called to calculate this?
[Ajay]: So the API **radius_client_sec_prot_response_authenticator_calc** is using mbedtls_md5_*  to calculate the checksum. As listed below:

865 static int8_t radius_client_sec_prot_response_authenticator_calc(sec_prot_t *prot, uint16_t msg_len, uint8_t *msg_ptr, uint8_t *auth_ptr)
 866 {
 867 #ifdef MBEDTLS_MD5_C
 868     if (prot->sec_cfg->radius_cfg->radius_shared_secret == NULL || prot->sec_cfg->radius_cfg->radius_shared_secret_len == 0) {
 869         return -1;
 870     }
 871 
 872     const uint8_t *key = prot->sec_cfg->radius_cfg->radius_shared_secret;
 873     uint16_t key_len = prot->sec_cfg->radius_cfg->radius_shared_secret_len;
 874     if (prot->sec_cfg->radius_cfg->radius_shared_secret_len == 0) {
 875         return -1;
 876     }
 877 
 878     int8_t ret_value = -1;
 879 
 880     mbedtls_md5_context ctx;
 881 
 882     tr_info("<<<<Inside %s >>>>>>>", __FUNCTION__);
 883     tr_info("key_len : %d",key_len);
 884     tr_info("key     : %s",key);
 885     tr_info("msg_len     : %d",msg_len);
 886     logHex(LogLevelDebug, LOG_MODULE, ">>>>>>>>>>key", key, key_len);
 887 
 888     mbedtls_md5_init(&ctx);
 889 
 890     if (mbedtls_md5_starts_ret(&ctx) != 0) {
 891         goto end;
 892     }
 893 
 894     logHex(LogLevelDebug, LOG_MODULE, "msg_ptr:", msg_ptr, msg_len);
 895 
 896     if (mbedtls_md5_update_ret(&ctx, msg_ptr, msg_len) != 0) {
 897         goto end;
 898     }
 899 
 900     if (mbedtls_md5_update_ret(&ctx, key, key_len) != 0) {
 901         goto end;
 902     }
 903 
 904 
 905     if (mbedtls_md5_finish_ret(&ctx, auth_ptr) != 0) {
 906         goto end;
 907     }
 908 
 909     logHex(LogLevelDebug, LOG_MODULE, "auth_ptr:", auth_ptr, 16);
 910     ret_value = 0;

What were the exact inputs to that function?
[Ajay] Here are the inputs the API needs.
sec_prot_t *prot => This is used to setup the key value from the freeradius shared secret(_key_) and length(_key_len_)
uint16_t msg_len => Input _length_ from the FreeRADIUS request packet. 
uint8_t *msg_ptr =>  Input _data_ from the FreeRADIUS request packet.
uint8_t *auth_ptr => The checksum value calculated after the MD5 checsum value, which is used in _mbedtls_md5_finish_ret_.

How were these inputs set up?
[Ajay] The inputs are setup by the FreeRADIUS packet. I can confirm that the values setup look correct and there is no memory correction as I have verified them from the packet captures from the wireshark.

For the above below is some data inputs:
Expected MD5 hash value : 247e088e2f152c98cac41378c5d42a49
Calculated MD5 hash value:  939338c389b8c27981302dc355b04aac

Input parameters:
2023-02-01 22:13:26.231 #1   0000000000000000 <log> 22:46:07.583 [debug] [        radp] {Wi-SUN Ev}: **key_len** : 11
2023-02-01 22:13:26.274 #1   0000000000000000 <log> 22:46:07.589 [debug] [        radp] {Wi-SUN Ev}: **key**     : abcdefghij
2023-02-01 22:13:26.274 #1   0000000000000000 <log> 22:46:07.596 [debug] [        radp] {Wi-SUN Ev}: **msg_len**     : 64
2023-02-01 22:13:26.274 #1   0000000000000000 <log> 22:46:07.603 [debug] [        radd] {Wi-SUN Ev}: >>>>>>>>>>key: ( 1/ 1): 6162636465666768696a00

The _msg_ptr_ recieved from the FreeRADIUS request:
2023-02-01 22:13:26.318 #1   0000000000000000 <log> 22:46:07.643 [debug] [         md5] {Wi-SUN Ev}: >>>>>>>>>>>>>>>end  :mbedtls_md5_starts_ret >>>>>>>>>>>>>>
2023-02-01 22:13:26.318 #1   0000000000000000 <log> 22:46:07.653 [debug] [        radd] {Wi-SUN Ev}: msg_ptr:: ( 1/ 4): 0b00004015d8d4d9320c470db8dc474f
2023-02-01 22:13:26.318 #1   0000000000000000 <log> 22:46:07.663 [debug] [        radd] {Wi-SUN Ev}: msg_ptr:: ( 2/ 4): 40148eb94f08010200060d205012b71d
2023-02-01 22:13:26.363 #1   0000000000000000 <log> 22:46:07.673 [debug] [        radd] {Wi-SUN Ev}: msg_ptr:: ( 3/ 4): c745bef338ef15d1695196d003171812
2023-02-01 22:13:26.363 #1   0000000000000000 <log> 22:46:07.683 [debug] [        radd] {Wi-SUN Ev}: msg_ptr:: ( 4/ 4): c79f030dc79d0e017032806682b8df38
2023-02-01 22:13:26.363 #1   0000000000000000 <log> 22:46:07.693 [debug] [        radd] {Wi-SUN Ev}: auth_ptr:: ( 1/ 1): 939338c389b8c27981302dc355b04aac

I am attaching a log file with the code snippets and debug logs so that above inputs are more clear.
Kindly let me know if you require further information and I will be happy to provide the same.

Many thanks for you response !

With regards,
Ajay.

[log_wisun_Mbetls_MD5.txt](https://github.com/Mbed-TLS/mbedtls/files/10562773/log_wisun_Mbetls_MD5.txt)


![Debug Logs mbed tls](https://user-images.githubusercontent.com/87020461/216186616-a319c880-30fb-434b-84cb-586cae54d5b1.JPG)

**Comment by ajaykrmishra** [comment]
@yanesca Thanks again.
I am able to solve both the issues. 
The issue is with the incorrect **key-len** value that we get from the prot (sec_prot_t *prot). 
I modified the key-len value like below in both the APIs **_radius_client_sec_prot_response_authenticator_calc_**  and **_radius_client_sec_prot_ms_mppe_recv_key_pmk_decrypt_**
 uint16_t key_len = prot->sec_cfg->radius_cfg->radius_shared_secret_len **- 1**;

And I can confirm that I am able to get the correct MD5 results in both the APIs.
Can you please confirm if the value of the shared secret should be actual length of the string or it should include the NUL value as well ?
In my scenario, the key value is = "abcdefghij"
The struct returns the key length as 11 which caused the issue. 
If I change the value to 10 it works fine.

Need to check where the radius protocol specific values are setup. 

Thank you!

With regards,
Ajay.

**Comment by yanesca** [comment]
That is marvellous, I am happy that you managed to find the issue.

The `'\0'` value at the end is a string terminator that the C language appends and uses for strings. It is not part of the key/password.

**Comment by ajaykrmishra** [comment]
Thank you @yanesca !!!
I found out that the key-len is incorrectly setup in the MBED, nanostack code. 
Filename : **./build/3pp/nanostack/cc/borderrouter_ws.c**
API:  **mesh_network_up**()

Here the length is passed as the sizeof which includes the '\0' and hence we are seeing this issue. Below is the code listing:
185        static uint8_t sharedSecret[]      = "abcdefghij";  // TODO: Change this
186         /*CyanConnode Key length - to be changed*/
187         ws_bbr_radius_shared_secret_set( wisun_if_id, **sizeof(sharedSecret)**,&sharedSecret[0] );

The **sizeof(sharedSecret)** needs to change to **strlen** or as  **sizeof(sharedSecret) - 1**
Since this is not related to MBED-TLS, I will report the issue in the MBED nanostack group.

Thank you for your help !

With regards,
Ajay.
