### ISSUE TITLE
Unify HMAC implementation between MD and PSA

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#6995]
https://github.com/gilles-peskine-arm/mbedtls/blob/psa-migration-md-cipher-strategy/docs/architecture/psa-migration/md-cipher-dispatch.md#unify-hmac-with-psa

**Comment by mpg** [comment]
Don't we have a problem with driver initialisation, though? Otherwise we could apply this optimisation to hashes as well.

**Comment by gilles-peskine-arm** [comment]
We'd have to make sure that if a hash or HMAC is accelerated but the driver isn't initialized, the dispatch goes to the legacy hash module (either directly or via the PSA hash layer). We also need to dispatch to the legacy hash module when PSA is completely disabled. So there's some tweaking to do to the HMAC code. Perhaps make it call md light? We need to play around with it a bit to minimize the number of dispatch layers (or at least layers that aren't zero-cost).

**Comment by mpg** [comment]
Perhaps I misunderstood what this possible optimization was about, but I thought it was about saving code size by having a single implementation of HMAC in builds that have both PSA and MD enabled. So, doing dynamic dispatch to legacy or PSA depending on whether PSA is initialized or not clearly goes against that goal.

> Perhaps make it call md light?

That's already what the code is doing: the HMAC part of MD is implemented in terms of `mbedtls_md_xxx` functions entirely. So, once MD light (that is, the hashing part of MD) is able to dispatch to PSA for accelerated hashes, that will automatically be the case for HMAC as well without doing anything specifically about it, unless I'm missing something big.

So, again, I thought this was really just about saving code size by avoiding what's essentially duplication in builds when we have both PSA and MD.

Note: I'm really tempted to revisit whether we want to (temporarily) disallow init functions for hash drivers, because:

- if we did that it would allow:
  - significantly simplifying the design by making MD just always to PSA in builds that have PSA;
  - saving code size in those builds by having only one implementation of "generic hash" (currently the large `switch( hash )` statements are largely duplicated between `md.c` and `psa_crypto_hash.c`);
- I'm more and more uncomfortable saying that we support `init` functions for hash drivers while we're not testing that. Currently it's unlikely to be an issue but once we move `entropy.c` to using MD-light, this raises questions about initialisation order and we can't really be sure we got it right (and won't break it in the future) if we don't actually have tests for that. That's certainly doable and certainly something we should be doing at some point, but if we can just define the problem out of existence for the time being I really wouldn't mind.

**Comment by mpg** [comment]
For the record, there was a misunderstanding on my side: I thought you mean "unify by just calling PSA from MD all the time", which doesn't work, but actually that's not the only approach to unification.

>  One reason is that it is a natural design to have an init function that does hardware detection. Sure, you can do it the first time an operation function is called, but that's a design wart. 

Right. Let's forget about this then.

**Comment by mpg** [comment]
For the record:

1. I don't think there's an easy strategy that works here considering the constraints, in particular the fact that we cant' rely on PSA being initialized. (I'm sure we could find a strategy that works, but I think the effort to design and implement it would be significant.)
2. I'm not convinced this is a great use of our time now, considering:
    a. Code size is only saved in configurations that have both `PSA_CRYPTO_C` and the full `MD_C` (as opposed to `MD_LIGHT`) enabled. IMO users who use PSA and care about code should (quit using MD directly if they were still doing so) and undefine `MD_C` (and rely on `build_info.h` to enabled `MD_LIGHT`).
    b. As I said, I think the design complexity is significant now, but it would become trivial after 4.0.

@tom-cosgrove-arm can we discuss this when you get back?

**Comment by mpg** [comment]
After discussing this with @tom-cosgrove-arm we agreed to close as rejected due to an unfavorable cost/benefit ratio:
- the cost is pretty high as this would require some design effort;
- this would only benefit 3.x as this will all go away in 4.0;
- TF-M can reach the same benefits just by stopping to use the legacy API for HKDF (and HMAC), and using only the PSA Crypto API for that, which they plan to do anyway - then disabling `MBEDTLS_HKDF_C` and `MBEDTLS_MD_C` in their config.

Regarding that last point:
- if TF-M is using the legacy HMAC API, then they can use the pair of programs `programs/psa/hmac_demo.c` and `programs/hash/md_hmac_demo.c` as an example for their migration.
- for the HKDF API, we have a PR pending with an example program: https://github.com/Mbed-TLS/mbedtls/pull/7944/files
- @tom-cosgrove-arm will make some measurements/estimate regarding what TF-M could save by using only the PSA API and not the legacy API for HMAC and HKDF, and communicate the results to them.

Overall, this is not just TF-M: any user who doesn't want to pay the price of having two implementations of HMAC (or HKDF for that matter) can already achieve that, with no change on our side, by using only one of the two APIs for that - preferably PSA as it's the future.

So, closing as rejected.
