### ISSUE TITLE
Remove driver entry points for psa_interruptible_{get/set}_max_ops

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#7032]
From Gilles:

> Rather than have driver entry points for set_max_ops and get_max_ops (which would be per operation), how about making this a simple global variable, and allowing drivers to call get_max_ops when they need the value? (With an operation argument, which the core would in practice ignore — except maybe in the future in multithreaded environments.)

**Comment by paul-elliott-arm** [comment]
The problem with this is: where do you place the call to `mbedtls_ecp_set_max_ops()`? I can do everything as above, but it breaks when you try to change max_ops mid operation,  as I can now only call `mbedtls_ecp_set_max_ops()` from the start functions. 

I cannot call this from the PSA layer (nor would I want to) and without a driver layer I cannot call the internal function either. I could potentially remove the get driver entry point, but not the set, basically.

If I am not explaining this well enough I can push a PR of what I have got (but which won't pass CI due to the above failures)

**Comment by gilles-peskine-arm** [comment]
> where do you place the call to mbedtls_ecp_set_max_ops()

Before each call to `mbedtls_xxx_restartable`.

> I can now only call mbedtls_ecp_set_max_ops() from the start functions.

Why?
