### ISSUE TITLE
Support AES in PKCS5

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7038]
The PBES2 tests in `test_suite_pkcs5` all rely on [DES, which is deprecated](https://github.com/Mbed-TLS/mbedtls/issues/7024). The PKCS5 module does not support AES, but it's cryptographically agile, so it should be easy to add AES support.

The goal of this task is:

* Add the [AES-CBC OID from RFC 8018](https://www.rfc-editor.org/rfc/rfc8018#appendix-C) to the OID module.
* In `test_suite_pkcs5`, add test cases using AES, equivalent to what we have for DES.

**Comment by jethrogb** [comment]
It's not just about the test suite, the pkcs5 module just doesn't support PBES2-AES at all right now.

**Comment by gilles-peskine-arm** [comment]
@jethrogb Good point! Fortunately the PKCS5 module has no direct dependency on DES, so I think adding AES support is as easy as declaring the OID… and adding test cases.

**Comment by zvolin** [comment]
Hi!
Tried your suggestion by only declaring the OIDs however I ended up debugging some segfault all the yesterday's evening :sweat_smile: . Will try to look more into it tho, however I'm not so familiar with the project

**Comment by jethrogb** [comment]
@zvolin and I were discussing the `mbedtls_pkcs5_pbes2` API and it's not clear to us how to use it safely. What are the requirements on the `output` buffer size and what is the actual size used on return?

**Comment by jethrogb** [comment]
`mbedtls_pkcs5_pbes2` calls `mbedtls_cipher_crypt` internally. `mbedtls_cipher_crypt` specifies `input` and `output` should be different memory ranges. `mbedtls_pkcs5_pbes2` passes these directly from its own arguments `data` and `output`. The only MbedTLS-internal use of `mbedtls_pkcs5_pbes2` is in `pkparse.c` where it passes `p` and `buf` right after a statement `buf = p`.

**Comment by gilles-peskine-arm** [comment]
Requested again: https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/Z62P3AIHGJ3H4KXI7HXAELNAEQFCWHHM/
