### ISSUE TITLE
Remove legacy dependencies from PSA tests

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7061]
PSA test suites should mostly not have legacy dependencies anymore. We mass-removed them with the help of [`tests/scripts/set_psa_test_dependencies.py`](https://github.com/Mbed-TLS/mbedtls/blob/development/tests/scripts/set_psa_test_dependencies.py) in #4012, #4158 and #4246. But we don't run this script on a regular basis. Some legacy dependencies have either escaped the renaming (some negative test cases aren't handled by the script) or snuck back in.

The goal of this task is to remove legacy dependencies from `test_suite_psa_*` except for ones that we decide are explicitly excused. The following dependencies are excluded from this issue:

* `MBEDTLS_GENPRIME` when generating RSA keys — no PSA equivalent.
* `MBEDTLS_ENTROPY_NV_SEED` in init tests — no PSA equivalent.
* `MBEDTLS_PK_WRITE_C` and `MBEDTLS_PK_PARSE_C` — tracked in https://github.com/Mbed-TLS/mbedtls/issues/7055.

Definition of done: this should return no hits (currently 135):
```
perl -ne 's/depends_on:// or next; print "$ARGV:$.:$_\n" foreach grep !/^MBEDTLS_(GENPRIME|PSA_.*|PK_PARSE_C|PK_WRITE_C|ENTROPY_NV_SEED)$/, /\bMBEDTLS_\w+/g' tests/suites/test_suite_psa*
```

Note: if some hits really can't be translated to PSA, remove the ones that can be, and evaluate whether the remaining hits should be excused or what's going on.

Although not a dependency, we'll probably want to do https://github.com/Mbed-TLS/mbedtls/issues/7062 around the same time, to avoid having to deal with the problem again in the future.

**Comment by mpg** [comment]
> * `MBEDTLS_GENPRIME` when generating RSA keys — no PSA equivalent.

Note: this recently gained a PSA equivalent, with the introduction of `KEYPAIR_GENERATE`, and all occurrences of this were replaced.
