### ISSUE TITLE
mbedtls_ssl_get_ciphersuite(ssl_context) says AES_GCM but ctx->mode is MBEDTLS_MODE_ECB

### ISSUE THREAD

**Issue by cpp77** [Mbed-TLS/mbedtls#7066]
After `mbedtls_ssl_handshake()` is successful I log the cipher suite being used:

`const char* cipher_suite = mbedtls_ssl_get_ciphersuite(const_cast<const mbedtls_ssl_context*>(&_ssl));`

It outputs:

`TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256`

which is the cipher suite I want. The code continues and receives Application messages.

However, when I pause and step through `mbedtls_cipher_update()`, the cipher mode is shown as `MBEDTLS_MODE_ECB`:

![image](https://user-images.githubusercontent.com/68331919/217690205-19cc8320-7890-475b-a961-c7e32684e53e.png)

I expected it to be `MBEDTLS_MODE_GCM`. Is this a misunderstanding somewhere on my part?

My repo is using f31c9e441b949944db6dc1a23a6ce579e635d57d

**Comment by gilles-peskine-arm** [comment]
GCM is an authenticated encryption mode. It uses a block cipher in CTR mode for the encryption part. Our GCM code implements the counter aspect of CTR inside `gcm.c` (I think that's an optimization), and uses a cipher context in ECB mode to process individual blocks. So in the `mbedtls_cipher_context` for GCM, the cipher-specific context points to a `mbedtls_gcm_context` object. Inside that object, there's an `mbedtls_cipher_context` in ECB mode. You're looking at that inner ECB mode context.

CCM has the same design, by the way.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because it is neither a bug report nor a feature request.

**Comment by cpp77** [comment]
@gilles-peskine-arm Thanks for your response. So GCM and ECB are not alternatives to one another, ECB is the mode which encrypts each block in parallel for GCM? 

From Googling, the above makes sense. However, I don't understand why `MBEDTLS_MODE_ECB` and `MBEDTLS_MODE_GCM` are both checked in `mbedtls_cipher_update()`? I know the GCM is surrounded with a #`ifdef` but the behavior reads like this:

```
mbedtls_cipher_update()
{
    switch (mode)
    {
        case MBEDTLS_MODE_ECB:
        // stuff
        
         case MBEDTLS_MODE_GCM:
        // stuff
    }
}
```

which does make them look like substitutes to one another?

I guess my question is: under what circumstances is `case MBEDTLS_MODE_GCM` executed?

**Comment by gilles-peskine-arm** [comment]
During the execution of a GCM operation, there are two `mbedlts_cipher_context` objects: the outer context used by the TLS code, which is in GCM mode; and the inner context used by the GCM code, which is in ECB mode.
