### ISSUE TITLE
Add negative test cases for tls1.3 early data

### ISSUE THREAD

**Issue by xkqian** [Mbed-TLS/mbedtls#7068]
### Suggested enhancement
Need negative cases to verify the ciphersuite mismatch, selected_id not equal to 0 .etc.

Add one extra option in ssl_client2 to set the different ciphersuite when resumtion.

[RC] Better to set up these tests in test_suite_ssl. It is not in the scope of ssl-opt.sh to test a client or server that misbehaves.
From the review on 6721, we need a test where a TLS 1.3 client try to resume a session with a ticket, send the early data extension but early data are not allowed for the ticket.

### Justification

Fullfill the test cases of early data, increase the coverage.

**Comment by yuhaoth** [comment]
https://github.com/Mbed-TLS/mbedtls/pull/6721/files#r1415606771 . 

Some test has been removed from existing PR per above reason. I think that belongs to this PR.

**Comment by ronald-cron-arm** [comment]
Close as won't do for the time being. Unfortunately, we have few TLS negative testing with a client/server that misbehaves and adding some for the TLS 1.3 early data feature is very low priority. We will revisit that when we expand that kind of testing of the TLS stack.

**Comment by tom-cosgrove-arm** [comment]
Rather than close this issue, and likely forget about it, why not move it to the TLS 1.3 misc epic and consider it a "COULD"?

**Comment by ronald-cron-arm** [comment]
I would rather link it to a general issue about TLS testing with a misbehaving peer. Do we have that?
