### ISSUE TITLE
CA callback not called in TLS 1.3

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7079]
Configuring a CA callback with `mbedtls_ssl_conf_ca_cb()` has no effect in TLS 1.3. This is not documented as a limitation, and there is no reason not to support it. See https://github.com/Mbed-TLS/mbedtls/issues/7075#issuecomment-1425604707

The goal of this task is to support a CA callback in TLS 1.3, the same way as in TLS 1.2.

This should be tested both from the server side and the client side.

**Comment by gilles-peskine-arm** [comment]
Related: [TLS currently doesn't support the X.509 certificate extension callback](https://github.com/Mbed-TLS/mbedtls/issues/7182) (only available via `mbedtls_x509_crt_parse_der_with_ext_cb`). Whatever method we add to make it support this, should work both for TLS 1.2 and TLS 1.3.

**Comment by adambvidex** [comment]
Is there a workaround for this bug? Our product requires it because the CA database cannot fit in RAM of the embedded device.

**Comment by ronald-cron-arm** [comment]
> Is there a workaround for this bug? Our product requires it because the CA database cannot fit in RAM of the embedded device.

#9002 fixes this issue.

**Comment by ronald-cron-arm** [comment]
Closing this issue as we have rather decided to address this more generally with #9018.
