### ISSUE TITLE
Save size when only MD light is enabled

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7119]
Implement the last paragraph of the definition of MD light:

> Unlike the full MD, MD light does not support null pointers as `mbedtls_md_context_t *`. At least some functions still need to support null pointers as `const mbedtls_md_info_t `* because this arises when you try to use an unsupported algorithm (`mbedtls_md_info_from_type()` returns `NULL`).

Edit (trying to clarify a bit): this is about [checks like this one](https://github.com/Mbed-TLS/mbedtls/blob/development/library/md.c#L458) we, when `MD_C` is defined, we have to keep for compatibility reasons, but when it isn't and only `MD_LIGHT` is, we have more freedom. In that case callers are other modules from the library (not applications), so we can assume people are not passing NULL pointers or context that were not properly setup.

The only exceptions are functions that directly take a `const mbedtls_md_info_t *` as a parameter (as opposed to a `mbedtls_md_contex_t *`) - here we need to handle NULL gracefully, as it's a common idiom (used in the library) to call them directly with the result of `mbedtls_md_info_from_type()` withtout checking for NULL first. I think the only two such functions are `mbedtls_md_setup()` and `mbedtls_md()` (but please double-check).

**Comment by mpg** [comment]
Also, when only `MD_LIGHT` is defined but not `MD_C`, we can remove the `hmac_ctx` field of `mbedtls_md_context_t` and the code that allocates & frees it in `setup()` and `free()`.

**Comment by tom-daubney-arm** [comment]
> Also, when only `MD_LIGHT` is defined but not `MD_C`, we can remove the `hmac_ctx` field of `mbedtls_md_context_t` and the code that allocates & frees it in `setup()` and `free()`.

Currently working on #7378 (and hence this issue too) and have noticed that this part of the work has already been implemented.

**Comment by mpg** [comment]
Ah, indeed. And according to `git blame`, this was done by me... Well, good to know :)
