### ISSUE TITLE
Generate key pairs which remain same

### ISSUE THREAD

**Issue by PrithviAPai** [Mbed-TLS/mbedtls#7129]
Hi Team,
I have a requirement to generate key pairs which remain same. Is there any provision in mbedTLS ? 
Any examples will help me a lot.

**Comment by daverodgman** [comment]
Closing as this is a support request - please address this kind of request to the mailing list mbed-tls@lists.trustedfirmware.org 

I'm not sure I fully understand the question, but it may be worth looking at the config option `MBEDTLS_ENTROPY_NV_SEED` - does this help with what you are looking for?
