### ISSUE TITLE
PBKDF2: implement `input_integer()`

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7130]
Implement `psa_key_derivation_input_integer()` ([spec](https://arm-software.github.io/psa-api/crypto/1.1/api/ops/kdf.html#c.psa_key_derivation_input_integer)). For now, it always returns `PSA_ERROR_INVALID_ARGUMENT`. Add negative unit tests (using `derive_input`) for:

- [x] Trying to use `input_integer(INPUT_COST)` at various stages of HKDF (invalid because HKDF has no cost).
- [x] Trying to use `input_integer(INPUT_xxx)` where INPUT_xxx is a valid bytes input to HKDF.
- [x] Trying to use `input_bytes(INPUT_COST)` where HKDF would expect a different input step.
- [ ] Correct input steps, but an invalid hash algorithm.
- [ ] Correct input steps, but the `PASSWORD` input is a key of a wrong type.
- [ ] Correct input steps, but the `PASSWORD` input is a key which does not allow `PSA_KEY_USAGE_DERIVE`.

Note: several tests use HKDF; this is intentional as we the new function and input types are only for PBKDF2 so we need to make sure that other KDFs that are already implemented correctly reject them.

**Comment by silabs-Kusumit** [comment]
@mpg Am I correct in understanding the testcases?
> Trying to use `input_integer(INPUT_COST)` at various stages of HKDF (invalid because HKDF has no cost).

> Trying to use `input_bytes(INPUT_COST)` where HKDF would expect a different input step.

If `PSA_KEY_DERIVATION_INPUT_COST` step is present in HKDF return `PSA_ERROR_INVALID_ARGUMENT`
> Trying to use `input_integer(INPUT_xxx)` where `INPUT_xxx` is a valid bytes input to HKDF.

`input_integer()` should not be used to provide inputs to HKDF

**Comment by mpg** [comment]
Cc @gilles-peskine-arm @ronald-cron-arm as I'm on holiday this week.

**Comment by gilles-peskine-arm** [comment]
@silabs-Kusumit Yes, this is correct.

**Comment by silabs-Kusumit** [comment]
@gilles-peskine-arm In `PSA_KEY_DERIVATION_INPUT_SALT` step is the case of `PSA_KEY_TYPE_PEPPER` to be handled differently than `PSA_KEY_TYPE_NONE`?

**Comment by gilles-peskine-arm** [comment]
@silabs-Kusumit We don't support `PSA_KEY_TYPE_PEPPER`, so for the time being, it's equivalent to any other invalid value such as `PSA_KEY_TYPE_NONE`. At the moment, none of the supported algorithms have a pepper input as distinct from salt, so we aren't yet tracking the desire to implement it.

**Comment by silabs-Kusumit** [comment]
@gilles-peskine-arm In all the algorithms (HKDF, PBKDF2) if one step has a bad input then should all the next steps have `PSA_ERROR_BAD_STATE` or only that step?
Example: HKDF: Input steps
1) secret with wrong key type
2) secret with correct key type
3) correct info
4) output

In this case will step 2 have `PSA_ERROR_BAD_STATE` or `PSA_SUCCESS`?

**Comment by gilles-peskine-arm** [comment]
If a step fails, the whole operation needs to be aborted. All subsequent steps should fail.

The reason it's designed that way is, especially in client-server implementations, implementers can't always distinguish between: the request wasn't even started, or the request failed midway and the data structure is corrupted, or the calculation was successful but reporting the status failed.

**Comment by silabs-Kusumit** [comment]
@gilles-peskine-arm Should I add the setup and struct declarations for PBKDF2 in this issue or should I include that in #7131?

**Comment by mpg** [comment]
Ah, right, indeed I think you need to implement `setup()` and have struct declarations for PBKDF2 in order to do any meaningful testing with it. I think there are two ways to go, either:
1. Split: First raise a PR that only tests with algs other than PBKDF2 (no need for `setup()` support and struct declaration); then raise a second PR with `setup()` + structs. (Note that the second PR might very well be the one that implements #7131.)
2. Directly raise a PR that includes `setup()` + structs and associated tests.

I'd say the choice depends on what size the PRs would be in each case. We strongly prefer smaller PRs (a handful of commits, at most a few hundred lines added/changed) as they allow iterating faster while keeping the quality high.
