### ISSUE TITLE
PBKDF2: implement `output_bytes()` (HMAC)

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7132]
Implement `psa_key_derivation_output_bytes()` for PBKDF2, ~using `mbedtls_pkcs5_pbkdf2_hmac_ext()`~ a pure-PSA implementation of PBKDF2, living in `psa_crypto.c` for now (as per the discussion below).

Note: we had an implementation of  `mbedtls_pkcs5_pbkdf2_hmac_ext()` based on PSA [in Mbed TLS 3.3.0](https://github.com/Mbed-TLS/mbedtls/blob/v3.3.0/library/pkcs5.c#L326), which can probably be useful as a starting point here.

Note: the implementation could be divided into steps, with one PR per step. For example:
1. Support only HMAC with just one block's worth of output, possibly in multiple calls to `output_bytes()` - if the application requests more, then an error is returned. (So, the library behaves as if `set_capacity(hash_output_size)` had been called.)
2. Support only HMAC with arbitrary output length.

(The above division is only a suggestion, but whatever steps are chosen, large PRs should be avoided.)

Add positive test cases (using `derive_output`) with for PBKDF2-HMAC with various hashes and costs. Only use low costs so that the generic test suite does not become too slow.

Follow-ups:
- #7134
- #7645

Edit: this is the first issue where the feature is complete enough to be usable; at this point we should add a ChangeLog entry.

**Comment by silabs-Kusumit** [comment]
@mpg From this [commit](https://github.com/Mbed-TLS/mbedtls/commit/49e67f814fc1ca5c5e48d787d5eeb4986c429ad6), pkcs5  only uses MD. So should the PSA implementation for PBKDF2_HMAC now be added directly in `psa_crypto.c`?

**Comment by mpg** [comment]
Good question! Actually the reason why pkcs5 now always use MD is that MD itself has gained the ability to call PSA when a driver is available. So, I think you can and should still use `mbedtls_pkcs5_pbkdf2_hmac_ext()` here, as it will dispatch to PSA when a driver is available.

**Comment by silabs-Kusumit** [comment]
@mpg The `mbedtls_pkcs5_pbkdf2_hmac_ext()` currently only supports single read for an operation. Adding multiple read functionality is simple but would require passing an additional parameter which would be an API change. 
Should I change the API or considering that CMAC work is planned on our side, write a different function which would accommodate both HMAC and CMAC with PSA API calls?

**Comment by mpg** [comment]
Ah, good point! We'd have to create `mbedtls_pkcs5_pbkdf2_hmac_ext2()` taking the extra parameter and then the API is starting to look clumsy, with 3 versions of the same function. One thing we could do is still create `mbedtls_pkcs5_pbkdf2_hmac_ext2()` but make in a library-internal function, declared in a new header `library/pkcs5_internal.h`. This would allow it to share its implementation with the existing functions, and be use by the PSA implementation, while avoiding cluttering the public header `pkcs5.h`.

Or, as you said, we could just re-implement PBKDF2-HMAC internally in PSA, based directly on PSA API calls.

@gilles-peskine-arm do you have an opinion on that, or other ideas?

**Comment by gilles-peskine-arm** [comment]
I'm not sure I understand the problem. What multiple reads are we talking about? What would be the extra parameter?

If this is about the fact that in the PSA API, you don't know in advance how much output the application will ask for: with PBKDF2, longer output requires doing almost all of the computation. So I guess the PSA layer should call the pkcs5 layer for one output block at a time. But I think that indeed requires a new function to calculate subsequent output blocks.

I suggest first implementing PBKDF2 with a limitation on the output size to one block, then (in a subsequent PR) adding that new function to PKCS5.

**Comment by gilles-peskine-arm** [comment]
Not exactly “only call `output_bytes()` once”, but having the PSA layer retrieve one block (as in: the size of output that PBKDF2 calculates near-independently), and using generic machinery to store that block's content in the PSA layer and possibly return it to the application piece by piece (e.g. 16 bytes of key and 16 bytes of IV from a 32-byte block).

Then, as a follow-up, add a function to pkcs5 that allows retrieving a non-initial block.

**Comment by mpg** [comment]
Hmm, would we retrieve that block by calling `mbedtls_pkcs5_pbkdf2_hmac_ext()` or by computing it ourselves using `psa_mac_xxx()` APIs? If you mean by calling `mbedtls_pkcs5_pbkdf2_hmac_ext()`, then the amount we request does not really have to be one block (that is, the hash's output size), but could be an arbitrary number. Though, since it's arbitrary we might as well pick the hash's output size indeed (because even if we asked for less, we would compute that much internally, and also see below).

> What would be the extra parameter?

I think if this is an internal function, we can have a low-level API that hands out one block at a time, then the block number (the `counter` variable of `pkcs5_pbkdf2_hmac()`) would be suitable. This would be a good argument for starting with one block indeed: then in step two we just have to change `mbedtls_pkcs5_pbkdf2_hmac_ext(..., block_size)` to `new_internal_function(..., 0)` (for block 0), and then add support for non-initial blocks.

**Comment by gilles-peskine-arm** [comment]
> would we retrieve that block by calling mbedtls_pkcs5_pbkdf2_hmac_ext() or by computing it ourselves using psa_mac_xxx() APIs?

By calling the pkcs5 function. Otherwise we're fully reimplement PBKDF2 in the PSA code. Mind you, maybe that's a better option since we want to support CMAC, which pkcs5 doesn't support?

> since it's arbitrary we might as well pick the hash's output size indeed
Yes, that's the point.

> we can have a low-level API that hands out one block at a time, then the block number (the counter variable of pkcs5_pbkdf2_hmac()) would be suitable
Yes, that's what I think we should do in step 2.

**Comment by mpg** [comment]
>  Otherwise we're fully reimplement PBKDF2 in the PSA code. Mind you, maybe that's a better option since we want to support CMAC, which pkcs5 doesn't support?

I think that was @silabs-Kusumit 's original point/question :)

Considering the discussion we just had (that is, we'd need to add a new internal API which would be pretty low-level, and proceed incrementally, starting with a step where users can't draw more than one block's worth of output), I'm starting to thing that re-implementing using `psa_mac_xxx()` APIs is quite tempting: it's more work, but not that much more, and it's not wasted since we'll need to do it at some point anyway to support CMAC.

**Comment by gilles-peskine-arm** [comment]
Reimplementing is probably not much more work that adapting what we have, but it means larger code in applications that link with both. I'm not sure if it's a problem here: will there be many applications on constrained devices that use both the PKCS5 module (presumably for encrypted PEM?) and PBKDF2 through PSA?

**Comment by mpg** [comment]
@silabs-Kusumit Sorry, posted my last message before I saw yours. Yes, I agree with your summary, and right now I'm finding option 2 more attractive. Also, most of the code for that can probably be directly taken from the PSA implementation of `mbedtls_pkcs5_pbkdf2_hmac_ext()` we had in Mbed TLS 3.3.0: https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/library/pkcs5.c#L326

> I'm not sure if it's a problem here: will there be many applications on constrained devices that use both the PKCS5 module (presumably for encrypted PEM?) and PBKDF2 through PSA?

I think constrained devices should not be using PEM, so I'm guessing that's not a problem in practice.

**Comment by silabs-Kusumit** [comment]
The algorithm was implemented with `psa_mac_xxx` before the switch to MD calling PSA drivers, so the additional work should not be too much if I reuse that code.
Structuring the code to accommodate for CMAC will take most of the effort

**Comment by mpg** [comment]
Then I suggest we add an implementation based on `psa_mac_xxx()`, but proceed in steps as follows:

1. Support only HMAC with just one block's worth of output, possibly in multiple calls to `output_bytes()` - if the application requests more, then an error is returned. (So, the library behaves as if `set_capacity(hash_output_size)` had been called.)
2. Support only HMAC with arbitrary output length.
3. Support also CMAC with arbitrary output length.

Wdyt?

**Comment by gilles-peskine-arm** [comment]
So implementing a pure PSA version sounds like the best option to me now.

It's the forward-looking way anyway, since in the long term we want crypto to be primarily based on PSA APIs, with legacy APIs such as `pkcs5.h` only provided for backward compatibility.

----

In terms of steps, whatever makes sense. It's ok to have a series of pull requests where the first few don't yet provide any functionality that's useful for an end-user, just testable building block (e.g. phase 1 only implements setup with full testing of parameter validation, then phase 2 implements the algorithm but only allows requests of exactly one block, then phase 3 extends this to an arbitrary number of whole blocks, then phase 4 implements block splitting. Or whatever makes sense.)

**Comment by silabs-Kusumit** [comment]
> Then I suggest we add an implementation based on `psa_mac_xxx()`, but proceed in steps as follows:
> 
> 1. Support only HMAC with just one block's worth of output, possibly in multiple calls to `output_bytes()` - if the application requests more, then an error is returned. (So, the library behaves as if `set_capacity(hash_output_size)` had been called.)
> 2. Support only HMAC with arbitrary output length.
> 3. Support also CMAC with arbitrary output length.

This looks okay. 

I am assuming the implementation will be added in `psa_crypto`?

**Comment by mpg** [comment]
> I am assuming the implementation will be added in `psa_crypto.c`?

Yes, I think so, for the time being - that is until, we have driver support.

I've edited the PR description to reflect the result of our discussion.
