### ISSUE TITLE
PBKDF2: test `output_key()`

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7133]
Add positive and negative test cases for `psa_key_derivation_output_key` for PBKDF2. Negative test cases have an output key of the wrong type.

Note: if this issue is done after #7645, we want test cases with both HMAC and CMAC, otherwise only HMAC.

**Depends on:** #7132

Edit: at this point we should edit the ChangeLog entry from #7132 to remove the restriction.

**Comment by silabs-Kusumit** [comment]
Do test cases need to be added in the `derive_key_type` test function?
Also are all the negative ECC tests needed for PBKDF2 in `derive_key_type` and `derive_key` functions?

**Comment by gilles-peskine-arm** [comment]
> Do test cases need to be added in the derive_key_type test function?

Yes.

> Also are all the negative ECC tests needed for PBKDF2 in derive_key_type and derive_key functions?

No. It's enough that we have derivation-of-ECC coverage with one KDF, we don't need it for all the KDF. What we need for PBKDF2 is to test that `derive_key` works if the password is a key and rejects non-key→key.
