### ISSUE TITLE
EC J-PAKE: partial fix for role vs user+peer

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7149]
,**Context:** The PSA Crypto PAKE extension API is quite clear: for (EC) J-PAKE, the application is supposed to call `set_user()` and `set_peer()` but does not have to call `set_role()`. See the [diagram for J-PAKE](https://arm-software.github.io/psa-api/crypto/1.1/ext-pake/AES0058-PSA_Certified_Crypto_API-1.1_PAKE_Extension-bet.1.pdf#page=16) and the text below: "J-PAKE does not assign roles to the participants, so it is not necessary to call psa_pake_set_role()." and "J-PAKE requires both an application and a peer identity."

Our implementation (and its tests) currently do the exact opposite: calls to `set_user()` and `set_peer()` fail and calling `set_role()` is mandatory.

**This task** is to apply a quick partial fix that allows applications following the spec to work in the special case where the user/peer IDs are "client"/"server" (in either order).

This is not a complete fix, as both [the J-PAKE RFC](https://www.rfc-editor.org/rfc/rfc8236) and the [PSA spec](https://armmbed.github.io/mbed-crypto/1.1_PAKE_Extension.0-bet.0/html/pake.html#c.psa_pake_set_user) allow any string to be used to either identifier (in fact, the J-PAKE RFC does not even contain the words "server" or "client"). However, "client"/"server" is an important special case as it's the one used by TLS.

**Suggested strategy:**
- [ ] Make `psa_pake_set_user()` and `psa_pake_set_peer()` accepts "client" or "server" as arguments, and internally set `operation->role` (or after #6567, that would be `operation->data.inputs.role`) accordingly (if `user_id` is "client", role is `CLIENT`, if `peer_id` is "client", role is `SERVER`, etc.). Return `PSA_ERROR_NOT_SUPPORTED` for any other argument. If `operation->role` was already set (not NONE) to a value other than the one that would be set, return `PSA_ERROR_NOT_SUPPORTED` (user="client", peer="client" would be valid according to the spec but we don't support it atm). Add corresponding unit tests and update the documentation accordingly.
- [ ] Adapt existing handshake test functions (`ecjpake_rounds_inject()` and `ecjpake_rounds()`) so that they stop calling `set_role()` but instead call `set_user()`+`set_peer()` with "client" and "server" appropriately. 
- [ ] Adapt the TLS code similarly.
- [ ] Change `psa_pake_set_role()` so that it always returns `PSA_ERROR_INVALID_ARGUMENT` (without changing the operation state) when called for J-PAKE (so, pretty much always, as J-PAKE is the only supported PAKE so far). Add corresponding unit tests.

**Related issues and PRs:**
- best done after #6567 in order to avoid conflicts;
- see #6961 for a discussion of a more complete fix.

**Comment by mprse** [comment]
I'm planning to implement fix on top of PR https://github.com/Mbed-TLS/mbedtls/pull/6567 hoping that it will be merged soon (this week as we are after full review from @ronald-cron-arm and waiting for review from @valeriosetti).

Got the following plan for the implementation changes:
- add `user` and `peer` to jpake inputs (`psa_crypto_driver_pake_inputs_s` struct). This fields will be set by psa_pake_set_user() and psa_pake_set_peer().
- in `psa_pake_complete_inputs` function `user` and `peer` will be validated (only `client - server` supported) and `role` will be set  accordingly.
