### ISSUE TITLE
AES and GCM using POWER crypto instructions

### ISSUE THREAD

**Issue by DemiMarie** [Mbed-TLS/mbedtls#7244]
### Suggested enhancement

Support POWER crypto instructions for AES and GCM

### Justification

Mbed TLS needs this because AES and GCM without hardware support is slow.

**Comment by daverodgman** [comment]
None of the core team have the right expertise to implement this, so I'm closing as we don't plan to work on it.

But we would accept a contribution if you or a community member wanted to look at this. CI / testing might be tricky, but we would like to add coverage for other platforms (maybe via QEMU) at some point, so it's not insurmountable.
