### ISSUE TITLE
Extract mbedtls_mpi_core_shift_l()

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7246]
Extract `mbedtls_mpi_core_shift_l()` from `mbedtls_mpi_shift_l()`:
https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.3.0/library/bignum.c#L732-L778

Requirements:

- As usual the MPI operand of `mbedtls_mpi_core_shift_l()` should be represented by a raw pointer
- After the change `mbedtls_mpi_shift_l()` should call `mbedtls_mpi_core_shift_l()`.
- `mbedtls_mpi_core_shift_l()` can't resize it's operand and ~~should return an error~~ truncate the output if the result doesn't fit
- Unit tests need to be added for `mbedtls_mpi_core_shift_l()` with the same coverage as what `mbedtls_mpi_shift_l()` has

**Comment by gilles-peskine-arm** [comment]
> mbedtls_mpi_core_shift_l() can't resize it's operand and should return an error if the result doesn't fit

That means it has to count bits. Then what guarantee does it have with respect to timing? What is our use case for it?

(This is why I didn't make a `core_shift_l` when I made `core_shift_r`.)

**Comment by yanesca** [comment]
For now it is only used for Curve448, later we might or might not need it for some operations related to RSA. At this point we don't know what shape or form that use case will be. I suggest we implement something that works for Curve448 and refactor it later when we know more about the other use cases.

I was suggesting cropped output, because that seemed natural extension of the semantics. Also, I was hoping that if we need something more, then we can simply return the carry, which is  a relatively small change from truncation.

That said, either version works for Curve448 and we should go with the option whichever you find simpler.
