### ISSUE TITLE
Design optimised reduction setup for moduli

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7264]
Optimised reduction uses different function depending on the modulus (as opposed to the reduction being implicit or parametrised by the modulus). Because of this for the setup to complete we need to set a function pointer in the modulus struct. The `ored` field in the modulus structure is reserved for this purpose. Question is how to set this field.

Option 1: Extend the mbedtls_mpi_mod_modulus_setup() function to receive an additional parameter to take the function pointer to set it

Option 2: Make setting the function pointer the responsibility of the caller and provide a setter function that does it.

**Comment by yanesca** [comment]
When thinking about it, I wanted to put the `optred` setup version in the `ecp_curves` module as that is the only place where it is used.

When thinking about it, I rejected the option, because I wanted to go with the internal setup variant as you described it above, but didn't want to break abstraction. I mean, I didn't like that in this setting
1. bignum_mod module has to export/offer the internal setup function
2. the `optred` setup has to directly access fields in struct from a lower level module
3. the `free` function would have to be able to clean up after both and it is located in a different module

**Comment by yanesca** [comment]
Here are my issues with each approach:
1. Extending the setup function: Makes every call more complicated
2. Adding a setter function: Setup leaves some objects unfit for use
3. Having two setup methods in bignum: Conceptually I feel one of them should be in ecp
4. Having two setup methods one in ecp: Implies breaking abstraction

Based on this, I think my aversion to subjective conceptual imperfection is the least serious concern, so we probably should go for option 3.

@paul-elliott-arm, @gabor-mezei-arm , @xkqian , @gilles-peskine-arm  do you have any thoughts about this or objections?

**Comment by gilles-peskine-arm** [comment]
Given that there are two representations, and they need different parameter lists, I think it makes more sense to have one function for each representation, i.e. (3) or (4).

Given that bignum knows what `OPT_RED` is, I don't see why the corresponding setup method wouldn't be in bignum, i.e. (3) seems the most by-the-book to me. Janos, can you clarify why you don't think that's right? The only argument I can find on this page is “ecp_curves module as that is the only place where it is used”, but this seems like happenstance (currently nobody else uses this format, but it could happen), not fundamental design.

**Comment by yanesca** [comment]
It is just that, nothing more, it feels like it conceptually belongs there. If it is in the ECP module, the use case is more clear, we can make more assumptions, be more sure that it is only used from there and makes the bignum_mod API more straightforward.

(To be clear: I am not trying to make a case for it, I am just answering your question.)

**Comment by yanesca** [comment]
There is an agreement to go for option (3).

**Comment by minosgalanakis** [comment]
I am closing this issue as complete and moving to the implementation as agreed on #7268
