### ISSUE TITLE
Test multiplication and inversion on named moduli

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7265]
Currently we only test the life cycle for named moduli. To be prudent we should test arithmetic functions like `mbedtls_mpi_mod_mul()` and `mbedtls_mpi_mod_inv()` with named moduli (i.e. moduli set up with `mbedtls_ecp_modulus_setup()`).

These functions are tested with universal moduli extensively, we don't need to test it again to the same extent, the goal is to gain more confidence that moduli that `mbedtls_ecp_modulus_setup()` created work with these functions.

The test function should take a single input and make sure that if we multiply it with it's own inverse we get 1.

Only add these tests for named moduli that don't have optimised reduction. That is, the exponent modulus of every curve in Mbed TLS and the coordinate modulus Brainpool curves (MBEDTLS_ECP_DP_BPXXXR1).

Tests for optimised reduction moduli will be added in #6025 and are out of scope for this issue.

**Comment by xkqian** [comment]
Let me try to understand this, please corret me if something goes wrong.

1. Add one test function named mpi_mod_mul_inv() similar as ecp_mod_setup() in test function file test_suite_ecp.function.
2. In the test function, we will firstly call mbedtls_ecp_modulus_setup(), and then the related test APIs mbedtls_mpi_mod_mul() and mbedtls_mpi_mod_inv().
3. Cause we have had the universal test cases for mbedtls_mpi_mod_mul() and mbedtls_mpi_mod_inv(), in the test function body, we can only give one input and compute its' inverse with mbedtls_mpi_mod_mul(), and  get 1 as the result.
4. For every Brainpool curves,  need at least one test case.
5. For every curve in Mbed TLS, need at least one test case.

BTW: I am not sure about this description: "Tests for optimised reduction moduli will be added in https://github.com/Mbed-TLS/mbedtls/issues/6025 and are out of scope for this issue". Does that mean we will have other APIs for multiply and inverse, which will replace the mbedtls_mpi_mod_mul() and mbedtls_mpi_mod_mul() ?

**Comment by yanesca** [comment]
> 3. Cause we have had the universal test cases for mbedtls_mpi_mod_mul() and mbedtls_mpi_mod_inv(), in the test function body, we can only give one input and compute its' inverse with mbedtls_mpi_mod_mul(), and get 1 as the result.

Yes, you get A as an input, calculate A_inv with `mbedtls_mpi_mod_inv()`. Then you call `mbedtls_mpi_mod_mul()` to calculate A * A_inv and check if the result is 1.

> 4. For every Brainpool curves, need at least one test case.
> 5. For every curve in Mbed TLS, need at least one test case.

Yes. Each curve has two moduli associated with it:
- one for the coordinates
- another one for the scalars

You can set up any of these by selecting a curve and telling [mbedtls_ecp_modulus_setup()](https://github.com/Mbed-TLS/mbedtls/blob/v3.4.0/library/ecp_invasive.h#L163-L183) whether you want the coordinate or the scalar modulus.

For Brainpool curves we need to test both. For the rest of the curves we need to test only the scalar modulus.

The test function could take the curve and the selector too as an input and a single function could serve all the test cases. For each modulus 2-3 random values should be enough (some of which could potentially be reused).

As far as I can tell, the test generation framework provides little to no advantage and should be fine to just add the test cases manually.

> BTW: I am not sure about this description: "Tests for optimised reduction moduli will be added in https://github.com/Mbed-TLS/mbedtls/issues/6025 and are out of scope for this issue". Does that mean we will have other APIs for multiply and inverse, which will replace the mbedtls_mpi_mod_mul() and mbedtls_mpi_mod_mul() ?

No, we don't have another API for these, the same test function will be reusable for those as well. We will simply be adding a couple of new test cases.
