### ISSUE TITLE
Analyze test cases that will fail in 2023 due to expiring certificates

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7283]
As reported in #6978, some of our test certificates will expire on 2023-08-07. The goal of this issue is to do a high-level analysis of the test cases that will fail in 2023 (taking a tiny extra amount of margin) and plan for their reconstruction.

Definition of done: a rough breakdown of the failing test cases that allows us to estimate how much test data we need to fix and how hard it will be. No code, at least not directly (code used for test or analysis may or may not be worthwhile to submit, but is not a deliverable for this issue).

----

The data:
[failures.development.csv.txt](https://github.com/Mbed-TLS/mbedtls/files/10978693/failures.development.csv.txt) (from [this CI run](https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbedtls-release-ci-testing/31/))
[failures.2.28.csv.txt](https://github.com/Mbed-TLS/mbedtls/files/10978697/failures.2.28.csv.txt) from [this CI run](https://ci.staging.trustedfirmware.org/view/Mbed-TLS/job/mbedtls-release-ci-testing/45/)

----

Method to obtain the raw data:

* Run a full test campaign on Linux — this should run all test cases at least once (except possibly platform-specific test cases, but those shouldn't involve certificates). Use a patched `all.sh` that runs the tests at a faked future time. Code in [this branch for development shortly before 3.4](https://github.com/gilles-peskine-arm/mbedtls/tree/all.sh-faketime), [this branch for 2.28](https://github.com/gilles-peskine-arm/mbedtls/tree/all.sh-faketime-2.28).
* List the failing test cases. They're available in the `failures.csv.xz` artifact on the Jenkins job.
    * This omits failures from `compat.sh`, but those use a very small number of certificates which are also used in `ssl-opt.sh` anyway, so for planning purposes we can assume that fixing the unit tests and `ssl-opt.sh` will also fix `compat.sh`.
    * To remove duplication due to the same test case running in multiple configurations:
    ```
    <failures.csv.xz unxz | cut -d \; -f 3- | sort -u >unique-failures.csv
    ```

**Comment by yuhaoth** [comment]
- [ ] `server5.*` will be out-of-data after 2023-9-22, and generate commands is missing

**Comment by yuhaoth** [comment]
#7495 is for 2.28 and #7494 is for `development`

**Comment by yuhaoth** [comment]
With #7494 , we have passed `test_full_cmake_clang` with `faketime -f '+4y'`
