### ISSUE TITLE
expose ecdsa_verify_restartable

### ISSUE THREAD

**Issue by evertvr** [Mbed-TLS/mbedtls#7333]
### Suggested enhancement

Would like to have the function `ecdsa_verify_restartable` exposed in the ecdsa API.

It seems it's just a matter of removing the `static` keyword and adding to the header. However I don't know if there are any security implications by exposing this context outside of the ecdsa module...

### Justification

Mbed TLS needs this because not everyone is using a pre-emptive multitasking OS.

**Comment by gabor-mezei-arm** [comment]
It is already made public in #7095. Will be available in the next release.
