### ISSUE TITLE
Do MbedTls bignum have sqrt operation?

### ISSUE THREAD

**Issue by Wenxing-hou** [Mbed-TLS/mbedtls#7339]
### Suggested enhancement
MbedTls  may need add bignum sqrt operation.

### Justification

When I enable  such as `EC_POINT_set_compressed_coordinates` api from Openssl, the bignum sqrt is needed.
`EC_POINT_set_compressed_coordinates` is set x9.62 compressed coordinates of a EC_point.
```
/** Sets the x9.62 compressed coordinates of a EC_POINT
 *  \param  group  underlying EC_GROUP object
 *  \param  p      EC_POINT object
 *  \param  x      BIGNUM with x-coordinate
 *  \param  y_bit  integer with the y-Bit (either 0 or 1)
 *  \param  ctx    BN_CTX object (optional)
 *  \return 1 on success and 0 if an error occurred
 */
int EC_POINT_set_compressed_coordinates(const EC_GROUP *group, EC_POINT *p,
                                        const BIGNUM *x, int y_bit,
                                        BN_CTX *ctx);
```

According to ECC, `BnY^2= BnX^3 + BnA* BnX + BnB`.  Bn is mbedtls_mpi format.
 When I calculate BY^2, I need to get BnY by using bignum sqrt operation.

**Comment by gabor-mezei-arm** [comment]
You should use `mbedtls_ecp_tls_read_point` for reading compressed data.

If you have any further question please use our mailing list: <mbed-tls-security@lists.trustedfirmware.org>.
