### ISSUE TITLE
Code Size: baremetal libmbedcrypto: r657: endian conversion

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7374]
Bring in the changes from https://github.com/Mbed-TLS/mbedtls-restricted/pull/657

Use functions for reading and writing 16/24/32-bit big endian values to save ROM.

May or may not be a code saving based on changes DR made a few months ago

Hoped-for savings: Text: 5935, Data: -28

If no improvement, don't do this!

**Comment by tom-cosgrove-arm** [comment]
Updating size as there's going to be a lot of manual checking of the files involved

**Comment by DemiMarie** [comment]
What about using `__builtin_bswap()` and friends?  Compilers should be able to optimize those to single machine instructions.

**Comment by tom-cosgrove-arm** [comment]
@DemiMarie Yes, there's all the stuff in https://github.com/Mbed-TLS/mbedtls/blob/development/library/alignment.h - this ticket is to see if there's anything else to do
