### ISSUE TITLE
Code Size: bignum: Use mbedtls_mpi_core_exp_mod

### ISSUE THREAD

**Issue by tom-cosgrove-arm** [Mbed-TLS/mbedtls#7398]
`mbedtls_mpi_exp_mod()` should use `mbedtls_mpi_core_exp_mod()` rather than duplicating code.

**Comment by gilles-peskine-arm** [comment]
This is already in the bignum tech debt backlog: https://github.com/Mbed-TLS/mbedtls/issues/6600
