### ISSUE TITLE
tests/suites/test_suite_alignment.* may be broken on big-endian platforms

### ISSUE THREAD

**Issue by zv-io** [Mbed-TLS/mbedtls#7428]
### Summary

On big-endian platforms such as ppc64 and sparc64, this test suite fails.

It was introduced in commit fb5fedcd00726555def8b1d47293e87562db0f86, and has never succeeded on such platforms.

### System information

Mbed TLS version (number or commit id): `v3.3.0` through `v3.4.0`
Operating system and version: (multiple)
```
Linux ppc64 6.0.0-5-powerpc64 #1 SMP Debian 6.0.10-2 (2022-12-01) ppc64 GNU/Linux
Linux gcc102.fsffrance.org 6.1.0+ #1 SMP Tue Dec 13 08:35:29 CST 2022 sparc64 GNU/Linux
```
Configuration (if not default, please attach `mbedtls_config.h`): (default)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): (multiple)
```
gcc (Debian 12.2.0-9.1) 12.2.0
gcc (Adelie 8.5.0) 8.5.0
```
Additional environment information: 

### Expected behavior

Test suite passes.

### Actual behavior

* [sparc64-v3.4.0-alignment.txt](https://github.com/Mbed-TLS/mbedtls/files/11207616/sparc64-v3.4.0-alignment.txt)
* same behavior on ppc64

### Steps to reproduce

```sh
git checkout v3.4.0 # or fb5fedcd00726555def8b1d47293e87562db0f86
git clean -dfx
mkdir x
cd x
cmake ..
make -j$(nproc)
make test
```

### Additional information

* https://git.adelielinux.org/adelie/packages/-/issues/1002

**Comment by daverodgman** [comment]
This looks like an error in the tests.

**Comment by daverodgman** [comment]
@zv-io Please could you report if #7440 fixes this on a big-endian machine?

**Comment by zv-io** [comment]
On sparc64:

```
Running tests...
Test project /home/zv/mbedtls/x
        Start   1: aes.cbc-suite
  1/115 Test   #1: aes.cbc-suite ..............................   Passed    0.02 sec
        Start   2: aes.cfb-suite
  2/115 Test   #2: aes.cfb-suite ..............................   Passed    0.03 sec
        Start   3: aes.ecb-suite
  3/115 Test   #3: aes.ecb-suite ..............................   Passed    0.02 sec
        Start   4: aes.ofb-suite
  4/115 Test   #4: aes.ofb-suite ..............................   Passed    0.01 sec
        Start   5: aes.rest-suite
  5/115 Test   #5: aes.rest-suite .............................   Passed    0.45 sec
        Start   6: aes.xts-suite
  6/115 Test   #6: aes.xts-suite ..............................   Passed    0.04 sec
        Start   7: alignment-suite
  7/115 Test   #7: alignment-suite ............................   Passed    0.01 sec
...
```
