### ISSUE TITLE
Clean up & improve PK write test functions

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7446]
The existing PK write test functions have issues that make them unfriendly to constrained devices:
1. They use 10000 bytes worth of stack buffers.
2. They depend on PEM.

The first point could be addressed by dynamically allocating the buffers to the exact size needed, which we can get from the file using `fseek()` + `ftell()` as in `mbedtls_pk_load_file()` (or perhaps even use that function directly). (This also means that we don't need to check we didn't write beyond what's expected, as ASan / valgrind will check that for us once the buffer's size is exactly what we need.)

The second point could be addressed by adding an extra parameter indicating whether the file is PEM or DER, and using the corresponding write function. (We could also just look at the file extension but that seems less clean.)

Note: a third problem with those functions is they all rely on `FS_IO`. However this might be harder to solve (and is common to the PK parse test functions) so we'll probably want to handle that separately.

**Comment by valeriosetti** [comment]
> The second point could be addressed by adding an extra parameter indicating whether the file is PEM or DER, and using the corresponding write function. (We could also just look at the file extension but that seems less clean.)

But is there any file in DER format? Because to me this seems not to be the case

**Comment by gilles-peskine-arm** [comment]
@valeriosetti Part of this task would be to change most of the tests to use DER, or duplicate them to test both DER and PEM. And it would involve adding a bunch of DER test files.

**Comment by mpg** [comment]
> change most of the tests to use DER, or duplicate them to test both DER and PEM. 

I think duplicate is the correct way here. We need to test that we're picking the correct PEM header for each key type (and once #6838 is in, it will even depend on the curve type, [to my surprise](https://github.com/Mbed-TLS/mbedtls/pull/6838#discussion_r1168348534)), so testing only DER wouldn't be enough. We might not need every single DER test to have a PEM counter-part, but having every single test in both PEM and DER version is a simple rule that guarantees we're testing enough, and I like simple rules.
