### ISSUE TITLE
Reject IPv4 addresses with excess leading zeros

### ISSUE THREAD

**Issue by DemiMarie** [Mbed-TLS/mbedtls#7477]
### Summary

IP addresses with excess leading zeros in an octet, such as `192.0.02.0`, are parsed inconsistently: some implementations consider the leading zero to indicate that the octet is octal, while others do not.  This has been the source of attacks in the past, so nowadays e.g. Python [rejects such addresses](https://github.com/python/cpython/pull/25099).

### System information

N/A

### Expected behavior

`192.0.02.0` is considered invalid

### Actual behavior

`192.0.02.0` is considered valid

### Steps to reproduce

Look at Mbed TLS’s IPv4 address parser

### Additional information

See links.

**Comment by AndrzejKurek** [comment]
Could you provide more details on how is it dangerous for the library? We don't accept octal number formats, `inet_pton` seems to only accept the dotted-decimal notation on the couple of platforms that I checked (Windows, Solaris, Linux).

**Comment by DemiMarie** [comment]
I believe `getaddrinfo` supports the octal format somewhere (I forget where).  Better to explicitly check for this and fail.

**Comment by gilles-peskine-arm** [comment]
@irwir In the past few decades, we've realized that “[be liberal in what you accept](https://en.wikipedia.org/wiki/Robustness_principle)” is [not always a good idea, especially for security](https://en.wikipedia.org/wiki/Robustness_principle#Criticism). So in the security world, we do sometimes stop supporting things that were allowed, but often misused. I don't know exactly where rejecting leading zeros in IPv4 addresses stands, in terms of feasibility (we want to reuse platform functions where possible, to save code size) and desirability (we don't want to break behavior that many people rely on). But it's definitely in consideration.

**Comment by AndrzejKurek** [comment]
Addressed in https://github.com/Mbed-TLS/mbedtls/pull/7532.
