### ISSUE TITLE
Fix test gap in PK write: private (opaque) -> public

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7480]
Currently `test_suite_pk_write` has that import a key (public or private) then write it back (same). But this is not the only thing that PKwrite is supposed to be able to do: we should be able to import a private key then export the public key. Moreover, we should be able to import a key, wrap it as opaque, then export the public key.

This task is to add such tests. We can probably use a single function (and set of cases in the data file). It would:
1. take as argument two files: one for the private key (loaded to a PK context), one for the public key (loaded to a buffer for comparison purposes);
2. write out the public key from the PK context and check it matches the expected output;
3. if `USE_PSA_CRYPTO` is defined, call `mbedtls_pk_wrap_as_opaque()` on the key, then do step 2 again.

~This needs to be done both with PEM and DER, for consistency.~  DER format is enough for the purpose of this test. (see [this comment](https://github.com/Mbed-TLS/mbedtls/issues/7480#issuecomment-1523062338)) 

Depends on: ~#7449~ (merged) and #7461 (mostly to avoid conflicts if we added `USE_PSA_INIT/DONE()` on both sides).

**Comment by valeriosetti** [comment]
> This needs to be done both with PEM and DER, for consistency.

Is it necessary? I mean, PEM and DER parsing and writing is already tested with `pk_write_key_check` and `pk_write_pubkey_check` so it seems to me that both mechanisms are already validated.
Since the purpose of this PR is to test the public key derivation, what would be the benefit of doing it both for PEM and DER?

**Comment by mpg** [comment]
Ah, good point! Just DER, then :)
