### ISSUE TITLE
PK: add support for `check_pair()` with "opaque" EC keys

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7485]
This is a follow-up to #7484 - one of the things that is not supported for no good reason (other than it was not required to meet the needs of the first user of PK "opaque" keys) is `check_pair()`. This task to add support for this.

This will mostly consist of defining a new function in `pk_wrap.c` and registering it in the corresponding slot of the `mbedtls_pk_ecdsa_opaque_info` structure. The new function can use the following strategy:
- call `psa_export_public_key()` on the PSA key id held within the `prv` context;
- call `mbedtls_ecp_point_write_binary()` on the public key held within the `pub` context;
- compare the results.
This is somewhat similar to `eckey_check_pair_psa`, except here we start with a PSA key id in the `prv` context (while `eckey_check_pair_psa` has to create it first).

Note: PK "opaque" keys only exist when `USE_PSA_CRYPTO` is enabled.

Note: once #7074 is done, it will likely be possible to use the new function created here in place of `eckey_check_pair_psa` for "normal" (non-opaque) EC keys.

**Depends on:** #7513

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by mpg** [comment]
Hi @bharsaklemukesh975 and hanks for offering your help!

As you may have seen, there is currently a lot of activity in this area, giving rise to conflicts or dependency chains sometimes, so I really appreciate you asking first! As it turns out, @valeriosetti is planning a preliminary PR that will change the structure of `PK_OPAQUE` keys in a way that should make things easier / avoid conflicts between this, #7484 and #7074, so I would recommend you wait for that PR to be merged before you start working on this. (@valeriosetti can you add a link to your PR here once it's created?)

I'll also expand the issue description with a bit more detail. In case you have questions, feel free to ask @valeriosetti or me.

**Comment by valeriosetti** [comment]
> @valeriosetti can you add a link to your PR here once it's created?

I only have the related issue for now: https://github.com/Mbed-TLS/mbedtls/issues/7513
I will add it also to the description of this issue for clarity

**Comment by mpg** [comment]
@bharsaklemukesh975 The pre-requisite https://github.com/Mbed-TLS/mbedtls/pull/7514 has now been merged, so feel free to start working on this when you want!

**Comment by bharsaklemukesh975** [comment]
Will add eckey_check_pair_pk_opaque() in pk_wrap.c, btw eckey_check_pair_psa() is implemented already?

**Comment by valeriosetti** [comment]
> Will add eckey_check_pair_pk_opaque() in pk_wrap.c, btw eckey_check_pair_psa() is implemented already?

I think that after #7074 the `eckey_check_pair_psa` can be used for both EC and opaque keys since the mechanism looks the same to me. The proposed implementation is [here](https://github.com/valeriosetti/mbedtls/blob/d2948ba58d131b2ec4b23b1dcd32e25c7f97608f/library/pk_wrap.c#L1060) 
@mpg wdyt?

**Comment by mpg** [comment]
@bharsaklemukesh975 I'm sorry, I think it turns out this is not a great area for you to contribute at the moment. We seem to be having just a bit too much trouble predicting dependencies and interactions between issues/PRs here to make it efficient for multiple contributors to be active in this area right now.

Sorry for not identifying this problem earlier. I don't want to reject offers for help, but I think right now it would be better for you to look for issues that would interest you in other areas than the [driver-only ECC EPIC](https://github.com/orgs/Mbed-TLS/projects/1#column-19391691) for which planning is unusually complex at the moment.
