### ISSUE TITLE
Expiry test error

### ISSUE THREAD

**Issue by llmlla** [Mbed-TLS/mbedtls#7497]
Hi：
I am using MedTLS for certificate authentication. The content of the certificate contains two timestamps:NotBefore and NotAfter. The validity of the legal certificate must be after NotBefore and before NotAfter, and the RFC document states that the current time used to validate the certificate must be GMT. But MbedTLS uses the local system time not GMT. The version I use is Mbed TLS version (2.6.0).

**Comment by gilles-peskine-arm** [comment]
Mbed TLS 2.6 has not been supported for years and has many known vulnerabilities and other bugs. Please upgrade to the latest [release](https://github.com/Mbed-TLS/mbedtls/releases), either in the development track (3.x) or in the long-time support track (2.28.x).

But in any case, even in old versions of Mbed TLS, the library code doesn't contain any way to query the system's timezone. It calls `gmtime()`, never `localtime()`. So the claim that it is validating against the local system time is very surprising.

If you genuinely believe that there is a bug in Mbed TLS, please give precise instructions to reproduce it: on what operating system, how the library is compiled, the exact code you're running, a certificate that reproduces the problem...
