### ISSUE TITLE
mbedtls_ecdsa_verify_restartable fails with ECDSA_SIGN_ALT

### ISSUE THREAD

**Issue by JonathanWitthoeft** [Mbed-TLS/mbedtls#7498]
When ECDSA_SIGN_ALT but not ECDSA_VERIFY_ALT, mbedtls_ecdsa_can_do was not being defined causing mbedtls_ecdsa_verify_restartable to always fail

**Comment by tom-daubney-arm** [comment]
Thank you for the report and the fix!
