### ISSUE TITLE
Undefined mbedtls_mpi_core_clz

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#7501]
### Summary
Function is declared and not defined, therefore it should be treated as an external.
https://github.com/Mbed-TLS/mbedtls/blob/09d23786f6fdcb4dfa88aad30c8767bd27a955be/library/bignum_core.h#L112
Here is an external reference
https://github.com/Mbed-TLS/mbedtls/blob/09d23786f6fdcb4dfa88aad30c8767bd27a955be/library/bignum.c#L1281
But due to `inline` specification it is not included into the mbedtls library.
https://github.com/Mbed-TLS/mbedtls/blob/09d23786f6fdcb4dfa88aad30c8767bd27a955be/library/bignum_core.c#L36

### System information

Mbed TLS 10f40916ebfb87ff3980d3ac58454dfae8766bc7 
Windows `11
VS 2022

### Expected behavior
Either inline should be removed or header files rearranged to enable correct library builds.

### Actual behavior
Build error: undefined external.

**Comment by daverodgman** [comment]
Please can you see if #7502 fixes this on your system?

**Comment by irwir** [comment]
Now it builds with the changes from `daverodgman:inline-clz`
Could [this topic](https://stackoverflow.com/questions/9353973/implementation-of-builtin-clz) be useful?
Also there are intrinsics in VS for Intel processors.

**Comment by tom-cosgrove-arm** [comment]
> Also there are intrinsics in VS for Intel processors

Pull requests are welcome from the community
