### ISSUE TITLE
OPC UA: merge crt and csr code setting SubjectAltName

### ISSUE THREAD

**Issue by AndrzejKurek** [Mbed-TLS/mbedtls#7523]
`mbedtls_x509write_crt_set_subject_alternative_name` and `mbedtls_x509write_csr_set_subject_alternative_name` share a lot of common code. This task is about studying the possibility and, if feasible, making them share the common part to save code size.
Depends on #7520 due to unbalanced support for MBEDTLS_X509_SAN_RFC822_NAME and MBEDTLS_X509_SAN_DIRECTORY_NAME.

**Comment by Neustradamus** [comment]
To follow
