### ISSUE TITLE
`psa_crypto`: `PSA_DRIVERS` variable not used anywhere in the build process

### ISSUE THREAD

**Issue by laukik-hase** [Mbed-TLS/mbedtls#7534]
### Summary

Mbed TLS documentation states that we can supply the PSA driver description files using the `PSA_DRIVERS` variable (see [here](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/proposed/psa-driver-integration-guide.md#how-to-build-mbed-tls-with-drivers)). But, this variable is not used anywhere in the Mbed TLS build process. 

```log
docs/proposed/psa-driver-integration-guide.md
29:2. Pass the driver description files through the Make variable `PSA_DRIVERS` when building the library.
33:    make PSA_DRIVERS="/path/to/acme/driver.json /path/to/nadir/driver.json" lib
```

1. How does the build process for supplying driver descriptors externally work?
2. How are the test `JSON` files (located [here](https://github.com/Mbed-TLS/mbedtls/tree/development/scripts/data_files/driver_jsons)) linked to the application while building the test programs?
 
### System information
- Mbed TLS version (number or commit id): [v3.4.0](https://github.com/Mbed-TLS/mbedtls/tree/v3.4.0)
- Operating system and version: Linux/Pop!_OS 20.04
- Compiler and options (if you used a pre-built binary, please indicate how you obtained it): `gcc 9.4.0` / `cmake version 3.24.1` (Built with `CMake` with instructions given [here](https://github.com/ARMmbed/mbedtls#cmake) - no additional flags)
- Additional environment information: NA

**Comment by gilles-peskine-arm** [comment]
The PSA driver documentation is a draft of the design we want to achieve. It isn't fully implemented yet. In particular, we have unfortunately not yet added driver support to our build scripts. For the time being, you need to either run `scripts/generate_driver_wrappers.py` before building, or edit files manually if the script doesn't yet support the functions you need.

For practical information on how to use drivers in Mbed TLS, please refer to the [Mbed TLS driver development guide](https://github.com/Mbed-TLS/mbedtls/blob/8e076e4132acd81e038288e10912e144593d32cb/docs/psa-driver-example-and-guide.md) (just merged this morning!).
