### ISSUE TITLE
AES: non-functional array used in round key calculation

### ISSUE THREAD

**Issue by yanrayw** [Mbed-TLS/mbedtls#7561]
# summary

In `aes.c`, we use 8 extra bytes for 192-bit and 16 extra bytes for 256-bit to calculate and store round keys. This behaves correctly in functionality because the extra caculated arrays are not used in encryption and decryption. And It doesn't report errors because we allocate 32 extra bytes for alignment. See CI failure [here](https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-head/detail/PR-7557-head/1/pipeline/445). 

DoD:

Use 208 bytes and 240 bytes to store round keys for 192-bit and 256 bit respectively.

**Comment by tom-cosgrove-arm** [comment]
Sorry, I'm not sure what the problem is here. The `buf` is documented as having extra space to be able to calculate more round keys than needed, which IIRC simplifies the code slightly

**Comment by yanrayw** [comment]
> Sorry, I'm not sure what the problem is here. The `buf` is documented as having extra space to be able to calculate more round keys than needed, which IIRC simplifies the code slightly

@tom-cosgrove-arm Take 192-bit case as an example, in last loop of round key calculation, we don't need to calculate `RK[10] ` and `RK[11]` [here](https://github.com/Mbed-TLS/mbedtls/blob/development/library/aes.c#L625). As for 256-bit case, in last loop we don't need to calculate `R[12] - R[15]` [here](https://github.com/Mbed-TLS/mbedtls/blob/development/library/aes.c#L643). 

We're expecting to allocate 208 bytes and 240 bytes for AES 192-bit and AES 256-bit respectively. But actually now we allocate 216 bytes and 256 bytes accordingly.

**Comment by yanrayw** [comment]
Oh, sorry Tom. I may misunderstand your meaning. I would expect we don't allocate extra space in round key `buf`. So I have an commit to redesign aes context. See commit here: https://github.com/Mbed-TLS/mbedtls/pull/7557/commits/1b996aa3694e7904a7e229165e54ef85220ec341

**Comment by gilles-peskine-arm** [comment]
As Tom notes, the extra space is there to simplify the code. Also note that there's some extra space which is for `MBEDTLS_PADLOCK_C` because the corresponding hardware requires extra alignment.

**Comment by yanrayw** [comment]
Sorry, my mistake. I thought the extra 32 bytes are allocated for alignment. I misunderstood how the code is designed.

Will we consider to calculate round keys like `aesce_setkey_enc` in `aesce.c`? It looks we could save some code size but might sacrifice some performance.
