### ISSUE TITLE
Remove mbedtls_pk_ec and mbedtls_pk_rsa

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7572]
The functions `mbedtls_pk_ec` and `mbedtls_pk_rsa` allow users to access break through the abstraction barrier of a `mbedtls_pk_context` object. They are problematic in a number of ways. They have a limitation that they only work if the PK object contains an RSA or ECP context, which hinders the migration to PSA. For PSA opaque keys, in Mbed TLS 3.x, we work around this by giving the keys the type `MBEDTLS_PK_OPAQUE` (in the sense of `MBEDTLS_PK_OPAQUE`), which means that checking the _actual_ type of the key requires checking further if `mbedtls_pk_get_type` returns `MBEDTLS_PK_OPAQUE`. For PSA transparent keys, they are problematic because we'd like to have both a PSA and a legacy low-level context, but the functions give a writable reference to the legacy context, which can invalidate the PSA data at an unpredictable time in the future — see https://github.com/Mbed-TLS/mbedtls/issues/7570.

In the next major release (i.e. 4.0), we plan to remove those two functions.

In 3.x, we should probably deprecate them officially. That means not using them inside the library anymore, and having documented replacements for the use cases we're aware of. So this task has prerequisites that can be done over the 3.x lifetime.

TODO: review the uses in the library.

### Use cases with mutation

**Key generation**. The legacy process (is it documented somewhere?) is: create a context of the appropriate type, then call `mbedtls_setup_pk`, then obtain the low-level context with `mbedtls_pk_{ec,rsa}` and call the low-level generation function `mbedtls_{ecp,rsa}_gen_key`, then use the pk object. This can't be done with another function, so we need to either add an API function `mbedtls_pk_gen_key` or make another process available. For PSA, the process is to first generate the key, then call `mbedtls_pk_setup_opaque`; so maybe we should add functions `mbedtls_pk_setup_from_rsa` and `mbedtls_pk_setup_from_ecp`?

**Construct a key in a way that neither random generation, nor parsing a key in a format supported by the PK module**. This may be a key that is parsed in a proprietary format, or derived deterministically in some way that Mbed TLS doesn't do. The current process is: create a context of the appropriate type, then call `mbedtls_setup_pk`, then obtain the low-level context with `mbedtls_pk_{ec,rsa}` and do whatever you need to do to construct the key object, then use the pk object. This generalizes the generation use case, and we can't create a pk function to do whatever the application needs to do. So we should add functions `mbedtls_pk_setup_from_rsa` and `mbedtls_pk_setup_from_ecp`. https://github.com/Mbed-TLS/mbedtls/issues/7574

**Set metadata in a key**, for example parsing an RSA key and then doing a PSS signature or verification. This is not officially supported, but I think it can actually be done by using `mbedtls_pk_rsa` and calling `mbedtls_rsa_set_padding` on the low-level object, then `mbedtls_pk_{sign,verify}`.

### Read-only use cases

**Obtain the key's constituent numbers**. For example to write the key in a format that pk doesn't support.

**Comment by mpg** [comment]
> **Key generation**. [...] For PSA, the process is to first generate the key, then call `mbedtls_pk_setup_opaque`; so maybe we should add functions `mbedtls_pk_setup_from_rsa` and `mbedtls_pk_setup_from_ecp`?

Counter-point: we're not removing any function before 4.0, and in 4.0 PSA will be mandatory, so I'd say when it comes to key generation, `psa_generate_key()` covers it and we don't need any new function for that (we might need new functions for other cases, though).

**Comment by mpg** [comment]
@daverodgman I'd like to argue this is actually a MUST for 4.0. These functions are fundamentally tied to `ecp.c` (resp. `rsa.c`) in that they return a pointer to a `mbedtls_ecp_keypair` (resp. `mbedtls_rsa_context`) so they mere existence is a problem for migrating everything to PSA, and has been a major pain in driver-only ECC work.

We really don't want to keep interfaces around with such strong ties to the legacy APIs / built-in implementations.

I'm moving this to the "MUST" column, please shout if you disagree.

**Comment by daverodgman** [comment]
@mpg The guideline I'm working to is: the MUSTs are things where we could not deliver the key 4.0 things without them (i.e., USE_PSA always enabled, consume TF-PSA-Crypto); the SHOULDs are things that accelerate us in the future; the COULDs are everything else that we'd like to do but aren't necessarily going to slow us down if we don't do them.

So on that basis, I think this is a SHOULD, but if you (and I assume @gilles-peskine-arm agrees based on the thumbs-up above) think it's a strong SHOULD, I'm happy to take it as a MUST.

**Comment by gilles-peskine-arm** [comment]
These two functions are part of the public API of the crypto library, and they're used in some sample and fuzzing programs, but they aren't used in the X.509/TLS library. The absolute minimum amount of work for removing them is to keep them but move them to a private header. The minimum of work for a viable product (if we repeat the mess that was 3.0, which we haven't finished cleaning up) would be to rewrite the sample/test programs, which we'll need to do anyway because they demonstrate/exercise legacy crypto APIs.

> the key 4.0 things without them (i.e., USE_PSA always enabled, consume TF-PSA-Crypto)

Strictly speaking, we can make USE_PSA always enabled at any time, and we can make TF-PSA-Crypto whatever it needs to be for consumption by X.509/TLS. That would meet the letter of the goal as you've written it here, but not the spirit of the goal which is to make cryptography in 4.0 based around the PSA API. These functions are very strong bridges to the crypto API: as long as they exist, the pk module (and therefore the X.509 and TLS stack) remains tied to non-PSA crypto implementations.

For the informal goal that 4.0 should have PSA as its crypto API, `mbedtls_pk_ec` and `mbedtls_pk_rsa` must not exist. Thus MUST. If we still have these functions in 4.0, we won't have delivered the 4.0 we've promised.

**Comment by mpg** [comment]
In addition to what Gilles said, a slight reformulation of mostly the same points:

> the MUSTs are things where we could not deliver the key 4.0 things without them (i.e., USE_PSA always enabled, consume TF-PSA-Crypto); the SHOULDs are things that accelerate us in the future; the COULDs are everything else that we'd like to do but aren't necessarily going to slow us down if we don't do them.

There's another category which this falls in: things that will not just accelerate us if we do them or slow us down if we don't, but that will _entirely block us_ in 4.x if we don't to them in 4.0.

> the key 4.0 things (i.e., USE_PSA always enabled, consume TF-PSA-Crypto)

These key things are not random, they serve a purpose: allow us to remove non-PSA crypto (in all places where crypto is used internally) in 4.x. For us to be able to achieve this goals, we must not have public APIs which fundamentally expose low-level non-PSA crypto.

If we don't remove these functions in 4.0, then we're stuck in a non-fully-PSA world until 5.0.

**Comment by yanesca** [comment]
Closing as this will be done as part of https://github.com/Mbed-TLS/mbedtls/issues/8452.
