### ISSUE TITLE
New functions mbedtls_pk_setup_rsa and mbedtls_pk_setup_ec

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7574]
If you want to construct a pk object (`mbedtls_pk_context`), there are three ways to do it:

* Parse a key in a format supported by the library with `mbedtls_pk_parse_xxx` or `mbedtls_pk_load_file`.
* Call `mbedtls_pk_setup` to create a “blank” PK object of the desired type, then call `mbedtls_pk_rsa` or `mbedtls_pk_ec` to get a pointer to the underlying low-level context and populate that as you wish.
* Call `mbedtls_pk_setup_rsa_alt` or `mbedtls_pk_setup_opaque` to construct a PK object from an existing low-level object (RSA-alt or PSA respectively).

[The `mbedtls_pk_rsa` and `mbedtls_pk_ec` functions are problematic](https://github.com/Mbed-TLS/mbedtls/issues/7572) so we'd like to have another way to do this. A natural solution would be to follow the example of RSA-alt and PSA, and construct the PK context from an existing `mbedtls_rsa_context` or `mbedtls_ecp_keypair`.

```
int mbedtls_pk_setup_rsa(mbedtls_pk_context *ctx, const mbedtls_rsa_context *rsa);
int mbedtls_pk_setup_ec(mbedtls_pk_context *ctx, mbedtls_pk_type_t type, const mbedtls_ecp_keypair *ec);
```

Open questions:

1. Should we do this at all? The `mbedtls_pk_{ec,rsa}` process is awkward but works. We [want to get rid of it in the next major release](https://github.com/Mbed-TLS/mbedtls/issues/7572), but it's still an open question whether the RSA and ECP modules will be public in that release. If they go private, those new setup functions will stop existing, so adding them in 3.x feels like a waste of effort. But if they remain public (I currently think they will, but opinions differ within the team), we'll need these new functions.
2. How do we manage memory? Mbed TLS normally have a clear view of pointer ownership: functions generally do not transfer pointer ownership. So the new setup functions should copy all the data into a new context. But in typical use, the caller will immediately free the low-level context used to create the key object, so having a copy is a waste of time and memory. Note that the existing function `mbedtls_pk_setup_rsa_alt` transfers ownership of the underlying `mbedtls_rsa_context` (`mbedtls_pk_free` will free it), and the function `mbedtls_pk_setup_opaque` creates a non-owning reference (the PSA key identifier must remain valid for as long as the PK context exists, and `mbedtls_pk_free` will not destroy it.)

**Comment by mpg** [comment]
My initial reaction is that I'm not really happy about tying the new functions to legacy types `mbedtls_rsa_context` and `mbedtls_ecp_keypair`. Whether or not RSA and ECP are public in 4.0, they won't be in 5.0. Whatever problem(s) the proposed functions are solving, shouldn't we try to solve it in a way that still works in 5.0?

As I commented on #7572, I don't think key generation is a problem in 4.0, so the remaining problems I see that those functions would solve is "Construct a key in a way that is neither random generation, nor parsing a key in a format supported by the PK module". How about a more neutral interface for that, for example:
```c
int mbedtls_pk_import_rsa_public(mbedtls_pk_context *ctx,
                                 const uint8_t *n, size_t n_size,
                                 const uint8_t *e, size_t e_size);
```
and similarly `rsa_private`, `ecc_public`, `ecc_private`.

**Comment by gilles-peskine-arm** [comment]
We're definitely not going to do this in 3.x. And if we end up making `rsa.h` and `ecp.h` public in 4.x and then we want a bridge from these low-level key manipulation modules to a high-level cryptographic operation API, we're likely to make that bridge to PSA rather than PK. So I agree, let's close this issue. Its purpose remains relevant, but the way it tries to achieve this purpose is not.
