### ISSUE TITLE
Provide legacy implementation of mbedtls_pk_sign_ext() when USE_PSA is not enabled

### ISSUE THREAD

**Issue by valeriosetti** [Mbed-TLS/mbedtls#7583]
Currently `mbedtls_pk_sign_ext()` depends on `MBEDTLS_PSA_CRYPTO_C` and that creates an asymmetry from other PSA friendly functions in the PK modules which instead depend on `MBEDTLS_USE_PSA_CRYPTO`. As a conssequence `MBEDTLS_PSA_CRYPTO_C` should be defined when working with RSA keys, but this [brings in other potentially undesired PSA code](https://github.com/Mbed-TLS/mbedtls/issues/7126).
As suggested [here](https://github.com/Mbed-TLS/mbedtls/issues/7126#issuecomment-1535972352) the goals of this task is to:

> I think we can and should make mbedtls_pk_sign_ext() always available (ie stop depending on MBEDTLS_PSA_CRYPTO_C), by providing a legacy implementation using rsa.h when PSA isn't available, and using either the PSA or the legacy based on USE_PSA_CRYPTO. That way, it will not only address the point made here, but also improve uniformity in the PK module

While at it, please also address the followings:

- fix comments mentioned [here](https://github.com/Mbed-TLS/mbedtls/pull/7514#discussion_r1185874727)
- as mentioned [here](https://github.com/Mbed-TLS/mbedtls/pull/7514#discussion_r1185896658) please check if `build_info.h`requires any adjustment after this

### Info for the associated PR:

- just label the corresponding PRs priority-medium
- don't put them on the unified board
- add @mpg as one of reviewers

**Comment by mpg** [comment]
Note: existing tests for this function also need their dependency declarations updated (removing `MBEDTLS_PSA_CRYPTO_C`), so that the new non-PSA code is also tested.

**Comment by mpg** [comment]
Great, thanks! And don't hesitate if you have any question :)

**Comment by mpg** [comment]
Indeed, by default external contributors can't add labels, PRs and issues have to be triaged by established teams member. Once someone has been contributing regularly and is familiar enough with our process, we can grant that permission.

Regarding reviewers, [our process](https://mbed-tls.readthedocs.io/en/latest/reviews/review-for-contributors/) is that reviewers self-assign most of the time - though it's of course OK to ask someone for a review in a comment or via another channel.
