### ISSUE TITLE
Clean up ECP curves

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7606]
### Suggested enhancement

Now that the ECP curves module has been cloned (https://github.com/Mbed-TLS/mbedtls/issues/7605), the recent refactoring is only needed in the new copy and need to be removed from the original one.

The task is to
- review the changes in `ecp_curves.c` since the code style switch (449bd8303eed8164b83682d2ce028dca0e49b1fa)  and identify those that are NOT related to the refactoring effort  (there shouldn't be much).
- roll back `ecp_curves.c` to 449bd8303eed8164b83682d2ce028dca0e49b1fa
- reapply the changes that are not related to the refactoring effort
- add the new ECP clone compile time guard (see https://github.com/Mbed-TLS/mbedtls/issues/7605) where necessary (some functions declarations in the headers won't be available with the original and corresponding unit tests will be relevant only when compiled with `ecp_curves_new.c`).

### Justification

The unnecessary code in the original copy increases code size unnecessarily, removing it resolves the problem.

**Comment by xkqian** [comment]
Will we only do the code style rollback and remove useless code in the new file ecp_curves_new.c?

**Comment by yanesca** [comment]
We are not rolling back the code style, we are keeping it. I choose the code style changes as a milestone, because that is the earliest point we can go back without needing to worry about code style. (Fortunately, we didn't do any Bignum changes to ecp_curves.c before that and it is enough to go back until then.)

After the prerequisite for this issue is done, ecp_curves.c and ecp_curves_new.c are identical. The goal of the current issue is that in the end:
- ecp_curves.c doesn't have any new bignum related changes (doesn't use bignum at all and is exactly like it was before.
- ecp_curves_new.c has the new bignum related changes

Does this answer your question?

**Comment by xkqian** [comment]
> After the prerequisite for this issue is done, ecp_curves.c and ecp_curves_new.c are identical. The goal of the current issue is that in the end:
> 
> * ecp_curves.c doesn't have any new bignum related changes (doesn't use bignum at all and is exactly like it was before.
> * ecp_curves_new.c has the new bignum related changes
> 
> Does this answer your question?

Yes, clearly. Thanks.

**Comment by paul-elliott-arm** [comment]
Unfortunately its not going to be enough to just revert `ecp_curves.c` here - there are changes to `ecp.c` which would also need rolling back - specifically so far I have found https://github.com/Mbed-TLS/mbedtls/pull/6939, but there definitely may be more, and potentially in other files. There is also newer work that will need to be re-applied on top of any roll back.

**Comment by xkqian** [comment]
> Unfortunately its not going to be enough to just revert `ecp_curves.c` here - there are changes to `ecp.c` which would also need rolling back - specifically so far I have found #6939, but there definitely may be more, and potentially in other files. There is also newer work that will need to be re-applied on top of any roll back.

Thanks fot the investigation of the failure of CI.  I just check the history of ecp.c, fortunately we didn't have too much changes after this commit https://github.com/Mbed-TLS/mbedtls/commit/449bd8303eed8164b83682d2ce028dca0e49b1fa, so I will apply the changes and hope we can solve kinds of errors.
