### ISSUE TITLE
TLS: Clean up (EC)DH dependencies

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7612]
During the work on driver-only ECC (top level), we replaced all dependencies on `ECDH_C` with `PSA_WANT_ALG_ECDH` in the TLS 1.3 code, and replace a lot but not all of the dependencies in TLS 1.2 as well. The "not all" part might be a problem.

There's also a pre-existing problem in how TLS 1.2 decides to include code: if `ECDH_C` is enabled, but none of the TLS 1.2 key exchanges  that uses ECDH is enabled, some of the support for ECDH in TLS 1.2 is still enabled. The TLS layer should, as much as possible, use TLS feature macros (`MBEDTLS_KEY_EXCHANGE_xxx`) rather than low-level ones (such as `ECDH_C`).

By contrast, ECJPAKE does things the right way: TLS code never looks a `MBEDTLS_ECJPAKE_C`, only `MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED`. Then `check_config.h` checks that whatever is needed is enabled (might be `ECJPAKE_C` or `PSA_WANT_ALG_JPAKE` with the appropriate curve).

This task is to achieve a similar state for ECDH.

This will be a bit more complex than the ECJPAKE case, as there are more than one TLS 1.2 key exchange that uses ECDH, and TLS 1.3 use it too. This can probably be resolved by taking advantage of existing "SOME" macros:
- `MBEDTLS_KEY_EXCHANGE_SOME_ECDHE_ENABLED` for TLS 1.2 ECDHE (ephemeral ECDH) key exchanges;
- `MBEDTLS_KEY_EXCHANGE_SOME_ECDH_ENABLED` for TLS 1.2 ECDH (static ECDH) key exchanges;
and defining new ones if needed, for example:
- `MBEDTLS_KEY_EXCHANGE_SOME_ECDH_OR_ECDHE_1_2_ENABLED` for any TLS 1.2 ECDH(E) key exchange;
- `MBEDTLS_KEY_EXCHANGE_SOME_ECDH_OR_ECDHE_ANY_ENABLED` for any TLS 1.3 or 1.2 ECDH(E) key exchange.
- [Edited to add] After #7627 perhaps `MBEDTLS_KEY_EXCHANGE_SOME_DH_ANY_ENABLED` for any TLS 1.3 or 1.2 (EC)DH(E) key exchange.

This task is completed when `grep ECDH_C library/ssl_*.c library/ssl_*.h include/mbedtls/ssl*.h` finds nothing (and all tests pass unchanged - except perhaps adjusting how dependencies are expressed, but without changing which tests are skipped - use `outcome-analysis.sh` to ensure that).

**Conflicts with:** #7613 - likely to change many of the same lines, so better not executed in parallel to avoid merge conflicts.
**Depends on:** #7627

**Comment by mpg** [comment]
Note: although the issue is originally about ECDH, there are similar issues to be fixed (although to a lesser extent hopefully) with FFDH in TLS 1.3, see https://github.com/Mbed-TLS/mbedtls/pull/7627#discussion_r1209980567 - and also https://github.com/Mbed-TLS/mbedtls/pull/7627#discussion_r1210053135 and https://github.com/Mbed-TLS/mbedtls/pull/7627#discussion_r1210053312 which I think are consequences of the first one.

It makes sense to fix both ECDH and FFDH at the same time, as some of the fields and functions uses are common.

**Comment by mpg** [comment]
Note: all occurrences of `ECP_LIGHT` or `ECP_C` in TLS code (including tests and programs) are also suspect and should be reviewed once this and #7613 are done.

**Comment by mpg** [comment]
See also https://github.com/Mbed-TLS/mbedtls/pull/7810#discussion_r1236755366

**Comment by valeriosetti** [comment]
@mpg While working at this I found that actually there are also `MBEDTLS_PK_CAN_ECDH` dependencies in the SSL/TLS code together with `MBEDTLS_ECJPAKE_C`. The latters are already mentioned in the description of this PR and I'm already working to remove them as you suggested (huge thanks btw for the tips!!!), while the former not.
It seems to me that:

- also these dependencies are to be replaced with the proper `KEY_EXCHANGE` symbol
- `KEY_EXCHANGE` symbols should have a dependency on `MBEDTLS_PK_CAN_ECDH` to be checked somewhere else

Am I missing something?

**Comment by mpg** [comment]
I don't think you're missing anything, but rather _I_ missed that when writing the issue's description :) Thanks for noticing. Indeed the goal of this issue is that all* ECDH guards inside the TLS code should be like "is there a key exchange (mode) that uses ECDH(E)?" rather than any variant of "is the crypto library able to do ECDH?" (be it `ECDH_C` or `PK_CAN_ECDH`).

Then in `check_config.h` each `KEY_EXCHANGE` symbol should have checks like "if the crypto library is not able to do all the operations I need, `#error`".

*If not all guards can be converted this way (I'm thinking about TLS 1.3 (psk-)ephemeral), then we should have the "can the crypto library do ECDH" in one place, to define a TLS-specific macro that's then used everywhere else.

(Note: for ECDSA the situation will be a bit more complicated due to client auth.)

**Comment by mpg** [comment]
Note: this may also conflict with #7858 but this should only be contextual conflicts (7858 is renaming a lot of things that are likely to be close to some of the guards you're modifying here), so I don't think this should prevent you from working on this now, just FYI. (Also, 7858 will hopefully get merged soon.)

**Comment by valeriosetti** [comment]
> Then in check_config.h each KEY_EXCHANGE symbol should have checks like "if the crypto library is not able to do all the operations I need, #error".
*If not all guards can be converted this way (I'm thinking about TLS 1.3 (psk-)ephemeral), then we should ideally have the "can the crypto library do ECDH" in only one place, to define a TLS-specific macro that's then used everywhere else.

I checked `check_config.h` and it seems to me that all TLS 1.2 key exchanges already have proper guards, i.e. `MBEDTLS_PK_HAVE_ECDH` and/or `MBEDTLS_PK_HAVE_ECDSA`. TLS 1.3 instead have direct references to `PSA_WANT_ALG` symbols, but I guess this is because TLS 1.3 directly goes to PSA functions and do not use any "intermediate" module such as the PK one.
Therefore, in short, it seems to me that all the guards in `check_config.h` are fine.

What I will try to do now, as anticipated on Slack, is to avoid duplicates between the `PK_HAVE_[ECDH/ECDSA]` symbols used in `check_config.h` and `PK_CAN` defined in `pk.h`. New symbols will be placed in `build_info.h` so that they will be accessible everywhere needed.

**Comment by mpg** [comment]
> Indeed the goal of this issue is that all* ECDH guards inside the TLS code should be like "is there a key exchange (mode) that uses ECDH(E)?" rather than any variant of "is the crypto library able to do ECDH?" (be it `ECDH_C` or `PK_CAN_ECDH`).

Forgot one: `PSA_WANT_ALG_ECDH` is also suspect and should, as much as possible, be replaced with TLS-level macros, like `MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_SOME_ECDHE_ENABLED` I was suggesting [here](https://github.com/Mbed-TLS/mbedtls/pull/7884#discussion_r1255374895).

Note: I suspect that in most of the 1.3 code, we only check for `WANT_ALG_ECDH` inside blocks that are already guarded by `SOME_EPHEMERAL_ENABLED` so functionally that's equivalent. But even in those case, I'd prefer not using `WANT_ALG_ECDH`, just to reduce the number of occurrences and make things easier to audit and more uniform.
