### ISSUE TITLE
Define PSA_WANT_KEY_TYPE_xxx_KEY_PAIR_yyy (step 1)

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7614]
Context: https://github.com/Mbed-TLS/mbedtls/issues/7439#issuecomment-1543790495 (and preceding + following discussion).

- [ ] Add macros `PSA_WANT_KEY_TYPE_xxx_KEY_PAIR_yyy` where xxx is any of RSA, ECC, DH in `mbedtls/config_psa.h` and `psa/crypto_config.h`, and yyy is any of  USE, IMPORT, EXPORT, GENERATE, DERIVE. All of them are enabled by default except `MBEDTLS_WANT_KEY_TYPE_RSA_KEY_PAIR_DERIVE` which if defined gives an error in `check_config.h` as it's not implemented.
- [ ] Add a new internal macro `MBEDTLS_PSA_WANT_KEY_TYPE_xxx_KEY_PAIR_LEGACY` where xxx is and or RSA, ECC (not DH) that's automatically defined (in `build_info.h` or `config_psa.h`) when:
  - for RSA: USE && IMPORT && EXPORT && GENERATE
  - for ECC: USE && IMPORT && EXPORT && GENERATE && DERIVE
- [ ] Replace test dependencies that were expressed in terms of the macros that are going to be deprecated/removed below with uses of the new (internal) macros defined above.
- [ ] Deprecate `PSA_WANT_KEY_TYPE_xxx_KEY_PAIR` for xxx in RSA, ECC,. Being deprecated, they shouldn't be enabled in the default config. If they're defined, they should auto-enable the same lists as above for RSA resp. ECC. If `MBEDTLS_DEPRECATED_WARNING` (resp. `_REMOVED) is defined, defining one of those macros will give a warning (resp. error) in `check_config.h` and the message should point to one of the new macros. A ChangeLog should be added under "New deprecations".
- [ ] Remove `PSA_WANT_KEY_TYPE_DH_KEY_PAIR` (it wasn't in any released version so far).

**Comment by valeriosetti** [comment]
Even thought this is not explicitly mentioned in the description, since we're changing dependencies in tests I guess that we'll want to run also `outcome-analysis.sh` on this, right?

**Comment by mpg** [comment]
Absolutely!
