### ISSUE TITLE
Pass structrures by pointer instead of by value

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#7616]
### Suggested enhancement
PR #7595 adds new code that passes structure arguments by value.
An attempt to address the same issue was made in PR #1766.

### Justification
The common and probably preferred way is to pass structure arguments by pointers.
Old API should not be broken because this is a new code.
Library code after the suggested change would look more natural and require no pointer dereferencing.

**Comment by davidhorstmann-arm** [comment]
Thanks for your suggestion to improve Mbed TLS!

Thinking about this and looking at previous discussion, I'm sceptical of the benefit for performance. The `mbedtls_pk_context` struct has this declaration:
```c
typedef struct mbedtls_pk_context {
    const mbedtls_pk_info_t *MBEDTLS_PRIVATE(pk_info);    /**< Public key information         */
    void *MBEDTLS_PRIVATE(pk_ctx);                        /**< Underlying public key context  */
#if defined(MBEDTLS_PSA_CRYPTO_C)
    mbedtls_svc_key_id_t MBEDTLS_PRIVATE(priv_id);      /**< Key ID for opaque keys */
#endif /* MBEDTLS_PSA_CRYPTO_C */
} mbedtls_pk_context;
```
It is 2 or 3 machine words in size, so quite small. Even if the compiler does not inline the call as discussed in #1766, the memory copying is minimal and it is likely that the struct will fit into registers for the function call.

With that in mind, the main benefit of this would be readability. I'm not sure whether the improvement in readability is worth making this change, @mpg perhaps you can comment?

**Comment by gilles-peskine-arm** [comment]
We are deprecating `mbedtls_pk_ec` and `mbedtls_pk_rsa`. Until the next major release of Mbed TLS, they have to stay as they are. In the next major release, they will be gone.

The new functions introduced in #7595 are designed to facilitate the transition inside the library, so to start out they have the same interface as the old functions. They will evolve based on the needs of calling sites and they will go away when the transition is over.

So I don't see anything to do here.

**Comment by irwir** [comment]
If this code is transient then it makes little sense to go for any polishing.

@davidhorstmann-arm
> It is 2 or 3 machine words in size, so quite small. Even if the compiler does not inline the call as discussed in #1766, the memory copying is minimal and it is likely that the struct will fit into registers for the function call.

This depends on the processor architecture and compiler. Besides, passing arguments in tegisters is a kind of optimization.
But if functions were inlined, it might be expected to get the same code in both cases.
