### ISSUE TITLE
PBKDF2: add support for CMAC

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#7645]
In #7132 we introduced an implementation of PBKDF2 based on `psa_mac_xxx()` APIs, which should work for both HMAC and CMAC - however we only tested HMAC.

Add test cases using CMAC, and fix any issue that might be found in the implementation when CMAC is used.

Note: if this issue done after #7133, it should have test cases for both `output_bytes()` and `output_key()` with CMAC.

**Depends on:** #7132

**Comment by silabs-Kusumit** [comment]
I am facing trouble finding standard test vectors for the PBKDF2-CMAC implementation. I managed to find one test vector in the OpenThread implementation, but that would not be enough. 
Can I treat the OpenThread implementation as standard and create new test vectors with it?

Do you have any suggestions on the accepted ways for creating new vectors?

**Comment by mpg** [comment]
Good question! I think if we're unable to find official test vectors, then yes, using an existing implementation as a source of test vectors is the best we can do. If we can locate a 2nd implementation of PBKDF2-CMAC in order to reproduce, that would give more confidence in the values we'll use as test vectors.

Wikipedia has a [list of PBKDF2 implementations](https://en.wikipedia.org/wiki/List_of_PBKDF2_implementations) (perhaps a bit out of date as it still calls us PolarSSL), we should check if any of them supports CMAC.

**Comment by gilles-peskine-arm** [comment]
Cryptodome is convenient (you can typically use it with a couple of lines of python) but I'm not sure if its [PBKDF2](https://pycryptodome.readthedocs.io/en/latest/src/protocol/kdf.html#pbkdf2) implementation supports CMAC. It accepts a PRF as argument, but the preprocessing of the password under HMAC and CMAC is different so I don't know if the way the library is implemented gives the correct result when not used with HMAC.
