### ISSUE TITLE
armclang compile fail for Cortex-m0

### ISSUE THREAD

**Issue by daverodgman** [Mbed-TLS/mbedtls#7647]
### Summary

`make lib CFLAGS="-Os --target=arm-arm-none-eabi -mcpu=cortex-m0" CC=armclang` fails (development and 2.28):

Many errors of the form:

```
bignum.c:1446:9: error: inline assembly requires more registers than available
        MULADDC_INIT
        ^
../include/mbedtls/bn_mul.h:683:13: note: expanded from macro 'MULADDC_INIT'
            "ldr    r0, %3                      \n\t"   \
            ^
```

This is very long-standing - I can reproduce with e.g. Mbed TLS 2.16.0 so presumably not too many people are affected by this (which seems surprising).

**Comment by daverodgman** [comment]
I wonder if this could be an armclang bug. It only fails when -Os is provided.

**Comment by gilles-peskine-arm** [comment]
This was already reported in https://github.com/Mbed-TLS/mbedtls/issues/1077
