### ISSUE TITLE
Make out-of-range INPUT_COST test case for PBKDF2 use PSA_VENDOR_PBKDF2_MAX_ITERATIONS

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7653]
https://github.com/Mbed-TLS/mbedtls/pull/7547 added a test case for PBKDF2 with an input cost out of range, but the test case as written can't depend on the macro that defines the bound, it has a (wrong) value hard-coded. Fixing this in #7547 is impractical because it requires a more recent development.

The goal of this issue is to implement https://github.com/Mbed-TLS/mbedtls/pull/7547#discussion_r1204581917.

**Comment by silabs-Kusumit** [comment]
@gilles-peskine-arm I tried to write a function for this with arguments `alg` and `int64_t cost`.
However when I pass `cost` as `PSA_VENDOR_PBKDF2_MAX_ITERATIONS+1` in the data file, it results in `0`. Passing only `PSA_VENDOR_PBKDF2_MAX_ITERATIONS` works fine. I think that this is due to the parser parsing it as `exp` instead of `int`.

**Comment by silabs-Kusumit** [comment]
Should I change function behavior such that `cost` parameter is treated as `PSA_VENDOR_PBKDF2_MAX_ITERATIONS + cost` or generically `max_value + cost`. We can add a `expected_status` parameter and check with costs `1`, `0` and `-1`.

**Comment by gilles-peskine-arm** [comment]
I think the problem is the definition of `PSA_VENDOR_PBKDF2_MAX_ITERATIONS`, not with the test framework:
```
#define PSA_VENDOR_PBKDF2_MAX_ITERATIONS 0xffffffff
```
That fits a 32-bit `unsigned int` but not `int`, so `PSA_VENDOR_PBKDF2_MAX_ITERATIONS + 1` is 0, going by the rules for promotion in C.

The definition should use the `UL` suffix on the constant to avoid this gotcha.

**Comment by gilles-peskine-arm** [comment]
On second thoughts, `PSA_VENDOR_PBKDF2_MAX_ITERATIONS` will become a configuration parameter, so we should make it easy to use. This is not a concern for most other constants in `crypto_values.h` and `crypto_sizes.h`. So it would be better to be robust at the point of use, i.e. write `(uint64_t) PSA_VENDOR_PBKDF2_MAX_ITERATIONS + 1` or `PSA_VENDOR_PBKDF2_MAX_ITERATIONS + 1ULL`.
