### ISSUE TITLE
Design comparison functions for the new Bignum modules

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#7669]
### Considerations

**Performance:** 
    - `_equals()` and `_is_zero()` are twice as fast as `cmp()`
    - we need `_is_one()` as well

**Code size:**
    - every function we add adds to the code size (if we have a single function called from everywhere, the code size is smaller than having 6 functions being called from various locations)
    - we have 3 modules, two of them restricted in use and operating on different types (types either meaning C types or conceptual types - _core and _raw both operate on raw pointers, but the pre and post conditions are different and they can be considered different types)
 
**Abstraction:**
Conceptually comparison beyond equals doesn't make sense outside of _core (these fields and rings don't have proper ordering, but certainly not in the conventional sense)

### Options

1. Translate the legacy functions as they are. This will result in 3 `_cmp_int()` and 3 `_cmp_mpi()` functions.
    - These would be calling each other in chain trivially
    - Code size overhead would be eliminated by static function declarations
2. Do `_equals()`, `_is_zero()` and `_is_one()`. This will result 3 functions in each module.
    - These would be calling each other in chain trivially
    - Code size overhead would be eliminated by static function declarations
    - is_one could call is_zero and the code size cost would be comparable to Option 1
    - Would be faster than Option 1
    - Not as flexible as option 1
3. Only have `_equals()`. Declare ZERO and ONE as constants (max curve size)
    - Conceptually clean
    - The constants would take more code size than the functions in the other versions (not much on 64 bit platforms, but larger difference on 32 bit and especially on thumb)
    - Would be faster than Option 1
    - Not as flexible as option 1
4. Have `_equals()` and `_equals_int()`
    - Comparable in code size to Option 1
    - Would be faster than Option 1
    - Not as flexible as option 1, but more flexible than option 2 and 3

### Definition of Done

This task is done when a way forward has been chosen (not necessarily one of the above options), it is reviewed and the description of https://github.com/Mbed-TLS/mbedtls/issues/6236 is updated. (Strike through the old description of 6236 to avoid confusion because of the existing commits.)

**Comment by gilles-peskine-arm** [comment]
Would we have this for constant-time functions as well?

In the proposed options, I dislike option 3. I don't find it clean at all. The constants ZERO and ONE would have to be as large as the largest bignum, which means they wouldn't scale well to RSA. The constants would need to be wrapped in each high-level interfaces that tag a bignum with its size. The code size increases sharply with the number of constants, although I suppose it's unlikely we'd ever add more easily-described constants. Counterpoint: in measuring the code size, note that the limb arrays for ZERO and ONE can overlap.

In terms of interface, I think having `equals_int` makes the code more readable, and we might as well write `is_zero` and `is_one` when comparing with those regardless of how it's implemented.

I don't have a good picture of how frequent the various cases are, and how often they're used in an inner loop (which is where performance matters). Maybe we can implement several cases and compare? Most of the work is converting the points of use and writing tests, not implementing the functions themselves, so we can do that last part more than once.

**Comment by yanesca** [comment]
> Would we have this for constant-time functions as well?

I was thinking about having only constant time versions of these.

> we might as well write `is_zero` and `is_one` when comparing with those regardless of how it's implemented.

That is a good point, probably should do that.

> Maybe we can implement several cases and compare? Most of the work is converting the points of use and writing tests, not implementing the functions themselves, so we can do that last part more than once.

That is a good idea. It would be even less work if we use your previous suggestion, because almost all of the calls would be using the `_equals()`, `_is_zero()` and `_is_one()` inline aliases.
