### ISSUE TITLE
Empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]

### ISSUE THREAD

**Issue by matetothpal** [Mbed-TLS/mbedtls#7675]
### Summary
Compiling Mbed TLS with clang >= v15 results in compilation errors.
This is an issue similar to https://github.com/Mbed-TLS/mbedtls/issues/7146 and https://github.com/Mbed-TLS/mbedtls/issues/6960 but this time in `library/psa_crypto_ffdh.h`

### System information

Mbed TLS version (current development branch (0b687840537144fa8887b7ede704002374b8c6d9)): 
Operating system and version: X86_64 Ubuntu 20.04
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): llvm 15.0.6
Additional environment information: -

### Expected behavior
Build successfully

### Actual behavior
Build error:
```
In file included from library/psa_crypto.c:38:
library/psa_crypto_ffdh.h:50:41: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_ERROR_INSUFFICIENT_MEMORY
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
library/psa_crypto_ffdh.h:51:41: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_ERROR_CORRUPTION_DETECTED
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
library/psa_crypto_ffdh.h:76:35: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_ERROR_NOT_PERMITTED
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
...
```

### Steps to reproduce
```
rm -fr build && mkdir build && pushd build && \
cmake -DCMAKE_C_COMPILER=clang .. && \
cmake --build . ; \
popd
```

**Comment by gilles-peskine-arm** [comment]
This specific case was fixed in https://github.com/Mbed-TLS/mbedtls/pull/7805.

With https://github.com/Mbed-TLS/mbedtls/pull/7968, we do a build with Clang 16 on our CI. We aren't doing a build with `-Wdocumentation` yet, so we aren't yet checking that other similar cases won't sneak it, but that's planned soon. So I'm closing this issue as resolved.
