### ISSUE TITLE
CSR with subject containing commas not accepted by cert_write

### ISSUE THREAD

**Issue by cwtios** [Mbed-TLS/mbedtls#769]
Hello,

I noticed during testing that the cert_write program will not accept a CSR generated by cert_req, if the CSR contains a subject with one or more items therein containing commas, which is then followed by another item.  For what its worth, the CSR can be handled by OpenSSL.

Here are the commands I am testing with:

To generate the CSR:
`cert_req.exe filename=test.key output_file=test.p10 subject_name="CN=example, O=Test\, Inc., C=US" key_usage=digital_signature,key_encipherment`

To generate the certificate given the CSR:
`cert_write.exe request_file=test.p10 issuer_key=issuer.key`

cert_write fails with "  !  mbedtls_x509write_crt_set_subject_name returned -0x2100 - X509 - Requested
OID is unknown".

I suppose this is due to the fact that cert_write loads the CSR and encodes the subject into a string, but does not escape the resultant string before attempting to parse it.  When it tries to parse the string it fails since the comma inside "Test, Inc." is not escaped.

A reasonable way to handle this would perhaps be to copy the subject from the CSR directly into the destination certificate structure, rather than round-tripping the subject into string format and then parsing it again.  If that is not acceptable, perhaps escaping the string after loading it from the CSR would be another solution.

Also worth noting, is that if I leave off the ", C=US" part of the subject in the initial cert_req run, the CSR will be accepted by cert_write, but the resulting certificate will contain a subject with only "CN=subject, O=Test".  The, ", Inc." part just gets silently discarded.

NOTE: Edited to format commands as code, to fix escaping issues.

Thanks,

Chris

**Comment by andresag01** [comment]
Thank you for your report. I can confirm that I am able to reproduce the issue reported.

As you say, the problem is that the string encoded into the CSR is not escaped. This causes a failure in the sample application at `programs/x509/cert_write.c` because the non-escaped string is used to craft the new certificate. We will further investigate the problem and issue an appropriate fix.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1175
