### ISSUE TITLE
library/aesni.c build fail on windows arm64

### ISSUE THREAD

**Issue by jiayuehua** [Mbed-TLS/mbedtls#7704]
### Summary
library/aesni.c build fail. report include\immintrin.h(15): fatal error C1189: #error:  This header is specific to X86 and X64 targets

### System information

Mbed TLS version (number or commit id): v2.28.3
Operating system and version: windows 11
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): msvc
Additional environment information: 

### Expected behavior
should build success

### Actual behavior

build fail

### Steps to reproduce

build on arm64 windows should reproduce

### Additional information
[4/100] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\arm64\cl.exe    -ID:\buildtrees\mbedtls\arm64-windows-dbg\include -ID:\installed\arm64-windows\include -ID:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\include -ID:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\library /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /W3 /utf-8 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folibrary\CMakeFiles\mbedcrypto.dir\aesni.c.obj /Fdlibrary\CMakeFiles\mbedcrypto.dir\mbedcrypto.pdb /FS -c D:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\library\aesni.c
FAILED: library/CMakeFiles/mbedcrypto.dir/aesni.c.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\arm64\cl.exe    -ID:\buildtrees\mbedtls\arm64-windows-dbg\include -ID:\installed\arm64-windows\include -ID:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\include -ID:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\library /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /W3 /utf-8 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folibrary\CMakeFiles\mbedcrypto.dir\aesni.c.obj /Fdlibrary\CMakeFiles\mbedcrypto.dir\mbedcrypto.pdb /FS -c D:\buildtrees\mbedtls\src\v2.28.3-daafc1cf77.clean\library\aesni.c
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\immintrin.h(15): fatal error C1189: #error:  This header is specific to X86 and X64 targets

**Comment by jiayuehua** [comment]
https://github.com/microsoft/vcpkg/pull/31867

**Comment by gilles-peskine-arm** [comment]
I believe this is fixed by https://github.com/Mbed-TLS/mbedtls/pull/8209 which is merged on the `mbedtls-2.28` branch and will be included in the next 2.28 release coming in a few days.
