### ISSUE TITLE
Add  missing commands `tests/data_files/*` into `tests/data_files/Makefile`

### ISSUE THREAD

**Issue by yuhaoth** [Mbed-TLS/mbedtls#7731]
### Suggested enhancement

Some files' commands are miss in `tests/data_files/Makefile`. That can record how the files are generated and reduce work loads when the files are invalid.

**Comment by gilles-peskine-arm** [comment]
I'm removing this from the Q2 epic because it's a long-term task. It'll be for the tech debt board which I want to create soon.
