### ISSUE TITLE
Rare intermittent failure of a TLS 1.3 session resumption test

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7795]
The failure is in one of the `ssl-opt` test cases:
```
TLS 1.3 m->m: Session resumption failure, age outside tolerance window, too old.  FAIL
  ! pattern 'sent selected_identity:' MUST NOT be present in the Server output
  ! outputs saved to o-XXX-1587.log
```

The logs:
[all_u16-test_psa_crypto_config_accel_hash_use_psa-o-cli-1587.log.gz](https://github.com/Mbed-TLS/mbedtls/files/11771081/all_u16-test_psa_crypto_config_accel_hash_use_psa-o-cli-1587.log.gz)
[all_u16-test_psa_crypto_config_accel_hash_use_psa-o-srv-1587.log.gz](https://github.com/Mbed-TLS/mbedtls/files/11771086/all_u16-test_psa_crypto_config_accel_hash_use_psa-o-srv-1587.log.gz)

Observed in https://jenkins-mbedtls.oss.arm.com/blue/organizations/jenkins/mbed-tls-pr-head/detail/PR-7717-head/8/pipeline running on https://github.com/Mbed-TLS/mbedtls/commit/3471e195b703bf9b3d093da5634e8d1fe3f5ca44. The test passed on OpenCI. The changes in that pull request are not related to the test.

**Comment by ronald-cron-arm** [comment]
Not finished, some parts of #8525 remaining.
