### ISSUE TITLE
Backport: crypto_config_test_driver_extension: handle PUBLIC_KEY the same way as KEY_PAIRs

### ISSUE THREAD

**Issue by valeriosetti** [Mbed-TLS/mbedtls#7796]
PR #7641 was merged but it lacked the backporting of a change in `crypto_config_test_driver.h` (see [this comment](https://github.com/Mbed-TLS/mbedtls/pull/7641#discussion_r1224416979)): asymmetric public keys symbols, i.e. `PSA_WANT_KEY_TYPE_xxx_PUBLIC_KEY` should be treated the same way as their private counterparts (i.e. `PSA_WANT_KEY_TYPE_xxx_KEY_PAIR`)

**Comment by mpg** [comment]
Was it really about `config_psa.h`? I thought it was the bit about `crypto_config_test_driver_extension.h` that we wanted to backport. At least for me, the reasoning for backporting was "`crypto_config_test_driver_extension.h` is tricky enough as it is, so let's avoid having to remember two versions of it too". Or is it tied to changes in `config_psa.h` in a way that I missed?

**Comment by gilles-peskine-arm** [comment]
`config_psa.h` is already pretty different in development vs 2.28 and is going to change a lot more. `crypto_config_test_driver_extension.h` is the one we should probably try to keep aligned.

**Comment by valeriosetti** [comment]
Ops, sorry, I totally misinterpreted what was the purpose of the [original comment](https://github.com/Mbed-TLS/mbedtls/pull/7641#discussion_r1224416979) indeed. I will fix both description and title of this issue.

**Comment by valeriosetti** [comment]
I'm closing this one because it was associated with PR #7798 which was merged yesterday. Perhaps I didn't put the correct keyword in the description to have this handled automatically by Github.

**Comment by gilles-peskine-arm** [comment]
@valeriosetti Thanks for remembering to close this! GitHub didn't close it automatically because that only happens if the target branch is the repository's main branch, which is `development`.  Issues that are resolved by merging to an LTS branch don't get closed automatically, and I forgot about that when I merged the PR.
