### ISSUE TITLE
Announce planned 4.0 deprecations

### ISSUE THREAD

**Issue by daverodgman** [Mbed-TLS/mbedtls#7800]
Mark things as deprecated in 3.x, so that we can remove things in 4.0.

This issue needs a list of what exactly we will deprecate before we can work on it; for now it's a placeholder.

**Comment by gilles-peskine-arm** [comment]
The discussion of what to remove in 4.0 is happening at https://github.com/Mbed-TLS/mbedtls/issues/6792.

Note that there are likely things we want to _change_ — not removing functionality, but changing the way to achieve the same functionality. But we don't particularly need to deprecate the old version in advance for that (although we certainly can, and given the number of things we want to change in 4.0 we should get started on those early).

**Comment by mpg** [comment]
See also https://github.com/Mbed-TLS/mbedtls/issues/8663 for a (provisional) list of things we want to make internal, which should be announced as well (from a user's point of view, it's the same as a removal).

**Comment by mpg** [comment]
See https://lists.trustedfirmware.org/archives/list/mbed-tls-announce@lists.trustedfirmware.org/thread/YREHWMX4EAHMTMGOUZUVDVOQBHHSNXUL/

> GitHub links — cryptographic mechanisms
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/102 — Custom ECC mechanisms
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/104 — Custom RSA mechanisms
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/105 — Import of incomplete RSA private keys
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/107 — Direct access to CTR_DRBG and HMAC_DRBG
> https://github.com/Mbed-TLS/mbedtls/issues/8459 — RSA PKCS#1v1.5 encryption
> https://github.com/Mbed-TLS/mbedtls/issues/9164 — DES (including 3DES)
> 
> GitHub links — cryptography implementations
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/103 — Partial ECC acceleration
> https://github.com/Mbed-TLS/mbedtls/issues/8151 — Dynamically registered secure element drivers
> 
> GitHub links — TLS 1.2
> https://github.com/Mbed-TLS/mbedtls/issues/5278 — FFDH in TLS 1.2
> https://github.com/Mbed-TLS/mbedtls/issues/8170 — RSA decryption cipher suites (RSA without DH/ECDH)
> https://github.com/Mbed-TLS/mbedtls/issues/9201 — Static ECDH cipher suites
> https://github.com/Mbed-TLS/mbedtls/issues/9202 — CBC cipher suites
> https://github.com/Mbed-TLS/mbedtls/issues/9201
> GitHub links — platform
> https://github.com/Mbed-TLS/mbedtls/issues/8108 — Platform interface redesign
> https://github.com/Mbed-TLS/TF-PSA-Crypto/issues/106 — Building with plain make or CMake
> https://github.com/Mbed-TLS/mbedtls/issues/8231 — x86_64: AESNI without compiler intrinsics
> https://github.com/Mbed-TLS/mbedtls/issues/9307 — Support for %zu in printf

**Comment by gilles-peskine-arm** [comment]
For 3.x, we missed the ball and never announced any of the deprecations.

For 4.0, we've [sent consultation emails](https://github.com/Mbed-TLS/mbedtls/issues/7800#issuecomment-2270641351). I expect that we'll send other messages once we've made decisions, but there's no particular timeline on announcements. Some aspects of the 4.0 design will not be finalized until March 2025, when we plan remaining changes based on the available time. So I consider this issue to be done.
