### ISSUE TITLE
Automatically generate PSA tests also for DH keys

### ISSUE THREAD

**Issue by valeriosetti** [Mbed-TLS/mbedtls#7812]
### Suggested enhancement

While working on #7771 I noticed this comment in `generate_psa_tests.py`:

https://github.com/Mbed-TLS/mbedtls/blob/a3a0025e1831b9d22e8587d88a4d4d42dfad38bb/tests/scripts/generate_psa_tests.py#L143

However due to the recent development on DH keys, I'm not sure this comment (and following actions) is still correct. If this is the case, then the following lines should be removed:

```
        constructors.key_types.discard('PSA_KEY_TYPE_DH_KEY_PAIR')
        constructors.key_types.discard('PSA_KEY_TYPE_DH_PUBLIC_KEY')
```

### Justification

Mbed TLS needs this in order to fully cover asymmetric keys testing.

**Comment by mpg** [comment]
I wanted to check if this was as trivial as commenting out those lines, then one thing led to another, and I ended up raising a PR :)
