### ISSUE TITLE
Why the domain parameters for secp384r1 doesn't have parameter A?

### ISSUE THREAD

**Issue by logself1988** [Mbed-TLS/mbedtls#7817]
### Summary
Recently we have implemented ECC hardware acceleration with mbedtls, we found that the domain parameters for secp384r1 doesn't have parameter A, that is different from the recommended parameters in this document [SEC 2: Recommended Elliptic Curve Domain Parameters](https://www.secg.org/SEC2-Ver-1.0.pdf). Is this correct ? If so, Why the difference here? Thanks.

### System information

Mbed TLS version (number or commit id): 3.4.0 or earlier verision
Operating system and version: FreeRTOS
Configuration (if not default, please attach `mbedtls_config.h`): MBEDTLS_ECDH_C, MBEDTLS_ECDSA_C enabled
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gcc
Additional environment information: running on risc-v processor

### Expected behavior
We expected a parameter A definition as recommened for secp384r1

### Actual behavior
There is no this definiton in ecp_curves.c

### Steps to reproduce
none

### Additional information
none

**Comment by logself1988** [comment]
> `A.p==NULL` in the group structure indicates that a = p - 3. The mbedtls code optimizes that case.
> 
> We have a [pending pull request](https://github.com/Mbed-TLS/mbedtls/pull/6999) to update the documentation, which is not very clear.
> 
> Do you need mbedtls to provide the A value? How are you integrating your accelerator? The preferred way to integrate accelerators nowadays is through the PSA API, completely independently of the contents of `ecp.c`. The legacy way, with `MBEDTLS_ECP_xxx_ALT`, will remain supported throughout 3.x versions, but will be removed in Mbed TLS 4.0.

Sorry for late reply, actually we need to use recommended parameters secp256r1 and secp384r1, and we need to convert those paramters loaded from mbedtls (by mbedtls_ecp_group_load) to internal domain parameters, so for your first question yes, we need mbedtls to provide the A value, and it is not the value as recommended, I wonder why there is the difference, is it for efficiency and the parameter is simplified? if we want to comply with the standard secp256r1 and secp384r1, how can we handle this? 
For second question, thanks for the information, we are using the legacy way to implement our accelerator now, is there any document that given more details for the prefered way with PSA API? Will it replace all the current XXX_ALT mechanism or only for `MBEDTLS_ECP_xxx_ALT`? We have  already implemented AES, HASH, RSA with the legacy way.

**Comment by gilles-peskine-arm** [comment]
> we need mbedtls to provide the A value, and it is not the value as recommended, I wonder why there is the difference, is it for efficiency and the parameter is simplified? if we want to comply with the standard secp256r1 and secp384r1, how can we handle this?

Having `A.p==NULL` is an optimized representation. If you need the numerical value of A, you need to check if `A.p == NULL` and if so calculate `mbedtls_mpi_sub_int(P, 3)` (or the equivalent if you have acceleration for bignum addition).

----

> is there any document that given more details for the prefered way with PSA API?

We have a [driver example and guide](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/psa-driver-example-and-guide.md).

> Will it replace all the current XXX_ALT mechanism or only for MBEDTLS_ECP_xxx_ALT? 

It will replace all ALT mechanisms.

**Comment by logself1988** [comment]
Got it. Thanks a lot.
