### ISSUE TITLE
Possible endless loop in mbedtls_ssl_handshake_step

### ISSUE THREAD

**Issue by kica-z** [Mbed-TLS/mbedtls#7860]
### Summary
When doing an SSL handshake with mbedtls whilst not having the appropriate configuration defines set it is possible to go into an endless loop due to the function `mbedtls_ssl_handshake_step` (mbedtls/library/ssl_tls.c) not adjusting the state. Whilst this is clearly a configuration problem on my side I would have expected the `mbedtls_ssl_handshake` function to return an error message and log that there was no change in state (possible misconfiguration). I could provide a PR for this myself I just wanted to check with you if such an adjustment is wanted/justified.

### System information

Mbed TLS version (number or commit id):  Still present on development branch
Operating system and version: -
Configuration (if not default, please attach `mbedtls_config.h`): -
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): -
Additional environment information: -

### Expected behavior

`mbedtls_ssl_handshake` returns an error code when the state has not changed within an iteration and logs that there might be a misconfiguration.

### Actual behavior

`mbedtls_ssl_handshake` is stuck in an endless loop due to the fact that the function `mbedtls_ssl_handshake_step` does not update the state.

### Steps to reproduce
1. Configure mbedtls for server SSL handshake
2. Disable `MBEDTLS_SSL_SRV_C`
3. Try doing a server SSL handshake

**Comment by gilles-peskine-arm** [comment]
Ideally a nonsensical configuration should result in a compile-time error from `check_config.h`. We try to detect conditions like “TLS 1.x enabled but no suitable cipher suite”, but I'm sure there are still ways where if you forget to enable some feature, you get a configuration that doesn't work. Patches welcome.

Independently from that, a little hardening of the handshake state machine to detect a lack of progress would be a good idea. We do however have to make sure we don't rule out legitimate cases. For example, I think there can be no state change in DTLS in several situations, such as receiving a duplicate packet.

**Comment by daverodgman** [comment]
Given that this problem is primarily down to a mis-configured library, I don't think it is worth keeping this open as fixing it is unlikely to get to the top of the priority list in the foreseeable future. We would accept a PR to fix (or simply better document) this though.
