### ISSUE TITLE
DTLS Connection ID issue

### ISSUE THREAD

**Issue by erpalma** [Mbed-TLS/mbedtls#7865]
### Summary

I'm testing DTLS session resumption on the client side and server side with the mbedtls built-in programs. There seems to be an issue with Connection IDs since they are either not accepted by the server or issued by the client.

### System information

Mbed TLS version (number or commit id): 
Both 3.4.0 and development (56b159a12aeeb7a0f7a6f2006125b8546278becb)

Operating system and version: 
Ubuntu 22.04

Configuration (if not default, please attach `mbedtls_config.h`): 
default

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
gcc 11

### Expected behavior

DTLS session resumption via CID should work, at least with the mbedtls built-in tools.

### Actual behavior

ssl_server2:
```
(initial handshake) Use of Connection ID was not offered by client.
```

ssl_client2:
```
(initial handshake) Use of Connection ID was rejected by the server.
(after renegotiation) Use of Connection ID was rejected by the server.
```

### Steps to reproduce

Run:

`./ssl_server2 server_port=10001 dtls=1 auth_mode=none cid=1`

`./ssl_client2 server_name=localhost server_port=10001 dtls=1 auth_mode=none cid=1`

**Comment by gilles-peskine-arm** [comment]
I'm not very familiar with this feature, but note that with just `cid=1`, you're only enabling CID support, you aren't actually telling the client or the server to send a CID. To send a CID, you need to pass `cid_val=something`. The default for `cid_val` is empty. Per [RFC 9146](https://datatracker.ietf.org/doc/html/rfc9146#name-the-connection_id-extension))

> A zero-length CID value indicates that the client is prepared to send using a CID but does not wish the server to use one when sending

> A zero-length value indicates that the server will send using the client's CID but does not wish the client to include a CID when sending.

[We have test cases for that](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.4.0/tests/ssl-opt.sh#L3037) so I think the library behaves correctly. But the messages from the test programs do seem misleading in the case where both sides offer to use a CID but neither side sends one.

**Comment by daverodgman** [comment]
Closing this as not-a-bug. Please re-open if you think this hasn't addressed your issue.
