### ISSUE TITLE
Error while mbedtls ssl read

### ISSUE THREAD

**Issue by jitensamsung** [Mbed-TLS/mbedtls#7872]
I am working on ESP8266 switch example from this [repo](https://github.com/SmartThingsCommunity/st-device-sdk-c-ref). I am getting the error
```
mbedtls_ssl_read=-0x004c
mbedtls_ssl_write=-0x004e
```
which says 'Reading information from the socket failed' and 'Writing information from the socket failed'.
Please help me solve this issue.
Thanks

**Comment by daverodgman** [comment]
Without any further information, this sounds like there may be an issue with the socket not being properly set up. Mbed TLS is simply reporting that its unable to use the socket provided to it to read/send data.

I don't think this is an Mbed TLS error, but please re-open if you have more info that suggests it is.

**Comment by jitensamsung** [comment]
Ok it's not a Mbed TLS issue but do you have any idea what might be the reason for this error and how to proceed with this.
Thanks
