### ISSUE TITLE
IAR warnings: New warnings on the version 2.28.3 on ecp.c

### ISSUE THREAD

**Issue by Kasimashi** [Mbed-TLS/mbedtls#7873]
### Summary

Using an EWARM compiler (IAR for Embedded Workbench ARM) , I've new warnings on MBEDTLS_MPI_CHK macro.

### System information

Mbed TLS version (number or commit id): 2.28.3
Operating system and version:  Windows 10
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):  EWARM
Additional environment information: 

### Expected behavior

We should not have any warning on compilation.

### Actual behavior

![image](https://github.com/Mbed-TLS/mbedtls/assets/62567511/514f3fdc-d086-45bd-b9e5-8b9f88506204)

### Steps to reproduce

Compile MbedTLS using EWARM 9.20.2

### Additional information

Analog with https://github.com/Mbed-TLS/mbedtls/issues/6924

**Comment by minosgalanakis** [comment]
Closing as complete since all relevant PR's have been merged
