### ISSUE TITLE
PSA maximum size macro definitions should take support into account

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7904]
The definitions of some buffer size macros in `include/psa/crypto_sizes.h` related to asymmetric cryptography range over all key types that are implemented in the library, rather than all key types that are enabled in a given build. This makes some buffers larger than they should be, especially in ECC-only builds that end up using buffers that are large enough for RSA or FFDH.

The goal of this task is to make the definitions of these macros either:

* only take into account key types that are enabled in the build; or
* only take ECC into account if RSA and FFDH are both disabled.

(The first choice is better but the second choice might be easier and will result in mostly the same numbers.)

The macros are:

* `PSA_SIGNATURE_MAX_SIZE`
* `PSA_EXPORT_KEY_PAIR_MAX_SIZE`
* `PSA_EXPORT_PUBLIC_KEY_MAX_SIZE`
* `PSA_RAW_KEY_AGREEMENT_OUTPUT_MAX_SIZE`

**Comment by mpg** [comment]
@valeriosetti I think this, from the 2c EPIC, is available for you to pick. (Would normally tell you on Slack, but [it's down at the moment](https://status.slack.com/2023-07/08e3781ccbef33d5).)
