### ISSUE TITLE
PSA crypto - global variable - synchronization on psa_crypto_init 

### ISSUE THREAD

**Issue by lhuang04** [Mbed-TLS/mbedtls#7945]
### Suggested enhancement
Per suggestion from @paul-elliott-arm, open a separate issue here to track the ones discussed in [global variable issue in PSA crypto](https://github.com/ARM-software/psa-api/issues/77).

- We may need synchronization between our libraries, otherwise we may run into thread-safety issues when we call [psa_crypto_init](https://github.com/Mbed-TLS/mbedtls/blob/development/library/psa_crypto.c#L7578-L7592) from different threads.

### Justification

Mbed TLS needs this because

**Comment by gilles-peskine-arm** [comment]
This is a subset of https://github.com/Mbed-TLS/mbedtls/issues/3263, but it doesn't call out `psa_crypto_init` explicitly, only functions that access keys, so I'm leaving it open for now.

Note that per our [roadmap](https://mbed-tls.readthedocs.io/en/latest/project/roadmap/), we intend to make the PSA subsystem thread safe by the end of 2024.
