### ISSUE TITLE
PSA crypto - global variable - share key slots

### ISSUE THREAD

**Issue by lhuang04** [Mbed-TLS/mbedtls#7947]
### Suggested enhancement
Per suggestion from @paul-elliott-arm, open a separate issue here to track the ones discussed in [global variable issue in PSA crypto](https://github.com/ARM-software/psa-api/issues/77).

- All libraries need to share the[ same set of key slots](https://github.com/Mbed-TLS/mbedtls/blob/development/library/psa_crypto_slot_management.c#L39-L44).

### Justification

Mbed TLS needs this because

**Comment by gilles-peskine-arm** [comment]
Can you please clarify what the requirement is here? I don't understand what you mean by “All libraries need to share the same set of key slots”. What libraries are you talking about? The key store is a global resource. https://github.com/ARM-software/psa-api/issues/77 asks for a way to instantiate multiple key stores, so I guess this is not what you're asking for here, but then what are you asking for?

We already have an issue to track [protecting access to keys from concurrent threads](https://github.com/Mbed-TLS/mbedtls/issues/3263).

**Comment by lhuang04** [comment]
> Can you please clarify what the requirement is here? I don't understand what you mean by “All libraries need to share the same set of key slots”. What libraries are you talking about?

The libraries are the ones we developed, they use mbedtls for different work loads. They are used in one app, each library will instantiate one mbedtls instance, but they need share the same global variable from mbedtls. It will be great if we keep them independent. 

> The key store is a global resource. https://github.com/ARM-software/psa-api/issues/77 asks for a way to instantiate multiple key stores, so I guess this is not what you're asking for here

Yes.

**Comment by paul-elliott-arm** [comment]
The [proposal](https://github.com/Mbed-TLS/mbedtls/issues/3263) to protect key access from concurrent thread access I think should cover this problem. I presume the issue here is concurrent access, from the various libraries?
