### ISSUE TITLE
Remove all internal functions from public headers

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#7964]
For historical reasons, we have public headers (`include/mbedtls/*.h`) that declare private functions. We should move their declarations to private headers. We started doing that during the lifetime of 2.x, but mostly only for new functions, so 2.28 LTS still has many private-use functions declared in public headers. Now, [we doubt whether it's ok to change those functions in a LTS release](https://github.com/Mbed-TLS/mbedtls/pull/7788#issuecomment-1643507413).

Ideally, public headers should not describe any private behavior. In practice, they have to describe the implementation of some types, since the compiler needs to know things like the size of variables of a “private” type. But we don't need to declare private functions that don't need cross-library linkage. (Functions used across libraries — crypto functions used in X.509 or TLS, or X.509 functions used in TLS — should be part of the public API.)

The goal of this task is to remove all functions that are not intended to be public from public headers, before we make a 3.x LTS branch.

**Comment by mpg** [comment]
Note: see https://github.com/Mbed-TLS/mbedtls/issues/7705 for a list.
