### ISSUE TITLE
Error in linking mbedtls with libwebsocket

### ISSUE THREAD

**Issue by sush126** [Mbed-TLS/mbedtls#7978]
### Summary
i am trying to link libwebsocket with mnbedTLS getting below linking issue , i am cross compiling for arm platform using bare metal

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Actual behavior

/lib/libwebsockets.a(ssl_pm.c.obj): in function `ssl_pm_new':
ssl_pm.c:(.text.ssl_pm_new+0x62): undefined reference to `mbedtls_net_init'
/home/projects/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ssl_pm.c:(.text.ssl_pm_new+0x6c): undefined reference to `mbedtls_net_init'
collect2: error: ld returned 1 exit status

**Comment by paul-elliott-arm** [comment]
Hi, this looks like you are having a linker issue with Libwebsocket rather than an issue with MbedTLS - perhaps this would be an issue better reported there?
