### ISSUE TITLE
driver-only ECC: curve acceleration macros

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8016]
Currently, we completely ignore which curves are required by the application vs provided by accelerators when deciding whether to include the built-in implementations `ECP_C`, `ECDH_C` etc.

However, to be consistent with the current semantic of these symbols, we should only disable the built-in implementation when all curves that are required (`PSA_WANT_ECC_xxx`) are also declared as accelerated (`MBEDTLS_PSA_ACCEL_ECC_xxx`).

So, what we should do when `MBEDTLS_PSA_CRYPTO_CONFIG` is enabled is:
- for each curve that is required (`PSA_WANT_ECC_xxx`), check if it's accelerated `MBEDTLS_PSA_ACCEL_ECC_xxx`:
  - if it's not, enable the corresponding `MBEDTLS_EC_DP_xxx` symbol, and set an internal flag to mark that not all curves are accelerated
- check that flag when deciding whether to enable `ECDH_C`, `ECDSA_C` and `ECJPAKE_C`: we'll enable the built-in implementation if there's no accelerator for this alg OR if the flag is set (which is the new part).

This will require adapting the existing tests for "ECP light only", "no ECP at all", "no ECP and no bignum", as they will have to declare all curves as accelerated. We may want to have a variable / helper function in `all.sh` that lists all PSA curves.

Note: might want to wait for https://github.com/Mbed-TLS/mbedtls/pull/7615 in order to avoid conflicts.

Note: Block ciphers provide a somewhat similar example where a capability, such as AES-GCM, is controlled by the conjunction of two macros (eg `KEY_TYPE_AES` and `ALG_GCM`). Might be useful as an example.

Note: one we declared all curves as accelerated, I suspect this will uncover a lot of places where we incorrectly use `MBEDTLS_ECP_DP` macros instead of `PSA_WANT` macros.

Depends on: #8014 to make dependency management easier.

**Comment by gilles-peskine-arm** [comment]
We should also add at least one component to `all.sh` to test that this is done correctly. We probably don't want to do the full `depends.py` on accelerated/non-accelerated, but at least test one case where there's one accelerated curve and one built-in curve, one case where ECDH is accelerated but not ECDSA, and one case where it's the other way round.

**Comment by mpg** [comment]
Good points regarding testing. 

> test one case where there's one accelerated curve and one built-in curve,

and where the key types and algorithms are accelerated (otherwise `ECP_C` is going to be included anyway, and we won't know if it's because of the non-accelerated curve or non-accelerated alg).

So, basically, we take the existing `no_ecp_at_all` component (where we added accel declarations for all curves as part of this task), remove the accel declaration for one curve, build and observe that `ecp.o`, `ecdh.o`, etc are no longer empty. (Should probably still be a separate component but might share the config function with the existing component.)

> one case where ECDH is accelerated but not ECDSA, and one case where it's the other way round.

We already have those: `accel_ecdh` accelerates only ECDH, `accel_ecdsa` only ECDSA and `accel_pake` only EC J-PAKE.

However, to really test the config part, in the ECDH component, we should disable `ECDSA_C`, `ECJPAKE_C` and `ECP_C`, and assert that tey get re-enabled by the config (grep that the object files are not empty), and same for the other components.

**Comment by mpg** [comment]
Note: while I'm away, I think the PR implementing this should get (at least) a design review from one of @gilles-peskine-arm or @ronald-cron-arm.
