### ISSUE TITLE
if length is 0 in mbedtls_aes_crypt_cbc, return Success. It should return MBEDTLS_ERR_AES_INVALID_INPUT_LENGTH

### ISSUE THREAD

**Issue by liuweifeng168** [Mbed-TLS/mbedtls#8028]
### Summary
if length is 0 in mbedtls_aes_crypt_cbc, return Success. It should return MBEDTLS_ERR_AES_INVALID_INPUT_LENGTH.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior
When invoking mbedtls_aes_crypt_cbc() function, length is 0, will return success. This doesn't make sense. If return success, output should be used. It is a vunerability.

**Comment by liuweifeng168** [comment]
> 
If a length of 0 is valid and return success, what should be output? Maybe hacker can use this, and cheat user to use "output" value.

**Comment by gilles-peskine-arm** [comment]
The low-level function `mbedtls_aes_crypt_cbc` just performs CBC encryption/decryption, it doesn't handle padding modes (you have to use the high-level modules for that: `mbedtls_cipher_xxx` or `psa_cipher_xxx`). So an empty input is valid. It just says to encrypt/decrypt 0 blocks, and the output is empty.

`mbedtls_aes_crypt_cbc` with an input of 0 bytes successfully produces an output of 0 bytes. This is the correct behavior.
