### ISSUE TITLE
PSA FFDH: feature macros for parameters

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8030]
FFDH, much like ECC, and unlike RSA, requires domain parameters before it even makes sense to define a key.

In PSA, domain parameters are defined by a pair (family, size), and for FFDH a single family of domain parameters is supported: that defined by RFC 7919, with a few sizes from 2048 to 8192.

Applications may want to enable FFDH with only some domain parameters. For this, PSA is supposed to provide a feature macro for each domain parameter: `PSA_WANT_DH_RFC7919_2048` to `PSA_WANT_DH_RFC7919_8192`. Unfortunately we forgot to add those feature macros when adding support for FFDH in PSA; this task is to fix that.

This needs to be fixed before FFDH is included in a public release, because it's part of the user-facing API.

- [x] Add feature macros in `psa/crypto_config.h`
- [x] Adjust `mbedtls/config_psa.h` (or however it's called at that point, see #7615) - see also #8016
- [x] Guard parameters/code with those macros as appropriate in `library/psa_crypto_ffdh.[ch]`
- [x] Guard cases / table entries with those macros as appropriate in `library/ssl*.c` and `programs/ssl/ssl_test_lib.c`.
- [x] Adjust the definition of `PSA_VENDOR_FFDH_MAX_KEY_BITS` in `include/psa/crypto_sizes.h`.
- [x] Add proper dependency declarations in tests: `test_suite_psa_crypto.data`, `test_suite_psa_crypto_metadata.data`, `generate_tls13_compat_tests.py`.
- [x] Check that https://github.com/Mbed-TLS/mbedtls/issues/7915 is resolved for FFDH (this should be the case after the previous steps).
- [x] [edited to add] Add an `all.sh` component that builds with only `PSA_WANT_DH_RFC7919_2048` and runs `make test`. 

Note: in general the end result should be very similar to what's done with ECC curves, which can be used as an example in most cases (except where they're currently incorrect - see #8016).

~Note: I'm not sure about testing. The obvious answer would be adding a new "domain" to `depends.py` (plus corresponding `all.sh` component) but currently it only works for legacy macros, as it's not using `MBEDTLS_PSA_CRYPTO_CONFIG`. However it would be good to adapt it, as the future is based on `PSA_CRYPO_CONFIG`. If that turns out to be hard, what's the minimum amount of testing we want here?~ (See comments below and "edited to add" above.)

**Comment by gilles-peskine-arm** [comment]
> The obvious answer would be adding a new "domain" to depends.py (plus corresponding all.sh component) but currently it only works for legacy macros, as it's not using MBEDTLS_PSA_CRYPTO_CONFIG. However it would be good to adapt it, as the future is based on PSA_CRYPO_CONFIG. If that turns out to be hard, what's the minimum amount of testing we want here?

Modernizing `depends.py` — either replacing it or supplementing it with a PSA-based enumeration — is something we need to do for 4.0. But I think it's not something we can rush. And I don't think it's something we need to rush.

FFDH parameters are very similar: they aren't like ECC where each curve can have specialized arithmetic. The only pieces of code you can realistically eliminate when a group is disabled are the constants and the switch cases. I think it's enough to do an ad hoc build with just one group (2048 is the most widely used, I think) and run the unit tests.

**Comment by mpg** [comment]
Ideally when adding those feature macros we should also add an properly handle the corresponding `_ACCEL_` macro. This would be pretty similar to what's done for curves, except FFDH is a bit simpler since there's only one algorithm.

More precisely, here's how the documentation in `docs/driver-only-builds.md` should look once this is all done properly:
```
Finite-field Diffie-Hellman (FFDH)
----------------------------------

It is possible to have all supported FFDH operations provided by a driver:

- the FFDH algorihm;
- key import, export, and random generation.

(Note: deterministic key derivation is not supported at all for FFDH as the
moment, both with drivers and the built-in implementation.)

More precisely, if you have driver support for:

- the FFDH algorithm (`MBEDTLS_PSA_ACCEL_ALG_FFDH` is enabled),
- and all desired DH key types (for each `PSA_WANT_KEY_TYPE_DH_xxx` that is
  enabled, the corresponding `MBEDTLS_PSA_ACCEL_KEY_TYPE_DH_xxx` is enabled),
- and all desired domain paramaters (for each `PSA_WANT_DH_xxx` that is
  enabled, the corresponding `MBEDTLS_PSA_ACCEL_DH_xxx` is enabled),
- and no other module needs `MBEDTLS_BIGNUM_C` (that is, RSA and ECC are both
  either disabled or fully accelerated),

then you can disable `MBEDTLS_DHM_C` and `MBEDTLS_BIGNUM_C` and still get full
FFDH functionality (except of course direct calls to the disabled modules).

Note: the built-in implementation of FFDH and DH key types in PSA does not
require `MBEDTLS_DHM_C` (only `MBEDTLS_BIGNUM_C`) so if you don't need the
legacy DHM API, you can always disable `MBEDTLS_DHM_C` and still get DH/FFDH
support in PSA, even without drivers.
```

**Comment by valeriosetti** [comment]
> > I think it's enough to do an ad hoc build with just one group (2048 is the most widely used, I think) and run the unit tests.
> 
> Great, that's what I was tempted to suggest as well.

Do you think it is worth testing both 2048 and 8192 instead of 2048? Just to be sure we didn't forget anything that fits unfortunately only for the 2048 case...

**Comment by gilles-peskine-arm** [comment]
It might make sense to test certain combinations of sizes for multiple algorithms, to validate buffer size calculations. For example, some buffers should be sized for the largest of {ECC, RSA, DH} (which in practice is only ever going to be ECC if RSA and DH are fully disabled). But I think this kind of testing is way out of scope here.
