### ISSUE TITLE
Why the cofactor A from  secp256r1  of ECDSA is NULL

### ISSUE THREAD

**Issue by fuxingguo16** [Mbed-TLS/mbedtls#8045]
### Justification

Mbed TLS needs this because

**Comment by tom-cosgrove-arm** [comment]
Can you give a bit more information, please? The cofactor for P-256 is 1 - where are you seeing `NULL`?

**Comment by gilles-peskine-arm** [comment]
`A.p == NULL` means that the value of A is equal P - 3. The implementation of curve arithmetic optimizes this case.

This will be clarified in https://github.com/Mbed-TLS/mbedtls/pull/6999.

**Comment by fuxingguo16** [comment]
> `A.p == NULL` means that the value of A is equal to P - 3. The implementation of curve arithmetic optimizes this case.
> 
> This will be clarified in #6999.

OK，I  got it,Thanks ~~

**Comment by fuxingguo16** [comment]
In standard Mbed TLS, if the elliptic curve parameters (including the A coefficient) are changed when using a known key pair for signing and verifying, will it have an impact on the results of signing and verifying?

> `A.p == NULL` means that the value of A is equal to P - 3. The implementation of curve arithmetic optimizes this case.
> 
> This will be clarified in #6999.

In standard Mbed TLS, if the elliptic curve parameters (including the A coefficient) are changed when using a known key pair for signing and verifying, will it have an impact on the results of signing and verifying?
