### ISSUE TITLE
Make PEM use cipher.c when available

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8051]
Currently our PEM module makes direct calls to `mbedtls_aes` and `mbedtls_des` function. Instead it should use the `mbedtls_cipher` API, for a number of reasons:
- single implementation for both ciphers should save code size when they're both enabled;
- when cipher gains the ability to dispatch to PSA, PEM will automatically benefit from that.

For this issue, the new implementation based on cipher should guarded by `#if defined(MBEDTLS_CIPHER_C)`, and the current implementation kept in the `#else` branch. (Testing notes: the default configuration has `CIPHER_C`, and we have a dedicated component without it, so we're fine already.)

(Note: later, when we have defined `MBEDTLS_CIPHER_LIGHT`, we'll auto-enable `CIPHER_LIGHT` when `PEM_C` is enabled, and remove the implementation based on `mbedtls_aes` and `mbedtls_des`. But no yet.)

Note: the Cipher implementation should explicitly set padding to `MBEDTLS_PADDING_NONE` (which is the only option for the low-level `mbedtls_aes` API, but the Cipher layer supports other options, so we need to select this one explicitly).

**Comment by gilles-peskine-arm** [comment]
PEM is not a thing that very constrained devices need. So a code size gain is not particularly relevant. Why not start requiring cipher unconditionally if PEM support is enabled and either AES or DES is enabled?

**Comment by mpg** [comment]
I agree, but on the other hand, it looks like the code of making PEM auto-enable only Cipher light rather than the full Cipher should be essentially zero, so why not do it?

**Comment by valeriosetti** [comment]
I have a question on this point:

> For this issue, the new implementation based on cipher should guarded by #if defined(MBEDTLS_CIPHER_C), and the current implementation kept in the #else branch. (Testing notes: the default configuration has CIPHER_C, and we have a dedicated component without it, so we're fine already.)

Keeping the old implementation available (i.e. the ones depending on `MBEDTLS_AES_C` and `MBEDTLS_DES_C`) when `MBEDTLS_CIPHER_C` is not defined IMO would make sense only on memory constrained devices. However, according to [this previous comment](https://github.com/Mbed-TLS/mbedtls/issues/8051#issuecomment-1673044442), it seems that PEM is not really used on those devices.
So my question is: why should we keep the old implementation around instead of just replacing it with `MMBEDTLS_CIPHER_C`?

**Comment by gilles-peskine-arm** [comment]
@valeriosetti I agree with you: I think we should make PEM require `MBEDTLS_CIPHER_C` (and auto-enable it in `build_info.h`), and reduce this to `MBEDTLS_CIPHER_LIGHT` when it's available.

**Comment by mpg** [comment]
Note: the plan was always to remove the non-cipher(-light) implementation at one point, see https://github.com/Mbed-TLS/mbedtls/issues/8059 - but I'm also happy to remove it now, for the reasons you two mentioned.

**Comment by gilles-peskine-arm** [comment]
Based on the [current plans for cipher light](https://github.com/Mbed-TLS/mbedtls/pull/8057), this is out of scope.

**Comment by mpg** [comment]
This is not only out of scope, but even if we enlarged the scope back, it's not 100% clear we'd keep this strategy for PEM, or go for something [more similar to CTR-DBRG](https://github.com/Mbed-TLS/mbedtls/issues/8337#issuecomment-1757414096) (I'm not saying we would, I'm really saying this is unclear and would need to be discussed if we ever get there), so let's put this on hold for the moment.

**Comment by mpg** [comment]
Closing as we're not going to address PEM with driver-only ciphers before 4.0, and after 4.0 the strategy will be different (and much simpler).
