### ISSUE TITLE
[G2] Create Cipher light

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8058]
See tentative definition in #8057 - this is similar to the existing MD light (introduced in #7120) and ECP light. (Don't worry about the definition being tentative: it will be refined if needed when we add more users in future tasks.)

This means that the outer guard of `cipher.c` will be changed from `CIPHER_C` to `CIPHER_LIGHT`, and then the parts of the file that are not part of Cipher light will be guarded by `CIPHER_C`. The macro `MBEDTLS_CIPHER_LIGHT` is private and does not appear in `mbedtls_config.h`.

Dependencies in `test_suite_cipher*` will need adjusting.

Rename the existing `all.sh` component `test_full_no_cipher` to `test_full_no_cipher_at_all` and create a new component `test_full_cipher_light_only` that will be initially very similar. For now, enable Cipher light by adding `-DMBEDTLS_CIPHER_LIGHT`.

Add a test `not grep mbedtls_cipher library/cipher.o` to the `no_cipher_at_all` component and a test `not grep mbedtls_cipher_auth library/cipher.o` to the `cipher_light_only` component.

**Comment by mpg** [comment]
On hold pending strategy discussion.

**Comment by mpg** [comment]
Err, wrong issue. This only has a normal dependency on #8057.

**Comment by valeriosetti** [comment]
I was reading the description of this issue and comparing it to the general strategy defined in #8337 and I have a question about this part:

> Rename the existing all.sh component test_full_no_cipher to test_full_no_cipher_at_all and create a new component test_full_cipher_light_only that will be initially very similar. For now, enable Cipher light by adding -DMBEDTLS_CIPHER_LIGHT.

If I understood correctly, in this new `test_full_cipher_light_only` component we might be able to enable also CCM/GCM (that were previously disabled in `test_full_no_cipher_at_all`) right?

**Comment by gilles-peskine-arm** [comment]
Yes, that will happen in https://github.com/Mbed-TLS/mbedtls/issues/8060.
