### ISSUE TITLE
Header file from tests subdirectory in library code

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8071]
### Summary
https://github.com/Mbed-TLS/mbedtls/blob/963513dba56991e2c741290841e2f33b9398ea52/library/constant_time.c#L33

Is this intentional?

Library builds successfully with this line commented out.

### System information

Mbed TLS version (963513dba56991e2c741290841e2f33b9398ea52): 
Windows 11
Visual Studio 2022

**Comment by davidhorstmann-arm** [comment]
It does seem this is unnecessary, thanks for spotting it!

We added this line to enable use of testing macros, which we have removed since.
