### ISSUE TITLE
Default CMake build fails with error "No module named ‘jsonschema'"

### ISSUE THREAD

**Issue by snej** [Mbed-TLS/mbedtls#8109]
### Summary

Just cloned the repo and am trying to build; as the README says, "Mbed TLS should build out of the box”. Nope; the usual CMake build fails very quickly for lack of what appear to be a Python module.

From some other related issues I gather that the Python stuff is just for testing. If that’s true, maybe the default build should not be building the tests? I don’t need to run tests, I just want to use the library.

### System information

Mbed TLS version (number or commit id): Commit [41d689f](https://github.com/Mbed-TLS/mbedtls/commit/41d689f389a51e078e4de0fba20391d9de5d83e6), default branch from Github
Operating system and version: macOS 13.4.1
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Apple Clang from Xcode 15; CMake 3.27.0
Additional environment information: 

### Expected behavior

I can run `mkdir build && cd build && cmake --build .` to build out-of-the-box.

### Actual behavior

```
$ mkdir build && cd build && cmake --build .
[  0%] Generating psa_crypto_driver_wrappers.c
[  0%] Generating suites/test_suite_ecp.generated.data
[  0%] Generating psa_constant_names_generated.c
[  0%] Generating suites/test_suite_psa_crypto_generate_key.generated.data, suites/test_suite_psa_crypto_low_hash.generated.data, suites/test_suite_psa_crypto_not_supported.generated.data, suites/test_suite_psa_crypto_op_fail.generated.data, suites/test_suite_psa_crypto_storage_format.current.data, suites/test_suite_psa_crypto_storage_format.v0.data
[  0%] Generating suites/test_suite_bignum.generated.data, suites/test_suite_bignum_core.generated.data, suites/test_suite_bignum_mod.generated.data, suites/test_suite_bignum_mod_raw.generated.data
[  0%] Generating query_config.c
[  0%] Built target mbedtls_test_helpers
[  0%] Built target generate_query_config_c
[  3%] Built target mbedtls_test
Traceback (most recent call last):
  File "/Users/snej/Projects/coro/vendor/mbedtls/library/../scripts/generate_driver_wrappers.py", line 29, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

### Steps to reproduce

1. `git clone --recursive https://github.com/Mbed-TLS/mbedtls.git mbedtls`
2. `cd mbedtls`
3. `mkdir build && cd build && cmake --build .`

**Comment by snej** [comment]
Tried using CMake option `-DENABLE_TESTING=OFF` but I still hit the same error, albeit in a different way:

```
...
[  7%] Generating version_features.c
[  8%] Generating error.c
[  8%] Generating psa_crypto_driver_wrappers.c
Traceback (most recent call last):
  File "/Users/snej/Projects/coro/vendor/mbedtls/library/../scripts/generate_driver_wrappers.py", line 29, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by tom-cosgrove-arm** [comment]
Did you follow the instructions in `README.md`?

```
The following tools are required:

* ...
* Python 3.8 and some Python packages, for some library source files, sample programs and test data. To install the necessary packages, run:
    ```
    python3 -m pip install --user -r scripts/basic.requirements.txt
    ```
    Depending on your Python installation, you may need to invoke `python` instead of `python3`. To install the packages system-wide, omit the `--user` option.
```

`jsonschema` is used to generate the PSA driver wrappers, part of the generated library source files

**Comment by gilles-peskine-arm** [comment]
To build the library _from a release_, you only need a C toolchain and make. To build the library _from git_, you also need Python, jsonschema and jinja2.

**Comment by gilles-peskine-arm** [comment]
By the way, we can [make jsonschema optional](https://github.com/Mbed-TLS/mbedtls/issues/6596) with not much effort, but the dependency on jinja2 is another matter: we'd have to rewrite the driver wrapper code. Removing the dependency on python is not realistic.
