### ISSUE TITLE
v3.4.1 build errors in Clang: "empty paragraph passed to '\retval’ command"

### ISSUE THREAD

**Issue by snej** [Mbed-TLS/mbedtls#8110]
### Summary

After failing to build the latest commit (#8109), I checked out the v3.4.1 tag and tried to build that. This time the build fails with a bunch of errors about invalid Doxygen tags; see below.

### System information

Mbed TLS version (number or commit id): v3.4.1
Operating system and version: macOS 13.4.1
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Apple Clang (from Xcode 15)
Additional environment information: 

### Expected behavior

Successful build

### Actual behavior

About a dozen errors of the form:
```
In file included from /Users/snej/Projects/coro/vendor/mbedtls/library/psa_crypto_driver_wrappers.c:31:
/Users/snej/Projects/coro/vendor/mbedtls/library/psa_crypto_pake.h:46:41: error: empty paragraph passed to '\retval' command [-Werror,-Wdocumentation]
 * \retval #PSA_ERROR_INSUFFICIENT_MEMORY
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

### Steps to reproduce

`mkdir build && cd build && cmake .. && make`

### Additional information

Looks like either the doc-comment syntax should be fixed or the `-Wdocumentation` warning should be disabled.

**Comment by tom-cosgrove-arm** [comment]
Fixed by #7805, which will be in the next release (3.5) of Mbed TLS
