### ISSUE TITLE
TLS1.3 supported in programs/ssl_server2

### ISSUE THREAD

**Issue by zliucd** [Mbed-TLS/mbedtls#8112]
### Suggested enhancement

```program/ssl_server2``` can only specify TLS1.2 in command line.  Supporting TLS1.3 would be very useful. The mbedtls version used is 3.4.0.

```
ssl_server2 -h

 usage: ssl_server2 param=<>...
 force_version=%s    default: "" (none)
                      options: tls12, dtls12
```

**Comment by gilles-peskine-arm** [comment]
You can specify `force_version=tls13` if you build the library with TLS 1.3 enabled (`config.py set MBEDTLS_SSL_PROTO_TLS1_3`). This applies to both the client and the server. Also, by default, those programs accept all supported versions.
