### ISSUE TITLE
HW AES acceleration improvement

### ISSUE THREAD

**Issue by RonEld** [Mbed-TLS/mbedtls#818]
defining `MBEDTLS_AES_ALT` enforces the whole AES API to be modified, but:
1. Some HW accelerators don't support all the AES modes supported by mbed TLS
~2. Modes not supported by HW may be supported by software~
3. Some HW accelerators can support only the AES block operation, which is supported by `MBEDTLS_AES_SETKEY_ENC_ALT` , `MBEDTLS_AES_SETKEY_DEC_ALT` , `MBEDTLS_AES_ENCRYPT_ALT` , `MBEDTLS_AES_DECRYPT_ALT` , but the `mbedtls_aes_context` needs to be modified to support the HW AES block operation, which currently can be modified only in case of `MBEDTLS_AES_ALT`

I suggest we have `mbedtls_aes_context` to be modified or have it hold an opaque buffer, for every AES_XXX_ALT operation,  not only for `MBEDTLS_AES_ALT`, and also have an alternative configuration for every AES mode, in case some modes are not supported by HW but need to be fall-backed to software

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSSL-1285

**Comment by RonEld** [comment]
update: It was decided and agreed that an alternative implementation can return `MBEDTLS_ERR_AES_FEATURE_UNAVAILABLE` for unsupported features in the module. This is recommended, as it decreases code size, and doesn't cause maintenance issues on the alternative implementation. Supporting this error is handled in #1716 
Item 3 is still an issue, but lower priority, as it is an alternative function implementation, and probably won't be an issue in real practice.

**Comment by tom-cosgrove-arm** [comment]
Closing this as future accelerator work should happen under the PSA Crypto driver framework
