### ISSUE TITLE
mbedtls_x509_crt_verify does not verify all certificates in the chain

### ISSUE THREAD

**Issue by songhaowang** [Mbed-TLS/mbedtls#8183]
### Summary

The "trust_ca" is always used first to verify the target certificate for each round verification, it causes "mbedtls_x509_crt_verify " ignore the invalid certificate in the chain.

"x509_crt_find_parent" also skips the non-parent certificate.

The above two logic lead to the "mbedtls_x509_crt_verify" returns success for the case that the certificate chain contains the valid certificate chain and mix with invalid certificate.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

"mbedtls_x509_crt_verify" returns failure.

### Actual behavior

"mbedtls_x509_crt_verify" returns success.

### Steps to reproduce

There is certification chain (A -> B -> C), and add C, D, B, E into the chain as the input parameter for "mbedtls_x509_crt_verify"
,  add A as parameter "trust_ca" for "mbedtls_x509_crt_verify".

**Comment by gilles-peskine-arm** [comment]
Can you please post a list of certificates and a small program to reproduce the problem? The problem is not clear to me.

> "mbedtls_x509_crt_verify" returns success for the case that the certificate chain contains the valid certificate chain and mix with invalid certificate.

This seems correct to me. If you add irrelevant certificates to a valid chain, the chain remains valid. It's a common scenario, for example, when a certificate S has been signed by two CAs C1 and C2, and the chain contains both a certificate of S by C1 and a certificate of S by C2, and the verified only trusts C1: the certificate by C2 is ignored.

**Comment by songhaowang** [comment]
Hi Gilles,

Thanks to your reply.

> for example, when a certificate S has been signed by two CAs C1 and C2, and the chain contains both a certificate of S by C1 and a certificate of S by C2, and the verified only trusts C1: the certificate by C2 is ignored.

Yes, in this case, it is reasonable because its purpose is simply to check whether S is trustworthy. But if people get some certificates, and don't know their relationship, want to verify that these certificates are a complete and ordered chain of certificates, and think that the intermingled unrelated certificates are breaking the chain, it seems that the current API does not achieve this purpose.

For example, there is the valid certificate chain (A --issue-->B--issue-->C), verify them with the following code
```c
ret = mbedtls_x509_crt_parse_der(&root_ca_ctx, bufferA, bufferA_length);
CHECK_RETVAL(ret);

ret = mbedtls_x509_crt_parse_der(&certificate_ctx, bufferC, bufferC_length);
CHECK_RETVAL(ret);

ret = mbedtls_x509_crt_parse_der(&certificate_ctx, bufferD, bufferD_length);
CHECK_RETVAL(ret);

ret = mbedtls_x509_crt_parse_der(&certificate_ctx, bufferB, bufferB_length);
CHECK_RETVAL(ret);

ret = mbedtls_x509_crt_parse_der(&certificate_ctx, bufferE, bufferE_length);
CHECK_RETVAL(ret);

ret = mbedtls_x509_crt_verify(&certificate_ctx, &root_ca_ctx, NULL, CN, &flags, NULL, NULL);
```

If "mbedtls_x509_crt_verify " cannot achieve this purpose, whether there is other function can do it?

Thanks a lot.

**Comment by gilles-peskine-arm** [comment]
>  its purpose is simply to check whether S is trustworthy.

This is indeed the goal of `mbedtls_x509_crt_verify`. It's checking whether the give certificate is trusted, with the help of the rest of the chain.

>  verify that these certificates are a complete and ordered chain of certificates, and think that the intermingled unrelated certificates are breaking the chain

If I understand correctly, you have a list of certificates C1, C2, ..., Cn and you want to check that C2 signs C1, C3 signs C2, etc. You can do that with
```
verify(C1, C2) == 0 &&
verify(C2, C3) == 0 && ...
verify(Cn-1, Cn) == 0
```

**Comment by songhaowang** [comment]
Hi Gilles,

Thanks, now it is clear, this implementation is by design.

> verify(C1, C2) == 0 &&
verify(C2, C3) == 0 && ...
verify(Cn-1, Cn) == 0

This is the method what I can think as well, thanks your suggestion, let's close this issue.
