### ISSUE TITLE
Discussion: Improving init/free API for structures

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8211]
Currently we have a convention that most structures (in TLS, X.509 and legacy crypto) come with a corresponding `_init()` and a `_free()` function (and sometimes a `_setup()` function). The convention is that:
- The main purpose of the `_init()` function is to guarantee that it's safe to call `_free()` function and other functions that operate on the structure (for example, it sets all pointers inside the struct to `NULL`). The `_init()` function usually does just that, and does not allocate resources - if resources need to be allocated before anything useful can be done with the structure, that's the job of the `_setup()` function.
- The `_free()` function frees the resources references by the structure, but not the memory used for the structure itself - that way, it can be used on structures that are allocated on the stack (or even globals which I don't think we have).

There a a number of long-standing usability issues with this. Depending on the strategy we use, API breaks may be required to fully deals with them, making this discussion relevant for 4.0.

Note: the number of structures affected should also go down significantly in 4.0, as the PSA Crypto API already got this right, and (most of) the legacy crypto API is going to be removed/hidden in 4.0, leaving only X.509 and TLS to fix.

### Risk missing init

Since a structure can only be initialized by calling a function, people who are still using the code ordering from the C89 era (even if they are actually using a C99-capable compiler): first declare all the variables, then start calling functions - those people are at risk of accidentally introducing code that might jump to cleanup and call the `_free()` function before the corresponding `_init()` had been called, resulting in all the kinds of nasty consequences associated with calling `free()` on a uninitialized variable.

Getting this wrong is not just a theoretical possibility, it's something that happens regularly in our own test code.

Possible ways to avoid it:
- since we require C99 anyway, tell users (including ourselves) to always call `_init()` right after declaring the structure and before any other variable declaration. Pro: no need to change our API. Con: may conflict with user's coding style, some people might even be using `-Wdeclaration-after-statement`, puts the problem on the user's hand.
- provide initializer _macros_ so that people can write `foo_t foo = FOO_INIT;`. Pro: results in more compact code, compatible with all code styles. Con: we need to provide these macros and decide how we implement them (designated initializers or not?).

Question for 4.0: if we add initializer macros, do we also want to remove the existing `_init()` functions, to keep the API smaller, and more attention to the macros? (Note: we could also add the macros in 4.x and remove the `_init()` functions in 5.0.)

### Confusion about what the free function does

Users regularly get confused about this: if `foo` points to a dynamically-allocated structure, then after calling `foo_free(foo);`, should you  call `free(foo);` too or not?

Possible way to avoid it: rename those functions to something other than `_free()`.

Question for 4.0: do we want to do that mass-renaming? If so, should leave the existing name as a synonym (static inline wrapper or macro) for a while and should it be opt-in (like, you need to include `compat-3.x.h` or similar in order to get the old name)?

**Comment by gilles-peskine-arm** [comment]
Strongly related:

* About the naming of “free” functions: https://github.com/Mbed-TLS/mbedtls/issues/7838
* About the semantics of “free” function: https://github.com/Mbed-TLS/mbedtls/issues/7836

**Comment by mpg** [comment]
Yes, I agree that those 3 issues together cover everything here, so I'm closing this issue.
