### ISSUE TITLE
Missing Requires comment in mbedtls_config.h

### ISSUE THREAD

**Issue by jnmeurisse** [Mbed-TLS/mbedtls#8215]
### Suggested enhancement
The option MBEDTLS_SSL_RENEGOTIATION should include the following requirement
       Requires: MBEDTLS_SSL_PROTO_TLS1_2

### Justification
The documentation should be consistent with tests done in  check_config.h. 
See https://github.com/Mbed-TLS/mbedtls/blob/170be457bde4e8611ed74398364d789e60fb1b3b/include/mbedtls/check_config.h#L934

**Comment by daverodgman** [comment]
Fixed by #8220
