### ISSUE TITLE
Test framework - 1

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#8224]
Make configuration agnostic the code in:

tests/suites/helpers.function, main_test.function, host_test.function
tests/include/test/arguments.h, helpers.h, macros.h, random.h
tests/src/helpers.c, random.c

**Comment by gilles-peskine-arm** [comment]
I don't understand the goal of this issue. There's at least going to be dependencies on `MBEDTLS_PLATFORM_xxx` in those files. Why those files in particular? Why would it help to make them configuration-agnostic?

**Comment by ronald-cron-arm** [comment]
Closing this as it is outdated. The dependency of framework files to Mbed TLS configuration has to be looked at though as they are intended to be used in TF-PSA-Crypto as well where configuration options are different.
