### ISSUE TITLE
error C4703

### ISSUE THREAD

**Issue by kouzhudong** [Mbed-TLS/mbedtls#8227]
### Summary

pkwrite.c(458): error C4703: 使用了可能未初始化的本地指针变量“oid”

### System information

Mbed TLS version (number or commit id): 
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by daverodgman** [comment]
Please could you provide more information? I am not sure what the issue is here.

**Comment by kouzhudong** [comment]
pkwrite.c(458): error C4703: 使用了可能未初始化的本地指针变量“oid”

**Comment by gilles-peskine-arm** [comment]
Faux positif, comme beaucoup de messages de MSVC au niveau 4.
