### ISSUE TITLE
Question: Calling mbedtls_ctr_drbg_seed using WINAPI CreateThread causes the program to exit.

### ISSUE THREAD

**Issue by Obsidian200** [Mbed-TLS/mbedtls#8238]
### Summary
Excuse me, I have a problem.
I am executing the rsa_genkey example in a thread. The thread was created using CreateThread. The program executes to `mbedtls_ctr_drbg_seed `and then exits automatically without reporting any errors!
I also tried using std::thread and _beginthread and also had problems
If executed in the main thread, everything works fine. I'm using the VS2022 compiler.
Please help me, thanks!

```
DWORD WINAPI ThreadFunc(LPVOID p)
{
	int ret = 1;
	int exit_code = MBEDTLS_EXIT_FAILURE;

	mbedtls_mpi N, P, Q, D, E, DP, DQ, QP;
	FILE* fpub = NULL;
	FILE* fpriv = NULL;
	const char* pers = "rsa_genkey";

	mbedtls_rsa_context rsa;
	mbedtls_entropy_context entropy;
	mbedtls_ctr_drbg_context ctr_drbg;

	mbedtls_entropy_init(&entropy);
	mbedtls_ctr_drbg_init(&ctr_drbg);
	mbedtls_rsa_init(&rsa);

	mbedtls_mpi_init(&N); mbedtls_mpi_init(&P); mbedtls_mpi_init(&Q);
	mbedtls_mpi_init(&D); mbedtls_mpi_init(&E); mbedtls_mpi_init(&DP);
	mbedtls_mpi_init(&DQ); mbedtls_mpi_init(&QP);

	mbedtls_printf("\n  . Seeding the random number generator...");
	fflush(stdout);


	if ((ret = mbedtls_ctr_drbg_seed(&ctr_drbg, mbedtls_entropy_func, &entropy,
		(const unsigned char*)pers,
		strlen(pers))) != 0) {
		mbedtls_printf(" failed\n  ! mbedtls_ctr_drbg_seed returned %d\n", ret);
		goto exit;
	}

	mbedtls_printf(" ok\n  . Generating the RSA key [ %d-bit ]...", KEY_SIZE);
	fflush(stdout);

	if ((ret = mbedtls_rsa_gen_key(&rsa, mbedtls_ctr_drbg_random, &ctr_drbg, KEY_SIZE,
		EXPONENT)) != 0) {
		mbedtls_printf(" failed\n  ! mbedtls_rsa_gen_key returned %d\n\n", ret);
		goto exit;
	}

	mbedtls_printf(" ok\n  . Exporting the public  key in rsa_pub.txt....");
	fflush(stdout);

	if ((ret = mbedtls_rsa_export(&rsa, &N, &P, &Q, &D, &E)) != 0 ||
		(ret = mbedtls_rsa_export_crt(&rsa, &DP, &DQ, &QP)) != 0) {
		mbedtls_printf(" failed\n  ! could not export RSA parameters\n\n");
		goto exit;
	}

	if ((fpub = fopen("rsa_pub.txt", "wb+")) == NULL) {
		mbedtls_printf(" failed\n  ! could not open rsa_pub.txt for writing\n\n");
		goto exit;
	}

	if ((ret = mbedtls_mpi_write_file("N = ", &N, 16, fpub)) != 0 ||
		(ret = mbedtls_mpi_write_file("E = ", &E, 16, fpub)) != 0) {
		mbedtls_printf(" failed\n  ! mbedtls_mpi_write_file returned %d\n\n", ret);
		goto exit;
	}

	mbedtls_printf(" ok\n  . Exporting the private key in rsa_priv.txt...");
	fflush(stdout);

	if ((fpriv = fopen("rsa_priv.txt", "wb+")) == NULL) {
		mbedtls_printf(" failed\n  ! could not open rsa_priv.txt for writing\n");
		goto exit;
	}

	if ((ret = mbedtls_mpi_write_file("N = ", &N, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("E = ", &E, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("D = ", &D, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("P = ", &P, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("Q = ", &Q, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("DP = ", &DP, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("DQ = ", &DQ, 16, fpriv)) != 0 ||
		(ret = mbedtls_mpi_write_file("QP = ", &QP, 16, fpriv)) != 0) {
		mbedtls_printf(" failed\n  ! mbedtls_mpi_write_file returned %d\n\n", ret);
		goto exit;
	}
	mbedtls_printf(" ok\n\n");

	exit_code = MBEDTLS_EXIT_SUCCESS;

exit:

	if (fpub != NULL) {
		fclose(fpub);
	}

	if (fpriv != NULL) {
		fclose(fpriv);
	}

	mbedtls_mpi_free(&N); mbedtls_mpi_free(&P); mbedtls_mpi_free(&Q);
	mbedtls_mpi_free(&D); mbedtls_mpi_free(&E); mbedtls_mpi_free(&DP);
	mbedtls_mpi_free(&DQ); mbedtls_mpi_free(&QP);
	mbedtls_rsa_free(&rsa);
	mbedtls_ctr_drbg_free(&ctr_drbg);
	mbedtls_entropy_free(&entropy);

	mbedtls_exit(exit_code);
}

int main(void)
{

	HANDLE hThread;
	DWORD threadId;
	hThread = CreateThread(NULL,0, ThreadFunc, 0, 0, &threadId);

}
```

### System information

Mbed TLS version (number or commit id): 3.4.1
Operating system and version: Win10 22H2
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): VS2022
Additional environment information:

**Comment by yanesca** [comment]
Hi @Obsidian200,

Threading is not enabled in the default config, do you have `MBEDTLS_THREADING_C` enabled in your configuration?

Mbed TLS doesn't come with WINAPI threading support out of the box, you need to implement a simple abstraction layer. Have you done that? Do you have `MBEDTLS_THREADING_ALT` enabled in your config?

**Comment by Obsidian200** [comment]
Thank you very much. @yanesca 
I have read the section on thread safety in the instructions document. But I am a new developer. There are some parts that I don't quite understand. I opened the MBEDTLS_THREADING_C macro definition in the mbedtls_config.h file. The compiler prompted me to open the MBEDTLS_THREADING_ALT or MBEDTLS_THREADING_PTHREAD macro definitions. My guess is that MBEDTLS_THREADING_PTHREAD is a Linux API and Windows doesn't support it. So I tried to open MBEDTLS_THREADING_ALT.
The compiler suggested that the "threading_alt.h" header file could not be found. I didn't continue to look for it.
I have a question. I read the documentation about thread safety. I am only executing the initialize RSA context code in one thread. But I am not executing it concurrently in multiple threads. And I am using local variables. There are no shared global variables. So I don't think he has anything to do with MBEDTLS_THREADING_ALT. Am I misunderstanding the MBEDTLS_THREADING_ALT macro definition? Is it possible to use a mutex implementation in the outer layer of a function without using MBEDTLS_THREADING_ALT?

**Comment by tom-cosgrove-arm** [comment]
It looks to me as if you are not waiting for the thread to execute after creating it in your `main()`, which will then call `exit()`.

Have you tried adding `WaitForSingleObject(hThread, INFINITE);` after `CreateThread()`?

**Comment by Obsidian200** [comment]
> It looks to me as if you are not waiting for the thread to execute after creating it in your `main()` - most C runtimes will call `exit()` when `main()` returns.
> 
> Have you tried adding `WaitForSingleObject(hThread, INFINITE);` after `CreateThread()`?

Thank you very much. @tom-cosgrove-arm.It's working now.
I forgot the execution process of the main thread. I've been tracing the step-by-step debugging process of the child thread. It always exits when it reaches mbedtls_ctr_drbg_seed. This led me to mistakenly believe that there might be an issue with mbedtls_ctr_drbg_seed.
