### ISSUE TITLE
Public header references a test path

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8259]
In `include/mbedtls/crypto_platform.h`, at some point after the 3.4.0 release (specifically https://github.com/Mbed-TLS/mbedtls/pull/7650/commits/2f1ae5a86ebd67faa50c3983b4567656c2234674), we introduced a reference to a path in `tests` in a public-facing file.
```
#if defined(MBEDTLS_PSA_CRYPTO_SPM)
#define PSA_CRYPTO_SECURE 1
#include "../tests/include/spe/crypto_spe.h"
#endif // MBEDTLS_PSA_CRYPTO_SPM
```

This is wrong: `MBEDTLS_PSA_CRYPTO_SPM` is a public feature (we don't even document it as experimental). Users must be able to activate it and drop their own `crypto_spe.h.

Reported by TF-M when they were preparing to integrate 3.5.

Generally speaking, non-test code (`include/**`, `library/**`, `programs/**` except for the programs specifically intended for testing such as `ssl_{client,server}2`) should not contain anything that's related to our testing environment. The one major exception is PSA driver support, where we have references to test drivers that will stay until our support for driver wrapper generation improves.

**Comment by tom-cosgrove-arm** [comment]
Should we add something to the CI to catch this in the future, along the lines of a simple `if grep -qR 'include.*tests' include library; then ...`?

**Comment by gilles-peskine-arm** [comment]
@tom-cosgrove-arm Yes, that would be a good idea. Also check for `MBEDTLS_TEST_xxx` symbols apart from a few whitelisted ones (`MBEDTLS_TEST_HOOKS`, PSA test drivers). Also check in non-test sample programs.
