### ISSUE TITLE
Clean up curves handling in libtestdriver1 config

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8274]
Currently curves are handled in a special way in `tests/include/test/drivers/config_test_driver.h`. As a consequence, they also seem to require special handling in each `all.sh` that accelerates, like [here](https://github.com/Mbed-TLS/mbedtls/blob/b51f3da3549034818ea5e7b66695a44c65454cbc/tests/scripts/all.sh#L2317) for example. Furthermore, it doesn't look like anyone clearly understands why things are this way.

This task is to either:
1. Fix handling of curves in libtestdriver1 config so that it's more uniform with other ACCEL macros, and no longer require special treatment in `all.sh` components that accelerate ECC.
2. Or if it can't seem to be done, document clearly why this special handling is needed.

**Comment by mpg** [comment]
Note: this is one part of https://github.com/Mbed-TLS/mbedtls/issues/6912

**Comment by valeriosetti** [comment]
@mpg 
The description mentions `config_test_driver.h` but I think the file we should modify here is `crypto_config_test_driver_extension.h`. Isn't it?

**Comment by mpg** [comment]
Yes indeed!
