### ISSUE TITLE
Improve STREAM and ECB_NO_PADDING handling in libtestdriver1 config

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8275]
In `all.sh`, the function `helper_libtestdriver1_adjust_config()` needs to disable `PSA_WANT_ALG_STREAM_CIPHER` and `PSA_WANT_ALG_ECB_NO_PADDING` for reasons that don't seem clear.

This task is to either:
1. Change handling of these in the PSA or libtestdriver1 config system so that the special handling in `all.sh` is no longer necessary.
2. Or if this can't seem to be done, clearly document the reasons.

**Comment by gilles-peskine-arm** [comment]
More generally: https://github.com/Mbed-TLS/mbedtls/issues/6912

**Comment by mpg** [comment]
Ah, I forgot we already had a more general issue. Thanks for the reference!

**Comment by mpg** [comment]
Closing as a duplicate of #8315, which btw was fixed by #8368.
