### ISSUE TITLE
Fix error reporting in driver testing parity

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8301]
In `tests/scripts/analyze_outcomes.py`, driver testing parity reports errors in a way that is fragile and that is hard to understand in the logs.

Definition of done: in `analyze_outcomes.py`:

* All errors are reported by calling `results.error` on a `Results` instance.
* There are no call to `sys.exit` except for fatal errors that prevent from running any kind of outcome analysis whatsoever, and for the final call based on `results.error_count`.
* There are no calls to `Results.log` using the class: all logging goes through the `Results` instance.

**Comment by mpg** [comment]
>There are no calls to Results.log using the class: all logging goes through the Results instance.

Out of curiosity, why? When reviewing the PR that introduced that, I thought it was a clever way of avoiding to have a Results instance to manage just for logging, and evidently I missed the reason why it was wrong - but I'm afraid I'm still missing it.

**Comment by gilles-peskine-arm** [comment]
As the class is written, of course, it makes no operational difference. But then you might as well call `print` directly. But if the class evolves to support some kind of selective logging, or to redirect logs to a file, then `log` will no longer by a class method, it will need an instance.
