### ISSUE TITLE
Remove trailing whitespace in prepare_release.sh

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8304]
On 3406564b012e2a1f909f9f9708e821d67133632a (nearly 3.5.0):

```
$ ./scripts/prepare_release.sh
$ grep ' $' programs/.gitignore
# 
```

We shouldn't have this trailing whitespace. `check_files.py` will complain about it.

The goal of this task is that after running `./scripts/prepare_release.sh` and committing the result, `check_files.py` is happy.

**Comment by mcagriaksoy** [comment]
I fixed that on PR: 8369
I hope it is okay?
