### ISSUE TITLE
Do generated files have to follow the current coding style?

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8310]
https://github.com/Mbed-TLS/mbedtls/blob/644fd346570eff0b35d650c2e3497a041abc76d5/scripts/generate_errors.pl#L207-L208
This creates statements in the previous style
`return( "_message ..._" );`
while the current style implies
`return "_message ..._";`

**Comment by gilles-peskine-arm** [comment]
No, [generated files are exempt](https://github.com/Mbed-TLS/mbedtls/blob/development/scripts/code_style.py#L74). We'd prefer to follow the coding style, but we do not enforce it, and we aren't prioritizing updating the existing files.

I started updating the existing files, but I paused that when I realized that there's one point that's hard to resolve: the code style enforces a maximum line length, whereas in some files it's very annoying to enforce a maximum line length. For example, in `error.c`, the coding style enforcement tool would want to either have a line break between `return` and the message, or keep them on the same line, depending on the exact length of the message.

**Comment by irwir** [comment]
Thanks for clarification.
The previous coding style was quite `peculiar` and less strict approach could be to provide more compliance, but wave troublesome requirements.

**Comment by gilles-peskine-arm** [comment]
> less strict approach could be to provide more compliance, but wave troublesome requirements

A major reason why we have a coding style is that we want to avoid noise in the form of changes where someone just restyled some code without changing its semantics (often because their editor did it automatically). This led us towards having a strict style. Furthermore, the easiest way we found to enforce the style is to canonicalize the code and reject any difference, which unfortunately forces us to be more strict than we'd like. But after about 9 months I think the new coding style has been a markedly net positive.

**Comment by irwir** [comment]
@gilles-peskine-arm, while on the subject of enforcing code style.
If uncrustify's output is exactly as in the current style requirements, why not process the generated files too?

**Comment by gilles-peskine-arm** [comment]
If we process the generated files, the end result is sensitive to whether you do (1. update generated files; 2. fix code style) or (1. fix code style; 2. update generated files). We picked a way that has less hassle: https://github.com/Mbed-TLS/mbedtls/pull/6820

To be clear, having generated files that conform to the code style [is something we want, ideally](https://github.com/Mbed-TLS/mbedtls/issues/7099). It's just lower priority than many, many other things we want.

**Comment by irwir** [comment]
You know the problem and working on it; Hopefully some day thing will get better.
Thanks again.
