### ISSUE TITLE
Clarify driver handling of ALG_STREAM and ALG_ECB

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8315]
Currently, `all.sh` has, in `helper_libtestdriver1_adjust_config()`, some special handling of `ALG_STREAM_CIPHER` and `ALG_ECB_NO_PADDING`, because apparently having them enabled causes partial support for cipher operations to be included in libtestdriver1 even when that's not wanted.

The algorithm `ALG_STREAM_CIPHER` is special is that it doesn't have any specific code: it's just what we use with stream ciphers, that don't require a "mode", but the PSA API still requires an alg, so `ALG_STREAM` fills that formal requirement, but what we get is really just the underlying stream cipher primitive.

The situation is almost the same with `ALG_ECB_NO_PADDING`, except it's for block ciphers, and it differs from "just the underlying primitive" by the fact that it can apply to more than one block.

Looking at `include/mbedtls/config_adjust_legacy_from_psa.h` we have the following:
```c
#if defined(PSA_WANT_ALG_STREAM_CIPHER)
#define MBEDTLS_PSA_BUILTIN_ALG_STREAM_CIPHER 1
#endif /* PSA_WANT_ALG_STREAM_CIPHER */
```
```c
#if defined(PSA_WANT_ALG_ECB_NO_PADDING) &&     \
    !defined(MBEDTLS_PSA_ACCEL_ALG_ECB_NO_PADDING)
#define MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING 1
#endif
// ...
/* If any of the block modes are requested that don't have an
 * associated HW assist, define PSA_HAVE_SOFT_BLOCK_MODE for checking
 * in the block cipher key types. */
#if (defined(PSA_WANT_ALG_CTR) && !defined(MBEDTLS_PSA_ACCEL_ALG_CTR)) || \
    (defined(PSA_WANT_ALG_CFB) && !defined(MBEDTLS_PSA_ACCEL_ALG_CFB)) || \
    (defined(PSA_WANT_ALG_OFB) && !defined(MBEDTLS_PSA_ACCEL_ALG_OFB)) || \
    defined(PSA_WANT_ALG_ECB_NO_PADDING) || \
    (defined(PSA_WANT_ALG_CBC_NO_PADDING) && \
    !defined(MBEDTLS_PSA_ACCEL_ALG_CBC_NO_PADDING)) || \
    (defined(PSA_WANT_ALG_CBC_PKCS7) && \
    !defined(MBEDTLS_PSA_ACCEL_ALG_CBC_PKCS7)) || \
    (defined(PSA_WANT_ALG_CMAC) && !defined(MBEDTLS_PSA_ACCEL_ALG_CMAC))
#define PSA_HAVE_SOFT_BLOCK_MODE 1
#endif
```

It looks like for some reason those are not handled the usual way regarding `ACCEL` macros.

This task to investigate why. Possible outcomes:

1. Remove special handling of those two if possible.
2. Otherwise, improve documentation about why they have to be handled in a special way.

**Comment by valeriosetti** [comment]
== Analysis for `ALG_STREAM_CIPHER` ==

It seems to me that this symbol isn't used much in the code. Most relevant places are:
- `mbedtls_cipher_info_from_psa()` in `psa_crypto_ciphers.c` which is just to return a `cipher_info_t` from PSA values
-  in `crypto_builtin_primitives.h` for enabling internal symbol `MBEDTLS_PSA_BUILTIN_CIPHER`
    - this is more relevant as it enables the cipher support on the PSA side (if no other mode is defined of course)

I would say that we can fix this by enabling the builtin version of the `ALG_STREAM_CIPHER` as we do for other algs. I expect some fixes to be applied in `all.sh` for the test components that are not automatically accelerating that component (before it was always accelerated as long as the `PSA_WANT` part was defined)
