### ISSUE TITLE
Restore support for Windows XP

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8316]
### Suggested enhancement
After 0ec1e6854849c554a49fb779a6c63f1356a11404 the minimum supported version is Windows Vista.
The rest of the library code does not require this limitation.

### Justification
Only about 30 lines need to be added to `entropy_poll.c` for continued support of Windows XP.

**Comment by tom-cosgrove-arm** [comment]
Windows XP was released over 20 years ago, its successor over 15 years ago, and went out of support by the manufacturer over 9 years ago. A justification "it's only 30 lines of code" doesn't really seem good enough - we'd have to continue to support and test

**Comment by irwir** [comment]
The manufacturer also already had dropped support for Windows Vista, 7, 8 and 8.1, had it not?
Yet all these old versions are still being used for whatever reasons.

The suggestion is to _add back_ what was removed. That code was being tested up to the above mentioned commit; and there are no indications that the same code should stop working. Also a deprecation comment (warning) might be added.

Of course, it is possible to replace one #include line and one function manually, but this should be done only once.

**Comment by gilles-peskine-arm** [comment]
My understanding is that code that uses the XP-era interface is banned from certain distribution channels (Windows Store?). So the old code would have to be guarded by conditional compilation.

We do accept code for platforms that we don't support or test, maintained at the submitter's discretion. So if you submit a patch for XP support, we'd consider it. But we would only accept it if we're confident that it doesn't break other platforms. In this case, we would need to make sure that including that code doesn't prevent applications from being included in the Windows store.

**Comment by irwir** [comment]
> In this case, we would need to make sure that including that code doesn't prevent applications from being included in the Windows store.

This phrase was somewhat unclear.
Now the name is Universal Windows Platform. But not only the name is volatile - some initially prohibited API calls became valid later.
For getting entropy there are 3 possibilities:
1. No platform-specific support
2. XP and above
3. Vista and above
Case 2 is known and expected to have issues with UWP requirements.
In cases 1 and 3 the library itself is expected to comply with UWP requirements.

Of course, cases 2 and 3 conditionally should use different code - the old and the current one.

**Comment by daverodgman** [comment]
We would be happy to take a PR as Gilles suggests, but for now I will close this issue.
