### ISSUE TITLE
Checksums missing in most recent release

### ISSUE THREAD

**Issue by KloolK** [Mbed-TLS/mbedtls#8329]
The two most recent releases are missing the checksums for the downloadable archives:

https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-3.5.0
https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.5

Maybe originally caused by #8312 ?

Would be great if someone could add those.
Thanks!

**Comment by ronald-cron-arm** [comment]
> Maybe originally caused by #8312 ?

I does not seem to be the case as we can see the "Checksum" sections in the links mentioned above. @minosgalanakis could you have a look to that?
