### ISSUE TITLE
Unable to compile with 32 bits using Mingw on mbedTLS v 3.5.0

### ISSUE THREAD

**Issue by g-tardy** [Mbed-TLS/mbedtls#8334]
### Summary

Since version 3.5.0 we are unable to compile mbedTLS version 3.5.0.

Works pretty well on previous 3.* versions (and 2.28.5). It stops with error message:

```
(...)
\mbedtls\library\aesni.h:69:
5: error: #error "Must use `-mpclmul -msse2 -maes` for MBEDTLS_AESNI_C"
 #   error "Must use `-mpclmul -msse2 -maes` for MBEDTLS_AESNI_C"
```

Seems to be linked to commit d6e312dde4c636cc25478e729227b9a9677bd579 applied on

```
(...)
#if defined(MBEDTLS_AESNI_HAVE_INTRINSICS)
#define MBEDTLS_AESNI_HAVE_CODE 2 // via intrinsics
#elif defined(MBEDTLS_HAVE_ASM) && \
    defined(__GNUC__) && defined(MBEDTLS_ARCH_IS_X64)
/* Can we do AESNI with inline assembly?
 * (Only implemented with gas syntax, only for 64-bit.)
 */
#define MBEDTLS_AESNI_HAVE_CODE 1 // via assembly
#elif defined(__GNUC__)
#   error "Must use `-mpclmul -msse2 -maes` for MBEDTLS_AESNI_C"
#else
#error "MBEDTLS_AESNI_C defined, but neither intrinsics nor assembly available"
#endif
(...)
```

Where line `defined(__GNUC__) && defined(MBEDTLS_HAVE_X86_64)` changed to :
 `defined(__GNUC__) && defined(MBEDTLS_ARCH_IS_X64)`

### System information

Mbed TLS version (number or commit id): 3.5.0
Operating system and version: Windows 7 x64 SP1, MingW32
Configuration (if not default, please attach `mbedtls_config.h`): Default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):

cmake . -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=OFF -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
cmake --build .

Additional environment information: 

Bin path for Mingw:
C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin

### Expected behavior

Compile version should pass

### Actual behavior

Compile version fails

### Steps to reproduce

Compile mbedTLS using 32 bits capabilities

**Comment by ronald-cron-arm** [comment]
Thanks for the bug report. We will look at fixing it before the next release.
