### ISSUE TITLE
Driver-only cipher/AEAD: goals for 3.6 and strategy

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8337]
This issue is used as a place to document the goals of the [driver-only cipher/AEAD (23q4) EPIC](https://github.com/orgs/Mbed-TLS/projects/1#column-19596455) and discuss the general strategy towards that goal. (Discussion can happen in comments and the present message will be edited when a consensus is reached.)

Broader context: see [`docs/architecture/psa-migration/strategy.md`](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/architecture/psa-migration/strategy.md); this is about implementing part of goal 5 "compile out our implementation when a driver is available" for ciphers & AEADs. See also what was done for MD, as documented in [`docs/architecture/psa-migration/md-cipher-dispatch.md`](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/architecture/psa-migration/md-cipher-dispatch.md).

# Goals

Note: the goals include a mixture of things that benefit code size (with or without drivers) and things specific to taking advantage of drivers.

**General considerations:** we focus on improving the situation for configurations typical of a constrained device with just enough crypto to support modern TLS - that is TLS with only AEADs.

## Primary goals

G1. (Software) In builds with no cipher mode that requires the decrypt direction of the block cipher primitive is enabled, the decrypt direction can be compiled out.
G2. (Software) It is possible to build `CIPHER_C` disabled and still get GCM, CCM, ChachaPoly and TLS. (A subset of `cipher.o` may remain, but code size would still be saved.)
G3. (Driver) When drivers for all required AEADs & block cipher key types are available, and the PSA RNG doesn't use CTR-DRBG (either it uses HMAC-DRBG or an external implementation is provided), it is possible to exclude built-ins for AEADs and block ciphers.

## Stretch goals

G4. (Driver) Same as G3 except the PSA RNG can use CTR-DRBG (which needs to work on top of the accelerated block cipher).
G5. (Driver) Same as G4 except we only have drivers for block cipher key types, but they do no support GCM or CCM (whose built-in implementations need to work on top of the accelerated block cipher).

## Non-goals

G6. (Driver) Same as G4 except we require driver to also support CBC, we allow a config closer to full, and everything works except perhaps not all modes are supported in Cipher. Compared to G4, that means adding support for PEM decryption, decryption of PKCS8-encrypted keys, PKCS5/PKCS12 en/decryption and CBC ciphersuites in TLS.
G7. (Driver) Same as G6 except we only have drivers for block cipher key types. 

Those are legitimate goals but were excluded from the scope of 3.6 based on the amount of time available. (They could be achieved by making Cipher able to dispatch to PSA for CBC too - for G6, directly call the CBC driver, and for G7, built CBC in software on top of the block cipher driver.)

# General strategy

(TODO: flesh it out)
(TODO: testing plan!)

- We define `CIPHER_LIGHT` to be the subset of `CIPHER_C` that supports GCM, CCM (~and CTR-DRBG, which migrates to use it instead of low-level AES~ under discussion).
- We make it it able to dispatch to PSA when a driver is present and drivers are initialized
  - Open questions: what API should it call? Use the key store or not?

**Comment by mpg** [comment]
> * We define `CIPHER_LIGHT` to be the subset of `CIPHER_C` that supports GCM, CCM and CTR-DRBG (which migrates to use it instead of low-level AES).
> 
> * We make it it able to dispatch to PSA when a driver is present and drivers are initialized

Rationale:
1. We have three modules (GCM, CCM and CTR-DRBG) that (in G5) will all want to "do AES" regardless of whether that's done by the built-in or a driver.
2. The logic for selecting built-in vs driver (when both are present) will likely not but fully compile-time but will include run-time elements (is the drivers subsystem initialized yet?) at least when both driver and built-in are present.
3. As a result, it makes sense to have an abstraction layer that implements the dual dispatch and can be used by all three modules.

Now, this "generic block cipher primitive interface with dual dispatch" internal API might either be something new that we design and implement from scratch, or we can re-use an existing abstraction layer.

4. Two of these modules already use the Cipher interface (more precisely they use a small subset of it that we're going to make independent an define as Cipher-light).
5. So it makes sense for the third module to use the same interface (Cipher-light) and that interface to implement dual dispatch to PSA.

Using Cipher-light is the plan I presented at the open tech forum (green arrows from CTR-DRBG and GCM/CCM to CL which is short for Cipher-light, in the diagrams below for G4 and G5).
![cipher-drv4](https://github.com/Mbed-TLS/mbedtls/assets/60640/c0d20f07-ecc6-4617-989a-a6be43dba5e3)
![cipher-drv3](https://github.com/Mbed-TLS/mbedtls/assets/60640/6490f57a-25dd-406b-bceb-949d9e14d5bd)

@gilles-peskine-arm I thought we had an agreement on that plan and could move forward based on it, but from other comments it appears that might not be the case. Can you confirm if you agree or if not, clarify on what point(s) you think further discussion is needed?

**Comment by mpg** [comment]
Ok, thanks for clarifying! I hadn't considered that perhaps the needs of CTR-DRBG and GCC/CCM, though similar, were perhaps different enough to justify them using different approaches.

> that instance is created after the initialization of drivers and the key store

Hmm, "is" or "can be"? Right now looking at [the code](https://github.com/Mbed-TLS/mbedtls/blob/development/library/psa_crypto.c#L7728) I see `mbedtls_psa_random_seed()` (which eventually calls mbedtls_ctr_drbg_seed()`) called before `psa_initialize_key_slots()`. Probably we could change it easily - you probably know better than me it that's possible, so if you thought that was the case already, it probably means it is possible?

I'm not sure entirely convinced about distinguishing between G4.1 and G4.2, but also I'm not sure we need to. I think if `ctr_drbg.c` does something like the following, we should be fine:

**Comment by mpg** [comment]
(Just posting the rough idea before I leave, I'll elaborate tomorrow if needed.)

**Comment by gilles-peskine-arm** [comment]
> > that instance is created after the initialization of drivers and the key store
>
> Hmm, "is" or "can be"? Right now looking at the code I see mbedtls_psa_random_seed() (which eventually calls mbedtls_ctr_drbg_seed()) called before psa_initialize_key_slots()`. Probably we could change it easily - you probably know better than me it that's possible, so if you thought that was the case already, it probably means it is possible?

Oh, oops. Can be (and is in https://github.com/Mbed-TLS/mbedtls/pull/6636). The RNG and the key store are independent.

> if we have both a built-in and a driver for AES, then the driver won't be used

That's a good point: ideally we would prefer the PSA driver (like we do in md), but here we're trying to do the best we can in limited time, and this feels like a reasonable compromise. The reason to prefer a PSA driver is that it may have better performance (and also potentially better security than the built-in AES, if that uses the default pure-software implementation). But users who care about this, and who can't disable AES_C even in 3.6, can write an AES_ALT implementations. In fact, if they care about this and have code that works before 3.6, they probably already have written an AES_ALT implementation.

**Comment by mpg** [comment]
I'll note that the pattern
```
#if defined(MBEDTLS_AES_C)
// keep current code using mbedtls_aes
#else
// add new code using psa_cipher
#endif
```
seems pretty reminiscent of the strategy first used for hashes, which turned out to have a lot of issues, an experience I'm not eager to repeat. So, I feel the need to justify how the situation of CTR-DRBG is different.

In my understanding, the issues with the initial strategy for hashes had the following causes:
1. For modules using MD (like RSA), the decision to go for PSA or legacy was based on whether `MD_C` was present, which didn't go well where some hashes were only available on the legacy side, and some others only on the PSA side. (This could have been avoided by requiring that all hashes available via legacy are also available via PSA, which we ended up doing anyway as a convenience.)
2. Various modules in the stack were making decisions about using legacy or PSA based on various criteria (is `SHA256_C` present? is `MD_C` present? is `USE_PSA` on? - the infamous 3 families of feature macros in `legacy_or_psa.h`) and not only did it make it hard to remember what feature macro to use for what modules, it made it impossible in situation where a high-level module like TLS want to use a hash both directly and via a variety of other modules. (TLS wants to know whether "SHA256 is available" and can't work with answers like "well, depends if you're talking about plain SHA256 or RSA-SHA256".)

I'll note none of these apply to CTR-DRBG:
1. It only uses AES and we're not planning to extend it to other block ciphers, at the very least not before 4.0 where the situation will be very different and much simpler.
2. It holds a very special position in the stack. In particular, users of CTR-DRBG don't think about things like "is AES available" when using CTR-DRBG, they just want random numbers.

I'll also note that this justifies handling CTR-DRBG differently from GCM/CCM, where using Cipher-light with dual dispatch makes more sense.

**Comment by gilles-peskine-arm** [comment]
> I feel the need to justify how the situation of CTR-DRBG is different.

Right, thanks for writing it all out. For me the key thing is that CTR_DRBG does not have dependencies that percolate up. No code in the library depends on it: they only depend on the existence of an RNG. Even application code mostly doesn't depend on CTR_DRBG itself, only on it as a building block for an RNG, which means that limitations on CTR_DRBG could be acceptable.

In particular, I don't think I've written it down explicitly, but we could consider that the 3.6 “cipher light” work excludes `MBEDTLS_CTR_DRBG_C` as such, i.e. excludes applications that rely on the full semantics of `ctr_drbg.h` functions, and instead only supports a `CTR_DRBG_LIGHT` which is only good for the typical scenario where all you need is `init`, `seed`, `random` and `free`. I'm not sure there's any real advantage to that though.

**Comment by mpg** [comment]
(Marking as closed as this is not really a task of its own, more like a place to discuss and document things.)
