### ISSUE TITLE
Parameter size mismatch in ssl_tls13_keys.c

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8344]
https://github.com/Mbed-TLS/mbedtls/blob/e7ebec6723b61bd54800f649b1391e980edf2fbd/library/ssl_tls13_keys.c#L1021-L1022
https://github.com/Mbed-TLS/mbedtls/blob/e7ebec6723b61bd54800f649b1391e980edf2fbd/library/ssl_tls13_keys.c#L1028-L1029
Third parameter of `mbedtls_cipher_setkey` declaration is `int key_bitlen` but the function is called with the value `size_t mbedtls_cipher_info_get_key_bitlen`
A type cast or change in declaration might be applied.

**Comment by mcagriaksoy** [comment]
I opened PR: https://github.com/Mbed-TLS/mbedtls/pull/8345

**Comment by irwir** [comment]
Why so much haste with a PR? Design decision from maintainer might be different.

**Comment by gilles-peskine-arm** [comment]
@irwir Please don't discourage people like this! We do appreciate contributions. We can't always spend as much time reviewing them as we'd like, and we might of course disagree on the approach, but you don't need to wait for a design decision for a small portability improvement.

**Comment by gilles-peskine-arm** [comment]
Of course, ideally, `mbedtls_cipher_setkey` would take an argument of type `size_t` since a key size is not a signed concept. But that's an API change, so we can't do this until the next major version of the library. And there's a good chance that Mbed TLS 4.0 won't have `cipher.h` anymore (though this is still undecided, it might still be present as a compatibility layer).

**Comment by irwir** [comment]
@gilles-peskine-arm, people might have asked before making a PR. This was not a critical bug at all.

After looking at all references to of `mbedtls_cipher_info_get_key_bitlen`, I see it its return value needs type cast every time it was used.
Too bad if this is this also an API break, because making the function returning `int` would be a better way.
Additionally, cipher.c at line 138 uses this non-unifomr cast:
`mbedtls_cipher_info_get_key_bitlen(def->info) == (unsigned) key_bitlen &&`
It might need a changed too.
