### ISSUE TITLE
Error compiling AESNI in Mbed-TLS with clang on Windows

### ISSUE THREAD

**Issue by sergio-nsk** [Mbed-TLS/mbedtls#8372]
### Summary

clang does not have MSVS intrinsics, the pre-processor condition below does not cover this case if clang runs in MSVC compatibility mode
https://github.com/Mbed-TLS/mbedtls/blob/1ec69067fa1351427f904362c1221b31538c8b57/library/aesni.h#L42-L46
It should be
```c
#if defined(_MSC_VER) && !defined(__clang__)
/* Visual Studio supports AESNI intrinsics since VS 2008 SP1. We only support
 * VS 2013 and up for other reasons anyway, so no need to check the version. */
#define MBEDTLS_AESNI_HAVE_INTRINSICS
#endif
```

### System information

Mbed TLS version 2.28.5, 3.5.0
Operating system and version: Windows 10/11
Default configuration.
Compiler: LLVM clang, clang-cl

### Expected behavior

Built without errors.

### Actual behavior

Got many errors
```
/mbedtls/library/aesni.c:62:17: error: passing 'unsigned int[4]' to parameter of type 'int *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        __cpuid(info, 1);
                ^~~~
C:\PROGRA~1\LLVM\lib\clang\16\include\intrin.h:60:17: note: passing argument to parameter here
void __cpuid(int[4], int);
                ^
/mbedtls/library/aesni.c:102:21: error: call to undeclared function '_mm_aesdec_si128'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            state = _mm_aesdec_si128(state, *rk);
                    ^
/mbedtls/library/aesni.c:102:21: note: did you mean '_mm_and_si128'?
C:\PROGRA~1\LLVM\lib\clang\16\include\emmintrin.h:2611:46: note: '_mm_and_si128' declared here
static __inline__ __m128i __DEFAULT_FN_ATTRS _mm_and_si128(__m128i __a,
                                             ^
<...>
```

### Additional infromation

Fixing PRs will be offered soon.

**Comment by gilles-peskine-arm** [comment]
This is different, but closely related to https://github.com/Mbed-TLS/mbedtls/issues/8332, and at first glance I think https://github.com/Mbed-TLS/mbedtls/pull/8339 should fix this. Can you please check if https://github.com/Mbed-TLS/mbedtls/pull/8339 works for you?

**Comment by sergio-nsk** [comment]
@gilles-peskine-arm Yes, it looks very similar. I tried to search existing issues with my errors and could not find them. #8339 will not work for me, because clang does not defined the macro `__GNUC__` and `<cpuid.h>` does not exist on Windows.

There is [Consider removing AESNI assembly #8231](https://github.com/Mbed-TLS/mbedtls/issues/8231), maybe it's more correct that #8339 does not update aesni.c for MinGW but disables easni.c like I want to do it in easni.h.

**Comment by lpy4105** [comment]
> #8339 will not work for me, because clang does not define the macro `__GNUC__` and `<cpuid.h>` does not exist on Windows.

I believe it would fix the issue arround `__cpuid`, but we do have issue of AESNI implementation selection for clang in MSVC compatible mode.

**Comment by pengsel** [comment]
Is there any way to solve this compilation problem without modifying the code?
