### ISSUE TITLE
Add support for compiling using clang-cl to target windows

### ISSUE THREAD

**Issue by daantimmer** [Mbed-TLS/mbedtls#8387]
### Suggested enhancement
Use CMAKE_C_SIMULATE_ID when available instead of CMAKE_C_COMPILER_ID to determine the current compiler used.

### Justification
Currently mbed-tls does not support building from linux, targeting windows, using clang-cl. Mbed-tls detects the Clang compiler and sets clang specific arguments. These are not supported by clang-cl, which expects MSVC-like arguments.

My current setup uses linux (devcontainer) to cross compile to target windows. However, the same issue will arrise when building on windows through clang-cl.

Mbed TLS needs this because there might be a chance mbed-tls is used in an environment where the compiler is clang-cl.

**Comment by davidhorstmann-arm** [comment]
Is this related to #8372?

**Comment by daantimmer** [comment]
It is related, but different. My PR/issue solved I different issue. I had no compilation errors. Only many warnings about unknown compiler arguments. Arguments that are valid for `clang` but not `clang-cl`.

**Comment by daantimmer** [comment]
Some additional information. I have a bunch of examples available. They use our devcontainer which is based on clang-15. (clang-17 container is in the works).

I only have a fully working build+example with a older version of mbedtls (3.2.1) because as issue #8372 points out, the current release doesn't work with clang-cl.

#mbedtls-3.2.1-unpatched
https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/tree/master
build results: https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/actions/runs/6565941644/job/17835580185#step:4:42 take note of the generated warnings about arguments. Build fails because I am not fetching the debug symbols via xwin.

#mbedtls-3.5.0-unpatched
https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/tree/update-mbedtls-to-3.5.0
build results: https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/actions/runs/6565950485/job/17835607064#step:4:34 here we see the errors that #8372 is talking about. Together with the warnings from v3.2.1-unpatched

#mbedtls-3.5.0-patched
(I'll have to fix this build for other reasons, seems like stuff has changed between #development and v3.5.0 w.r.t. the generated files)
https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/tree/update-mbedtls-to-pr-version
build results: https://github.com/daantimmer/mbed-tls-xwin-cross-compilation/actions/runs/6565947582/job/17835599953
here we still see the errors from #8372 however the warnings from the incorrect/unknown arguments is gone.

**Comment by daantimmer** [comment]
@davidhorstmann-arm is there anything else that I need to do or what is expected from my side? I am happy to make changes where required :-)
