### ISSUE TITLE
Ensure correct state for key content write

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#8411]
In #8410 we implemented state transitions for key slots, denoting whether the thread has read access (READ), exclusive access (WRITING) or not using the slot at all (UNUSED).

The task is to make sure that functions that need write access, move the state into WRITING first and transition to READ or UNUSED once they don't need it anymore. Functions that can't do that, because they are called by a function that itself needs exclusive access, need to document that the caller needs to move the slot to WRITING first.

(Moving to WRITING state means actually changing the state to that. If it is already in WRITING state, it means that some other thread has exclusive access.)

Internal utility functions, especially those that are not used anywhere should only document that they need access.

Any function that only documents the requirement for WRITING state should have a check guarded by `MBEDTLS_TEST_HOOKS` that tests whether it is indeed in a correct state when called. (It is a useful check for testing and debugging, but in a multithreaded environment doesn't guarantee anything.)

**Comment by paul-elliott-arm** [comment]
Closing after epic redesign.
