### ISSUE TITLE
Ensure correct state for key content read

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#8419]
In https://github.com/Mbed-TLS/mbedtls/issues/8410 we implemented state transitions for key slots, denoting whether the thread has read access (READ), exclusive access (WRITING) or not using the slot at all (UNUSED).

Since the key locking mechanism for reading was already present and we build on that, most content read should happen when the slot is already in the correct state. The exception is multipart operations, which are out of scope for this issue.

The task is to
- double check that all content read indeed happens in the correct state
- if it doesn't then fix it
- if the function doesn't lock the key for itself, document that the caller needs to lock the slot

Any function that only documents the requirement for WRITING state should have a check guarded by MBEDTLS_TEST_HOOKS that tests whether it is indeed in a correct state when called. (It is a useful check for testing and debugging, but in a multithreaded environment doesn't guarantee anything.)

**Comment by paul-elliott-arm** [comment]
Closing after EPIC redesign.
