### ISSUE TITLE
Wrong rsa->len Value When Built in Visual Studio x64

### ISSUE THREAD

**Issue by CloudExt** [Mbed-TLS/mbedtls#8424]
### Summary

Built in x86 is OK, but built in x64 version, rsa->len(ctx->len) got wrong value.

In rsa.c:

function `mbedtls_rsa_import_raw()`
```
if (N != NULL) {
    MBEDTLS_MPI_CHK(mbedtls_mpi_read_binary(&ctx->N, N, N_len));
    ctx->len = mbedtls_mpi_size(&ctx->N);
}
```

mbedtls_mpi_size(&ctx->N) returned 0x100;
But when it assigned to ctx->len, it beccome 0x10000000000. (left shifted 32bit)

![螢幕擷取畫面 2023-10-26 161034](https://github.com/Mbed-TLS/mbedtls/assets/22338810/e81b3f8e-f799-47fa-9279-f7ae3293138e)

### System information

Mbed TLS version (number or commit id): f38e2fe97b5a11712145c4e38034dcce640d7817
Operating system and version: Windows 10 22H2
Configuration (if not default, please attach `mbedtls_config.h`): default config
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Visual Studio 2019
Additional environment information: 

### Expected behavior

ctx->len should be 0x100

### Actual behavior

ctx->len be 0x10000000000

**Comment by tom-cosgrove-arm** [comment]
Can you share the key you were using here? This function is used by the tests, so it would be good to have the code you were using too

**Comment by CloudExt** [comment]
Hi Tom,

unsigned char PublicKey0[461] = {
    0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x50,
    0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D,
    0x2D, 0x2D, 0x0D, 0x0A, 0x4D, 0x49, 0x49, 0x42, 0x49, 0x44, 0x41, 0x4E,
    0x42, 0x67, 0x6B, 0x71, 0x68, 0x6B, 0x69, 0x47, 0x39, 0x77, 0x30, 0x42,
    0x41, 0x51, 0x45, 0x46, 0x41, 0x41, 0x4F, 0x43, 0x41, 0x51, 0x30, 0x41,
    0x4D, 0x49, 0x49, 0x42, 0x43, 0x41, 0x4B, 0x43, 0x41, 0x51, 0x45, 0x41,
    0x78, 0x67, 0x73, 0x39, 0x31, 0x37, 0x34, 0x65, 0x78, 0x66, 0x66, 0x39,
    0x5A, 0x64, 0x4C, 0x72, 0x67, 0x46, 0x44, 0x63, 0x0D, 0x0A, 0x61, 0x76,
    0x79, 0x7A, 0x54, 0x71, 0x61, 0x35, 0x49, 0x6B, 0x75, 0x2B, 0x7A, 0x6C,
    0x33, 0x4A, 0x56, 0x4B, 0x75, 0x38, 0x6B, 0x32, 0x44, 0x6C, 0x5A, 0x57,
    0x79, 0x65, 0x62, 0x50, 0x4C, 0x64, 0x4A, 0x45, 0x75, 0x32, 0x56, 0x33,
    0x4C, 0x68, 0x39, 0x6D, 0x79, 0x6A, 0x79, 0x35, 0x47, 0x79, 0x51, 0x7A,
    0x33, 0x46, 0x67, 0x31, 0x4C, 0x5A, 0x67, 0x43, 0x39, 0x52, 0x74, 0x44,
    0x58, 0x6E, 0x0D, 0x0A, 0x5A, 0x63, 0x63, 0x57, 0x78, 0x47, 0x2F, 0x51,
    0x2B, 0x71, 0x52, 0x44, 0x6C, 0x30, 0x72, 0x68, 0x64, 0x78, 0x59, 0x7A,
    0x50, 0x34, 0x4E, 0x6A, 0x2F, 0x53, 0x78, 0x4C, 0x51, 0x77, 0x41, 0x55,
    0x38, 0x68, 0x4F, 0x56, 0x6B, 0x46, 0x61, 0x61, 0x43, 0x69, 0x75, 0x6A,
    0x71, 0x55, 0x2F, 0x34, 0x47, 0x63, 0x6C, 0x54, 0x5A, 0x75, 0x72, 0x39,
    0x46, 0x6B, 0x33, 0x57, 0x6B, 0x41, 0x73, 0x30, 0x0D, 0x0A, 0x77, 0x45,
    0x4D, 0x61, 0x67, 0x6C, 0x32, 0x2F, 0x66, 0x72, 0x68, 0x73, 0x77, 0x36,
    0x57, 0x6D, 0x44, 0x61, 0x41, 0x4E, 0x37, 0x4E, 0x64, 0x56, 0x33, 0x69,
    0x36, 0x4C, 0x72, 0x68, 0x4E, 0x64, 0x51, 0x7A, 0x43, 0x4E, 0x73, 0x69,
    0x59, 0x6E, 0x73, 0x5A, 0x33, 0x39, 0x69, 0x71, 0x73, 0x30, 0x4E, 0x58,
    0x6F, 0x46, 0x57, 0x47, 0x76, 0x32, 0x6B, 0x6C, 0x48, 0x42, 0x4E, 0x59,
    0x4E, 0x4E, 0x0D, 0x0A, 0x58, 0x2B, 0x56, 0x62, 0x6A, 0x42, 0x33, 0x7A,
    0x74, 0x39, 0x69, 0x30, 0x46, 0x6E, 0x37, 0x75, 0x39, 0x33, 0x5A, 0x2B,
    0x55, 0x67, 0x58, 0x44, 0x4E, 0x78, 0x47, 0x64, 0x6D, 0x72, 0x30, 0x36,
    0x59, 0x38, 0x4E, 0x2B, 0x4E, 0x6C, 0x6B, 0x74, 0x67, 0x30, 0x57, 0x43,
    0x55, 0x68, 0x4D, 0x79, 0x37, 0x50, 0x77, 0x49, 0x50, 0x42, 0x54, 0x4A,
    0x62, 0x75, 0x61, 0x39, 0x54, 0x77, 0x56, 0x61, 0x0D, 0x0A, 0x56, 0x67,
    0x4E, 0x31, 0x54, 0x67, 0x34, 0x44, 0x6B, 0x69, 0x43, 0x58, 0x31, 0x46,
    0x46, 0x71, 0x39, 0x6F, 0x62, 0x35, 0x61, 0x72, 0x71, 0x76, 0x32, 0x42,
    0x50, 0x71, 0x77, 0x38, 0x37, 0x61, 0x46, 0x39, 0x73, 0x7A, 0x45, 0x64,
    0x79, 0x57, 0x6F, 0x6F, 0x70, 0x72, 0x78, 0x34, 0x61, 0x34, 0x42, 0x57,
    0x67, 0x4B, 0x55, 0x32, 0x34, 0x4E, 0x34, 0x76, 0x4B, 0x51, 0x33, 0x44,
    0x47, 0x76, 0x0D, 0x0A, 0x5A, 0x51, 0x49, 0x42, 0x4A, 0x51, 0x3D, 0x3D,
    0x0D, 0x0A, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x50,
    0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D,
    0x2D, 0x2D, 0x0D, 0x0A, 0x00
};unsigned char SpyderPublicKey0[461] = {
    0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x42, 0x45, 0x47, 0x49, 0x4E, 0x20, 0x50,
    0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D,
    0x2D, 0x2D, 0x0D, 0x0A, 0x4D, 0x49, 0x49, 0x42, 0x49, 0x44, 0x41, 0x4E,
    0x42, 0x67, 0x6B, 0x71, 0x68, 0x6B, 0x69, 0x47, 0x39, 0x77, 0x30, 0x42,
    0x41, 0x51, 0x45, 0x46, 0x41, 0x41, 0x4F, 0x43, 0x41, 0x51, 0x30, 0x41,
    0x4D, 0x49, 0x49, 0x42, 0x43, 0x41, 0x4B, 0x43, 0x41, 0x51, 0x45, 0x41,
    0x78, 0x67, 0x73, 0x39, 0x31, 0x37, 0x34, 0x65, 0x78, 0x66, 0x66, 0x39,
    0x5A, 0x64, 0x4C, 0x72, 0x67, 0x46, 0x44, 0x63, 0x0D, 0x0A, 0x61, 0x76,
    0x79, 0x7A, 0x54, 0x71, 0x61, 0x35, 0x49, 0x6B, 0x75, 0x2B, 0x7A, 0x6C,
    0x33, 0x4A, 0x56, 0x4B, 0x75, 0x38, 0x6B, 0x32, 0x44, 0x6C, 0x5A, 0x57,
    0x79, 0x65, 0x62, 0x50, 0x4C, 0x64, 0x4A, 0x45, 0x75, 0x32, 0x56, 0x33,
    0x4C, 0x68, 0x39, 0x6D, 0x79, 0x6A, 0x79, 0x35, 0x47, 0x79, 0x51, 0x7A,
    0x33, 0x46, 0x67, 0x31, 0x4C, 0x5A, 0x67, 0x43, 0x39, 0x52, 0x74, 0x44,
    0x58, 0x6E, 0x0D, 0x0A, 0x5A, 0x63, 0x63, 0x57, 0x78, 0x47, 0x2F, 0x51,
    0x2B, 0x71, 0x52, 0x44, 0x6C, 0x30, 0x72, 0x68, 0x64, 0x78, 0x59, 0x7A,
    0x50, 0x34, 0x4E, 0x6A, 0x2F, 0x53, 0x78, 0x4C, 0x51, 0x77, 0x41, 0x55,
    0x38, 0x68, 0x4F, 0x56, 0x6B, 0x46, 0x61, 0x61, 0x43, 0x69, 0x75, 0x6A,
    0x71, 0x55, 0x2F, 0x34, 0x47, 0x63, 0x6C, 0x54, 0x5A, 0x75, 0x72, 0x39,
    0x46, 0x6B, 0x33, 0x57, 0x6B, 0x41, 0x73, 0x30, 0x0D, 0x0A, 0x77, 0x45,
    0x4D, 0x61, 0x67, 0x6C, 0x32, 0x2F, 0x66, 0x72, 0x68, 0x73, 0x77, 0x36,
    0x57, 0x6D, 0x44, 0x61, 0x41, 0x4E, 0x37, 0x4E, 0x64, 0x56, 0x33, 0x69,
    0x36, 0x4C, 0x72, 0x68, 0x4E, 0x64, 0x51, 0x7A, 0x43, 0x4E, 0x73, 0x69,
    0x59, 0x6E, 0x73, 0x5A, 0x33, 0x39, 0x69, 0x71, 0x73, 0x30, 0x4E, 0x58,
    0x6F, 0x46, 0x57, 0x47, 0x76, 0x32, 0x6B, 0x6C, 0x48, 0x42, 0x4E, 0x59,
    0x4E, 0x4E, 0x0D, 0x0A, 0x58, 0x2B, 0x56, 0x62, 0x6A, 0x42, 0x33, 0x7A,
    0x74, 0x39, 0x69, 0x30, 0x46, 0x6E, 0x37, 0x75, 0x39, 0x33, 0x5A, 0x2B,
    0x55, 0x67, 0x58, 0x44, 0x4E, 0x78, 0x47, 0x64, 0x6D, 0x72, 0x30, 0x36,
    0x59, 0x38, 0x4E, 0x2B, 0x4E, 0x6C, 0x6B, 0x74, 0x67, 0x30, 0x57, 0x43,
    0x55, 0x68, 0x4D, 0x79, 0x37, 0x50, 0x77, 0x49, 0x50, 0x42, 0x54, 0x4A,
    0x62, 0x75, 0x61, 0x39, 0x54, 0x77, 0x56, 0x61, 0x0D, 0x0A, 0x56, 0x67,
    0x4E, 0x31, 0x54, 0x67, 0x34, 0x44, 0x6B, 0x69, 0x43, 0x58, 0x31, 0x46,
    0x46, 0x71, 0x39, 0x6F, 0x62, 0x35, 0x61, 0x72, 0x71, 0x76, 0x32, 0x42,
    0x50, 0x71, 0x77, 0x38, 0x37, 0x61, 0x46, 0x39, 0x73, 0x7A, 0x45, 0x64,
    0x79, 0x57, 0x6F, 0x6F, 0x70, 0x72, 0x78, 0x34, 0x61, 0x34, 0x42, 0x57,
    0x67, 0x4B, 0x55, 0x32, 0x34, 0x4E, 0x34, 0x76, 0x4B, 0x51, 0x33, 0x44,
    0x47, 0x76, 0x0D, 0x0A, 0x5A, 0x51, 0x49, 0x42, 0x4A, 0x51, 0x3D, 0x3D,
    0x0D, 0x0A, 0x2D, 0x2D, 0x2D, 0x2D, 0x2D, 0x45, 0x4E, 0x44, 0x20, 0x50,
    0x55, 0x42, 0x4C, 0x49, 0x43, 0x20, 0x4B, 0x45, 0x59, 0x2D, 0x2D, 0x2D,
    0x2D, 0x2D, 0x0D, 0x0A, 0x00
};

**Comment by CloudExt** [comment]
Maybe this is struct padding issue?
sizeof(mbedtls_mpi) in my application:
![1](https://github.com/Mbed-TLS/mbedtls/assets/22338810/9511b02b-b3f1-4876-bc17-55bfe037da58)

and in mbedTLS lib:
![2](https://github.com/Mbed-TLS/mbedtls/assets/22338810/5b736eac-9ec5-4419-8036-56ade017e3fa)

It could be set by config? But I don't know which option is the key point.

**Comment by CloudExt** [comment]
UPDATE:

I manually add 
`#pragma pack(push, 1)`
in front and
`#pragma pack(pop)`
at the end of struct definition of `mbedtls_mpi` and `mbedtls_rsa_context`, and it works now.

Does it has smarter way to do this?

**Comment by tom-cosgrove-arm** [comment]
It sounds like your application and the library have been compiled with different padding options - how are you building the library and the application?

**Comment by CloudExt** [comment]
Oh, I found where the different settings:

![圖片](https://github.com/Mbed-TLS/mbedtls/assets/22338810/a990574c-02cf-4d44-b5e6-1ccc9f870da5)

**Struct Member Alignment** in my application is `/Zp1` and library is `Default`.
I change library to `/Zp1` too (and have to add a macro define `WINDOWS_IGNORE_PACKING_MISMATCH`) and it worked now.

Thanks for your help!

**Comment by tom-cosgrove-arm** [comment]
Closing at OP reports issue resolved
