### ISSUE TITLE
Require few member accessor api from mbedtls_ssl_session and mbedtls_ssl_context structure

### ISSUE THREAD

**Issue by sabarike** [Mbed-TLS/mbedtls#8456]
We are integrating the latest MbedTLS v3.5.0 from MbedTLS v2.x. In our code, we are accessing the below private structure members. As per the [3.0-migration-guide.md](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md), we have to use the setter/getter api for access. But there is no setter/getter apis for below members.

#### Members from mbedtls_ssl_session structure 
* ciphersuite
* master
* id_len
* id

#### Members from mbedtls_ssl_context structure 
* handshake
* state
* in_window_top
* in_window
* cur_out_ctr
* session_negotiate
   
Could you help us to find if there is setter/getter apis for above member access? If no setter/getter api, could you add those accessor apis ?

**Comment by minosgalanakis** [comment]
We are currently reviewing/considering adding acessors for specific `MBEDTLS_PRIVATE` structures. 

Could you please provide more information on your use-cases for the following `mbedtls_ssl_context` members:
- `in_window_top`
- `in_window`
- `cur_out_ctr`
- `session_negotiate`

As well as the `mbedtls_ssl_session->master`?

Please check #8529 for the overall plan, and feel free to comment there as well.

**Comment by tom-cosgrove-arm** [comment]
Ping @sabarike - could you provide more information as above please?

**Comment by minosgalanakis** [comment]
As discussed in issue [4383 ](https://github.com/Mbed-TLS/mbedtls/issues/8529)and  the design review issue [8529](https://github.com/Mbed-TLS/mbedtls/issues/4383), accessors for the `id` and `ciphersuite_id` and `id_len` are being added in [pr8888](https://github.com/Mbed-TLS/mbedtls/pull/8888)

The handshake and handshake state are not to be directly exposed, but approporiate callbacks have been added in other tickets.

I will be closing this ticket, but please feel free to reach out with your use requirements for the other accessors listed above.
