### ISSUE TITLE
Our Mutex Thread testing layer is not thread safe

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#8473]
### Summary

As per #8472  the `isvalid` field in the `mbedtls_threading_mutex_t` struct is not protected by a mutex, so the wrappers in `threading_helpers.c` reading and writing it on lock or unlock is going to cause a race condition on the `isvalid` field, which means that this test is very unlikely to work as expected in a multithreaded environment. Worse still, malfunction of these tests could cause a mutex to stop working.

The new TSAN compiler sanitiser mode flags this race condition immediately. I have a couple of ideas as to how to fix this, and obviously this is also dependant on how we decide to fix #8472

## Option 1. Remove the mutex testing layer.

I would hope that TSAN would catch most of the cases that are tested here, and I'm pretty sure pthreads itself will error on a few of the others.

## Option 2. Make it safe.

By wrapping all of the reading and writing of `isvalid` in a mutex we could easily make this safe, but I think it should be behind its own flag. I know these wrappers will only be used in a test environment, so performance isn't particularly a concern here here but the need to lock a mutex to lock or unlock a mutex could very much hide some timing issues from TSAN if the two are only run together. Care will also have to be taken to avoid deadlocking / negative interaction with the new test_info mutexes.

**Comment by gilles-peskine-arm** [comment]
By mutex testing layer, do you mean `MBEDTLS_TEST_MUTEX_USAGE`? If so: I think we should keep it. It doesn't check much, but it's fully deterministic. If it's not thread-safe, that's not really a concern. We'll just run it in a configuration where we have threading enabled (so that the mutex objects exist) but we don't actually create other threads.

**Comment by paul-elliott-arm** [comment]
Sorry, to explain, this refers to the wrappers in `threading_helpers.c` (I have edited the body to clear this up). 

Given these hook into the operation of the mutex, I'm not really sure how to test these in a single threaded mode - Many of the mutexes won't actually exist unless you turn on the relevant flags, or certainly won't be used, given the performance impact of doing so. I'm not sure we would get any meaningful results like this, put it that way

These tests would have to be actively disabled if any threading was actually turned on, given they trip TSAN, and would cause the CI to fail.

**Comment by paul-elliott-arm** [comment]
Currently trending towards Option 2, but also moving `isvalid` so it only exists (and is checked / manipulated) under `MBEDTLS_TEST_MUTEX_USAGE`, thus retaining full test coverage, but thread-safe.
