### ISSUE TITLE
Redesign mbedtls_pk_verify_ext and mbedtls_pk_sign_ext to respect key policies

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8493]
With `mbedtls_pk_verify_ext` and `mbedtls_pk_sign_ext` on an RSA key, you can indifferently perform a v15 verification or a PSS verification, regardless of whether the key's padding mode is set to v15 or v21 (PSS/OAEP). This defeats the purpose of having a padding mode set on a key, which is to prevent accidentally using a key for an unintended purpose (which is often a source of subtle security vulnerabilities).

Note that for `mbedtls_pk_sign_ext`, this likely means removing the function since it would no longer have a useful purpose. `mbedtls_pk_verify_ext` may or may not still have a useful purpose because it supports extra options (alternative hash and accepted salt length).

The goal of this issue is to remove the ability to bypass a key's policy from the pk API. This may require https://github.com/Mbed-TLS/mbedtls/issues/8492 to allow the PK module to manage the key's policy on its own.

Part of the more general https://github.com/Mbed-TLS/mbedtls/issues/8452

**Comment by mpg** [comment]
For the record, it's not clear to me if and how PK should manage policies, as I've discussed in #8492. I think this ties to the larger discussion about what shape (if any) PK should have in 4.0, that is #8452 - and the question there is really not a binary remove of keep, but if we choose "keep", what exactly we mean by that.

**Comment by gilles-peskine-arm** [comment]
`mbedtls_pk_verify_ext` has two jobs:

* It allows selecting between RSA-v1.5 and RSA-PSS signatures regardless of the padding mode set in the key object.
* For PSS signatures, it allows specifying some options: an alternate hash for the MGF, and an expected salt length.

The objective of this issue is to remove the first job. It's not clear to me that we can sensibly also remove the second job by including all the options in the key context. If we can do that then the objective becomes to remove `mbedtls_pk_verify_ext` from the API.

Note that there is also a function `mbedtls_pk_sign_ext`. That function only has the first job, so part of this issue is removing it.

We still need to determine what this means in terms of API to configure a key's algorithm, and in terms of how calling code (including our own X.509 and TLS code) uses the API.

**Comment by gilles-peskine-arm** [comment]
This is part of the larger pk redesign in https://github.com/Mbed-TLS/mbedtls/issues/8452. I don't think it makes sense to consider it separately, so I'm closing this issue.
