### ISSUE TITLE
cmake build of v3.5.1 failed

### ISSUE THREAD

**Issue by markusbaetz** [Mbed-TLS/mbedtls#8507]
### Summary
I tried to build mbedtls with cmake but failed in configuration build

### System information

Mbed TLS version v3.5.1: 
Operating system and version: Win 10
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Steps to reproduce

clone repository with latest tag v3.5.1under windows 10

create directory next do mbedtls repository clone
- mkdir build
- cmake ../mbedtls

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.37.32825.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python3: C:/Python312/python.exe (found version "3.12.0") found components: Interpreter
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
CMake Error at library/CMakeLists.txt:275 (add_library):
  Cannot find source file:

    error.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at library/CMakeLists.txt:291 (add_library):
  Cannot find source file:

    ssl_debug_helpers_generated.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at programs/ssl/CMakeLists.txt:40 (add_executable):
  Cannot find source file:

..... query_config.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at programs/test/CMakeLists.txt:72 (add_executable):
  Cannot find source file:
  ...

**Comment by markusbaetz** [comment]
checkout master and build works

**Comment by gilles-peskine-arm** [comment]
That's really strange: `master` currently has exactly the same content as `mbedtls-3.5.1`. Are you sure you didn't have any stale files in either the source directory or the build directory?

**Comment by markusbaetz** [comment]
you are right. when i checkout mbedtls-3.5.1 there are also no error. 
But if I try to checkout tag v3.5.1I'll get the errors.

`git log -1
commit 4dec9ebdc2d0e49a87cfd5f0d7bc2dc9d21beae9 (HEAD -> v3.5.1, origin/development, origin/coverity_scan, origin/HEAD)
Merge: c75ee77db c55b50034
Author: Gilles Peskine <gilles.peskine@arm.com>
Date:   Wed Nov 8 18:07:04 2023 +0000`

**Comment by markusbaetz** [comment]
checkout master
`it log -1
commit edb8fec9882084344a314368ac7fd957a187519c (HEAD -> master, tag: v3.5.1, tag: mbedtls-3.5.1, origin/master)
Author: Dave Rodgman <dave.rodgman@arm.com>
Date:   Wed Nov 8 11:36:00 2023 +0000`

**Comment by tom-cosgrove-arm** [comment]
I am unable to reproduce this, even after correcting the steps in the description (which is missing a `cd build`).

I also removed Perl and Python (which is the most likely thing to be a problem - I note you do have Python in your system) and the build succeeds.

Directories `v3.5.1` and `build` did not exist before running these commands

```
D:\home\tom\projects\mbedtls>systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

D:\home\tom\projects\mbedtls>git clone -o upstream -b v3.5.1 https://github.com/Mbed-TLS/mbedtls.git v3.5.1

D:\home\tom\projects\mbedtls>ls v3.5.1
3rdparty               CONTRIBUTING.md        LICENSE                SUPPORT.md             docs                   programs
BRANCHES.md            ChangeLog              Makefile               cmake                  doxygen                scripts
BUGS.md                ChangeLog.d            README.md              configs                include                tests
CMakeLists.txt         DartConfiguration.tcl  SECURITY.md            dco.txt                library                visualc

D:\home\tom\projects\mbedtls>mkdir build

D:\home\tom\projects\mbedtls>cd build

D:\home\tom\projects\mbedtls\build>cmake ../v3.5.1
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30140.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: D:/home/tom/projects/mbedtls/build

D:\home\tom\projects\mbedtls\build>cmake --build .

: succeeds
```

**Comment by tom-cosgrove-arm** [comment]
Please, when reporting problems show all the commands run and the output. Just posting snippets makes it very hard for us to figure out what has gone wrong.

Please start with a fresh checkout into a new directory like I did above and report what happens

**Comment by markusbaetz** [comment]
Thanks for the quick help. (FYI: I use mbedtls as subdirectory in my cmake project). I just use master with current commit/tag and this will work. 👍

**Comment by tom-cosgrove-arm** [comment]
> I just use master with current commit/tag and this will work

Note that this means there is "something else" wrong - as @gilles-peskine-arm said, `master` and `v3.5.1` (and `mbedtls-3.5.1`) are identical (point to the same commit)

**Comment by gilles-peskine-arm** [comment]
[`v3.5.1`](https://github.com/Mbed-TLS/mbedtls/tree/v3.5.1) is not 4dec9ebdc2d0e49a87cfd5f0d7bc2dc9d21beae9, it's edb8fec9882084344a314368ac7fd957a187519c, same as [`mbedtls-3.5.1`](https://github.com/Mbed-TLS/mbedtls/tree/mbedtls-3.5.1).

4dec9ebdc2d0e49a87cfd5f0d7bc2dc9d21beae9 is not a release commit, and you need to run `scripts\make_generated_files.bat` on Windows if you aren't using a release.

**Comment by markusbaetz** [comment]
I started the whole thing again in a docker environment. And here everything runs without any problems. It's probably due to my submodule. Thanks again!
