### ISSUE TITLE
Please submit a new version to cocoapod

### ISSUE THREAD

**Issue by rupy1014** [Mbed-TLS/mbedtls#8520]
The latest version appears to be 3.5.1, but the current CocoaPod version is 2.14.1. Please distribute the latest version

**Comment by tom-cosgrove-arm** [comment]
We update the software here, we don't generally supply it to package managers, that's the job of whoever wants to have it distributed via that package manager.

Note that there are several changes from 2.14.1 to 3.5.1 that mean it wouldn't be a drop-in replacement.

[The page over there](https://cocoapods.org/pods/mbedTLS) says "Maintained by Glenn Schmidt" so I think that's who you should ask to do this.

(And also note that Mbed TLS moved from the ARMmbed to its own Mbed-TLS organisation on GitHub a while ago)

**Comment by tom-cosgrove-arm** [comment]
Closing this, as this isn't an action for us to take
