### ISSUE TITLE
Standardise repository detection in Mbed TLS and TF-PSA-Crypto

### ISSUE THREAD

**Issue by tom-daubney-arm** [Mbed-TLS/mbedtls#8524]
### Suggested enhancement
Provide a standard mechanism to allow various build and test scripts to detect which repository they are being called from. This could be done by introducing a file in to Mbed TLS and TF-PSA-Crypto where the contents of the file identifies the repository as suggested by @gilles-peskine-arm .

### Justification

Mbed TLS needs this because since the introduction of TF-PSA-Crypto various scripts need to know in a robust and uniform way which repository they are being called from since the directory structure and functionality of the repositories differ.

**Comment by ronald-cron-arm** [comment]
See also [comment in 9394](https://github.com/Mbed-TLS/mbedtls/pull/9394#issuecomment-2242258673)
