### ISSUE TITLE
Review requested `MBEDTLS_PRIVATE ` accessors.

### ISSUE THREAD

**Issue by minosgalanakis** [Mbed-TLS/mbedtls#8529]
### Suggested enhancement

As specified in the MBed-TLS 3.X migration guide [most structure fields are now private](https://github.com/Mbed-TLS/mbedtls/blob/909cf5a3ecc1e91c62e148f96f03400ca88869ff/docs/3.0-migration-guide.md#most-structure-fields-are-now-private) . Community can request the addition of private getter/setter functions for their use cases.

There has been a range of such requests #6151, #5441, #8456, #4383 , #7722 as well as some already planned as part of the transition work #5016, #5017

In some cases it may not be a straighforward ask e.g. #4383

The scope of this task is to collect all such requests under one design-review ticket and decide which one we will be implemented as part of the next relase, and which ones have special considerations.

### Scope
The output of this issue is a collection of s-sized subtasks, for accepted getters/setters, appropriately linked with the others items in the epic, and reviewed and approved by members of the team.

**Comment by minosgalanakis** [comment]
## Guidance

Please review as per your field of expertise the following table containing data which have been made private during the 2->3 transition. 

This is a comprehensive list of things we have been planning or have been asked to add accessors to.

Comments will be used as a design review in order to design which ones we will be impementing at 3.6 LTS.


| Struct         | Member | Getter | Setter | Links | 
|----------------|---------------|---------------|----------------|-----------|
| mbedtls_ssl_session ||||#8456|
|| `ciphersuite`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `master`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `id_len`, `id`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
| mbedtls_ssl_context ||||#8456|
|| `handshake` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `state` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | Probably not as discussed here #4383|
|| `in_window_top` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `in_window` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `cur_out_ctr` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `session_negotiate` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
| mbedtls_rsa_context   |||#5014|
|| `len` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `N`, `P`, `Q`, `D`, `E`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `DP`, `DQ`, `QP`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
| mbedtls_dhm_context   |||#5015|
|| `len` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
|| `P`, `Q` | <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |
| mbedtls_ecp_keypair   |||#5441, #5017, #4838|
|| `grp`, `D`, `Q`| <ul><li>[X] </li></ul> |  <ul><li>[ ] </li></ul>  | Getters added at #5014|
| mbedtls_ecp_point   |||#5441, #5017, #4838|
|| `X`, `Y`, `Z`| <ul><li>[X] </li></ul> |  <ul><li>[ ] </li></ul>  | Getters added at  #7815|
| mbedtls_ecdh_context  |||#5016|
||`grp`, `Q`, `Qp`| <ul><li>[ ] </li></ul> |  <ul><li>[ ] </li></ul>  | |

**Comment by mpg** [comment]
Thanks for collecting everything into a nice table! One point though: I don't think checkboxes are ideal here as unchecked could mean either "not reviewed yet" or "reviewed and decided against it". I suggest a tri-state Y / N / ? instead.
