### ISSUE TITLE
Handshake failure due to ticket arrival

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8591]
### Summary
Testing `sls_mail_client.c` with locally installed `hMailServer` (based on OpenSSL library).
Server cannot be connected due to handshake failure.

### System information
Mbed TLS version 3.5.0
Operating system and version: Windows 11
Compiler: Visual Studio 2022

### Expected behavior
Successful mail exchange.

### Actual behavior
When handshaking gets to `MBEDTLS_SSL_HANDSHAKE_OVER` state, the mail server sends a ticket.
Now, since the step returned with a non-zero state `MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET`, handshaking got aborted.

### Additional information
https://github.com/Mbed-TLS/mbedtls/blob/857d29f29aa6699603fad340c15462303cf4f1fa/library/ssl_tls.c#L3924
This addition quickly patched the issue, but the problem might be deeper:
>  if (ret == MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET &&
>      ssl->state == MBEDTLS_SSL_HANDSHAKE_OVER) {
>      ret = 0;
>  }

**Comment by ronald-cron-arm** [comment]
Thanks a lot for the report. The quick path basically disables the reception of TLS 1.3 session tickets by applications thus we cannot to that. I see two possible ways forward:
1. ignoring in your application code (mail client it seems) the MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET returned value (can be returned by mbedtls_ssl_handshake_step(), mbedtls_ssl_handshake() and mbedtls_ssl_read()).
2. disabling the MBEDTLS_SSL_SESSION_TICKETS configuration option when you build the Mbed TLS library for your mail client. I know that we have some pending issues around that but we are aiming to fix them shortly.

**Comment by irwir** [comment]
The is MbedTLS example mail client. It has got changes for TLS 1.3, but more than one issue was encountered.

>     1. ignoring in your application code (mail client it seems) the MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET returned value (can be returned by mbedtls_ssl_handshake_step(), mbedtls_ssl_handshake() and mbedtls_ssl_read()).

The client calls mbedtls_ssl_handshake(), and one of the steps (not the last) fails inside the library code.
Should the remaining steps be skipped, the connection might end up having a wrong state.
Hence the patch was a natural choice.

Hopefully, the issue would be properely resolved soon.

**Comment by fargiolas** [comment]
>     1. ignoring in your application code (mail client it seems) the MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET returned value (can be returned by mbedtls_ssl_handshake_step(), mbedtls_ssl_handshake() and mbedtls_ssl_read()).

Sorry for hijacking this ticket a little, didn't dig into the code yet but I'm seeing MBEDTLS_ERR_SSL_RECEIVED_NEW_SESSION_TICKET returned also by mbedtls_ssl_write().

According to the docs I should close/reset the connection for anything but the normal return codes and this error as far as I can tell is not handled in the ssl_client2.c example for the write case. Is it ok to just ignore it if session tickets are disabled client side? (I cannot go for option 2 and disable it at build time at the moment).

**Comment by irwir** [comment]
My basic understanding of ticket handling is that server sends a ticket when a handshake had been completed successfully.
Client could store the ticket and might use it for future fast reconnects.
But only `ssl_tls13_server.c` has processing in `MBEDTLS_SSL_TLS1_3_NEW_SESSION_TICKET` state, while there is nothing in the corresponding client  module.
That server processing routine restarts (an already completed) handshaking, which is not what the client side needs.

**Comment by irwir** [comment]
After the commit 9b4e964c2cf5c8ace19bd654660a2b030e02704b  mail application could successfully connect and send an email.
