### ISSUE TITLE
cmac aes-ecb mode may give users some misunderstandings

### ISSUE THREAD

**Issue by s0ck4t7** [Mbed-TLS/mbedtls#8617]
https://github.com/Mbed-TLS/mbedtls/blob/f3ccfddb45dc964124145789e433f22d382ca5a6/library/cmac.c#L179C2-L187C6

In CMAC, only ”AES-ECB“ mode is supported, which may lead to some misunderstandings for users.
But in OpenSSL version 3.1, apart from the AES-CBC mode, all other modes have been defined as invalid modes. You can refer to the following link.
https://github.com/openssl/openssl/issues/16873

The differences between these two may potentially cause users to have some misunderstandings or confusion.

**Comment by s0ck4t7** [comment]
Hi, Thank you for your reply.
I provided the user with an example of using AES-CBC in OpenSSL, but when the user tried to implement it in mbedtls, they found that only AES-ECB mode was available. The user's intuition is that these two modes have some differences, but the obtained results are the same.

**Comment by gilles-peskine-arm** [comment]
AES-CMAC is a mode of AES. It's an implementation detail that OpenSSL's AES-CMAC implementation is constructed on top of AES-CBC, whereas Mbed TLS's AES-CMAC implementation is constructed on top of AES-ECB. It's unfortunate that this implementation detail is reflected in the API, but it's not something that can easily be changed.

The legacy `mbedtls/cmac.h` will be removed in Mbed TLS 4.0: there will only be the PSA interface, where AES-CMAC is specified as the `PSA_ALG_CMAC` algorithm with a `PSA_KEY_TYPE_AES` key.

> The user's intuition is that these two modes have some differences, but the obtained results are the same.

ECB and CBC are different. But in both cases, the user is requesting CMAC. So naturally the results are the same.

I really don't see how we could improve the documentation or the interface, apart from completely redesigning the interface which we've already done.

**Comment by bensze01** [comment]
Closing this issue, as there seems to be agreement about the way forward as to 4.0.
