### ISSUE TITLE
Add support for AES EAX mode

### ISSUE THREAD

**Issue by frkv** [Mbed-TLS/mbedtls#862]
AES EAX mode is used in Google Eddystone beacon implementation.

Relevant resources:

Main repository for eddystone:
https://github.com/google/eddystone

Explaining AES EAX-use in eddystone-tlm:
https://github.com/google/eddystone/blob/master/eddystone-tlm/tlm-encrypted.md

**Comment by iceman1001** [comment]
And here I needed this... 

I understand its not a prio.

**Comment by N1CHOLA5** [comment]
Me too...this would have been a nice simple to use encrypt + authenticate system - but since mbedtls doesnt support I guess its back to the drawing board!
