### ISSUE TITLE
Ignored return value in TLS tests

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#8621]
### Summary

Coverity flagged this issue:

in ssl_helpers.c, line 526, the return value to the call to `mbedtls_test_ssl_message_queue_pop_info()` in `mbedtls_test_mock_tcp_recv_msg()` is not checked. This would seem to me to be erroneous, especially as it returns the message length on success, but its possible that this is causing a test gap.

Given that fixing this would be a small undertaking for those with knowledge of the area, but a fairly big task for me, I am putting this in an issue.

**Comment by Harry-Ramsey** [comment]
Fixed in commit: [a9b90de6dd46b4483fd009b5bd075410dbf7b294](https://github.com/Mbed-TLS/mbedtls/commit/a9b90de6dd46b4483fd009b5bd075410dbf7b294).
