### ISSUE TITLE
mbedtls_memory_buffer_alloc_init not found

### ISSUE THREAD

**Issue by PocketPi** [Mbed-TLS/mbedtls#8631]
### Summary
When i follow or at least try to follow the guide here: https://github.com/Mbed-TLS/mbedtls-docs/blob/main/kb/how-to/using-static-memory-instead-of-the-heap.md

the following function: mbedtls_memory_buffer_alloc_init is not found when i compile. 

### System information

Mbed TLS version (number or commit id):  2fde39a22
Operating system and version:  FreeRTOS
Configuration (if not default, please attach `mbedtls_config.h`): 
/* mbed TLS feature support */
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_PKCS1_V21
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_NO_PLATFORM_ENTROPY

/* mbed TLS modules */
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_ERROR_C
#define MBEDTLS_MD_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA256_C

/* Miscellaneous options */
#define MBEDTLS_AES_ROM_TABLES

#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C

### Expected behavior
I expected the function to be found

### Actual behavior
it not found 

error: implicit declaration of function 'mbedtls_memory_buffer_alloc_init' [-Werror=implicit-function-declaration]

**Comment by bensze01** [comment]
Hi - from your description it sounds like you are missing an `#include <mbedtls/memory_buffer_alloc.h>` statement in the file you are compiling.

I'm closing this issue, but we would be happy to answer questions related to this or any other issue you encounter on our mailing list at [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org).
