### ISSUE TITLE
Improve threading tests 

### ISSUE THREAD

**Issue by yanesca** [Mbed-TLS/mbedtls#8650]
### Suggested enhancement

There are some improvements found during review of #8342 :
https://github.com/Mbed-TLS/mbedtls/pull/8342#discussion_r1431944842
https://github.com/Mbed-TLS/mbedtls/pull/8342#discussion_r1431948789
https://github.com/Mbed-TLS/mbedtls/pull/8342#discussion_r1431952285

### Justification

We would like to address these in a separate PR so that we can merge #8342 early and reduce the risk of conflicts.

**Comment by gilles-peskine-arm** [comment]
With https://github.com/Mbed-TLS/mbedtls/pull/8653, `--make-vars` is no longer needed, so we can just remove it instead of improving it.
