### ISSUE TITLE
programs/ssl/ssl_server DoS

### ISSUE THREAD

**Issue by hey3e** [Mbed-TLS/mbedtls#8694]
### Summary
Send a TLS 1.3 ClientHello without extensions cause programs/ssl/ssl_server and ssl_server2 DoS.

### System information

Mbed TLS version (number or commit id): 3.4.0 f1c032a
Operating system and version: Ubuntu 22.04.2 LTS
Configuration (if not default, please attach mbedtls_config.h): #define MBEDTLS_SSL_PROTO_TLS1_3
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): default
Additional environment information: no

### Expected behavior
Server continue the handshake or at least can not deny other handshakes.

### Actual behavior
Server deny any handshake.

### Steps to reproduce

1. For client 1, disable tls1.3 client hello extensions. In `/library/ssl_client.c`, modify `if (propose_tls13)` to `if (!propose_tls13)` then `make`. Make client 2 default.
2. `./programs/ssl/ssl_server`
3. client 1: `./programs/ssl/ssl_client2 force_version=tls13`. Handshake failed.
4. client 2: `./programs/ssl/ssl_client2 force_version=tls13` Handshake still failed.

### Additional information
Similar to issue #8654.

**Comment by yanesca** [comment]
Do you mean that you would expect the handshake to go through without extensions in the client hello?

Also, step 4. is identical to step 3., is that intentional?

**Comment by hey3e** [comment]
I can understand handshake in step 3 failed due to the lack of extensions.

However, the handshake of client 2 is correct. The handshake should not fail. Apparently the server denies service.

**Comment by yanesca** [comment]
Ah, I missed that part, now I understand, thank you for explaining.

I did the steps like that: 
1. compiled two clients, one default (client 2) and one not sending the hello extensions (client 1)
2. started the server (had to use certificate from a later version as the test certificate in 3.4.0 had already expired):
> ./programs/ssl/ssl_server2 debug_level=1 force_version=tls13 crt_file=../mbedtls/tests/data_files/server5.crt key_file=../mbedtls/tests/data_files/server5.key
3. tried to connect with the modified client (client 1)
> ./programs/ssl/ssl_client21 debug_level=1 force_version=tls13
4. finally tried to connect with the default one (client 2)
> ./programs/ssl/ssl_client22 debug_level=1 force_version=tls13

But I am getting a successful connection in step 4. Can you confirm that you can connect to the server if you skip step 3?

**Comment by hey3e** [comment]
Thanks for reply.

Yes, I repeated your steps with cert and the server still refused client 2. client 2 can connect to server if I skip step 3. Is your client 1 and client 2 on the same machine?

I saw updates in issue #8654. I believe they have some similarities.

**Comment by yanesca** [comment]
Both client 1 and client 2 are on the same machine for me.

Could you please pass `debug_level=3` to the client in step 4. and attach the outcome here in a text file?

**Comment by hey3e** [comment]
It is similar to step 3. 

[hello_extension.txt](https://github.com/Mbed-TLS/mbedtls/files/13920012/hello_extension.txt)

**Comment by hey3e** [comment]
Thanks for reproduction.

The current development head does not have this issuue.

**Comment by yanesca** [comment]
This issue was fixed in https://github.com/Mbed-TLS/mbedtls/pull/8595 (including non-regression test).
