### ISSUE TITLE
Clarify the documentation of mbedtls_pk_setup_opaque

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8712]
In the documentation of `mbedtls_pk_setup_opaque`, clarify which algorithm the functions `mbedtls_pk_{sign,verify,encrypt,decrypt}` will perform with the resulting key.

Definition of done: updated documentation, and possibly add unit tests if the documentation ends up stating things that are currently untested.

Related, but should in principle be independent: https://github.com/Mbed-TLS/mbedtls/issues/8710

**Comment by mpg** [comment]
Note: adding this to the "legacy-to-PSA migration helpers" EPIC as I think that was the intention (was on the EPICs board but not in any EPIC).
