### ISSUE TITLE
Turn off mbedtls_psa_crypto_c related macro，parse cert ERROR

### ISSUE THREAD

**Issue by huzai9527** [Mbed-TLS/mbedtls#8724]
### Summary
when i Turn off mbedtls_psa_crypto_c related macro in mbedtls_config.h, call  ` ret = mbedtls_x509_crt_parse(&cert, client_cert, client_cert_length)` will get a fault cert struct, and the function return value is 0. 

### System information

Mbed TLS version (number or commit id): 3.5.1
Operating system and version: ubuntu 22.04
Configuration (if not default, please attach `mbedtls_config.h`):  default mbedtls_config.h turn off  mbedtls_psa_crypto_c realated macro
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gcc
Additional environment information: 

### Expected behavior
Turn off crypto related macro should not enfluence x509 parse.

### Actual behavior

![image](https://github.com/Mbed-TLS/mbedtls/assets/33509974/94242d27-ffe6-4ff8-a570-41ed7588bf95)

### Additional information
![image](https://github.com/Mbed-TLS/mbedtls/assets/33509974/165afea6-687d-4152-a8c3-c18ae77e60bc)
this will be parse ok.

**Comment by daverodgman** [comment]
It looks like this may have been fixed by #7930 - please could you check?

**Comment by huzai9527** [comment]
used latest code，same error occurred.
![image](https://github.com/Mbed-TLS/mbedtls/assets/33509974/4c8f2ba2-8b39-417a-bafc-13a05c60195b)
It looks like more test case should be added. I found this error by following steps:
1. turn off configs which i don't need.
2. use the lib compiled by the new config.h.
3. parse the cert(ATTENTION: this step return no error).
4. then i try to verify cert(faild), but passed on openssl.
5. finally, i found that the parsed cert is incorrectly.

**Comment by daverodgman** [comment]
Please could you attach the cert, or (ideally) a command line to generate a cert which demonstrates this behaviour? thanks

**Comment by huzai9527** [comment]
with my pleasure. actually，when you turn off the related Marco，as this patch shows
```diff --git a/include/mbedtls/mbedtls_config.h b/include/mbedtls/mbedtls_config.h
index 6a5828c74..ebb562f48 100644
--- a/include/mbedtls/mbedtls_config.h
+++ b/include/mbedtls/mbedtls_config.h
@@ -2841,7 +2841,7 @@
  *
  * Uncomment to enable the LMS verification algorithm and public key operations.
  */
-#define MBEDTLS_LMS_C
+// #define MBEDTLS_LMS_C
 
 /**
  * \def MBEDTLS_LMS_PRIVATE
@@ -3174,7 +3174,7 @@
  *               is enabled in PSA (unless it's fully accelerated, see
  *               docs/driver-only-builds.md about that).
  */
-#define MBEDTLS_PSA_CRYPTO_C
+// #define MBEDTLS_PSA_CRYPTO_C
 
 /**
  * \def MBEDTLS_PSA_CRYPTO_SE_C
@@ -3203,7 +3203,7 @@
  *           either MBEDTLS_PSA_ITS_FILE_C or a native implementation of
  *           the PSA ITS interface
  */
-#define MBEDTLS_PSA_CRYPTO_STORAGE_C
+// #define MBEDTLS_PSA_CRYPTO_STORAGE_C
 
 /**
  * \def MBEDTLS_PSA_ITS_FILE_C
```

- then use gcc compile library
```
make clean && make lib
``` 
- write a test.c use the library, and run it
- test.c
```
#include "mbedtls/x509_crt.h"

void b(){};
int main() {
    mbedtls_x509_crt cacert;
    mbedtls_x509_crt_init(&cacert);

    int ret = mbedtls_x509_crt_parse_file(&cacert, "./any_cert.pem");
    if (ret != 0) {
        char error_buf[100];
        mbedtls_strerror(ret, error_buf, 100);
        printf("Failed to parse rootCA.pem: %s\n", error_buf);
    }

    b();
    mbedtls_x509_crt_free(&cacert);

    return 0;
}
```
```
gcc -g -L. -I. test_verify_cert.c -lmbedx509 -lmbedcrypto && ./a.out
```
- you will find a.out run with out any error, but if you use gdb break at b() and show the cacert, you will find the cert is wrong(from pk).
- gdb command
```
gdb
file a.out
b b
r
n
n
p cacert
```

**Comment by daverodgman** [comment]
I don't see the problem here. The `mbedtls_pk_context` struct has various fields which may or may not be present depending on the configuration that Mbed TLS was built with. The `priv_id` field (aka `private_priv_id`) is only supposed to be present if `MBEDTLS_USE_PSA_CRYPTO` is defined:

https://raw.githubusercontent.com/Mbed-TLS/mbedtls/development/include/mbedtls/pk.h#:~:text=%23if%20defined(MBEDTLS_USE_PSA_CRYPTO)%0A%20%20%20%20mbedtls_svc_key_id_t%20MBEDTLS_PRIVATE(priv_id)%3B%20%20%20%20%20%20/**%3C%20Key%20ID%20for%20opaque%20keys%20*/%0A%23endif%20/*%20MBEDTLS_USE_PSA_CRYPTO%20*/

You mentioned that you receive a "fault cert struct". What is the problem with the resulting `mbedtls_x509_crt` struct that you receive?

**Comment by huzai9527** [comment]
Sorry for taking up your time. I found that this problem was caused by me referencing an external header file and the header file did not correspond to the lib. This issue can be closed. Thank you so much。
