### ISSUE TITLE
X506_crt: compiler error under _WIN32 and 

### ISSUE THREAD

**Issue by MaJerle** [Mbed-TLS/mbedtls#8750]
### System information

Mbed TLS version (number or commit id): [development branch as of right now](https://github.com/Mbed-TLS/mbedtls/commit/aa3fa98bc4a99d21a973b891bf7bda9a27647068)
Operating system and version: Windows 11, _WIN32, compiled for windows
Configuration (if not default, please attach `mbedtls_config.h`): Disabled PSA and all corresponding PSA requirement too.
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): GCC 12.2 windows.
Additional environment information: None

### Expected behavior

`x509_crt.c` to compile.

### Actual behavior

It throws an error that `inet_pton` doesn't exist.

### Steps to reproduce

Just compile the X509 under windows. Solution was to manually enable `#define MBEDTLS_TEST_SW_INET_PTON` just before functions, to change which part of the code is actually compiled.

### Additional information

Part of c509_crt.c file.
```c
#ifdef _WIN32
#ifdef _MSC_VER
#pragma comment(lib, "ws2_32.lib")
#include <winsock2.h>
#include <ws2tcpip.h>
#elif (defined(__MINGW32__) || defined(__MINGW64__)) && _WIN32_WINNT >= 0x0600
#include <winsock2.h>
#include <ws2tcpip.h>
#else
/* inet_pton() is not supported, fallback to software version */
#define MBEDTLS_TEST_SW_INET_PTON
#endif
#elif defined(__sun)
/* Solaris requires -lsocket -lnsl for inet_pton() */
#elif defined(__has_include)
#if __has_include(<sys/socket.h>)
#include <sys/socket.h>
#endif
#if __has_include(<arpa/inet.h>)
#include <arpa/inet.h>
#endif
#endif

// This has been manually added...
#define MBEDTLS_TEST_SW_INET_PTON
```

**Comment by paul-elliott-arm** [comment]
Hi,

We don't have a lot of windows devs here, thus its quicker to ask you this question - defining `MBEDTLS_TEST_SW_INET_PTON` works because it brings in the software implementation, but `inet_pton` *should* be available via `ws2tcpip.h` (see https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton)

Could you check this is definitely not being included in your build?

**Comment by MaJerle** [comment]
Header finds the definition, but linker fails for some reason. Maybe a problem on my side.

Since X509 is used in embedded too, w/o necessary having TLS but rather certificate exchange and authentication, is it possible to disable this IP feature somehow?

**Comment by paul-elliott-arm** [comment]
Unfortunately inet_pton() is used to parse Subject Alternative Names for crts in `x509_crt_verify_name()` - it would be slightly involved to remove this, but admittedly not impossible, but also something we not entirely likely to do in the short term, given it was requested that we put it in. 

If you are not using Alt names in such a way, then  the software implementation would be fine for you (it would be fine either way, but its going to mean increased code size)

**Comment by MaJerle** [comment]
Thanks. Fair enough.
