### ISSUE TITLE
Better Documentation for Multipart Encryption

### ISSUE THREAD

**Issue by gauravzero** [Mbed-TLS/mbedtls#8762]
### Suggested enhancement
I was reading about **mbedtls_cipher_auth_encrypt_ext** and **mbedtls_gcm_starts** series of functions which both let me do AES GCM (256) with AEAD. I believe the difference is that the latter is multipart? I couldn't find any documentation on what this means, and what the real differences/pros/cons of using one over the other is. Could you please add this?

### Justification

Mbed TLS needs this because it would help users to understand which API to use based on their use case. Right now i'm not sure what multipart or the difference between the aforementioned APIs are.

**Comment by paul-elliott-arm** [comment]
Hi, the documentation can be found in the headers, or compiled here: https://mbed-tls.readthedocs.io/en/latest/

`mbedtls_cipher_auth_encrypt_ext()` is capable of both oneshot and multipart operation using multiple cipers - see the above documentation for the order of calls required to use this interface, this call alone is not enough. 

`mbedtls_gcm_starts()` is a much lower level function that is part of the pure GCM functionality (again see the docs for the order of function calls that have to be made, in both cases you are going to need a context, and for that context to be properly initialised)

The main difference between the two is that `mbedtls_cipher_auth_encrypt_ext()` will do much of the AEAD work for you, whereas `mbedtls_gcm_*` you will have to do parts of that yourself. 

You may also want to consider the `psa_aead_*` which also automate the job and support both oneshot and multipart, but use the PSA interface.

The usefulness of multipart over one shot occurs in various scenarios:

1. When you don't have all of the plaintext or ciphertext given to you at the same time - said data may be very large, and (for example) sent over the network in chunks.
2. When memory requirements prevent you from holding all of the plaintext / ciphertext in memory at the same time.
3. When processing all of the encryption or decryption at once would cause significant blocking of other processing, breaking this blocking  up into chunks can be desirable.

I hope this helps.

In future, this is a conversation that is probably better had on the mailing list : mbed-tls@lists.trustedfirmware.org

**Comment by gauravzero** [comment]
Hi Paul,
Thanks for the quick response, this definitely helps. I'll take a look at the header files, thanks for the lead.

Apologies on the new issue -- ill use the mailing list next time. 

I think this issue can be closed now. I'm new to this, so I'm not sure if I have to close this thread.

**Comment by paul-elliott-arm** [comment]
Not a problem, I can close this :)
