### ISSUE TITLE
Better support for PKCS#7

### ISSUE THREAD

**Issue by bengtnyman** [Mbed-TLS/mbedtls#8768]
### Suggested enhancement

We find several open tickets in the backlog for PKCS#7, preferably with CMS and CRL support. Current support in 3.5.1 is limited. Those tickets has been open for quite some time. What is the plan moving forward?

### Justification

Mbed TLS needs this because also embedded IoT devices should comply with this standard approach and a full stack is not fitting resource constrained devices.

Thank you in advance!

//Bengt

**Comment by paul-elliott-arm** [comment]
Hi,

I'm afraid that full PKCS#7 support is not going to be a priority at least in the short / medium term. The original support was contributed by an external supporter and we merely reviewed it. I would say that we would welcome PRs  for this, however they would obviously be quite large, so we would also have to find time to review them, which in the short term is going to be difficult, given we have a number of other things we need to deliver.

I understand this is probably not the answer you were looking for, and things may indeed change in the longer term, however at the moment this is the best I can offer.

**Comment by bengtnyman** [comment]
Thanks you for the answers. What other options do we have for digital signing with MbedTLS?

**Comment by paul-elliott-arm** [comment]
Whilst we don't provide anything that encapsulates digital signing like PKCS#7 does, we do provide all the basics for you to implement your own (key agreement mechanisms, both RSA and EC and a fairly comprehensive set of hash algorithms) given this is obviously an essential part of TLS. 

If the thing you are wishing to talk to insists on talking CMS, then obviously that is going to be more work, but still not impossible. If you can use your own message format then this should not be too difficult.

**Comment by bengtnyman** [comment]
Thanks agian for great guidance on how to approach the challenge. We will explore the possibility of implementing something ourselves, since we are already a heavy MbedTLS user.
