### ISSUE TITLE
Officially drop support for MSVC 2013 and 2015 in 3.6

### ISSUE THREAD

**Issue by mpg** [Mbed-TLS/mbedtls#8770]
Rationale:

- Both versions have a lifetime that's shorter than that of 3.6.
- Additionally, MSVC 2015 crashes on current development https://github.com/Mbed-TLS/mbedtls/issues/8735
- Additionally, MSVC 2013 causes issues related to `vsnprintf()` not being compliant enough.
- We've [asked on the list](https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/46KE7EQT5QVRWYMFX33UPU7LBCG46IUT/) and so far nobody as expressed and interest in those versions.

Actions:

- [x] Add a ChangeLog entry.
- [x] Update the README
- [ ] Remove the workaround used by TLS 1.3 Early Data tests of depending on !1.2 to avoid running on Windows (see https://github.com/Mbed-TLS/mbedtls/pull/8727/commits/ae2d81c314c15350484c6188995a1bac9791f3ef for example)
- [ ] Check if any hack related to old versions can now be removed?
  - Handling of `vsnprinft()` in the platform module?
  - Use of `inline`?
  - Etc. Ideally should check the output of `grep -R _MSC_VER library include`.

**Comment by mpg** [comment]
See also https://github.com/Mbed-TLS/mbedtls/pull/8725

**Comment by minosgalanakis** [comment]
This task will be split in two tasks.  The support for the older version of the compliers the Changelong and Readme, and the appropriate CI changes has been fixed as per [PR8923]( https://github.com/Mbed-TLS/mbedtls/pull/8923)

The rest of the ask ( looking into the code for workarounds for older MSCV compilers and cleaning them up) will be handled in a later ticket.
