### ISSUE TITLE
Fix release checksums in announcements

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8777]
We normally include the SHA256 checksums of release tarballs in release announcements. Each release includes four tarballs: two with the `v${version}` prefix (using the format GitHub wants for release tag names) and two with the `mbedtls-${version}` prefix (using our own format for release tag names); for each, one `.zip` and one `.tar.gz`.

Unfortunately, it seems that we're in the habit of announcing the files called `mbedtls-${version}`, but we actually provide the checksums of the `v${version}` files. Reported [on the mailing list](https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/SJED3CEXPZQ4CTC4CIAECVF27YZ6YBFF/) for the latest release.

Methodology:
```
gh release list -R https://github.com/Mbed-TLS/mbedtls | cut -f 3 >tags.txt
for x in $(<tags.txt sed 's/^v//; s/^mbedtls-//; s/.*/v& mbedtls-&/'); do wget -nc https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/$x.{tar.gz,zip}; done
for x in $(cat tags.txt); do wget -nc https://github.com/Mbed-TLS/mbedtls/releases/tag/$x -O $x.html; done
cat *.html | egrep -o '[0-9a-f]+  (v|mbedtls-)[0-9.]+\.(tar\.gz|zip)' | sha256sum -c

# List the bad release announcements
for x in *.html; do if egrep -o '[0-9a-f]+  (v|mbedtls-)[0-9.]+\.(tar\.gz|zip)' $x | sha256sum -c 2>/dev/null | grep -q FAILED; then echo ${x%.html}; fi; done
```

Output: only 2.28.5 and 3.5.0 have correct checksums!
```
v2.7.17
v2.7.18
v2.7.19
v2.16.8
v2.16.9
v2.16.10
v2.16.11
v2.16.12
v2.24.0
v2.25.0
v2.26.0
v2.27.0
v2.28.0
v2.28.1
v2.28.7
v3.0.0
v3.1.0
v3.2.0
v3.2.1
v3.3.0
v3.4.0
v3.5.1
v3.5.2
```

Goals of this issue:

* Update all the offending release announcements (list above).
* Update our release procedure to avoid this in the future.

**Comment by gilles-peskine-arm** [comment]
Alternatively, maybe checksums are a thing of the past? After all the main security control on both release announcements and tarball content is the same: HTTPS on GitHub. So maybe we should just stop providing checksums?

(Even so, we still need to fix or remove the existing wrong checksums.)

**Comment by yanesca** [comment]
The checksum provided in the release announcement is intentionally for the mbedtls tags. When we started releasing on github, we still had the website. The checksum made sense to validate the tarball downloaded from the website. Later we changed licencing and simplified the release process and simply linked github from the website. When we did this, we forgot to retire the checksum from the release announcement.

**Comment by daverodgman** [comment]
Looking at the 3.5.2 release:

The release notes for 3.5.2 said:
`35890edf1a2c7a7e29eac3118d43302c3e1173e0df0ebaf5db56126dabe5bb05 mbedtls-3.5.2.tar.gz`
The URL for the zip in the release notes is:
`https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.5.2.zip`
But if I click that URL, it downloads a file named `mbedtls-3.5.2.zip` containing a directory named `mbedtls-3.5.2`. The zip does indeed have the advertised hash `35890edf1...`

So for me, the only inconsistent part is the URL.
