### ISSUE TITLE
Make "mpi_one" array a "const" 

### ISSUE THREAD

**Issue by marmur99** [Mbed-TLS/mbedtls#8792]
### Suggested enhancement

I'm suggesting move mpi_one defined as:
`static mbedtls_mpi_uint mpi_one[] = { 1 };`
to .text section by defining it as "const".

### Justification
The way the array is currently defined, it ends up in the .data section needing initialization pre- main(). In many cases (including mine), it is the only global variable defined in libmbedtls. 
Since the content of the array is means to remain constant, it makes more sense to move it to .text section. 
It will improve memory utilization, and help with memory planning for multi-stages applications (bootrom, bootloader, firmware), where mbedtls resides in the bootrom code space, and is used by the bootloader, and/or firmware. In such scenarios, maintaining global variables is a hassle.

Mbed TLS needs this because

**Comment by tom-cosgrove-arm** [comment]
Closing as this was fixed by #8665
