### ISSUE TITLE
check_config.h should only check, not adjust

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8796]
In Mbed TLS 3.5 and still on development as of 1d7bc1ecdf04db9b137931442fd46fe278813f2b, [`check_config.h`](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/check_config.h) doesn't only perform checks but also defines helper symbols, e.g.

```
#if defined(MBEDTLS_SHA256_C) || \
    (defined(MBEDTLS_PSA_CRYPTO_C) && defined(PSA_WANT_ALG_SHA_256))
#define MBEDTLS_MD_HAVE_SHA256
#endif
```

These definitions should be in `include/config_adjust_*.h` (or `include/psa/crypto_adjust_*.h` if defining a `PSA_WANT` symbol, but there are no instances of that at the moment). Having them in `check_config.h` is a problem because:

* It's surprising to maintainers (it's unexpected that “check” can change things).
* It may cause bugs because the symbols are defined after some other place that consumes them. I don't know if any of the symbols currently defined in `check_config.h` are affected, but it has been a problem in the past, which led to the creation of the `adjust` headers with a carefully planned inclusion order. See https://github.com/Mbed-TLS/mbedtls/issues/7609, https://github.com/Mbed-TLS/mbedtls/pull/8159.
* It relies on `check_config.h` being always included, which [is something we're planning to stop](https://github.com/Mbed-TLS/mbedtls/issues/8105) (though this won't happen in 3.x, and in 4.0 many of the auxiliary symbols will be obsolete).

**Comment by mpg** [comment]
> * It's surprising to maintainers (it's unexpected that “check” can change things).

Note: those symbols were `#undef`ed near the end of the file. Which I think mostly addresses the other points as well.

I'd still like to clean that up, because it was surprising to both of us, which is not a good sign. Also, the macros `MD_HAVE` were actually redundant with `MD_CAN` macros defined in `config_adjust_legacy_crypto.h`.
