### ISSUE TITLE
Bad SHA3 performance with GCC

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8819]
It seems that GCC is pretty bad at optimizing our SHA3 code: it's between 2× and 3× slower than Clang. Here's `programs/test/benchmark sha3_256` built with `gcc-11 -O3` on my Linux/x86_64 computer:
```
  SHA3-256                 :     118404 KiB/s,         22 cycles/byte
```

Compare with `clang-14 -O3` on the same machine:
```
  SHA3-256                 :     241472 KiB/s,         10 cycles/byte
```

There's a similar ratio with `-m32`. @dave-rodgman reports a similar difference on armv8 M1. Dave looked into it a bit and found that clang doesn't autovectorize `keccak_f1600` whereas GCC does a bit, but turning off auto-vectorization only improves by 10% so that's not the main cause.

With other algorithms, Clang and GCC are within 5% or so of each other. So there seems to be something specific in our SHA3 that GCC doesn't optimize well.

**Comment by daverodgman** [comment]
In short: I think the difference is mostly due to clang being more aggressive about unrolling loops. Manually unrolling some of the loops tends to help gcc close the gap (although both benefit).
