### ISSUE TITLE
LTS support policy documentation

### ISSUE THREAD

**Issue by chenrui333** [Mbed-TLS/mbedtls#8828]
### Suggested enhancement

👋 I just saw there is this note for the most recent [Mbed TLS 2.28.x](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.7) release, my question is if there is any release policy doc to reference to the LTS release line in general? Thanks!

### Justification

Mbed TLS needs this because it helps downstream consumption of Mbed TLS project.

**Comment by tom-daubney-arm** [comment]
Hello, I am not 100% sure what you're asking for here. Does the information in: https://github.com/Mbed-TLS/mbedtls/blob/development/BRANCHES.md answer your question?

**Comment by tom-daubney-arm** [comment]
I am closing the issue now. Feel free to reopen if you feel there is a bug to report here.
