### ISSUE TITLE
Deprecate or remove mbedtls_pk_wrap_as_opaque

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8848]
Deprecate `mbedtls_pk_wrap_as_opaque`. It is subsumed by `mbedtls_pk_import_into_psa` introduced by https://github.com/Mbed-TLS/mbedtls/issues/8708.

Do one of the following:

* Mark `mbedtls_pk_wrap_as_opaque` as formally deprecated, but keep it. This requires mostly stopping using it in tests, since test code can't use deprecated functions to test non-deprecated functions.
* Remove `mbedtls_pk_wrap_as_opaque` completely. This requires stopping using it in tests.
* Remove `mbedtls_pk_wrap_as_opaque` from public headers. Keep it around for testing, to be cleaned up in a follow-up which can happen even on an LTS branch.

~Depends on #8710 (PR #8842).~

**Comment by valeriosetti** [comment]
I suspect that @mpg feedback is required here in order to determine which of the 3 suggested options should be implemented.

**Comment by gilles-peskine-arm** [comment]
Removing from public headers is the easiest, so it'll be our fallback if we run out of time.
