### ISSUE TITLE
Make psa_crypto_transaction thread safe

### ISSUE THREAD

**Issue by paul-elliott-arm** [Mbed-TLS/mbedtls#8849]
### Suggested enhancement

The global variable `psa_crypto_transaction` requires protection in order to be thread safe.

Add a new global mutex (although this could potentially be the same mutex as #8425, however I suspect this may complicate the task here, as well as potentially that one) and make sure that every function accessing or modifying the `psa_crypto_transaction` variable in psa_crypto_storage.c takes that mutex. 

The functions should take the mutex in a way that the consistency of the whole structure is guaranteed - one potential approach here would be to make the variable static, and add accessors.

The task is complete when the above described mutex and protection is added along with multi-threaded unit tests to ensure this (test with TSAN).

**Comment by Ryan-Everett-arm** [comment]
During team discussion we have decided to not make this variable thread-safe. `psa_crypto_transaction` is part of the deprecated `MBEDTLS_PSA_CRYPTO_SE_C` driver interface. This has been replaced by a new, thread-safe, PSA driver interface. [This PR](https://github.com/Mbed-TLS/mbedtls/pull/8891) documents the decision.
