### ISSUE TITLE
Nonstandard extension - zero-sized array in struct/union

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#8866]
https://github.com/Mbed-TLS/mbedtls/blob/09e6fb42eb8862bdec04adac0c34046f13dc6f65/include/psa/crypto_struct.h#L229
Warning C4200  for this line in Visual Studio 2022  - `nonstandard extension used: zero-sized array in struct/union`.

**Comment by tom-cosgrove-arm** [comment]
This is a flexible array member, a perfectly fine part of standard C99:

> As a special case, the last element of a structure with more than one named member may
have an incomplete array type; this is called a flexible array member.

The issue here is with Visual Studio 2022

**Comment by gilles-peskine-arm** [comment]
AFAIK Visual Studio does support flexible array members, and it didn't complain about them in our CI builds which go back to VS2013. Please make sure that you compile in a C99 or C11 mode, not C90 mode.

**Comment by irwir** [comment]
Microsoft also says:
> This causes a Level-2 warning when a C++ file is compiled and a Level-4 warning when a C file is compiled.

CI should not complain because of the level 4.
For me this was compiled as a part of C++ solution, and I usually prefer to see more warnings.

Closing the issue since this is valid in C99 and not an MS extension.

**Comment by SadieCat** [comment]
We're getting this issue on Clang as a library user.

```
 /opt/homebrew/include/psa/crypto_struct.h:229:13: fatal error: flexible array members are a C99 feature [-Wc99-extensions]
    uint8_t data[];
            ^
1 error generated.
```

This C feature was not included when C99 was merged into the C++ spec. This means if you are using mbedTLS from a C++ project you need to compile with non-portable vendor extensions to use mbedTLS.

https://en.wikipedia.org/wiki/Flexible_array_member#Availability

**Comment by tom-cosgrove-arm** [comment]
Hmm, these definitions should be inside `extern "C"` to avoid exactly this

**Comment by irwir** [comment]
[extern "C" and extern "C++" function declarations](https://learn.microsoft.com/en-us/cpp/cpp/extern-cpp?view=msvc-170&devlangs=cpp&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk%28extern_CPP%29%3Bk%28extern%29%3Bk%28DevLang-C%252B%252B%29%3Bk%28TargetOS-Windows%29%26rd%3Dtrue#extern-c-and-extern-c-function-declarations)
Literally, it seems the declaration allows C calling convention, not C syntax or language extenstions.

**Comment by gilles-peskine-arm** [comment]
> This C feature was not included when C99 was merged into the C++ spec in C++11.

Ah, that is a problem that I was no aware of.

> https://en.wikipedia.org/wiki/Flexible_array_member#Availability

> > Flexible array members are not officially part of C++

Hmm, is this up-to-date? https://en.cppreference.com/w/cpp/language/array (which is usually accurate in my experience, but I'm a C programmer, not a C++ programmer) suggests that `uint8_t data[];` is syntactically valid, and the section “Arrays of unknown bound” suggests that it's a valid incomplete type. Can an experienced C++ programmer please let me know what the situation is here? How do C++ programs typically consume C headers that define structures with flexible array members?
