### ISSUE TITLE
Create mbedtls-framework repository

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8879]
Create and seed a repository https://github.com/Mbed-TLS/mbedtls-framework (similar to https://github.com/gilles-peskine-arm/mbedtls-framework):

* Default branch: `main` (let's be modern)
* Same access permissions as https://github.com/Mbed-TLS/mbedtls.
* Description" TF-PSA-Crypto and Mbed TLS version-independent build and test framework", also create a minimal readme file
* Same license (Apache 2 + GPL 2+) as Mbed TLS (copy `LICENSE`) (my prototype has an automatically created incomplete `LICENSE`)

**Comment by daverodgman** [comment]
https://github.com/Mbed-TLS/mbedtls-framework/ created

**Comment by gilles-peskine-arm** [comment]
- [x] Repository created
- [x] Meaningful description
- [x] Same access permissions
- [x] `main` branch and all tags protected
- [x] `LICENSE` populated with Apache+GPLv2+
- [x] Relevant labels copied from `mbedtls`
- [x] DCO check set up but `dco.txt` missing. Tracked in https://github.com/Mbed-TLS/mbedtls-framework/issues/1.

I can't think of anything else that's required for the creation of the repository so I'm closing this issue.
