### ISSUE TITLE
Adapt the release process to cover the framework submodule

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8881]
Adapt the release process to account for the existence of a submodule in versions of Mbed TLS starting with 3.6. (Also applies to TF-PSA-Crypto.) See https://github.com/Mbed-TLS/mbedtls/issues/8880 regarding the creation of the submodule.

Since `git archive` ignores submodules, this means we need to make our own archives (which we want to do for other reasons anyway: [confusion over directory names](https://github.com/Mbed-TLS/mbedtls/issues/8777), non-stability of the archives automatically generated by GitHub).

**Comment by minosgalanakis** [comment]
The easiest way to do so is use the extended and maintained version of git archive, available in pypi as [git-archive-all ](https://pypi.org/project/git-archive-all/). It is under an [MIT license](https://github.com/Kentzo/git-archive-all/tree/master) so we could even modify it if needed in the future. 

I have confirmed that the following workflow works

~~~~~
git clone git@github.com:Mbed-TLS/mbedtls.git mbedtls && cd mbedtls
git checkout $RELEASE_TAG
git-archive-all --prefix $RELEASE-PREFIX --force-submodules mbedtls_super_release.tar.gz
sha256sum mbedtls_super_release.tar.gz > sha256_sum.txt
~~~~~

And it is small enough to be installed only on the executor as part of the release script, so we shouldn't even have to add it as a dependency.

**Comment by minosgalanakis** [comment]
As of today 11/03/2024 there is no official way to disable github autogenerated files -> [discussion](https://github.com/orgs/community/discussions/6003).

As a workaround we should be:

1. Creating prefixed releases e.g mbedtls-v3.6-lts.tar.bz2
2. Adding a note to inform users about the source.zip & source.tar.gz being automatically generated and not containing the full codebase.

**Comment by minosgalanakis** [comment]
The proccess has been updated and is under review at [confuence](https://confluence.arm.com/display/CESW/Shift+2)
