### ISSUE TITLE
Pass the readthedocs CI with the framework submodule

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8885]
Definition of done: our readthedocs CI job is capable of testing an Mbed TLS pull request or branch that has the framework submodule introduced per https://github.com/Mbed-TLS/mbedtls/issues/8880.

Definition of done: pretty much, https://github.com/Mbed-TLS/mbedtls/pull/8877 passing the readthedocs job.

**Comment by davidhorstmann-arm** [comment]
This is working in #8886, feel free to cherry-pick the change from there, or I can push it to #8880.

**Comment by gilles-peskine-arm** [comment]
Thanks! I'll cherry-pick the commit.
