### ISSUE TITLE
mbedtls_entropy_free not checking for NULL context

### ISSUE THREAD

**Issue by Roytak** [Mbed-TLS/mbedtls#8915]
Hi,

I am using mbedtls-3.5.2. Every mbedtls_XXX_free() API function I came across checks for NULL parameter (just like `free()` does), however, `mbedtls_entropy_free` does not. Is there a reason for this?

In my code both the client and server share the same dynamically allocated ctr_drbg and entropy structs (not sure if this is the correct approach though). At the end of a session both of them try to free these structs and whoever does first sets them to NULL, which works well with `mbedtls_ctr_drbg_free()`, but not as much with `mbedtls_entropy_free()`. That is where I ran into this issue.

**Comment by gilles-peskine-arm** [comment]
The fact that `mbedtls_xxx_free(NULL)` works isn't documented, but since it already works for most functions (including low-level crypto modules like `mbedtls_aes_free` and `mbedtls_sha256_free`), I agree that it should work for all of them. I can't think of a good reason for `mbedtls_entropy_free` to be an exception. (There are a couple more — `grep -E -A4 '^void mbedtls_\w+_free\(' library/*.c` .)

**Comment by Troy-Butler** [comment]
Hi, would you mind assigning this task to me?

**Comment by Troy-Butler** [comment]
You're welcome! Do I need to include a changelog for this?

**Comment by gilles-peskine-arm** [comment]
Hmmm, I'm not sure. Generally, we do want a changelog entry for something that a user cared about enough to raise an issue. On the other hand, I'm uncomfortable announcing a feature in a changelog entry if it isn't something that we do guarantee. I think if there's a changelog entry, there should be a test. But then we'd want to test all the existing functions, which is a lot of work compared to just adding a check in a couple of library functions. I'll solicit a third opinion.

**Comment by Troy-Butler** [comment]
Ok. I'll hold off until I hear back from you.

**Comment by mpg** [comment]
I'm inclined to say no ChangeLog entry (as exception to the usual rules about user requests). I agree that we shouldn't announce it without testing it, and I don't think we want to start testing every single free function at this point.
