### ISSUE TITLE
if mbedtls can support other certs policy？

### ISSUE THREAD

**Issue by LubanTech1** [Mbed-TLS/mbedtls#8935]
### Suggested enhancement

When I use mbedtls to parse a certificate, mbedtls returns an error if the certificate policy is 2.23.146.1.2.1.3. Does mbedtls support the certificate policy field?

### Justification

Mbed TLS needs this because 
Many commercial certificates use the certificate policy field. If mbedtls supports only the any policy, mbedtls is not universal.

**Comment by gilles-peskine-arm** [comment]
I don't understand what you're asking. Can you please clarify?

Mbed TLS can parse certificates that contain the [certificate policies extension](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.4). But Mbed TLS itself doesn't know about policies. By default, certificates containing anything other than `anyPolicy` are rejected. To allow certificates with a policy, you need to provide a callback function that decides whether the policy is met. Call [`mbedtls_x509_crt_parse_der_with_ext_cb`](https://mbed-tls.readthedocs.io/projects/api/en/v3.5.2/api/file/x509__crt_8h/#_CPPv438mbedtls_x509_crt_parse_der_with_ext_cbP16mbedtls_x509_crtPKh6size_ti25mbedtls_x509_crt_ext_cb_tPv). The [callback](https://mbed-tls.readthedocs.io/projects/api/en/v3.5.2/api/file/x509__crt_8h/#_CPPv425mbedtls_x509_crt_ext_cb_t) should return 0 if the policy is met and a negative value (e.g. `MBEDTLS_ERR_X509_INVALID_EXTENSIONS`, or a value that's different from any `MBEDTLS_ERR_xxx` if you prefer) if the policy is not met. You can find an example callback `parse_crt_ext_cb()` in `tests/suites/test_suite_x509parse.function`.

**Comment by LubanTech1** [comment]
Thank you for your reply. But，My service uses a certificate whose policy_oid is not ANY_POLICY during SSL link establishment. The x509_get_certificate_policies function returns an error when determining that policy_oid is not MBEDTLS_OID_ANY_POLICY. How should I deal with this situation?

**Comment by gilles-peskine-arm** [comment]
You need to write a callback to handle the `CERTIFICATE_POLICIES` extension, like [this](https://github.com/Mbed-TLS/mbedtls/blob/v3.5.2/tests/suites/test_suite_x509parse.function#L318).

**Comment by gilles-peskine-arm** [comment]
@fargiolas You need to tell the TLS layer to pass the extension callback to the X.509 layer. Unfortunately [this is not implemented](https://github.com/Mbed-TLS/mbedtls/issues/7182). There's a [patch for it](https://github.com/Mbed-TLS/mbedtls/pull/7846), which we could even potentially add to the 3.6 long-time support branch if there's demand, but it's currently blocked because it's missing tests.

**Comment by fargiolas** [comment]
@gilles-peskine-arm Thank you. My question was mostly to be sure I wasn't overlooking an already existing functionality. Will follow the other issue and the pull request. I think it would be a nice addition to the existing callback feature as there is no way at the moment to complete an handshake if server certificate has a policy field.
