### ISSUE TITLE
Python libraries to generate wrapper code for PSA functions

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8961]
Write generic Python libraries that can be used to generate wrapper code for PSA functions. We intend to use them for several purposes:

* Generate driver wrappers (replacing the current implementation using Jinja2 templates)
* Generate client-side and server-side IPC code to test client-server usage
* Tracing helpers
* etc.

----

We have merged the core libraries as part of a security fix:

* [`c_wrapper_generator.py`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/scripts/mbedtls_dev/c_wrapper_generator.py) to generate wrapper functions;
* [`c_parsing_helper.py`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/scripts/mbedtls_dev/c_parsing_helper.py) to list PSA API functions;
* Some code in [`generate_psa_wrappers.py`](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/tests/scripts/generate_psa_wrappers.py) should be lifted out into a new module: methods like `_detect_buffer_parameters` will be needed for the client-server stub generator, whereas `poison` stuff will not be.

As part of the security fix, we only reviewed the output of the generator, not the generator code (which was only reviewed for non-harmfulness, not for correctness and maintainability). As a consequence, the goals of this task are:

1. Review `c_wrapper_generator.py` and `c_parsing_helper.py`.
2. Extract the code from `tests/scripts/generate_psa_wrappers.py` that's generically useful for all PSA wrapper code into a new module and review it fully.

**Comment by minosgalanakis** [comment]
This issue has been resolved with [Framework PR#25](https://github.com/Mbed-TLS/mbedtls-framework/pull/25)
