### ISSUE TITLE
PSA client-server: run unit tests

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#8966]
Definition of done:

* We can run `make test` on a PSA client-only build in the `full` configuration minus threads, with a PSA crypto server connected through psasim, and everything passes.
* The test suite has no dependencies on `MBEDTLS_PSA_CRYPTO_C`, only on `MBEDTLS_PSA_CRYPTO_CLIENT`, except in places where we have explicitly concluded that the code doesn't make sense on a client-server build.

This issue is very large and should be broken down. Further study is required to break it down: we pretty much need to have the client-server mechanism and see how it goes when running the tests. There will likely be an intermediate stage where we only run certain test suites or even only certain test functions.

Prerequisites: https://github.com/Mbed-TLS/mbedtls/issues/8965, https://github.com/Mbed-TLS/mbedtls/issues/8968

**Comment by tom-cosgrove-arm** [comment]
How does "This issue is very large and should be broken down. Further study is required to break it down" track with `size-m`?

**Comment by gilles-peskine-arm** [comment]
`size-m` is my gut feeling, but we need to see test results to have a better idea. It might end up being smaller if driver-only has already solved all the problems except RSA. Or it might end up being larger if there are lots of different problems.
