### ISSUE TITLE
mbedtls 3.6.0: submodule framework not found

### ISSUE THREAD

**Issue by Schamschula** [Mbed-TLS/mbedtls#8993]
### Summary
While updating the MacPorts Portfile for mbedtls3 to version 3.6.0, I encountered the following error during the configuration stage:

> -- Found Threads: TRUE  
> CMake Error at CMakeLists.txt:287 (message):
>   
>   /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.0/framework/CMakeLists.txt
>   not found.  Run `git submodule update --init` from the source tree to fetch
>   the submodule contents.
> 
> 
> -- Configuring incomplete, errors occurred!

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: 
macOS 13.6.6 22G630 arm64
Xcode 15.2 15C500b
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
clang version 15.0.7
Target: arm64-apple-darwin22.6.0
Additional environment information: 

### Expected behavior
Complete package

### Actual behavior
Missing subdirectory

### Steps to reproduce
Download, extract, run cmake

### Additional information
This did not happen with the previous release.

**Comment by tom-cosgrove-arm** [comment]
From Mbed TLS version 3.6 onwards, Mbed TLS requires https://github.com/Mbed-TLS/mbedtls-framework as a submodule.

As per the error message, this requires running

```
git submodule update --init
```

After checking out version 3.6 or above

**Comment by tom-cosgrove-arm** [comment]
> **Steps to reproduce**
> Download, extract, run cmake

I suspect you did not actually download the release.

If you go to the release page at https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0 and download the release asset mbedtls-3.6.0.tar.bz2 from the bottom, you don't get this problem:

```
macbook $ curl -LO https://github.com/Mbed-TLS/mbedtls/releases/download/v3.6.0/mbedtls-3.6.0.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4698k  100 4698k    0     0  4769k      0 --:--:-- --:--:-- --:--:-- 9106k
mackbook $ tar xfz mbedtls-3.6.0.tar.bz2
macbook $ cd mbedtls-3.6.0
neo $ make
  CC    aes.c
  CC    aesni.c
:
: etc
```
```

**Comment by Schamschula** [comment]
I used the same script for prior versions before.  It downloaded

`https://github.com/ARMmbed/mbedtls/archive/mbedtls-3.6.0/mbedtls-3.6.0.tar.gz`

**Comment by Schamschula** [comment]
Downloading from GitHub tags is deprecated under MacPorts. I just tried downloading using the tarball option: same result.

**Comment by tom-cosgrove-arm** [comment]
That script has downloaded an artefact created by GitHub from the release tag, not the release asset we uploaded and that I pointed you at

**Comment by tom-cosgrove-arm** [comment]
You need to figure out how to get MacPorts to download the asset we have uploaded, not one generated by GitHub - this is not something we can help with; you should probably ask MacPorts.

To be clear: yes, you'll need to get the submodule if you checkout from git or download something generated by GitHub.

You will not have this problem if you download the release asset we have created and put at the bottom of our release page

**Comment by Schamschula** [comment]
I had missed the GitHub user name and the directory prefix had changed. Also needed to switch to the .bz2 file.
