### ISSUE TITLE
[ARM] bignum multiplication improvement

### ISSUE THREAD

**Issue by pjbakker** [Mbed-TLS/mbedtls#9]
MULADDC_CORE can be improved for ARM.

I am using PolarSSL's rsa.c for 2048-bit key with STM32F103 processor.
It takes 1.78 second to sign in current implementation.
With this change, it takes 1.72 second.

Please see attached patch.
https://gist.github.com/4079268

Tomstdenis:
ARMv4 TDMI and ARMv5 up support much more efficient multiplication. You may want to look into that. From a practical standpoint new devices are V5 or higher anyways so supporting V4 and below is kinda archaic.

We could help you speed up your math lib. We have an ARM A9 to profile on as well.

**Comment by clemensg** [comment]
Hi,

would be nice to leverage the NEON instructions like `VMUL` on Cortex-A8, Cortex A-9 and upwards.
I discovered the following paper: [Fast Software Polynomial Multiplication on ARM Processors Using the NEON Engine](http://link.springer.com/chapter/10.1007%2F978-3-642-40588-4_10#page-1)
Luckily, the preprint is freely available on the authors site: [Link to PDF](http://conradoplg.cryptoland.net/files/2010/12/mocrysen13.pdf)
(Source code: http://conradoplg.cryptoland.net/software/ecc-and-ae-for-arm-neon/)

What do you think about this approach of using the [Karatsuba algorithm](https://en.wikipedia.org/wiki/Karatsuba_algorithm) and implementing it with NEON instructions?

**Comment by mpg** [comment]
Looks nice, thanks for the links! We'll study that and hopefully integrate something along these lines in a future version. Unfortunately I can't make any promises as to when.
