### ISSUE TITLE
Redefinition warnings depending on available curves

### ISSUE THREAD

**Issue by mschulz-at-hilscher** [Mbed-TLS/mbedtls#9029]
### Summary

Compiling without SECP192R1 leads to warnings during compilation.

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: Linux 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Configuration (if not default, please attach `mbedtls_config.h`): `//#define MBEDTLS_ECP_DP_SECP192R1_ENABLED`
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

No compiler warnings.

### Actual behavior

```
suites/test_suite_pk.function:139: warning: "MBEDTLS_TEST_PSA_ECC_ONE_CURVE_BITS" redefined
  139 | #define MBEDTLS_TEST_PSA_ECC_ONE_CURVE_BITS 256
      |
suites/test_suite_pk.function:74: note: this is the location of the previous definition
   74 | #define MBEDTLS_TEST_PSA_ECC_ONE_CURVE_BITS 224
```

### Steps to reproduce

Deactivate SECP192R1 in mbedtls_config.h:

```
//#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
```

**Comment by gilles-peskine-arm** [comment]
Oh, oops, the logic is wrong when secp192k1 is enabled but secp192r1 is disabled. (Getting a compilation error rather than mysterious test failures if I got the logic wrong was on purpose.)
