### ISSUE TITLE
[RSA2048-PSS ] mbedtls and openssl failed to verify signature generate by each other

### ISSUE THREAD

**Issue by thanhlev** [Mbed-TLS/mbedtls#9032]
### Summary

1. Used Openssl to generate private and public key

```shell
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out privkey.pem
openssl rsa -pubout -in privkey.pem -out pubkey.pem

``` 

2. Generate hash256 digest using openssl

- Generate

```shell
openssl dgst -sha256 -binary -out digest_256.bin raw_data.txt
``` 

- Raw data

```shell
cat raw_data.txt

this is raw data
```

- Digest info

```shell
00000000  c0 48 6f 7e 2e 5d bc cc  65 27 83 5b 7d be b6 b8  |.Ho~.]..e'.[}...|
00000010  74 fe bc 7c 4a a3 ac 5d  dd 5b 2f 8d 8f fb 69 4c  |t..|J..].[/...iL|
00000020
```

3. Sign the hash data

```shell
openssl dgst -sha256 \
        -sigopt rsa_padding_mode:pss \
        -sigopt rsa_pss_saltlen:-1 \
        -sign privkey.pem  -binary -out raw_data.txt.sig digest_256.bin
```
4. Verify using openssl

```shell
openssl dgst -sha256 \
    -sigopt rsa_padding_mode:pss \
    -sigopt rsa_pss_saltlen:-1 \
    -signature raw_data.txt.sig \
    -verify pubkey.pem  digest_256.bin

Verified OK
```
5. Verify using `rsa_verify_pss` in mbedtls/programs/pkey

```shell

./rsa_verify_pss pubkey.pem raw_data.txt

. Reading public key from 'pubkey.pem'
  . Verifying the RSA/SHA-256 signature failed
  ! mbedtls_pk_verify returned -17280
```
6. If I sign the hash by `rsa_sign_pss` then I can verify using above command
7. Openssl also failed to verify the signature generate by `rsa_sign_pss`

```shell
Verification failure
40C7F18286790000:error:02000068:rsa routines:RSA_verify_PKCS1_PSS_mgf1:bad signature:../crypto/rsa/rsa_pss.c:132:
40C7F18286790000:error:1C880004:Provider routines:rsa_verify:RSA lib:../providers/implementations/signature/rsa_sig.c:815:
```

### System information

Mbed TLS version (number or commit id): v3.6.0
Operating system and version: Linux pc 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux 
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): cd mbedtls && make -j12
Additional environment information: Openssl version : OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

### Expected behavior
mbedtls and openssl are able to verify the signature generate by each other (RSA-PSS)

### Actual behavior
mbedtls and openssl are only able to verify signature generated by it self

### Steps to reproduce
1. Used Openssl to generate private and public key

```shell
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out privkey.pem
openssl rsa -pubout -in privkey.pem -out pubkey.pem

``` 

2. Generate hash256 digest using openssl

- Generate

```shell
openssl dgst -sha256 -binary -out digest_256.bin raw_data.txt
``` 

- Raw data

```shell
cat raw_data.txt

this is raw data
```

- Digest info

```shell
00000000  c0 48 6f 7e 2e 5d bc cc  65 27 83 5b 7d be b6 b8  |.Ho~.]..e'.[}...|
00000010  74 fe bc 7c 4a a3 ac 5d  dd 5b 2f 8d 8f fb 69 4c  |t..|J..].[/...iL|
00000020
```

3. Sign the hash data

```shell
openssl dgst -sha256 \
        -sigopt rsa_padding_mode:pss \
        -sigopt rsa_pss_saltlen:-1 \
        -sign privkey.pem  -binary -out raw_data.txt.sig digest_256.bin
```
4. Verify using openssl

```shell
openssl dgst -sha256 \
    -sigopt rsa_padding_mode:pss \
    -sigopt rsa_pss_saltlen:-1 \
    -signature raw_data.txt.sig \
    -verify pubkey.pem  digest_256.bin

Verified OK
```
5. Verify using `rsa_verify_pss` in mbedtls/programs/pkey

```shell

./rsa_verify_pss pubkey.pem raw_data.txt

. Reading public key from 'pubkey.pem'
  . Verifying the RSA/SHA-256 signature failed
  ! mbedtls_pk_verify returned -17280
```

**Comment by lidapeng-qv** [comment]
@thanhlev I also encountered the same problem. How did you solve it?
