### ISSUE TITLE
Using PSA Crypto without updating the git commit tree of mbedtls submodule 

### ISSUE THREAD

**Issue by Harshal5** [Mbed-TLS/mbedtls#9036]
### Suggested enhancement

Currently, we are using `mbedtls` as a submodule in our project and we use the ALT approach to support our hardware crypto accelerators. We were investigating the changes that would be needed to migrate to mbedtls' PSA crypto approach, and as I understand from the [example readme](https://github.com/Mbed-TLS/mbedtls/blob/development/docs/psa-driver-example-and-guide.md#process-for-entry-points-where-auto-generation-is-not-implemented), it seems that we need to plug in our psa driver function calls in the `psa_crypto_driver_wrappers.h` file under our decided macro. Is my understanding correct? 

If so, this calls for adding changes in our `mbedtls` submodule. Just wanted to confirm if there could be a way in which we can externally plug the driver dispatch layer to avoid any changes in the `mbedtls` submodule. What would you suggest?

**Comment by gilles-peskine-arm** [comment]
We have a script to generate driver wrappers from a JSON description (`scripts/generate_driver_wrappers.py`), but that script currently only supports a very small set of functions (import, generate key, sign/verify). Unfortunately the development of this script is currently blocked due to a lack of resources.

**Comment by Harshal5** [comment]
@gilles-peskine-arm
Thanks for the quick reply!

> but that script currently only supports a very small set of functions (import, generate key, sign/verify).

Does this mean that once the script fully supports all the functions, the driver dispatch layer can be kept outside the mbedtls submodule?

**Comment by gilles-peskine-arm** [comment]
Yes, once we finish that script you'll be able to build Mbed TLS with third-party drivers without having to change any file in the mbedtls subtree.

**Comment by Harshal5** [comment]
Got it! Okay, so I think we will need to proceed by maintaining some patches in our `mbedtls` submodule as of now.

Thanks!
