### ISSUE TITLE
mbedtls hangs after NewSessionTicket

### ISSUE THREAD

**Issue by orangepizza** [Mbed-TLS/mbedtls#9039]
### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: openwrt, https://github.com/openwrt/openwrt/pull/15092
Configuration (if not default, please attach `mbedtls_config.h`): 
[mbedtls_config.h.txt](https://github.com/Mbed-TLS/mbedtls/files/15026160/mbedtls_config.h.txt)

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gcc 11
Additional environment information: 

### Expected behavior
read call returns after NewSessionTicket, so client can process it

### Actual behavior
it hangs somewhere between ssl_tls13_handle_hs_message_post_handshake() which sets return code MBEDTLS_ERR_SSL_WANT_READ
and mbedtls_ssl_read(which should made debug log at ssl_msg.c line 5867) and hangs until timeout.

### Steps to reproduce
try to handshake at TLS1.3 server as client 

### Additional information
full lv4 log of failed connection :
[test.txt](https://github.com/Mbed-TLS/mbedtls/files/15026290/test.txt)

**Comment by waleed-elmelegy-arm** [comment]
Hi @orangepizza 
Can you share with me the commands you used to reproduce this issue? I tried a TLS 1.3 connection to google.com like you did in the log but I can't seem to reproduce the issue I get a successful connection, Thanks.

**Comment by orangepizza** [comment]
> Hi @orangepizza Can you share with me the commands you used to reproduce this issue? I tried a TLS 1.3 connection to google.com like you did in the log but I can't seem to reproduce the issue I get a successful connection, Thanks.

I'm just using normal uclient-fetch there without any flag given, but real Problem is I surely don't know full reproduction conditions: it never been reproducible from others

**Comment by waleed-elmelegy-arm** [comment]
Can you try using ssl_client2 in programs with your setup to see if the problem still exists? Thanks.

**Comment by orangepizza** [comment]
tests it and it didn't had so I guess it's something from openwrt side:

**Comment by orangepizza** [comment]
tests it and it didn't had so I guess it's something from openwrt side:
