### ISSUE TITLE
mbedtls_md_hmac does not work as expected on Mac M2

### ISSUE THREAD

**Issue by disa6302** [Mbed-TLS/mbedtls#9059]
### System information

Mbed TLS version (number or commit id): v2.28.5
Operating system and version: Mac M2
Configuration (if not default, please attach `mbedtls_config.h`): [config_mbedtls.txt](https://github.com/Mbed-TLS/mbedtls/files/15123631/config_mbedtls.txt)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): Using External_Project:

```
cmake_minimum_required(VERSION 3.6.3)

project(libmbedtls-download NONE)

include(ExternalProject)

if (BUILD_STATIC_LIBS)
  set(BUILD_SHARED 0)
else()
  set(BUILD_SHARED 1)
endif()

if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  set(CMAKE_MACOSX_RPATH 1)
else()
  set(CMAKE_MACOSX_RPATH 0)
endif()

message(STATUS "C flags here are ${CMAKE_C_FLAGS}")

ExternalProject_Add(
  project_libmbedtls
  GIT_REPOSITORY  https://github.com/ARMmbed/mbedtls.git
  GIT_TAG         v2.28.5
  PREFIX          ${CMAKE_CURRENT_BINARY_DIR}/build
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${OPEN_SRC_INSTALL_PREFIX}
    -DUSE_SHARED_MBEDTLS_LIBRARY=${BUILD_SHARED}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_MACOSX_RPATH=${CMAKE_MACOSX_RPATH}
    -DENABLE_TESTING=OFF
    -DENABLE_PROGRAMS=OFF
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  BUILD_ALWAYS    TRUE
  TEST_COMMAND    "")
```

Additional environment information: 

### Expected behavior

`mbedtls_md_hmac(mbedtls_md_info_from_type(MBEDTLS_MD_SHA256), key, keyLen, message, messageLen, outBuffer)` returns the SHA256 related info

### Actual behavior

The md_info returned is NULL.

### Steps to reproduce:

I added some debug in my fork branch to understand the behavior. Weirdly, when I invoke `mbedtls_md_info_from_type(MBEDTLS_MD_SHA256)` , I added a debug inside this function by forking this repository to print `md_type` value and it prints it out as 4 instead of 6. Even if I pass 6, it displays it as 4, which seems strange. I am not sure if there is some multithreading issue happening here. This also happens within a specific function only in my application. If I run the same  thing at the start of the application, the value seems correct -> indicating the appropriate `#define MBEDTLS_SHA256_C` is set up. But as the application progresses in running, the value seems to be set to 4 (`SHA1`).

The same code runs fine on Ubuntu 22.04. The problem seems to be only in Mac M2. I recall it working on M1 too earlier. If there are some mbedtls logs that would help, could you let me know how I could enable them?

**Comment by gilles-peskine-arm** [comment]
> But as the application progresses in running, the value seems to be set to 4 (SHA1).

This is a sign of memory corruption. So the problem is very likely not Mac M2, but code that corrupts memory. What memory ends up being corrupted is very system-dependent, so probably your Ubuntu build doesn't have this problem because it's corrupting something else (perhaps corrupting some unused memory so you don't see a bug).

I recommend Asan ([Address Sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer)) to diagnose this kind of issues. Configure it in enforcing mode and enable backtraces (this may require setting some environment variables, it depends on your toolchain), and there's a good chance that it'll tell you where your memory is getting corrupted.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because the problem very likely to be in the application code, not in Mbed TLS. In any case, it's completely impossible to diagnose and reproduce without having the full application code.
