### ISSUE TITLE
Client certificate verify

### ISSUE THREAD

**Issue by utopia104** [Mbed-TLS/mbedtls#9116]
Hi Team,

I have a client certificate chain (cert, intermediate cert and root cert) and I have got 1 public key on my server. Is there any way in mbedTLS where I can validate the client certificate using only the public key on my server?

**Comment by gowthamsk-arm** [comment]
Support Requests should be directed to our mailing list at [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org). Please forward your query there. 

Closing this issue now.
