### ISSUE TITLE
Can't disable certificate verification with TLSv1.3

### ISSUE THREAD

**Issue by sfan5** [Mbed-TLS/mbedtls#9133]
### Summary

It's not possible to disable certificate verification when using TLSv1.3.
This is especially a major problem because 3.6.0 enabled it by default.

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: Linux x86_64
Configuration (if not default, please attach `mbedtls_config.h`): cmake default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): gcc 13.2.1
Additional environment information: n/a

### Expected behavior

connection continues anyway like with `force_version=tls12`

```
# ./programs/ssl/ssl_client2 server_name=cloudflare.com server_port=443 auth_mode=optional force_version=tls12
build version: Mbed TLS 3.6.0 (build 50724864)

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok (key type: RSA)
  . Setting up the SSL/TLS structure... ok
  . Connecting to tcp/cloudflare.com/443... ok
  . Performing the SSL/TLS handshake...
Verify requested for (Depth 1):

Verify requested for (Depth 0):
 ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256 ]
    [ Key size is 256 ]
    [ Record expansion is 21 ]
    [ Maximum incoming record payload length is 16384 ]
    [ Maximum outgoing record payload length is 16384 ]
  . Verifying peer X.509 certificate... failed
  ! The certificate is not correctly signed by the trusted CA

  . Peer certificate information    ...
[...]
  > Write to server: 34 bytes written in 1 fragments

GET / HTTP/1.0
Extra-header: 


  < Read from server: 329 bytes read

[...]
  . Closing the connection... done

```

### Actual behavior

```
# ./programs/ssl/ssl_client2 server_name=cloudflare.com server_port=443 auth_mode=optional 
build version: Mbed TLS 3.6.0 (build 50724864)

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the client cert. and key... ok (key type: RSA)
  . Setting up the SSL/TLS structure... ok
  . Connecting to tcp/cloudflare.com/443... ok
  . Performing the SSL/TLS handshake...
Verify requested for (Depth 1):

Verify requested for (Depth 0):
 failed
  ! mbedtls_ssl_handshake returned -0x2700
    Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes if not using TLS 1.3.
    For TLS 1.3 server, try `ca_path=/etc/ssl/certs/`or other folder that has root certificates

Last error was: -0x2700 - X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

```

**Comment by sfan5** [comment]
By the way I found this discussion #7075 and it looks like it's intentional that this doesn't work.
I disagree with the reasoning but putting that aside, one could also argue that making such a change is not backwards-compatible either.

**Comment by tom-daubney-arm** [comment]
Hi @sfan5, thank you for raising this. 

As you are already aware, this issue is being tracked by #7075 so I will be closing this issue as a duplicate. 

We elected to switch TLS 1.3 on by default at the start of the 3.6 LTS chain because over the lifetime of the LTS (a few years) it seems unlikely that many people will still be using TLS 1.2. Furthermore, a lot of users who are using the library in their applications would have their own configs so this change shouldn't be an issue in that case. We are looking at this though and it is tracked in #7075.
