### ISSUE TITLE
Signature of mbedtls_ssl_get_own_cid is using MBEDTLS_SSL_CID_OUT_LEN_MAX instead of MBEDTLS_SSL_CID_IN_LEN_MAX

### ISSUE THREAD

**Issue by jaudiger** [Mbed-TLS/mbedtls#9179]
### Summary

IMO the current signature of the function mbedtls_ssl_get_own_cid() is not using the right define the staticaly create the output array of the own CID as shown below: 

```c
int mbedtls_ssl_get_own_cid(mbedtls_ssl_context *ssl,
                            int *enabled,
                            unsigned char own_cid[MBEDTLS_SSL_CID_OUT_LEN_MAX],
                            size_t *own_cid_len);
```

Inside the structure mbedtls_ssl_context, this field is defined with the following define:

```c
struct mbedtls_ssl_context {
    ...
    unsigned char MBEDTLS_PRIVATE(own_cid)[MBEDTLS_SSL_CID_IN_LEN_MAX];
    ...
}
```

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: Fedora 40
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): GCC 12.3
Additional environment information: 

### Expected behavior

```c
int mbedtls_ssl_get_own_cid(mbedtls_ssl_context *ssl,
                            int *enabled,
                            unsigned char own_cid[MBEDTLS_SSL_CID_IN_LEN_MAX],
                            size_t *own_cid_len);
```

### Actual behavior

```c
int mbedtls_ssl_get_own_cid(mbedtls_ssl_context *ssl,
                            int *enabled,
                            unsigned char own_cid[MBEDTLS_SSL_CID_OUT_LEN_MAX],
                            size_t *own_cid_len);
```

### Steps to reproduce

Just enable the define MBEDTLS_SSL_DTLS_CONNECTION_ID

### Additional information

I have this patch locally to update the signature of this function:

```patch
diff --git a/include/mbedtls/ssl.h b/include/mbedtls/ssl.h
index 172d4693b..4226c1436 100644
--- a/include/mbedtls/ssl.h
+++ b/include/mbedtls/ssl.h
@@ -2364,7 +2364,7 @@ int mbedtls_ssl_set_cid(mbedtls_ssl_context *ssl,
  */
 int mbedtls_ssl_get_own_cid(mbedtls_ssl_context *ssl,
                             int *enabled,
-                            unsigned char own_cid[MBEDTLS_SSL_CID_OUT_LEN_MAX],
+                            unsigned char own_cid[MBEDTLS_SSL_CID_IN_LEN_MAX],
                             size_t *own_cid_len);
 
 /**
diff --git a/library/ssl_tls.c b/library/ssl_tls.c
index c5e06491c..ddcecf79c 100644
--- a/library/ssl_tls.c
+++ b/library/ssl_tls.c
@@ -132,26 +132,29 @@ int mbedtls_ssl_set_cid(mbedtls_ssl_context *ssl,
 
 int mbedtls_ssl_get_own_cid(mbedtls_ssl_context *ssl,
                             int *enabled,
-                            unsigned char own_cid[MBEDTLS_SSL_CID_OUT_LEN_MAX],
+                            unsigned char own_cid[MBEDTLS_SSL_CID_IN_LEN_MAX],
                             size_t *own_cid_len)
 {
     *enabled = MBEDTLS_SSL_CID_DISABLED;
 
-    if (ssl->conf->transport != MBEDTLS_SSL_TRANSPORT_DATAGRAM) {
+    if (ssl->conf->transport != MBEDTLS_SSL_TRANSPORT_DATAGRAM ||
+        mbedtls_ssl_is_handshake_over(ssl) == 0) {
         return MBEDTLS_ERR_SSL_BAD_INPUT_DATA;
     }
 
     /* We report MBEDTLS_SSL_CID_DISABLED in case the CID length is
      * zero as this is indistinguishable from not requesting to use
      * the CID extension. */
-    if (ssl->own_cid_len == 0 || ssl->negotiate_cid == MBEDTLS_SSL_CID_DISABLED) {
+    if (ssl->transform_in->in_cid_len == 0 &&
+        ssl->transform_in->out_cid_len == 0) {
         return 0;
     }
 
-    if (own_cid_len != NULL) {
-        *own_cid_len = ssl->own_cid_len;
+    if (own_cid_len != NULL) {
+        *own_cid_len = ssl->transform_in->in_cid_len;
         if (own_cid != NULL) {
-            memcpy(own_cid, ssl->own_cid, ssl->own_cid_len);
+            memcpy(own_cid, ssl->transform_in->in_cid,
+                   ssl->transform_in->in_cid_len);
         }
     }
 

```

This patch is doing more than that, since I also need for my use case to access the own CID from a loaded security session from mbedtls_ssl_context_load(), and also before the end of a handshake. So the patch shouldn't be taken as is, of course.

**Comment by davidhorstmann-arm** [comment]
Hi, thanks for reporting this! It certainly seems to be a bug, possibly a copypasta in the getter function signatures, although I can't seem to produce a build failure as yet.

**Comment by jaudiger** [comment]
> Hi, thanks for reporting this! It certainly seems to be a bug, possibly a copypasta in the getter function signatures, although I can't seem to produce a build failure as yet.

I think by default, both MBEDTLS_SSL_CID_OUT_LEN_MAX and MBEDTLS_SSL_CID_IN_LEN_MAX are equals. In my setup, they have two different values.

**Comment by gilles-peskine-arm** [comment]
Arrays in function arguments are strictly equivalent to pointers, so according to the C rules, `int f(unsigned char[MBEDTLS_SSL_CID_OUT_LEN_MAX])` is the same as `int f(unsigned char*)` is the same as `int f(unsigned char[MBEDTLS_SSL_CID_IN_LEN_MAX])`. But there is a GCC warning that will fire up sometimes if the compiler figures out the size at the calling site.
