### ISSUE TITLE
Add API to parse DER signature and export R and S components

### ISSUE THREAD

**Issue by MaJerle** [Mbed-TLS/mbedtls#9181]
### Suggested enhancement

ECDSA signature DER format varies in length, while many embedded hardware expects fixed length with their hardware accelerators, and in binary stream format.

It is therefore necessary to parse DER formatted signature to `2` fixed length signature components (`r` and `s`).
Below is the function, that could be potentially integrated in the API.

```c
/**
 * \brief           Parse DER formatted signature and export R and S components
 * 
 * \param           signature: Signature stream in DER format
 * \param           signature_len: Total length of signature in bytes
 * \param           rbuff: Buffer to store R component
 * \param           rsize: Max length of buffer for R component
 * \param           sbuff: Buffer to store S component
 * \param           ssize: Max length of buffer for S component
 * \return          int 
 */
int
prv_parse_signature_der_to_r_and_s(const void* signature, size_t signature_len, uint8_t* rbuff, size_t rsize,
                                   uint8_t* sbuff, size_t ssize) {
    int mbedtlsres;
    unsigned char* p = (void*)signature;
    const unsigned char* end = (const void*)((uintptr_t)p + signature_len);
    size_t len;
    mbedtls_mpi r, s;

    mbedtls_mpi_init(&r);
    mbedtls_mpi_init(&s);

    /* Parse data... */
    if ((mbedtlsres = mbedtls_asn1_get_tag(&p, end, &len, MBEDTLS_ASN1_CONSTRUCTED | MBEDTLS_ASN1_SEQUENCE)) != 0) {
    } else if (p + len != end) {
        mbedtlsres = 1; /* Set invalid... */
    } else if ((mbedtlsres = mbedtls_asn1_get_mpi(&p, end, &r)) != 0
               || (mbedtlsres = mbedtls_asn1_get_mpi(&p, end, &s)) != 0
               || (mbedtlsres = mbedtls_mpi_write_binary(&r, rbuff, rsize)) != 0
               || (mbedtlsres = mbedtls_mpi_write_binary(&s, sbuff, ssize)) != 0) {
    }

    mbedtls_mpi_free(&r);
    mbedtls_mpi_free(&s);

    return mbedtlsres;
}
```

### Justification

Mbed TLS needs this because it is being used on the embedded devices that have accelerators for public key cryptography and these usually require separate R and S components of the signature to be given to the hardware.

**Comment by gilles-peskine-arm** [comment]
This used to be a gap in the API, but since Mbed TLS 3.6.0, these functions exist:
[`mbedtls_ecdsa_raw_to_der`](https://mbed-tls.readthedocs.io/projects/api/en/v3.6.0/api/file/psa__util_8h/#_CPPv424mbedtls_ecdsa_raw_to_der6size_tPKh6size_tPh6size_tP6size_t) and [`mbedtls_ecdsa_der_to_raw`](https://mbed-tls.readthedocs.io/projects/api/en/v3.6.0/api/file/psa__util_8h/#_CPPv424mbedtls_ecdsa_der_to_raw6size_tPKh6size_tPh6size_tP6size_t).

**Comment by gilles-peskine-arm** [comment]
If you're working with hardware accelerators, you should [move from the legacy API to the PSA API](https://github.com/Mbed-TLS/mbedtls/blob/mbedtls-3.6.0/docs/psa-transition.md#creating-a-psa-key-via-pk), which has better accelerator support and will be the only cryptography API in Mbed TLS 4.0. `psa_sign_hash` and `psa_verify_hash` use the fixed-size (r,s) format for ECDSA signatures.

**Comment by MaJerle** [comment]
Thanks, will look into this one.
