### ISSUE TITLE
Remove CBC cipher suites

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#9202]
TLS ≤1.2 CBC cipher suites are [hard to implement securely](https://en.wikipedia.org/wiki/Lucky_Thirteen_attack) unless the encrypt-then-MAC (EtM) extension is enabled. They no longer exist in TLS 1.3. They are a significant burden to maintain, because their existence adds a lot of complexity to several functions in the TLS module.

[RFC 9325](https://datatracker.ietf.org/doc/html/rfc9325) deprecates CBC cipher suites unless the EtM extension is enabled. Unfortunately, it is not possible to negotiate EtM support cleanly: a client cannot declare that it only accepts CBC cipher suites when EtM is enabled, it can only announce that it supports both, which may result in the server selecting a CBC cipher suite but rejecting the EtM extension, even when the server might have also allowed an AEAD cipher suite.

In 2025, are CBC cipher suites still relevant, or has AEAD (GCM, CCM or ChachaPoly) finally become available everywhere Mbed TLS runs?

(Related: https://github.com/Mbed-TLS/mbedtls/issues/7679 — if we keep them, they might be disabled by default.)

Mailing list thread: https://lists.trustedfirmware.org/archives/list/mbed-tls@lists.trustedfirmware.org/thread/GDEIRA66Y4SEUINHCG2TCJ2NPGL5KJK7/

**Comment by gilles-peskine-arm** [comment]
[CBC cipher suites were relevant for RTE (real-time ethernet)](https://github.com/Mbed-TLS/mbedtls/issues/3854#issuecomment-722393121) in 2020. Are they still relevant 5 years later?

**Comment by gilles-peskine-arm** [comment]
Architectural decision: we are removing CBC cipher suites.

The primary driver for this decision is to simplify some spaghetti code in `ssl_msg.c` that has lead to security issues due to its complexity.

**Comment by mpg** [comment]
Note: removing CBC ciphersuites means we can also remove support of the Encrypt-then-Mac extension. Make sure to also remove the option in test programs, and to fully remove related tests.

Note: there are still remnants from the Truncated HMAC extension (that was removed in 3.0), for example tests in ssl-opt.sh, and a `trunc_hmac` command-line option in SSL test programs. This task would be a good opportunity to remove them as well.

**Comment by mschulz-at-hilscher** [comment]
We still need AES CBC for implementing CIP Security for Ethernet/IP:
![grafik](https://github.com/user-attachments/assets/ad56fbad-6609-41ea-becd-f5c93c143fc6)

Source: The CIP Networks Library Volume 8: CIP Security, Edition 1.17, November 2023

**Comment by mschulz-at-hilscher** [comment]
We additionally need AES CBC for implementing OPCUA:
https://reference.opcfoundation.org/Core/Part7/v104/docs/6.6.159

**Comment by gilles-peskine-arm** [comment]
CBC cipher suites will remain in Mbed TLS 4.x. We'll probably revise this in 5.0, but we can create a new issue then, so I'm closing this issue as a wontfix.
