### ISSUE TITLE
Question about mbedtls_x509_crt_parse() & mbedtls_x509_crt_free()

### ISSUE THREAD

**Issue by wwtd** [Mbed-TLS/mbedtls#9297]
### Summary
I want to use mbedtls_x509_crt_parse() to parse a crt, and my code just like
```c
int func(uint8_t * cert_str, uint32_t cert_str_len)
{
    mbedtls_x509_crt tmp_cert;
    int ret = 0;
    
    mbedtls_x509_crt_init(&tmp_cert);
    if((ret = mbedtls_x509_crt_parse(&tmp_cert, cert_str, cert_str_len)) !=0)
    {
        //do something
    }
   
    mbedtls_x509_crt_free(&tmp_cert);
    return ret;
}
```

However, this code cannot pass static scanning. Because in some cases, such as when it works failed, mbedtls_x509_crt_free() may have already been called in mbedtls_x509_crt_parse(). Once the function mbedtls_x509_crt_free() has been called , it will free **cert_cur->sig_opts** directly. Above all, this will cause a double-free issue.

Should I change another way to use mbedtls_x509_crt_free() like this below?
```c
int func(uint8_t * cert_str, uint32_t cert_str_len)
{
    mbedtls_x509_crt tmp_cert;
    int ret = 0;
    
    mbedtls_x509_crt_init(&tmp_cert);
    if((ret = mbedtls_x509_crt_parse(&tmp_cert, cert_str, cert_str_len)) !=0)
    {
        //do something
    }
    else
    {
        mbedtls_x509_crt_free(&tmp_cert);
    }
    return ret;
}
```
Thank you!

**Comment by gilles-peskine-arm** [comment]
It should be safe to call `mbedtls_x509_crt_free()` multiple times on the same object. `mbedtls_x509_crt_free()` calls `free()` on some pointer fields, and it sets those pointer fields to a null pointer afterwards. The second call to `mbedtls_x509_crt_free()` will call `free` on those null pointers, which is a no-op.

In our test suites, we call `mbedtls_x509_crt_free()` systematically whenever we've called `mbedtls_x509_crt_init()`, including both positive and negative tests of `mbedtls_x509_crt_parse`. Your original code follows that model, and it's definitely meant to be correct.

Have you actually observed a double-free? If so, please tell us exactly how to reproduce it (exact Mbed TLS version, library configuration, input, code).

**Comment by wwtd** [comment]
Hi, @gilles-peskine-arm . No actually double-free was actually observed, I guess my scanning tool is confused. 
Thanks for your patience, I'll close this issue.
