### ISSUE TITLE
analyze_outcomes: inconsistent ordering of driver vs reference

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#9298]
Sample error from `analyze_outcomes.py` on driver-vs-reference comparison:

```
*** Analyze driver test_psa_crypto_config_accel_cipher_aead_cmac vs reference test_psa_crypto_config_reference_cipher_aead_cmac ***

Error: PASS -> SKIP/FAIL: ssl-opt;TLS: password protected server key, two certificates
```

The header line says “driver vs reference” but the error line says “reference -> driver”. This is misleading. We should use a consistent order, either driver-then-reference or reference-then-driver. @mpg Do you have any preference?

**Comment by mpg** [comment]
Ah, right, I hadn't considered that. I don't have a strong preference, anything's fine with me as long as it's clear(er than the existing).
