### ISSUE TITLE
Replace `MBEDTLS_PK_CAN/HAVE_ECDSA*` with its `PSA_WANT` counterparts

### ISSUE THREAD

**Issue by gabor-mezei-arm** [Mbed-TLS/mbedtls#9337]
Replace these macros:
- `MBEDTLS_PK_HAVE_ECC_KEYS` to `PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY`
- `MBEDTLS_PK_CAN_ECDSA_SIGN` to `PSA_WANT_ALG_ECDSA && PSA_WANT_KEY_TYPE_ECC_KEY_PAIR_BASIC`
- `MBEDTLS_PK_CAN_ECDSA_VERIFY` to `PSA_WANT_ALG_ECDSA && PSA_WANT_KEY_TYPE_ECC_PUBLIC_KEY`
- `MBEDTLS_PK_CAN_ECDSA_SOME` to `PSA_WANT_ALG_ECDSA`

The macros should be replaced in all files except `mbedtls_config.h`, `check_config.h` and `config_adjust_*.h`.

Ensure that the test are run in the same way.

**Comment by gilles-peskine-arm** [comment]
It's never `PSA_WANT_ALG_ECDSA` but instead `PSA_WANT_ALG_ECDSA || PSA_WANT_ALG_DETERMNISTIC_ECDSA`. (Randomized) ECDSA and deterministic ECDSA are distinct signature algorithms, but they are functionally equivalent. This comes up often, so we should define a symbol like
```
#define PSA_HAVE_ALG_SOME_ECDSA (PSA_WANT_ALG_ECDSA || PSA_WANT_ALG_DETERMNISTIC_ECDSA)
```
in `include/psa/*adjust*.h`.
