### ISSUE TITLE
MBEDTLS_DEBUG_C

### ISSUE THREAD

**Issue by leventf16** [Mbed-TLS/mbedtls#9391]
### Summary
MBEDTLS_DEBUG_C doesn't have effect.

### System information

Mbed TLS version (number or commit id): v1.2
Operating system and version: FreeRTOS
Configuration (if not default, please attach `mbedtls_config.h`): 
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior 
After uncommenting MBEDTLS_DEBUG_C we expect to have debug output.

### Actual behavior
We don't have any debug output?!

**Comment by ronald-cron-arm** [comment]
Hi, it works on our CI in various configurations thus setting MBEDTLS_DEBUG_C is expected to have the desired effect on the build. You may want to set the debug threshold to a value greater than 0: see `mbedtls_debug_set_threshold()`. It seems to me that it is rather a support request thus I am closing the issue and if you have additional questions please use our mailing list at [mbed-tls@lists.trustedfirmware.org](mailto:mbed-tls@lists.trustedfirmware.org).
