### ISSUE TITLE
.def file with export function list for dynamic DLL on windows 

### ISSUE THREAD

**Issue by AdamBialas** [Mbed-TLS/mbedtls#94]
There is no definition file for export functions to use polarissl as dynamic dll with other languages like delphi .

**Comment by lordcrc** [comment]
Just a .def file is of limited use I think, because one would have to keep the defines in sync in the importing program, so that the structures are the same. 

This is especially error-prone if the language the importing program is written in does not natively use a pre-processor, like Delphi.

**Comment by sbutcher-arm** [comment]
Removing the 'fix available' label as I've had to close #1363 due to lack of a CLA.

**Comment by tom-daubney-arm** [comment]
Closing this as this is not something that we plan to do. If someone would like to contribute this as a PR then please feel free to do so.
