### ISSUE TITLE
AES 128 CBC not outputting correct data

### ISSUE THREAD

**Issue by josesimoes** [Mbed-TLS/mbedtls#9433]
### Summary

When trying to encrypt a byte array with AES 128 CBC the encrypted data is not correct, according to NIST test vectors.

### System information

Mbed TLS version (number or commit id):  3.6.0
Operating system and version: ChibiOS RTOS
Configuration (if not default, please attach `mbedtls_config.h`): see attached
[nf_mbedtls_config.h.txt](https://github.com/user-attachments/files/16417556/nf_mbedtls_config.h.txt)

Compiler and options (if you used a pre-built binary, please indicate how you obtained it): GCC 13.2.rel1

### Expected behavior

When using this code snippet to encrypt a byte array the output is not the expected.
As additional context: this is coming from .NET nanoFramework code base

```
    // init mbedtls context
    mbedtls_cipher_init(&ctx);

    // set up the cipher
    cipherInfo = mbedtls_cipher_info_from_type(MBEDTLS_CIPHER_AES_128_CBC);
    mbedtls_cipher_setup(&ctx, cipherInfo);

    // need a work buffer to hold the encrypted data
    workBuffer = (uint8_t *)platform_malloc(plainTextArray->m_numOfElements + cipherInfo->private_block_size);

    if (workBuffer == NULL)
    {
        NANOCLR_SET_AND_LEAVE(CLR_E_OUT_OF_MEMORY);
    }

    // set the padding mode to none
    mbedtls_cipher_set_padding_mode(&ctx, MBEDTLS_PADDING_NONE);

    mbedtls_cipher_setkey(&ctx, keyArray->GetFirstElement(), keyArray->m_numOfElements * 8, MBEDTLS_ENCRYPT);

    // encrypt the data
    mbedtls_cipher_crypt(
        &ctx,
        ivCopy,
        ivArray->m_numOfElements,
        plainTextArray->GetFirstElement(),
        plainTextArray->m_numOfElements,
        workBuffer,
        &olen);

    // sanity check
    if (olen != plainTextArray->m_numOfElements)
    {
        NANOCLR_SET_AND_LEAVE(CLR_E_FAIL);
    }

    // make sure nothing is left in memory
    mbedtls_cipher_free(&ctx);

    // copy back to the return array
    memcpy(cipherTextArray->GetFirstElement(), workBuffer, plainTextArray->m_numOfElements);


```

### Actual behavior

When passing the array
`6bc1bee22e409f96e93d7e117393172a`
with key
`2b7e151628aed2a6abf7158809cf4f3c`
and IV
`000102030405060708090a0b0c0d0e0f`

I'm getting as cipher text 
`3ad77bb40d7a3660a89ecaf32466ef97`

instead of the expected

`7649abac8119b246cee98e9b12e9197d`

Interestingly that's the output for AES 128 ECB using the same text and key.
These test vectors are coming from [NIST](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/[nistspecialpublication800-38a.pdf](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf)
F.1.1 ECB Example Vectors block #1  page 24 
F.2.1 CBC Example Vectors block #1 page 27

Am I missing something or have a wrong config somewhere?

### Additional information

We already have the AES 128 ECB successfully implemented and all unit tests (using those NIST test vectors) are passing.

**Comment by waleed-elmelegy-arm** [comment]
I think NIST test vectors does use padding so I don't think you should use 'MBEDTLS_PADDING_NONE' here, also, I can see you are using ivCopy are you sure you copied the IV content from ivArray and both have the correct IV? because if the IV buffer happens to be all zeros and there is no padding and input is 16 bytes block then indeed CBC would behave like ECB, Thanks.

**Comment by josesimoes** [comment]
Yes, I've double checked in debug that the IV is being copied correctly and that the content is the one from the test vector.

I'm using padding none because that's the only mode supported by calling code. I mean the API is not supporting any padding option.

Also, I've crossed checked with a .NET test app using the same test vectors and setting padding to none and the output is the expected.

To your point that this would behave as ECB given those conditions, made me think that there could be an issue with the code as I briefly went through it on a debug and noticed it "jumps" on several conditions like the padding none, etc.

You can confirm that code looks correct and is calling the Mbed APIs with the proper order and parameters (yes, assuming those have the correct data)?

Any thoughts on where I should look into to dig into this?

**Comment by waleed-elmelegy-arm** [comment]
The use of MbedTLS APIs looks correct to me apart from maybe checking the error code of each call to make sure the call was successful and the data you are seeing in the buffers are not old data, I replicated roughly what you are doing and I am getting the correct result so unless the input data are not correct I can't really see something obviously wrong.
Here the code I have used to test:
`int main(int argc, char *argv[])
{
    int ret;
    size_t olen;

    unsigned char IV[16] = {
                            0x00, 0x01, 0x02, 0x03,
                            0x04, 0x05, 0x06, 0x07,
                            0x08, 0x09, 0x0a, 0x0b,
                            0x0c, 0x0d, 0x0e, 0x0f
                           };

    unsigned char key[32] =  {
                                0x2b, 0x7e, 0x15, 0x16,
                                0x28, 0xae, 0xd2, 0xa6,
                                0xab, 0xf7, 0x15, 0x88,
                                0x09, 0xcf, 0x4f, 0x3c
                              };
    unsigned char buffer[32] = {
                                    0x6b, 0xc1, 0xbe, 0xe2,
                                    0x2e, 0x40, 0x9f, 0x96,
                                    0xe9, 0x3d, 0x7e, 0x11,
                                    0x73, 0x93, 0x17, 0x2a
                                };
    unsigned char workBuffer[32];

    const mbedtls_cipher_info_t *cipherInfo;
    mbedtls_cipher_context_t ctx;

    // init mbedtls context
    mbedtls_cipher_init(&ctx);

    // set up the cipher
    cipherInfo = mbedtls_cipher_info_from_type(MBEDTLS_CIPHER_AES_128_CBC);
    ret = mbedtls_cipher_setup(&ctx, cipherInfo);
    if (ret) {
        printf("FAIL: %x at line#%d\n", ret, __LINE__);
        goto exit;
    }

    ret = mbedtls_cipher_set_padding_mode(&ctx, MBEDTLS_PADDING_NONE);
    if (ret) {
        printf("FAIL: %x at line#%d\n", ret, __LINE__);
        goto exit;
    }

    ret = mbedtls_cipher_setkey(&ctx, key, 16*8, MBEDTLS_ENCRYPT);
    if (ret) {
        printf("FAIL: %x at line#%d\n", ret, __LINE__);
        goto exit;
    }
    ret = mbedtls_cipher_crypt(
        &ctx,
        IV,
        16,
        buffer,
        16,
        workBuffer,
        &olen);

    if (ret) {
        printf("FAIL: %x at line#%d\n", ret, __LINE__);
        goto exit;
    }

    if (olen != 16)
    {
        printf("FAIL: %x at line#%d\n", ret, __LINE__);
        goto exit;
    }

    for (int i = 0; i < 16; i++) {
        printf("%x", workBuffer[i]);
    }
    mbedtls_printf("\n");


    exit:
    mbedtls_cipher_free(&ctx);
    return ret;
}
`
