### ISSUE TITLE
Changing the time to system time only 

### ISSUE THREAD

**Issue by RominaRsn** [Mbed-TLS/mbedtls#9522]
### Suggested enhancement

Hi, I hope this message finds you well. 
I have been integrationg mbedTLS 2 in a tool for keeping track of certificates and their validity. However, I have this problem that I cannot test a certificate expiration by changing the system time because it seems like the mbedTLS is checking the time from GMT. I wonder if there is already a feature that could so and if not I think it would be very useful to have it.
### Justification

Mbed TLS needs this because this helps test cases that the certificates expire during the procedure.

**Comment by gilles-peskine-arm** [comment]
What we and a lot of other people do is to run tests with [faketime](https://github.com/wolfcw/libfaketime). You can see a draft version of some testing we've been working on in https://github.com/Mbed-TLS/mbedtls/pull/7799 (but that's probably more complicated than just making your own stuff, `faketime` is really easy to use).

If you're on an embedded system without shared libraries, you can make a test build of Mbed TLS with `-DMBEDTLS_PLATFORM_TIME_ALT` and link your own function `mbedtls_time` that returns whatever you want.

**Comment by gilles-peskine-arm** [comment]
I'm closing this issue because the requested feature is already present in one form, and there are third-party tools that make it unnecessary in most scenarios.
