### ISSUE TITLE
mbedtls 3.6.1 tarball missing submodules

### ISSUE THREAD

**Issue by Schamschula** [Mbed-TLS/mbedtls#9524]
### Summary
mbedtls 3.6.0 was available as a .bz2 tarball from GitHub releases. Unfortunately, the .tar.gz archive for version 3.6.1 is incomplete, missing sub-modules. See below.

### System information

Mbed TLS version (number or commit id): 3.6.1
Operating system and version: macOS 14.6.1
Configuration (if not default, please attach `mbedtls_config.h`): N/A
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): N/A
Additional environment information: 

### Expected behavior
Cmake configuration successfully completes.

### Actual behavior
```
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:304 (message):
  
  /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_devel_mbedtls3/mbedtls3/work/mbedtls-3.6.1/framework/CMakeLists.txt
  not found.  Run `git submodule update --init` from the source tree to fetch
  the submodule contents.


-- Configuring incomplete, errors occurred!
```

### Steps to reproduce
Download https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.6.1.tar.gz and attempt to run cmake.

### Additional information
It should not be necessary to run `git submodule update --init`
Doing so means there are no proper checksums.

**Comment by paul-elliott-arm** [comment]
Hi Schamschula

From the release notes:

> ❕mbedtls-3.6.1.tar.bz2 are our official release files. source.tar.gz and source.zip are automatically generated snapshot's that github is generating. They do not include external dependencies, and [can't be configured](https://github.com/orgs/community/discussions/6003)

Does the same happen with the attached `mbedtls-3.6.1.tar.bz2` ?

**Comment by Schamschula** [comment]
OK. I see that there are two tags v3.6.1 and mbedtls-3.6.1. Only the second has the .tar.bz2 archive.

There reason the update initially failed is that the file name has changed with this release: `v3.6.0.tar.bz2` to `mbedtls-3.6.1.tar.bz2`

I've fixed that in the MacPorts Portfile. All is now well!
