### ISSUE TITLE
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 not adding to ciphersuite list

### ISSUE THREAD

**Issue by RominaRsn** [Mbed-TLS/mbedtls#9527]
### Summary
Hi, I hope this message finds you well. I have been trying to use cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for encryption in both my server and client. However, when I try to perform the handshake the handshake fails with "no matching TLS ciphers". 
To trouble shoot I have cleared the ciphersuite list and have only added this cipher suite to the list. I have also added the following to  mbedtls_config.h.

#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_ECP_DP_BP256R1_ENABLED
#define MBEDTLS_ECP_DP_BP384R1_ENABLED
#define MBEDTLS_ECP_DP_BP512R1_ENABLED
/* Montgomery curves (supporting ECP) */
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ECP_DP_CURVE448_ENABLED

// Enable support for elliptic curve cryptography
#define MBEDTLS_ECP_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_ECDH_C

// Enable SHA-2 (SHA-256, SHA-384, SHA-512)
#define MBEDTLS_SHA384_C

// Enable ECDHE-ECDSA key exchange
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED

### System information

Mbed TLS version (number or commit id):  2.28
Operating system and version: Ubuntu 22.04.4 LTS
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):

**Comment by mpg** [comment]
Hi! Is this your entire config? It seems to be missing the symmetric part of the ciphersuite: for `AES_256_GCM` you'll want `MBEDTLS_AES_C` and `MBEDTLS_GCM_C` as well.

Note: if this is just for TLS, you don't need the 192-bit and 224-bit curves as these won't be used by TLS anyway.

**Comment by RominaRsn** [comment]
Hi, thank you for your reply.

No, these are the things I have added extra. Here is the complete content
of the config file which already includes the macros u mentioned:

#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

/* System support */
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_TIME
#define MBEDTLS_HAVE_TIME_DATE
#define MBEDTLS_NO_UDBL_DIVISION
#define MBEDTLS_PLATFORM_C
#define MBEDTLS_DEBUG_C

/* mbed TLS feature support */
#define MBEDTLS_CIPHER_MODE_CBC
#define MBEDTLS_PKCS1_V15
#define MBEDTLS_KEY_EXCHANGE_RSA_ENABLED
#define MBEDTLS_SSL_PROTO_TLS1_2
#define MBEDTLS_SSL_PROTO_TLS1_1
#define MBEDTLS_SSL_PROTO_TLS1
#define MBEDTLS_SSL_RENEGOTIATION
#define MBEDTLS_ENABLE_WEAK_CIPHERSUITES
#define MBEDTLS_CIPHER_NULL_CIPHER

#define MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_CERTIFICATES

/* mbed TLS modules */
#define MBEDTLS_GCM_C
#define MBEDTLS_AES_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_CIPHER_C
#define MBEDTLS_CTR_DRBG_C
/* #define MBEDTLS_DES_C */
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_MD_C
#define MBEDTLS_MD5_C
#define MBEDTLS_NET_C
#define MBEDTLS_OID_C
#define MBEDTLS_PK_C
#define MBEDTLS_PK_PARSE_C
#define MBEDTLS_RSA_C
#define MBEDTLS_SHA1_C
#define MBEDTLS_SHA256_C
#define MBEDTLS_SSL_CLI_C
#define MBEDTLS_SSL_SRV_C
#define MBEDTLS_SSL_TLS_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_X509_CRL_PARSE_C
#define MBEDTLS_X509_USE_C
#define MBEDTLS_SSL_CACHE_C

#define MBEDTLS_ECDSA_C
#define MBEDTLS_ECP_C
#define MBEDTLS_ECP_DP_SECP192R1_ENABLED
#define MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#define MBEDTLS_ECP_DP_SECP384R1_ENABLED
#define MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define MBEDTLS_ECP_DP_SECP192K1_ENABLED
#define MBEDTLS_ECP_DP_SECP224K1_ENABLED
#define MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define MBEDTLS_ECP_DP_BP256R1_ENABLED
#define MBEDTLS_ECP_DP_BP384R1_ENABLED
#define MBEDTLS_ECP_DP_BP512R1_ENABLED
/* Montgomery curves (supporting ECP) */
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ECP_DP_CURVE448_ENABLED

// Enable support for elliptic curve cryptography
#define MBEDTLS_ECP_C
#define MBEDTLS_X509_CRT_PARSE_C
#define MBEDTLS_ECDH_C

// Enable SHA-2 (SHA-256, SHA-384, SHA-512)
#define MBEDTLS_SHA384_C

// Enable ECDHE-ECDSA key exchange
#define MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED


/* For test certificates */
#define MBEDTLS_BASE64_C
#define MBEDTLS_CERTS_C
#define MBEDTLS_PEM_PARSE_C

#define MBEDTLS_PKCS12_C
#define MBEDTLS_PKCS5_C

/* For testing with compat.sh */
#define MBEDTLS_FS_IO

#define MBEDTLS_X509_CHECK_KEY_USAGE
#define MBEDTLS_X509_CHECK_EXTENDED_KEY_USAGE

#include "mbedtls/check_config.h"

#endif /* MBEDTLS_CONFIG_H */



Kind regards,
Romina

**Comment by mpg** [comment]
Thanks! I can't spot anything obviously wrong with the config you posted.

Can you try to compile a program that lists supported ciphersuites (see code snippet below) and post the output?

```c
for (const int *list = mbedtls_ssl_list_ciphersuites(); *list != 0; list++) {
    printf(" %s\n", mbedtls_ssl_get_ciphersuite_name(*list));
}
```

**Comment by RominaRsn** [comment]
Thank you for the suggestion. 
Please find the list of ciphers below: 

 TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA
 TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
 TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA256
 TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA
 TLS-RSA-WITH-AES-256-CBC-SHA256
 TLS-RSA-WITH-AES-256-CBC-SHA
 TLS-RSA-WITH-AES-128-GCM-SHA256
 TLS-RSA-WITH-AES-128-CBC-SHA256
 TLS-RSA-WITH-AES-128-CBC-SHA
 TLS-ECDHE-ECDSA-WITH-NULL-SHA
 TLS-RSA-WITH-NULL-SHA256
 TLS-RSA-WITH-NULL-SHA
 TLS-RSA-WITH-NULL-MD5

One thing that I was suspecting was the support of this cipher suite in TLS 1.2, since there is this comment in ssl_ciphersuites.h:
#define MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384  0xC02C **/**< TLS 1.2 */**

Regards,

**Comment by mpg** [comment]
Thank you for the new info!

I can see that `TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256` is present, which is very close to the ciphersuite you want, except for two bits: (1) the AES key size and (2) SHA256 instead of SHA384. I'm also noticing that that is no SHA384 ciphersuite in the list.

Actually in 2.28 we didn't have that macro yet: in order to enable SHA-384 the macro you need to use is `MBEDTLS_SHA512_C`, which will enabled both SHA-512 and SHA-384. That's for technical reasons: both of them share most of their implementation. But as a user, you shouldn't have to know about those details, and that's why we have `MBEDTLS_SHA384_C` since Mbed TLS 3.0 IIRC. But in 2.28 you still need to use `MBEDTLS_SHA512_C`. Please let me know if that fixes your problem.

PS: as you probably already know, 2.28 is only support until end of 2024, so I'd like to encourage you to move to the 3.6 branch, which will be supported until at least March 2027.

PPS: are you sure you want the `NULL` ciphersuites enabled? They provide no confidentiality, only authentification.

**Comment by RominaRsn** [comment]
Hi, thank you for your reply!

I tried adding the macro  MBEDTLS_SHA512_C and I can see the
TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384 in the list of ciphers now, thank
you for your help. However, I still have the same problem with the
handshake.
The error is: MBEDTLS_ERR_SSL_NO_USABLE_CIPHERSUITE, Algorithm not
supported.

Thank you for your feedback on the version and null cipher; I am only using
these cipher suites for testing and since some are only available on 2.28 I
will have to stick to this version I guess :)

Kind regards,

**Comment by RominaRsn** [comment]
I recreated my certificates with ECDSA and now the handshake is successful.

Thank you so much for your help, that really solved the problem :)

Kind regards,
Romina

**Comment by mpg** [comment]
Seems like everything is resolved, so I'm closing this issue. Thanks again for your interest in Mbed TLS.
