### ISSUE TITLE
Generate tf_psa_crypto_version_features.c

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#9530]
### Suggested enhancement
Add to the tf-psa-crypto build system the generation of tf_psa_crypto_version_features.c.

Depends on #9420.

### Justification
Mbed TLS needs this for the repo split.

**Comment by gilles-peskine-arm** [comment]
Note that [errors will be overhauled](https://github.com/Mbed-TLS/mbedtls/issues/8501), and I suspect we'll get rid of `generate_errors.pl`.

**Comment by ronald-cron-arm** [comment]
No equivalent to Mbed TLS version_features.c in TF-PSA-Crypto.
