### ISSUE TITLE
Adapt generate_errors.pl for the repo split

### ISSUE THREAD

**Issue by ronald-cron-arm** [Mbed-TLS/mbedtls#9531]
### Suggested enhancement
For 3.6, generate_errors.pl should behave as it currently does.
For development, generate_errors.pl should include only the TLS and x509 errors (from the include directory include/mbedtls) in the generated file.
For TF-PSA-Crypto, generate_errors.pl should include the crypto errors (from the include directory tf-psa-crypto/drivers/builtin/include/mbedtls) in the generated file.

### Justification
Mbed TLS needs this for the repo split.

**Comment by gilles-peskine-arm** [comment]
Note that [errors will be overhauled](https://github.com/Mbed-TLS/mbedtls/issues/8501), and I suspect we'll get rid of `generate_errors.pl`.

**Comment by ronald-cron-arm** [comment]
> Note that [errors will be overhauled](https://github.com/Mbed-TLS/mbedtls/issues/8501), and I suspect we'll get rid of `generate_errors.pl`.

Yes I was aware of that. I was thinking about doing minimal changes to `generate_errors.pl` but actually we maybe do not need not. Would it be acceptable after the split to have errors.c in Mbed TLS as it is currently and no errors.c in TF-PSA-Crypto?

**Comment by gilles-peskine-arm** [comment]
We'll have to see how much we manage to unify the error codes. But in principle, yes, I think it would be reasonable to not have an error message printing interface in TF-PSA-Crypto 1.0.

In the longer term, I'd like to have the more general `psa_constant_names` as a library module in TF-PSA-Crypto. But that's been on the back burner for years, it can wait until after 1.0.

**Comment by ronald-cron-arm** [comment]
No need to do that eventually. We will keep error.c in Mbed TLS as it is for the time being and do not add similar support in TF-PSA-Crypto. When working on #8501 we may revisit that.
