### ISSUE TITLE
Segmentation fault in mbedtls_x509_crt_free

### ISSUE THREAD

**Issue by ko-maren** [Mbed-TLS/mbedtls#9570]
### Summary

I'm currently updating from v2.28.8 to v3.6.0. In this context I issued a segmentation fault in the function `mbedtls_x509_crt_free`. 

I'm using the pkcs11-helper library for some parts, and in a function of the library I figured out a segmentation fault in mbedtls (https://github.com/OpenSC/pkcs11-helper/blob/pkcs11-helper-1.28.0/lib/_pkcs11h-crypto-mbedtls.c `__pkcs11h_crypto_mbedtls_certificate_is_issuer`):
```c
__pkcs11h_crypto_mbedtls_certificate_is_issuer(...)
{
	mbedtls_x509_crt x509_issuer;
	mbedtls_x509_crt x509_cert;
[...]
	memset(&x509_issuer, 0, sizeof(x509_issuer));
	if (0 != mbedtls_x509_crt_parse (&x509_issuer, issuer_blob, issuer_blob_size)) {
		goto cleanup;
	}

	memset(&x509_cert, 0, sizeof(x509_cert));
	if (0 != mbedtls_x509_crt_parse (&x509_cert, cert_blob, cert_blob_size)) {
		goto cleanup;
	}
[...]
cleanup:
	mbedtls_x509_crt_free(&x509_cert);
	mbedtls_x509_crt_free(&x509_issuer);
[...]
}
``` 

If  `mbedtls_x509_crt_parse (&x509_issuer, issuer_blob, issuer_blob_size)` is returning an error, and the code jumps to `cleanup`, an segmentation fault occurs in `mbedtls_x509_crt_free(&x509_cert);`

I already compared `mbedtls_x509_crt_free` from v2.28.8 and v3.6.0. The main difference seems to be that in v2.28.8, before calling `mbedtls_free` on the different objects in the `mbedtls_x509_crt` struct, `mbedtls_platform_zeroize` is called where a memset of the structure is done.

Example of freeing the `mbedtls_x509_name` in `mbedtls_x509_crt_free` for v2.28.8:
```c
        name_cur = cert_cur->issuer.next;
        while (name_cur != NULL) {
            name_prv = name_cur;
            name_cur = name_cur->next;
            mbedtls_platform_zeroize(name_prv, sizeof(mbedtls_x509_name));
            mbedtls_free(name_prv);
        }
```

Example of freeing the `mbedtls_x509_name` in `mbedtls_x509_crt_free` for v3.6.0:
```c
mbedtls_asn1_free_named_data_list_shallow(cert_cur->issuer.next);


void mbedtls_asn1_free_named_data_list_shallow(mbedtls_asn1_named_data *name)
{
    for (mbedtls_asn1_named_data *next; name != NULL; name = next) {
        next = name->next;
        mbedtls_free(name);
    }
}
```

With a memset before the free, it would be possible to use the `mbedtls_x509_crt_free` safely even if the pointer handing over is pointing to a struct without using a memset before.

### System information

Mbed TLS version (number or commit id): 3.6.0
Operating system and version: 
Configuration (if not default, please attach `mbedtls_config.h`):  [mbedtls_config.txt](https://github.com/user-attachments/files/17026174/mbedtls_config.txt)
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information: 

### Expected behavior

`mbedtls_x509_crt_free` should work even if the struct is only set without any additional memset.

### Actual behavior

If no memset is used on the struct before it is handed over to `mbedtls_x509_crt_free`, a segmentation fault is thrown.

### Steps to reproduce

See function of pkcs11-helper library above. Don't use memset on the struct `mbedtls_x509_crt` before calling `mbedtls_x509_crt_free`

**Comment by tom-cosgrove-arm** [comment]
> `mbedtls_x509_crt_free` should work even if the struct is only set without any additional `memset

In the code provided, `x509_issuer` and `x509_cert` are not set, only declared. Calling a cleanup function on them is not going to work.

Specifically, you must call `mbedtls_x509_crt_init()` on each of them before doing anything else.

This is documented, for example in [`mbedtls_x509_crt_parse_der()`](https://github.com/Mbed-TLS/mbedtls/blob/development/include/mbedtls/x509_crt.h#L368), where it says

```
 * \param chain    The pointer to the start of the CRT chain to attach to.
 *                 When parsing the first CRT in a chain, this should point
 *                 to an instance of ::mbedtls_x509_crt initialized through
 *                 mbedtls_x509_crt_init().
```

**Comment by ko-maren** [comment]
Thanks! I thought there was such a function, but I also didn't found it.
