### ISSUE TITLE
Expose internal configuration symbols from TF-PSA-Crypto to Mbed TLS

### ISSUE THREAD

**Issue by gilles-peskine-arm** [Mbed-TLS/mbedtls#9607]
In Mbed TLS 4.0, we will need to access some internal symbols from the TF-PSA-Crypto configuration. As of Mbed TLS 3.6, when `MBEDTLS_USE_PSA_CRYPTO` is enabled, the X.509 and TLS code mostly relies on `PSA_WANT_xxx` or symbols derived from it (e.g. `MBEDTLS_MD_CAN_xxx`, `MBEDTLS_PK_HAVE_xxx`) to know whether a cryptographic mechanism is supported. That came from the “driver-only” work. But there are a few exceptions where the X.509 and TLS code still relies on legacy symbols. TF-PSA-Crypto's configuration will be entirely based on `PSA_WANT_xxx`, but it will still have legacy symbols internally. Some of these must be in a header that Mbed TLS 4.x will consume until we finish the migration to PSA.

* RSA: `MBEDTLS_RSA_C`, `MBEDTLS_PKCS1_V15`, `MBEDTLS_PKCS1_V21`

**Comment by yanesca** [comment]
Closing this as it will be resolved by [#9559](https://github.com/Mbed-TLS/mbedtls/issues/9559) as described in https://github.com/Mbed-TLS/mbedtls/blob/development/docs/proposed/config-split.md.
