### ISSUE TITLE
mbedtls_ssl_renegotiate and mbedtls_ssl_handshake symbols occur more than once?

### ISSUE THREAD

**Issue by theoden8** [Mbed-TLS/mbedtls#9670]
### Summary

If I run:

```
nm -A libmbedtls.a \
  | grep 'mbedtls_' \
  | awk '{print $NF}' \
  | sort \
  | uniq -c \
  | sort -nr
```

I get something like:

```
   4 _mbedtls_ssl_handshake_set_state
   3 _mbedtls_ssl_handshake_wrapup
   2 _mbedtls_ssl_renegotiate
   2 _mbedtls_ssl_handshake_wrapup_free_hs_transform
   2 _mbedtls_ssl_handshake_server_step
   2 _mbedtls_ssl_handshake_client_step
   2 _mbedtls_ssl_handshake
   1 _psa_crypto_init
   1 _mbedtls_ssl_handshake_step
   1 _mbedtls_ssl_handshake_free
```

Which in my case probably means that `psa_crypto_init()` initializes instance that is not used by other instances.

So here: https://github.com/Mbed-TLS/mbedtls/blob/38d4c91b06717483bca17239eebe20befc78b32d/library/ssl_tls13_generic.c#L1578 we call psa_generate_key.

This in turn fails here:
https://github.com/Mbed-TLS/mbedtls/blob/38d4c91b06717483bca17239eebe20befc78b32d/tf-psa-crypto/core/psa_crypto.c#L1788

And that is a problem, as it fails here:

https://github.com/Mbed-TLS/mbedtls/blob/38d4c91b06717483bca17239eebe20befc78b32d/tf-psa-crypto/core/psa_crypto_slot_management.c#L602

Because `&global_data` in slot_management file is different from the one that was initialized.

### System information

Mbed TLS version (number or commit id): 38d4c91b06717483bca17239eebe20befc78b32d
Operating system and version: MacOS 14.6.1 intel
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it):

`cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="$PWD"/install-dir`

```
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: x86_64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Additional environment information: 

### Expected behavior

When I print `&global_data` static variable pointer in [psa_](https://github.com/Mbed-TLS/mbedtls/blob/38d4c91b06717483bca17239eebe20befc78b32d/tf-psa-crypto/core/psa_crypto_slot_management.c), it should always return the same value

### Actual behavior

I get different values depending on whether linked directly or through libevent_mbedtls.c. Presumably, there should only be one occurrence for functions that are related to using `psa_generate_key`.

### Steps to reproduce

https://github.com/libevent/libevent/pull/1719

**Comment by tom-cosgrove-arm** [comment]
This would appear to be more of an issue with how Mbed TLS is being integrated than an actual issue with Mbed TLS itself. We are a library, and we only have one `psa_crypto_init()` function, so I would say

> When I print &global_data static variable pointer in [psa_](https://github.com/Mbed-TLS/mbedtls/blob/38d4c91b06717483bca17239eebe20befc78b32d/tf-psa-crypto/core/psa_crypto_slot_management.c), it should always return the same value

is a requirement we place on how you include Mbed TLS in your application, rather than an issue with our code

**Comment by theoden8** [comment]
Hmm, shouldn't the library cause linkage error in this case?

**Comment by tom-cosgrove-arm** [comment]
> Hmm, shouldn't the library cause linkage error in this case? I.e. duplicate symbols

It really depends how things are linked, what symbols are made public, and how symbols are resolved. If a static library is linked into another library, and none of the static library's symbols are exposed by that other library, then no, there won't be duplicate symbols.

> I get different values depending on whether linked directly or through libevent_mbedtls.c

This would suggest where the problem might be

**Comment by ronald-cron-arm** [comment]
This does not seem an issue in Mbed TLS to me either. It seems to be rather a support request. Thus I am closing this issue and please use the [mailing list](https://lists.trustedfirmware.org/mailman3/lists/mbed-tls.lists.trustedfirmware.org/) for support requests and discussions of Mbed TLS integration.
