### ISSUE TITLE
mbedtls_net_connect connect failed

### ISSUE THREAD

**Issue by kgfly12** [Mbed-TLS/mbedtls#9710]
### Summary
In function mbedtls_net_connect()，line 193：if function socket() return ok， but connect() failed，then close(fd); 
you'd better reinit `ctx->fd = -1; ` Otherwise when APP use mbedtls_net_connect() failed, it will implement mbedtls_net_free(fd), and then close(fd) twice.

### System information

Mbed TLS version (number or commit id): 
Operating system and version: Ubuntu 22.04
Configuration (if not default, please attach `mbedtls_config.h`): default
Compiler and options (if you used a pre-built binary, please indicate how you obtained it): 
Additional environment information:

**Comment by gowthamsk-arm** [comment]
Fix in #9711
