### ISSUE TITLE
mbedTLS does not compile on MS-DOS DJGPP

### ISSUE THREAD

**Issue by SuperIlu** [Mbed-TLS/mbedtls#9813]
mbedTLS does not compile on MS-DOS DJGPP because the toolchain does define `__unix__`, but does not provide `suseconds_t`.
Excluding the code path with modifying the `#if` to be false when `__DJGPP__` is defined makes it compile fine.

PRs #9810, #9811 and #9812 do fix that for me.

**Comment by gilles-peskine-arm** [comment]
Fixed by https://github.com/Mbed-TLS/mbedtls/pull/9810 and backports.
