### ISSUE TITLE
Duplicate header file

### ISSUE THREAD

**Issue by irwir** [Mbed-TLS/mbedtls#9822]
https://github.com/Mbed-TLS/mbedtls/blob/f4f37eced7c39db5db4c6b5c5c6ec98bd81fe416/tf-psa-crypto/core/psa_crypto.c#L23
https://github.com/Mbed-TLS/mbedtls/blob/f4f37eced7c39db5db4c6b5c5c6ec98bd81fe416/tf-psa-crypto/core/psa_crypto.c#L28

**Comment by gilles-peskine-arm** [comment]
Thanks for the report. A double header inclusion is a defect, but it's an extremely minor one, not worth getting a pull request through or keeping sorted on the backlog. Especially as we're likely to refactor headers quite a bit before the next major release. So I'm going to close this issue: if it happens, good, but we aren't going to keep track of it.

**Comment by irwir** [comment]
> we're likely to refactor headers quite a bit

Presumably this was a result of 3.0 refactoring.
It might be suggested to add a fix into any nearest PR which touches `psa_crypto.c`; same with backports if needed.

**Comment by irwir** [comment]
Two more cases:
`stddef.h`  in `tf-psa-crypto\core\common.h`
`mbedtls/error_common.h` in `tf-psa-crypto\core\psa_crypto.c`

Duplication in the same header file should be trivial to diagnose; Intellisense in Visual Studio would show a warning.
Cannot tell if GCC has similar capabilities.
