### ISSUE TITLE
Not support PSA_ALG_DETERMINISTIC_ECDSA_BASE

### ISSUE THREAD

**Issue by zhang-wenchao** [Mbed-TLS/mbedtls#9871]
```
int32_t psa_k256_sign_hash(const uint8_t *private_key, const uint8_t *hash,
			      size_t hash_length, uint8_t *signature)
{
	size_t signature_length;
	psa_status_t status = psa_crypto_init();
	if (status != PSA_SUCCESS) {
		return status;
	}

	psa_key_attributes_t attributes = PSA_KEY_ATTRIBUTES_INIT;
	psa_key_id_t key_id;

	psa_set_key_type(&attributes, PSA_KEY_TYPE_ECC_KEY_PAIR(PSA_ECC_FAMILY_SECP_K1));
	psa_set_key_bits(&attributes, 256);
	psa_set_key_algorithm(&attributes, PSA_ALG_DETERMINISTIC_ECDSA_BASE);
	psa_set_key_usage_flags(&attributes, PSA_KEY_USAGE_SIGN_HASH);

	status = psa_import_key(&attributes, private_key, 32, &key_id);
	if (status != PSA_SUCCESS) {
		return status;
	}

	status = psa_sign_hash(key_id, PSA_ALG_DETERMINISTIC_ECDSA_BASE, hash, hash_length,
				  signature, 64, &signature_length);

	psa_destroy_key(key_id);
	return status;
}
```
psa_sign_hash return -135

#define PSA_ERROR_INVALID_ARGUMENT      ((psa_status_t)-135)

**Comment by zhang-wenchao** [comment]
Try `PSA_ALG_DETERMINISTIC_ECDSA(PSA_ALG_ANY_HASH)) `

-135 PSA_ERROR_INVALID_ARGUMENT

**Comment by gilles-peskine-arm** [comment]
`PSA_ALG_DETERMINISTIC_ECDSA_BASE` is not an algorithm, it's just an intermediate macro used to build other macros. Use e.g. `PSA_ALG_DETERMINISTIC_ECDSA(PSA_ALG_SHA_256)` for a deterministic ECDSA signature using SHA-256.

For the key policy (argument to `psa_set_key_algorithm`), you can use `PSA_ALG_DETERMINISTIC_ECDSA(PSA_ALG_ANY_HASH)`, to say that the key may be used to sign any hash. When signing (argument to `psa_sign_hash`), you do need to specify which hash to use.
